### ISSUE TITLE
icon suggestion: egg icon and net icon

### ISSUE THREAD

**Issue by Iri-net** [google/material-design-icons#1000]
It would be nice to have an egg icon and a net icon (phising net)

**Comment by anugrah8abadi** [comment]
![egg](https://user-images.githubusercontent.com/65443162/82306839-c46b0880-99e9-11ea-8f71-8054f2f3a288.png)

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
