### ISSUE TITLE
Weelchair and Truck

### ISSUE THREAD

**Issue by Angelk90** [google/material-design-icons#1006]
You can add icons similar to these, obviously without the circle.

Example:
![weelchair_free](https://user-images.githubusercontent.com/20476002/78164747-840bf700-744a-11ea-8837-0ea697f72e4b.png)

![truck_free](https://user-images.githubusercontent.com/20476002/78164746-83736080-744a-11ea-9632-49db4b8d6615.png)

**Comment by jalpadoshi** [comment]
Icons now available on: https://fonts.google.com/icons
