### ISSUE TITLE
Icon request: Various chart icons (bar, line, area, pie, etc)

### ISSUE THREAD

**Issue by epelc** [google/material-design-icons#101]
It would be nice specifically for applications which have stats or analytic's if there were some chart icons. I think the following basic ones would be good to start off with.
- bar
- line
- area
- pie

Here's a picture of what they might look like(from fontawesome)
![image](https://cloud.githubusercontent.com/assets/5204642/7217624/a4bc1d78-e605-11e4-97eb-9239b16fc64f.png)

**Comment by visualpharm** [comment]
If Google gives us a sign they're responding to the pull requests, we can release these: http://icons8.com/web-app/for/androidL/chart

**Comment by golfziller** [comment]
try again , this example on tab
<Tab icon={<i class="material-icons">
bar_chart
</i>} >

**Comment by RoelN** [comment]
Looks like these have been added in the meantime: https://material.io/resources/icons/?search=chart&style=baseline
