### ISSUE TITLE
please add code point for check_circle_outline

### ISSUE THREAD

**Issue by Krishnakumarskr** [google/material-design-icons#1010]

**Comment by hasancemcerit** [comment]
As well as `warning_outline` and `build_outline`

**Comment by paulofreitas** [comment]
`check_circle_outline` is `e92d`

You can check a more up to date list of code points in this link: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart

`warning_outline` and `build_outline` doesn't exist, it's just `warning` and `build` with a different theme. You need to load the `Material Icons Outlined` web font to use it as desired. Take a look: https://stackoverflow.com/a/61749083/222758

**Comment by RoelN** [comment]
Thanks @paulofreitas for explaining! Closing this issue because I believe it has been addressed.
