### ISSUE TITLE
please add exit pip (picture-in-picture) icon

### ISSUE THREAD

**Issue by Poopooracoocoo** [google/material-design-icons#1011]

**Comment by jalpadoshi** [comment]
Icons now available on: https://fonts.google.com/icons

**Comment by Poopooracoocoo** [comment]
Am I missing something? What should I be searching for to find the exit PiP icon? @jalpadoshi

**Comment by jalpadoshi** [comment]
name of the icon: picture_in_picture

**Comment by Poopooracoocoo** [comment]
@jalpadoshi That has existed for a long time now. I was looking for an exit icon.
