### ISSUE TITLE
Where can I find rounded version of font files?

### ISSUE THREAD

**Issue by michaltaberski** [google/material-design-icons#1012]
I need to do self hosting of material design icons. I can see regular font files under:
https://github.com/google/material-design-icons/tree/master/iconfont
However I need to host rounded version of material icons - where can I find it?

**Comment by zachkrall** [comment]
@michaltaberski 

This readme file has a list of the google font cdn options
https://github.com/google/material-design-icons/blob/master/font/README.md

```html
<link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round"
      rel="stylesheet">
```

**Comment by RoelN** [comment]
Thanks @zachkrall. All founds can also be found in the repo now: https://github.com/google/material-design-icons/tree/master/font
