### ISSUE TITLE
Totally unresponsive website

### ISSUE THREAD

**Issue by StLa1** [google/material-design-icons#1014]
The website is very unresponsive, and thus unusable. Happens on Windows, iOS, Mac. It becomes responsive for a few seconds every once in a while, then freezes again. Scrolling is possible, but the page is frozen.

**Comment by RoelN** [comment]
@StLa1 Closing this as I can't seem to reproduce. If you are still running into this problem, feel free to reopen or create a new issue with details about the OS/browser/network you're using.
