### ISSUE TITLE
Wrong Icon Name

### ISSUE THREAD

**Issue by 54mu3l** [google/material-design-icons#1022]
On the resources page the filter-alt icon is listed with the name `filter_alt`:
![image](https://user-images.githubusercontent.com/17022670/84235607-6ae09000-aaf6-11ea-9f16-0cc1ec77129c.png)
https://material.io/resources/icons/?search=filter&icon=filter_alt&style=baseline

But the name `filter_alt` doesn't work for me (using v3.0.1 with Quasar). Instead of the expected `filter_alt` icon I get the `filter` icon displayed:
![image](https://user-images.githubusercontent.com/17022670/84235588-6025fb00-aaf6-11ea-9a44-dfe33c178b93.png)

In the woff file I found the icon I was looking for under the name `filter_list_alt`.
So it seems that the resources page is wrong.

**Comment by abohosam1772** [comment]
نيسان سنترا 2014

**Comment by TheTyrius** [comment]
I'm also using quasar and having trouble with some icons (e.g. 'construction' and 'engineering'), but I'm not getting a wrong icon (rather no icon at all).

**Comment by Vaseem88** [comment]
I am also getting the same error as described by @54mu3l, using  `filter_list_alt` for filter icon has solved the problem, please check the icon on the resource page

**Comment by 54mu3l** [comment]
> I am also getting the same error as described by @54mu3l, using `filter_list_alt` for filter icon has solved the problem, please check the icon on the resource page

Are you using Quasar as well? Or smth different?

**Comment by Vaseem88** [comment]
I am using Web-pack

**Comment by gdebrion** [comment]
Hello,

Same problem here with NPM package and webpack. The icon `filter_alt` does not exists…

**Comment by mabdullah786** [comment]
Guys any update ?

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
