### ISSUE TITLE
Can I use a Material Design Icon as a logo?

### ISSUE THREAD

**Issue by AryanBeezadhur** [google/material-design-icons#1023]
> Attribution is not required.
Can I use an icon from Material Design Icons as a logo for my open source project on GitHub?

**Comment by erdos-2** [comment]
> > Can I use an icon from Material Design Icons as a logo for my open source project on GitHub?
I also have the same question, but my project is not open source.

**Comment by AryanBeezadhur** [comment]
@erdos-2 

Check the license. Under **Permissions**, there is a tick next to "Commercial use" and "Modification", but under **Limitations**, there is a cross next to "Trademark use". So you can only use it for a logo if you do not trademark it.

![image](https://user-images.githubusercontent.com/34424160/174877815-ea83d8da-2a3e-4c49-94e9-d09262b8cfc0.png)
