### ISSUE TITLE
node_modules: tar folder error

### ISSUE THREAD

**Issue by shouvikchatterjee** [google/material-design-icons#1027]
D:\HTML\Learning\quiz>npm update
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'tar'
npm ERR! Require stack:
npm ERR! - C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\extract-stream.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\extract.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\index.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\lib\install.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\lib\update.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\lib\npm.js
npm ERR! - C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-20T10_17_09_408Z-debug.log

Above error is getting whenever I am trying to run any npm command except 'npm start'

**Comment by shouvikchatterjee** [comment]
![image](https://user-images.githubusercontent.com/36500786/85199552-1d41ff80-b30e-11ea-851f-ded8f00870ba.png)

**Comment by shouvikchatterjee** [comment]
I cant able to uninstall,repair,reinstall nodejs due to this....don't understand how to resolve this. Please suggest any idea.

**Comment by RoelN** [comment]
This seems like a Node issue, not something specific to Material Icons, perhaps you can try filing an issue with them?
