### ISSUE TITLE
Icon missing: fastfood

### ISSUE THREAD

**Issue by jimcj28** [google/material-design-icons#1029]
The following icon is missing from material-design-icons/iconfont/

**fastfood**
![fastfood icon](https://user-images.githubusercontent.com/7611327/85448501-bf5b2500-b564-11ea-8336-3ae2959c45f3.png)

**Comment by kalyani489** [comment]
Can I work on this issue?

**Comment by RoelN** [comment]
Confirmed that ligature is missing. Related to https://github.com/google/material-design-icons/issues/1082

**Comment by tphinney** [comment]
I think this is all better now?

**Comment by tphinney** [comment]
I see it in both the Material Icons font and the new Material Symbols font. Closing now.
(Heck, I remember working on it in Material Symbols—a lot of pain to do the 700 weight!)
