### ISSUE TITLE
"Google" and "Google Plus" icons are missing.

### ISSUE THREAD

**Issue by bmg02** [google/material-design-icons#1035]
Hey there, I want to use "Google" or "Google Plus" icon in web page. But they are missing in Material UI icons. So currently, if I want to use them how can I use it?

**Comment by tphinney** [comment]
Currently we do not provide icons for Google or Google products in the Material Icons/Symbols
Those icons are reserved for the Google-internal versions of the icons

**Comment by bmg02** [comment]
Thank you for your response. I believe Google should provide icons for Google and its product. Because they are already publically available. People will anyhow use it in their projects. But if you provide it here only, then that may make it easier for developers.
