### ISSUE TITLE
Icon request: pointer

### ISSUE THREAD

**Issue by nkoren** [google/material-design-icons#104]
You  know, something like this: ![pointer icon](http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/glossy-black-icons-business/080745-glossy-black-icon-business-cursor.png)

**Comment by jestelle** [comment]
Thanks @nkoren 
I can't guarantee we'll get to icon requests soon, but we will eventually take them into consideration.

**Comment by RoelN** [comment]
@nkoren The link is broken, would you mind explaining how this icon would look?

**Comment by jalpadoshi** [comment]
This  icon is available on fonts.google.com/icons. Similar to hand-crusor.
