### ISSUE TITLE
Update newest sets of icons in SVG, PNG and icon font formats in the GitHub repository

### ISSUE THREAD

**Issue by ytx21cn** [google/material-design-icons#1042]
It seems like that the material icons on the [Material Icons](https://material.io/resources/icons) have been updated with additional icons, but they are not yet updated in this GitHub repository.
![1](https://user-images.githubusercontent.com/5900105/87882176-1bbe3280-c9b3-11ea-8ab7-2abf800beca3.png)

As a result, it is now unable to fetch the updated icon collection at once, both in the form of images and icon fonts.

**I am looking forward to see them updated in GitHub ASAP.**

**Comment by ytx21cn** [comment]
Follow up: **This is the collection of the newest font files.**

[Google-material-icons-font.zip](https://github.com/google/material-design-icons/files/4944753/Google-material-icons-font.zip)

Downloaded from: https://fonts.google.com/download?family=Material%20Icons|Material%20Icons%20Outlined|Material%20Icons%20Sharp|Material%20Icons%20Round|Material%20Icons%20Two%20Tone

**Comment by wexs** [comment]
hello～请问你发的这个font资源是怎么找到的（想着以后要更新），我直接访问fonts.google.com网站却没有找到～ @ytx21cn

**Comment by ytx21cn** [comment]
> hello～请问你发的这个font资源是怎么找到的（想着以后要更新），我直接访问fonts.google.com网站却没有找到～ @ytx21cn

This is NOT in the Google Fonts directory if you access it directly.

My steps to find out the exact URL:

1. Open the [Material Design Icons](https://material.io/resources/icons/) page.
2. Using Firefox, press F12 to open **Developer Tools**. Then click on the **Style editor** tab.
3. Switch to the `styles.css` style sheet, and copy the import URL at the top. It would be `https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Sharp|Material+Icons+Round|Material+Icons+Two+Tone`.
![Screenshot from 2020-07-23 11-36-32](https://user-images.githubusercontent.com/5900105/88324648-d95d6400-ccd8-11ea-83e5-177950ecb16d.png)
4. Copy that URL and open it in a new tab. You see the source code:
![Screenshot from 2020-07-23 11-38-12](https://user-images.githubusercontent.com/5900105/88324841-20e3f000-ccd9-11ea-99d4-1252cdff872a.png)
5. **Save this URL in a text file, for later use.**

6. Now go to [Google Fonts](https://fonts.google.com).
7. Download one font family offered in the directory, e.g. Roboto.
8. From the list of recent downloads, right click "Roboto.zip" and select **Copy Download Link**.
![Screenshot from 2020-07-23 11-42-06](https://user-images.githubusercontent.com/5900105/88325720-34dc2180-ccda-11ea-9cca-ab9163201c0e.png)


9. Paste the copied download link in the address box. It would be `https://fonts.google.com/download?family=Roboto`.
10. **Go back to the URL you have saved in step 5.** Now copy everything after `family=` in that URL, and use it to replace the content after `family=` in the address box.
11. Now you get the full URL: https://fonts.google.com/download?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Sharp|Material+Icons+Round|Material+Icons+Two+Tone. Press ENTER so that the zip would be downloaded.

**Comment by wexs** [comment]
Get！！💗💗

**Comment by rsheeter** [comment]
#1055 aims to bring https://material.io/resources/icons and this repo into better sync.

**Comment by jjrauch32-lab** [comment]
Kk
