### ISSUE TITLE
Publish the codepoints

### ISSUE THREAD

**Issue by teddydoors** [google/material-design-icons#1044]
Why don't you publish any codepoints for Material Icons? That's the only way as I know If you want to add icons with :before and :after tags (in CSS language).

Also, why did you make a change in the icon "Details", and no explanation!?

**Comment by maltfield** [comment]
bump

**Comment by maltfield** [comment]
btw, I found the codepoints here (see the `.codepoints` files that correspond to each font file)

 * https://github.com/google/material-design-icons/tree/master/font

See also:

 * https://github.com/google/material-design-icons/issues/1067

**Comment by rsheeter** [comment]
#1068 added codepoints files for each font. My fault for deleting in the initial update.
