### ISSUE TITLE
Incorrect size for add_task when using webfont

### ISSUE THREAD

**Issue by MikeJerred** [google/material-design-icons#1045]
When using the `add_task` icon, the HTML element takes up a very large width.

I have tested this using the webfont, and reproduced here: https://stackblitz.com/edit/js-yagxst?file=style.css

**Comment by RoelN** [comment]
This looks fine when I test it:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/4570664/105018067-d2739c00-5a44-11eb-9232-424c164c71d1.png">

Can you reopen this issue if you still run into this problem?
