### ISSUE TITLE
bar_chart icon is too small

### ISSUE THREAD

**Issue by guoyunhe** [google/material-design-icons#1046]
The bar_chart icon is much smaller (both width and height) than other icons:

![Screenshot_20200730_171821](https://user-images.githubusercontent.com/5836790/88934136-e950e700-d288-11ea-9921-7787a5f5452c.png)

**Comment by RoelN** [comment]
This looks to be fixed in the font, as well as in the SVG: https://github.com/google/material-design-icons/blob/master/src/editor/bar_chart/materialicons/24px.svg Feel free to reopen if you still run into this issue, with some more details (e.g. which asset/font you're using)

**Comment by guoyunhe** [comment]
@RoelN I think the problem still exists:

1. the bounding rectangle of bars are 14x14px, while the very similar icon signal_cellular_alt is 15x16px, and it looks more balanced
2. three bars have different widths: the first is 3px and the other two are 2.8px, it is not pixel perfect. while the very similar icon signal_cellular_alt has same width and is pixel perfect

https://github.com/google/material-design-icons/blob/master/src/editor/bar_chart/materialicons/24px.svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M5 9.2h3V19H5zM10.6 5h2.8v14h-2.8zm5.6 8H19v6h-2.8z"/> <!-- non-integers -->
</svg>
```

https://github.com/google/material-design-icons/blob/master/src/device/signal_cellular_alt/materialicons/24px.svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M17 4h3v16h-3zM5 14h3v6H5zm6-5h3v11h-3z"/> <!-- all integers -->
</svg>
```

**Comment by RoelN** [comment]
@guoyunhe Ah, sorry to hear it isn't fixed. I'm currently not working on this project, but I've re-opened the issue with the appropriate label so I hope this will get picked up!

**Comment by tphinney** [comment]
I agree; it is a design question—and stacked_bar_chart is even “worse.” Signal_cellular_alt and equalizer provide a couple of different approaches. I would favor tweaking bar_chart and stacked_bar_chart

**Comment by tphinney** [comment]
This has since been fixed, a while ago now—thanks for your patience.
