### ISSUE TITLE
SVG file dump missing some newer icons

### ISSUE THREAD

**Issue by snds** [google/material-design-icons#1047]
I have downloaded the SVG file dump and they are not matching what is shown on the Icon resource page (https://material.io/resources/icons/?style=baseline)

I am currently having to visually match every icon against the basic list that you guys have on the site and manually download any missing glyphs. I would really like to get an updated batch.

**Comment by Download** [comment]
Unfortunately, this repo seems to be outdated. Also see [NPM package is outdated](https://github.com/google/material-design-icons/issues/1050).

**Comment by rsheeter** [comment]
This repo should be a superset of material.io after the merge of #1055. Apologies for the N year delay ([more about that](https://github.com/google/material-design-icons/issues/1054#issuecomment-675099807)) :D
