### ISSUE TITLE
icon requests: search filter, refund, remove shopping cart....

### ISSUE THREAD

**Issue by ghost** [google/material-design-icons#105]
The current filter icon doesn't really represent a search filter meaning.
- search filter
- remove shopping cart
- refund
- discount
- person remove

**Comment by jestelle** [comment]
Thanks @robertbaker 
I can't guarantee how quickly we'll get to icon requests, but we will eventually have a look at them.
In the meantime, you might try the community resource http://materialdesignicons.com
This unofficial, and not supported by Google, but does have a nice breadth of additional icons.

**Comment by shellscape** [comment]
Given that 4 years has passed is it same to assume that `how quickly we'll get to icon requests` is essentially never?

**Comment by RoelN** [comment]
Multiple icons are requested in this issue, I'm closing it as the assets have been updated since this issue was reported.  If not, feel free to reopen this issue or create a new one with more information.
