### ISSUE TITLE
Codepoint 58848 not found in font flutter

### ISSUE THREAD

**Issue by harishkunjithaya257** [google/material-design-icons#1051]
hey,

have been using stable upgraded version of flutter.
on building APP bundle i am getting below error.p
![rsz_screenshot_from_2020-08-12_18-06-59](https://user-images.githubusercontent.com/68266782/90016040-0c3abc80-dcc7-11ea-8587-8f40bfc79056.png)
lease do assist 

" Codepoint 58848 not found in font flutter"

**Comment by AJOnlineServices** [comment]
Also getting the same error: "Codepoint 58848 not found in font, aborting"

**Comment by rinku1902** [comment]
Getting same issue :
E:\Android\fluxstore-multivendor>flutter build appbundle --target-platform android-arm,android-arm64,android-x64
Codepoint 58848 not found in font, aborting.

http://prntscr.com/u1ghxp

Please Help!
