### ISSUE TITLE
V4: how to get woff, woff2, .. for self-hosting

### ISSUE THREAD

**Issue by tmtron** [google/material-design-icons#1059]
we must use self-hosting for the fonts and cannot use the google CDN

How can we get/build the woff, woff2, .. versions of the fonts?

i.e. in V3 different fonts files were in the [iconfont](https://github.com/google/material-design-icons/tree/3.0.2/iconfont) directory and we could simply copy them.  
In V4 there is only the `ttf` version in the font directory.

**Comment by xbeat** [comment]
You can convert the ttf online using this free tool: [](https://cloudconvert.com/ttf-converter)

**Comment by rsheeter** [comment]
woff2 is widely supported (https://caniuse.com/#feat=woff2) and can be output by https://github.com/fonttools/fonttools or https://github.com/google/woff2. Depending on your browser support listing woff2 and the [ot]tf as sources might be sufficient, if not there are converters for many other formats.

**Comment by ytx21cn** [comment]
I am using Ubuntu.
The ttf / otf → woff utility is [**woff-tools**](https://packages.ubuntu.com/source/woff-tools).
The ttf / otf → woff2 utility is [**woff2**](https://packages.ubuntu.com/source/woff2).
These two utilities provide convenient command-line conversions to the desired formats.
