### ISSUE TITLE
Icon request: Outbox

### ISSUE THREAD

**Issue by Sereri** [google/material-design-icons#106]
It would be nice if there was an outbox icon included. There is one in the gmail app right now so I guess you guys _do_ already have that, at least somewhere :wink:

**Comment by jestelle** [comment]
Thanks @Sereri 

I can't guarantee how quickly we'll get to icon requests, but we will eventually have a look at them.
In the meantime, you might try the community resource http://materialdesignicons.com
It's unofficial, and not supported by Google, but does have a nice breadth of additional icons.

**Comment by bennidhamma** [comment]
looks like there is one now... 

https://fonts.google.com/icons?icon.query=outbox

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
