### ISSUE TITLE
Missing icons in release package

### ISSUE THREAD

**Issue by raphaellueckl** [google/material-design-icons#1061]
Hi

[The icons `east` and `west` from the documentation are not present in the downloaded icons](https://material.io/resources/icons/?icon=east&style=baseline). Is there a reason for this or did I do something wrong?

**Comment by fpauser** [comment]
Same for the icon "login" and some more.

**Comment by Download** [comment]
#1050

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
