### ISSUE TITLE
Social: person_remove and person_remove_alt_1 are the same

### ISSUE THREAD

**Issue by tech-meppem** [google/material-design-icons#1062]
The icons (in social) for person_remove and person_remove_alt_1 have the `-` on the same side, whereas the person_add and person_add_alt_1 have the `+` on different sides.
See image:
![image](https://user-images.githubusercontent.com/54634811/91324062-87b56700-e7b9-11ea-97e8-90417280f990.png)

**Comment by RoelN** [comment]
Thanks for reporting! Closing this issue in favor of https://github.com/google/material-design-icons/issues/1107
