### ISSUE TITLE
Is "outbond" a typo of "outbound"?

### ISSUE THREAD

**Issue by tv42** [google/material-design-icons#1063]
https://material.io/resources/icons/?icon=outbond&style=baseline

It is an arrow pointing outward from a circle.

It seems like it was intended to be "outbound"?

"Outbond" is pretty specific: 

> Definition of outbond
: laid with its longer side parallel to the face of a wall
an outbond brick

https://www.merriam-webster.com/dictionary/outbond

**Comment by RoelN** [comment]
Looks like `outbond` was added by mistake, and an `outbound` alias was added to fix the issue. `Outbond` is most likely still in there for backwards compatibility.

**Proposed solution:** Keep misspelled `outbond` for backwards compatibility and close this issue.

**Comment by tphinney** [comment]
Currently there is no `outbond` at all and `outbound` is all there is, in the latest fonts.
If somebody feels we ought to be supporting the `outbond` typo as well, for legacy reasons, let me know.
