### ISSUE TITLE
Outline icon font not installing in windows

### ISSUE THREAD

**Issue by manishminz** [google/material-design-icons#1064]
![image](https://user-images.githubusercontent.com/47636906/91539861-a04b8b80-e937-11ea-811c-9f4eed1c61cb.png)

**Comment by RoelN** [comment]
Most likely related to the overzealous subsetting of the name table (contains name ID 0, 1, 2 and 6 only).

Proposed solution: keep all nameIDs from 0 to 6, as discussed in FontTools/pyftsubset issues, to create a valid installable font.

**Comment by dtrunk90** [comment]
@RoelN I'm facing the same issue with all of the OTF fonts on Windows 10. TTF installs fine and ligatures working in WordPad for example, but Photoshop CS6 doesn't show any icons. OTF files are not installable at all. Same files are installable in Ubuntu without any problems. Tested same files on my Ubuntu Host + Win 10 Guest (VirtualBox).

How to "keep all nameIDs from 0 to 6" (whatever this is) without creating any font files? I simply want to use the existing font files from the fonts folder.

**Comment by RoelN** [comment]
@dtrunk90 My proposed solution was a note to the Google team that will update the fonts, so they know how to fix this so you can correctly use the fonts in this repo :-)

**Comment by tphinney** [comment]
I believe this is all better now, there have been several font updates in the past year.
