### ISSUE TITLE
Improve icon for Join a meeting in Gmail

### ISSUE THREAD

**Issue by Gprshty** [google/material-design-icons#1066]
### Improve the Icon for Join a meeting

In Gmail, left-hand side panel, just below Categories, Under "Meet": Icon for "Join a meeting" can be improved.

Start a meeting appropriately shows the camera icon next to it; whereas "Join a meeting" show - a keyboard.

Instead, it should have a three people icon in the background with a slightly bigger one-person silhouette icon in the foreground - indicating a person join a meeting (with others.)

I am attaching a suggestion icon, of course, that can be improved.

Current Icon:

![Gmail_joinAMeetingIcon](https://user-images.githubusercontent.com/70486748/91667495-9a65ce00-eb22-11ea-8691-998531784538.png)

Suggestion Icon:

![Joinmeetinsuggestion](https://user-images.githubusercontent.com/70486748/91668074-1a8e3280-eb27-11ea-9e58-7fd4ee41d14e.png)
 Icon:

**Comment by RoelN** [comment]
This sounds like an issue for the Gmail team, instead of one for Material Icons. Perhaps you can forward your suggestion to the Gmail team via https://support.google.com/mail/answer/9212652?

**Comment by Gprshty** [comment]
Thanks @RoelN But, Unable to access the link you shared

@google-admin where to suggest Gmail icon related issues.
