### ISSUE TITLE
Codepoints link 404s

### ISSUE THREAD

**Issue by maltfield** [google/material-design-icons#1067]
This repo generates the following page:

 * https://google.github.io/material-design-icons/

Which contains the following paragraph:

> Find both the icon names and codepoints on the material icons library by selecting any icon and opening the icon font panel. A [codepoints index](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) is also available on our git repository which shows the complete set of names and character codes.

Which contains a link to the following page:

 * https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

...which is a 404.

Where can I get the unicode codepoints for each icon?

**Comment by rsheeter** [comment]
`font/<font file basename>.codepoints` (just added); will update docs.
