### ISSUE TITLE
[](git clone https://gerrit.googlesource.com/gitiles) #210

### ISSUE THREAD

**Issue by ebi60** [google/material-design-icons#1069]
[](git clone https://gerrit.googlesource.com/gitiles) #210

_Originally posted by @ebi60 in https://github.com/google/gitiles/issues/211#issuecomment-684129169_

**Comment by RoelN** [comment]
Closing this issue because it doesn't contain a concrete question or a detailed description. Feel free to reopen this issue or create a new one with more information.
