### ISSUE TITLE
Icon request : Hand icon

### ISSUE THREAD

**Issue by hatemsh** [google/material-design-icons#107]
The hand icon from the guidelines

![image](https://cloud.githubusercontent.com/assets/11914962/7656259/1f37cce6-fb32-11e4-818e-8bc39df174e6.png)

**Comment by jestelle** [comment]
We love icon requests.  But we don't have a clear pipeline for handling them and acting on them yet.
Keep them coming, and +1 the ones you like, and we'll eventually do a pass and try to hit some off these.

**Comment by db2k** [comment]
+1

**Comment by codeator** [comment]
+1

**Comment by wyne** [comment]
+1

**Comment by adarshv90** [comment]
+1

**Comment by patrikx3** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon is available  on fonts.google.com/icons
