### ISSUE TITLE
Login icon rendering empty

### ISSUE THREAD

**Issue by sharathsg27** [google/material-design-icons#1071]
Hello guys,

I'm trying to use **<i class="material-icons">login</i>** but it's rendering empty in my Angular 10 project. But other icons are rendering fine. But not with this. Also not sure are there any other icons with the same issue.

1. I've added **"<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">"** in my **index.html** page
2. Added "node_modules/material-design-icons/iconfont/material-icons.css" in angular.json
3. Imported as well in style.scss file: @import "~material-design-icons/iconfont/material-icons.css"

I've attached the inspect of the icon element for reference. Can you please look into this?
<img width="1772" alt="Screenshot 2020-09-02 at 12 33 47 PM" src="https://user-images.githubusercontent.com/29069848/91942446-97ccc980-ed18-11ea-99b2-8008578daec9.png">

**Comment by Download** [comment]
See #1050 

You should find another way to use material icons, because this repo is not publishing to NPM, because Alphabet Inc does not have enough money to publish to NPM or answer your questions.

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
