### ISSUE TITLE
ic_history - Icon width is too high then usual one

### ISSUE THREAD

**Issue by ussainraswi-go** [google/material-design-icons#1072]
While using <i class="material-icons">**ic_history**</i> - its looks fine, but if you inspect using dev tools you can see the overall width is high like 2em. pls fix it. There is also an alternate - **restore**.  

ic_history & restore Both looks similar.

**Comment by RoelN** [comment]
The icon looks fine to me on https://material.io/resources/icons/?style=baseline Which font version are you using? 

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
