### ISSUE TITLE
 <mat-icon>filter_alt</mat-icon> is rendering collections icon 

### ISSUE THREAD

**Issue by spp125** [google/material-design-icons#1073]
I am using  "material-design-icons": "^3.0.1", and Angular 10.0.4

    "@angular-devkit/build-angular": "^0.1000.4",
    "@angular/cli": "^10.0.4",
    "@angular/compiler-cli": "^10.0.5",

In my template file I am using filter_alt icon but its rendering collections icon. I am not sure if its a bug or something else is happening there. Please take a look

**Comment by cryptonrohit** [comment]
I am also facing the same issue.

**Comment by christophechevalier** [comment]
Same for me.  

@spp125 @cryptonrohit 
**Workaround**: Try using `filter_list_alt` instead `filter_alt`. It's okey for me.

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
