### ISSUE TITLE
addchart should be renamed to add_chart for consistency

### ISSUE THREAD

**Issue by Phritzy-zz** [google/material-design-icons#1079]

**Comment by RoelN** [comment]
Proposal: add a `add_chart` ligature and keep the `addchart` ligature for backwards compatibility.

**Comment by tphinney** [comment]
That's exactly how it was handled in the latest fonts.
Well, except that the glyph itself is called "add_chart"—but keeping the old name via ligature is exactly what we did for backwards compatibility.
