### ISSUE TITLE
Live preview has a broken link

### ISSUE THREAD

**Issue by seongjaelee** [google/material-design-icons#108]
http://google.github.io/material-design-icons/

indeterminate check box image is broken.

![screen shot 2015-05-15 at 10 45 25 pm](https://cloud.githubusercontent.com/assets/948301/7664895/2604bc88-fb54-11e4-922f-09858dc5a7e9.png)

**Comment by jestelle** [comment]
Moved this icon to the toggle section.
Fixed the broken index.
