### ISSUE TITLE
Update NPM to Version 4

### ISSUE THREAD

**Issue by astone2014** [google/material-design-icons#1080]
Any plans to update npm to 4.0.0 of material icons?

When I switched to the npm library from the hosted web font I was missing some icons.

**Comment by astone2014** [comment]
Looks like the new version is just missing from NPM. I'm sure you guys will eventually upload.

Thanks for the great icons!

**Comment by astone2014** [comment]
There is no longer any package.json. Is npm support being removed in 4.0?

**Comment by McGiogen** [comment]
The commit that deleted package.json is 1e4722ecb69f83fe2fd68d9f38b637a72ee0b93d, part of the pull request #1055 

This issue can be closed in favor of #1050
