### ISSUE TITLE
The SVG icons are not optimized and contain extra superfluous elements

### ISSUE THREAD

**Issue by user72356** [google/material-design-icons#1081]
The previous version of this repository had a "design" and a "production" version of the SVG icons. The design version had extra elements (such as paths, etc.), which I suppose were used during the design of the icons. The production version had these extra elements removed to lighten up the weight and simplify the SVG. This was quite beneficial for those of us who use the SVG icons in our pages. 

Now the current version of the repository only has the "design" version with the extra markup. If we're going to have access to to only 1 version, it would be most beneficial for most users that these be the lighter, production version.

Thank you

**Comment by RoelN** [comment]
Looks like this has been addressed in the meantime, so closing this issue for now. If not, feel free to reopen this issue!
