### ISSUE TITLE
Duplicate code name with same codepoint as another icon in MaterialIcons-Regular.codepoints: 'star_outline e83a'

### ISSUE THREAD

**Issue by juliettef** [google/material-design-icons#1082]
'star_outline' code name is duplicated and one of the instances has the same 'e83a' codepoint as 'star_border'

star_border e83a
star_outline e83a
star_outline f06f

https://github.com/google/material-design-icons/blob/96206ade0e8325ac4c4ce9d49dc4ef85241689e1/font/MaterialIcons-Regular.codepoints#L1331-L1334

**Comment by RoelN** [comment]
This looks like a bug in the original Material Icons font on fonts.googleapis.com, where a ligature is duplicated:

```xml
 <LigatureSet glyph="s">
            ...
            <Ligature components="t,a,r,underscore,o,u,t,l,i,n,e" glyph="uniE83A"/>
            <Ligature components="t,a,r,underscore,o,u,t,l,i,n,e" glyph="uniF06F"/>
```

@rsheeter This should be fixed in the font I think, after that this repo should be updated.

**Comment by rsheeter** [comment]
star_outline should be f06f. I'll pass this along internally.

**Comment by tphinney** [comment]
I think this has been long since resolved. In the latest variable fonts, there are fewer actual glyphs for star_(whatever) but the old codepoints and ligatures are still supported. Any fonts deriving from those should have the same functionality.
