### ISSUE TITLE
icon expand more too small

### ISSUE THREAD

**Issue by llooz** [google/material-design-icons#109]
Why some icons like ic_expand_more have a smaller content area?

**Comment by jestelle** [comment]
All our icons are designed to work well together and this particular icon is intended to be smaller and carry less weight than many of our other icons.

Are you finding a particular situation where it doesn't feel like it works for you?

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
