### ISSUE TITLE
Icon request: shield with moon

### ISSUE THREAD

**Issue by nielsfaber** [google/material-design-icons#1094]
For alarm systems, there are the:
- `shield-car` for 'armed away' mode
- `shield-home` for 'armed home' mode 

Would be great to have a shield to represent 'armed night' mode. 
It is very common in alarm systems to have this mode.
Would also be useful for Home Assistant.

**Comment by jalpadoshi** [comment]
The 'shield_moon' icon is now available on https://fonts.google.com/icons
