### ISSUE TITLE
[Icon Request] Cookie

### ISSUE THREAD

**Issue by CyberGen49** [google/material-design-icons#1095]
As the title describes, I think a cookie icon would be a great addition to the set/font.

I've been putting together a site and was pretty surprised to discover that there was no material cookie icon that I could use to represent a cookie notice. I opted for `push_pin` since I couldn't find anything else that fits.

Edit: If this isn't the place for icon requests, let me know where I should be posting.

**Comment by jalpadoshi** [comment]
The 'cookie' icon is now available on https://fonts.google.com/icons
