### ISSUE TITLE
[Icon Request] WhatsApp icon

### ISSUE THREAD

**Issue by IshaanRawat** [google/material-design-icons#1097]
A WhatsApp icon would be great help. Already loving the suite of icons this library has.
Have to add an extra svg everytime I have to use it.

P.S. A lot of social icons are missing.

**Comment by cyberalien** [comment]
Here: https://github.com/Templarian/MaterialDesign/blob/master/svg/whatsapp.svg

**Comment by mtenorio-cmp** [comment]
x2

**Comment by jalpadoshi** [comment]
Currently we are not able to add 3P  social icon requests to our catalogue

**Comment by xtance** [comment]
Wait, I think there was a whatsapp icon but then it got removed very recently.
This why tf one shouldn't rely on a CDN - things break without your interaction with them.. =|
