### ISSUE TITLE
Icon "dynamic_feed" missing on npm

### ISSUE THREAD

**Issue by sayantansinha** [google/material-design-icons#1098]
I read through a few issues (#1050 & #1055 ), and it seems like this icon "dynamic_feed" is another addition to the list.
What is the plan for keeping the npm package updated? Currently, I cannot this icon at all. Any pointers would be really appreciated.

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

**Comment by jjrauch32-lab** [comment]
Ok
