### ISSUE TITLE
Why was the grey600 removed?

### ISSUE THREAD

**Issue by forresthaynes** [google/material-design-icons#110]
I checked the git hub notes and I see that the check in for doing so says that it will be explained, but I can't find the explanation anywhere.

Tints don't work pre-android 5.0, so that will not work for my application.  I didn't know if the new suggestion was to only use black or white, or if it is a deprecated feature and I don't get a choice except for black and white now.

Any help provided is appreciated.

**Comment by jestelle** [comment]
@forresthaynes Great question!  And we'll be publishing some more documentation very soon to help make things more clear.

In short, the reason we removed grey600, is we've been seeing people incorrectly using these assets.
Grey600 is the equivalent to Black @ 54% opacity, on white.

Thus Grey600 assets are an appropriate substitute for using a black icon with opacity, but only when used on a white background.

We've found people using Grey600 icons on non-white backgrounds, which can look quite bad and is not desired.

We recommend using the black icon @ 54%.

Also, while you can't use the new Android 5.0 tinting APIs in older versions of Android, it is possible to tint drawables in older versions of Android, it just can take a little more code.

We'll be publishing some recommended best practices here soon.

I hope that helps clarify things, and do let me know if there are more questions.

**Comment by jestelle** [comment]
Check out this post: 
https://chris.banes.me/2015/04/22/support-libraries-v22-1-0/
Specifically the section about Drawable tinting.

That said, for Grey600, you probably don't actually want to tint the icon, but actually set the alpha to 54% on your icon button, and use the black icon.

**Comment by manastungare** [comment]
Hey Josh, not all places that accept an icon (on Android) support tinting today. 

E.g. Preferences XML files on Android allow a single android:icon attribute, but there’s no way to also specify a tint for that. Since 54% is the recommended opacity for that use case, the _grey600_ icons were a perfect match to use there.

I now have to go tint the icons myself, adding an unnecessary step to my build process.

**Comment by manastungare** [comment]
Also, most tinting requires code, whereas pre-tinted icons can be easily used in XML alone, leaving the code cleaner and skipping unnecessary CPU cycles.

**Comment by floating-cat** [comment]
Grey600 is not the equivalent to Black @ 54% opacity.
Actually it is #757575, not #8a0000 (Black @ 54% opacity). #757575 is darker than #8a0000.

If you use Android Studio 1.4 Beta 2, you can just use SVG version with the different `android:fillColor`, and the IDE would generate PNG version for you.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
