### ISSUE TITLE
[ICON REQUEST] Punch Clock (timecard)

### ISSUE THREAD

**Issue by piltorious** [google/material-design-icons#1102]
It would be great to have a punch clock or timecard icon. I didn't find anything in the existing icon set that was close. Great for enterprise apps dealing with HR, paychecks, etc.

**Examples**
https://cdn.iconscout.com/icon/premium/png-512-thumb/timeout-15-549480.png
https://cdn.iconscout.com/icon/premium/png-512-thumb/timeout-14-549316.png

**Comment by jalpadoshi** [comment]
The 'punch_clock' icon is now available on https://fonts.google.com/icons
