### ISSUE TITLE
[[ICON REQUEST] Google Home app style sprinker &/or a b-hyve icons

### ISSUE THREAD

**Issue by danielbrunt57** [google/material-design-icons#1103]
It would be nice to have this icon in addition to mdi-sprinkler-variant...
![Sprinkler System](https://user-images.githubusercontent.com/49846893/99156408-73289280-2675-11eb-9b41-7b063c690eed.JPG)
See [Google Home app adds proper sprinkler icons and controls](https://www.androidpolice.com/2019/10/10/proper-google-assistant-integration-comes-to-orbit-bhyve-smart-sprinkler/)

For a b-hyve icon, it looks like this...
![image](https://user-images.githubusercontent.com/49846893/99156477-fba73300-2675-11eb-9d37-17aaec5a4597.png)
Refer to [b-hyve icons](https://www.google.com/search?sxsrf=ALeKk025CSdFg5Yqp4nSagO5xKyCdW8veQ:1605386101509&source=univ&tbm=isch&q=b-hyve+icons&client=firefox-b-d&sa=X&ved=2ahUKEwj55rqi8YLtAhXYITQIHTgWCTgQ420oCnoECAsQPA&biw=1536&bih=722#imgrc=tYXN5fmR3oxefM)

And/or perhaps a more generic hive icon?
![download-bee-hive-icon-clipart-beehive-computer-icons-bee-863134](https://user-images.githubusercontent.com/49846893/99156732-3c07b080-2678-11eb-89c2-87be57de0cef.png)

**Comment by jalpadoshi** [comment]
The 'sprinkler' and 'hive' icons are now available on https://fonts.google.com/icons
