### ISSUE TITLE
Wrong icon for Book_online

### ISSUE THREAD

**Issue by milhomem** [google/material-design-icons#1104]
The icon we get from downloading and here in the source-code for material-design-icons/png/action/book_online/ is not the same we see here https://material.io/resources/icons/?icon=book_online&style=baseline

How can I find the correct one?

**Comment by RoelN** [comment]
The icon as PNG/SVG is indeed not the same as in the font. I marked this a bug so the design team can look into this. Thanks for reporting!

**Comment by 6643** [comment]
Hope to solve this small problem soon

**Comment by tphinney** [comment]
Currently the font and the catalog show the same thing, an icon that looks like this:
<img width="98" alt="Screen Shot 2022-04-27 at 10 16 11 PM" src="https://user-images.githubusercontent.com/6548266/165681286-1de57834-0370-4def-bb00-610605ed4e47.png">
 
I have to admit I don’t understand how this represents the concept of “book_online” and am not sure if this is correct and as intended.

**Comment by tphinney** [comment]
Looking at this again, I suddenly understood.
The word “book” in “book_online” is a VERB, not a noun. As in online booking to get a ticket to something.
