### ISSUE TITLE
ad_units.svg fails to upload to s3

### ISSUE THREAD

**Issue by softmarshmallow** [google/material-design-icons#1106]
I can upload other 5000 svgs, but only ad_units fails. tried other networks, other machine but always fails. 
I think something is missconfigured with the file itself.

`/material-design-icons/src/device/ad_units/materialicons/24px.svg`

**Comment by RoelN** [comment]
There doesn't seem to be anything wrong with the file itself. Perhaps it's an issue with allowed file names on S3 — maybe you can check?

Feel free to reopen if you believe the issue is with the file itself.

**Comment by softmarshmallow** [comment]
Not much with the file name.
i tried the different name, but something might be miss-configured with the metadata? (if it contains one)
