### ISSUE TITLE
The icon person_remove_alt is the same as person_remove

### ISSUE THREAD

**Issue by adrzip** [google/material-design-icons#1107]
Unlike person_add_alt where the plus sign is on the left side of the icon, person_remove_alt has the minus sign on the right side just like person_remove. In other words, there is no icon to remove person where the minus sign is on the left.

<img width="1066" alt="Screen Shot 2020-11-20 at 21 25 51" src="https://user-images.githubusercontent.com/5606128/99866492-37129780-2b77-11eb-91bb-bcf96fef14bf.png">

**Comment by tphinney** [comment]
At this point there is only one version for each of person_add and person_remove
So it seems the problem is resolved, though perhaps not in the manner expected!
