### ISSUE TITLE
Link dead to download fonts

### ISSUE THREAD

**Issue by rkristelijn** [google/material-design-icons#1109]
### Current

https://github.com/google/material-design-icons/README.md points to Read more in the font portion of our full developer guide. (https://google.github.io/material-design-icons/#icon-font-for-the-web). This points to Method 2: that points to `https://github.com/google/material-design-icons/tree/master/iconfont` which gives 404. 

### Desired

https://google.github.io/material-design-icons/#icon-font-for-the-web points to an url (unkown yet) to be able to download woff2, woff and ttf font files (preferably updated with the latest).

**Comment by RoelN** [comment]
This has been fixed, thanks very much for reporting!
