### ISSUE TITLE
Downloads include only "action" folder. Why? How can I get the all the icons?

### ISSUE THREAD

**Issue by ppeccin** [google/material-design-icons#111]

**Comment by jestelle** [comment]
There is a bug, we're fairly certain at Github, with how their zip files are produced.
You can see a lot of discussion on issue #8 

The simplest solution is to try downloading the zip [from here](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip)

Let me know if that doesn't work for you.
