### ISSUE TITLE
Include codepoints (e.g. e038) on website

### ISSUE THREAD

**Issue by Ben-CA** [google/material-design-icons#1110]
It would be **really nice** if the website for the material design icons (https://material.io/resources/icons/ ) gave us a nice simple way to get the icon codes (e.g. e038), not just the names as it does currently:

![image](https://user-images.githubusercontent.com/47060874/101209095-d08e7e80-3638-11eb-9c38-d7369d570e51.png)

I prefer to use the icon codes in my development, and I find myself constantly going here for reference:
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

**Comment by cyberalien** [comment]
That's not possible because of how new fonts are built. They don't have code points for all icons and code points that do exist are inconsistent across font variations. Fonts rely on ligatures, not code points.

**Comment by Ben-CA** [comment]
Maybe it's not possible for all of them... but it certainly would be for most, that have the codepoints specified here:
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

And when you say inconsistent across font variations - I'm just referring to the MaterialIcons font.

**Comment by cyberalien** [comment]
Oh, you are right. Missed that file and it does have everything, except for two tone icons. Doh.

**Comment by tomasdev** [comment]
Would love to better understand the use case on why you need the codepoint on Material Icons @Ben-CA

**Comment by Ben-CA** [comment]
I never use the ligatures in my code - always use the hex numbers. Not really sure why; I suppose it's shorter. So I find them here: https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

Would just save a bit of time if they were listed alongside the graphical view of the icon.

I see RoelN mentioned how another person (#936) wanted the same thing. Probably there's others who haven't bother posting.

**Comment by Ben-CA** [comment]
It appears there's been other requests (#772, #813) that would be resolved by having these codepoints listed directly alongside the ligatures where the graphical representation is shown.

**Comment by Ben-CA** [comment]
Also: #774, #772, #766, #531 - numerous people have wanted this, but might be explaining it slightly differently.

**Comment by tomasdev** [comment]
@Ben-CA thank you!

**Comment by arghlex** [comment]
@Ben-CA hi not sure if this might help for your situation, but I was having the same issue trying to get a specific icon codepoint, but then found the codepoints are listed on Google Fonts when you select one: https://fonts.google.com/icons

**Comment by Ben-CA** [comment]
Thanks @arghlex - that's exactly what I'm looking for. Not sure why they don't simply have this listed the same way everywhere (https://material.io/resources/icons/ ) 

https://fonts.google.com/icons has it quite nicely displayed:
![image](https://user-images.githubusercontent.com/47060874/110344355-030e9580-7ff3-11eb-9b9f-a28678d8060e.png)

**Comment by tomasdev** [comment]
The Fonts Icons site has launched recently, and thus we took your feedback. The Material icons site will eventually redirect to the new Fonts Icons :-)

**Comment by Ben-CA** [comment]
Cool!
