### ISSUE TITLE
Provide method to install 4.0.0 with npm

### ISSUE THREAD

**Issue by Lukenickerson** [google/material-design-icons#1113]
Problems:

* Running `npm install material-design-icons` installs 3.0.1 ([see npm](https://www.npmjs.com/package/material-design-icons))
* Running `npm install https://github.com/google/material-design-icons` gives an error.

Solutions:

* Publish latest version to npm 
* Include a `package.json` file in the root of this repo

**Comment by RoelN** [comment]
Closing this in favor of https://github.com/google/material-design-icons/issues/1085, which addresses the same issue.
