### ISSUE TITLE
https://materialdesignicons.com/ website is dead

### ISSUE THREAD

**Issue by LinoAlejandro** [google/material-design-icons#1114]
cant enter to website 
```
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by clomads** [comment]
its now showing a generic hosting template via WebFaction - commenting to stay in the loop

**Comment by trembylene** [comment]
Commenting to also stay in the loop for this one.

**Comment by TotallyNotInUse** [comment]
Just to let you know guys, the website is back up.
