### ISSUE TITLE
library is not working

### ISSUE THREAD

**Issue by EduardoSaavedra** [google/material-design-icons#1115]
I´m trying to enter to Material Desing Icons and isn´t working https://cdn.materialdesignicons.com/3.6.95/ also we are trying to get all the icons from  the version 3.6.95 and it seems that the cdn is dead
![image](https://user-images.githubusercontent.com/40034969/102813131-e2d52000-438d-11eb-8d91-0af0bcfe3a97.png)

**Comment by rnovec** [comment]
Same for v4.9.95
https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css

The CDN provider is dead

**Comment by clomads** [comment]
website is also down

**Comment by abons** [comment]
I had the same issue and switchen to another host. Find your version here: https://cdnjs.com/libraries/material-design-icons

Or download and host yourself

**Comment by trick0** [comment]
http://materialdesignicon.com/ (http, not https) is redirecting to untrustworthy sites

something like:
`filter.onwardclick.co ... CK5pJOmoA_0&t=535280911`

**Comment by ycycorona** [comment]
Can’t access the website too

**Comment by clomads** [comment]
> http://materialdesignicon.com/ (http, not https) is redirecting to untrustworthy sites
> 
> something like:
> `filter.onwardclick.co ... CK5pJOmoA_0&t=535280911`

I believe the official site is http://www.materialdesignicons.com - with an 's' at the end

**Comment by rsheeter** [comment]
materialdesignicons.com isn't ours. https://github.com/Templarian/MaterialDesign/issues/5692 (ty @abons) seems to suggest it's being rebuilt right now.
