### ISSUE TITLE
Please publish latest version to npmjs.org

### ISSUE THREAD

**Issue by KishanRanoliya** [google/material-design-icons#1117]
[NPM Repo](https://www.npmjs.com/package/material-design-icons)
![mdi](https://user-images.githubusercontent.com/31383892/103395560-aefbb680-4b54-11eb-97dc-f8842c098c2b.png)

**Comment by RoelN** [comment]
Closing this in favor of https://github.com/google/material-design-icons/issues/1085, which addresses the same issue.
