### ISSUE TITLE
dynamic_form icon shows as a microphone

### ISSUE THREAD

**Issue by scblur869** [google/material-design-icons#1118]
when using the CDN version of material icons from google the dynamic_form icon shows as documented here: https://material.io/resources/icons/?icon=dynamic_form&style=baseline

but when I downloaded the latest release locally and installed it in my angular project it shows as this icon under the same name as dynamic_form...
https://material.io/resources/icons/?icon=mic&style=baseline

**Comment by RoelN** [comment]
@scblur869 When you say "downloaded the latest release", where did you download it from? The fonts currently in this repo seem to point to the correct icon for `dynamic_form`?

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
