### ISSUE TITLE
Missing icons: chevron-down/up

### ISSUE THREAD

**Issue by epelc** [google/material-design-icons#112]
The chevron down and up icons are missing

**Comment by MGaetan89** [comment]
You mean `keyboard arrow down` and `keyboard arrow up` [here](http://google.github.io/material-design-icons/)?

**Comment by epelc** [comment]
Yes. Are they in this repo? I searched for `down` and only the dropdown caret came up.

**Comment by epelc** [comment]
O I see they are thanks!
