### ISSUE TITLE
dark_mode and light_mode icons are missing

### ISSUE THREAD

**Issue by dummyco** [google/material-design-icons#1124]
`dark_mode` and `light_mode` icons are available at https://material.io/resources/icons/, however, they are missing in this repository.

**Comment by ozgurg** [comment]
Yeah, I've been looking for these. :D

**Comment by tphinney** [comment]
They are in the latest variable fonts at least, and I think they may be in the others

**Comment by tphinney** [comment]
Just to clarify, when using the Material Symbols variable fonts (see https://fonts.google.com/icons)
Use default Grade for Light Mode
Use -25 Grade for Dark Mode
