### ISSUE TITLE
mat-autocomplete problem with formControl binding in reactive forms

### ISSUE THREAD

**Issue by Ric-01** [google/material-design-icons#1127]
Hi all,

I face the following issue when using material autocomplete version 11.0.3 together with Angular 11.0.9:
If coding the formControl property binding into the the connected input element like described on the documentation page together with reactive forms approach, the posted object is always null. 
I changed it by doing like follows:

Instead of 
<input type="text" matInput [formControl]="myFormControlName" [matAutocomplete]="auto" />
I did the following:
<input type="text" matInput formControlName="myFormControlName" [matAutocomplete]="auto" />
Only the latter one works in that sense, that the object posted from the input is not null in onSubmit event.

**Comment by RoelN** [comment]
This is the issue tracker for Material Design Icons, not for anything Angular :-) I suggest asking on an Angular forum/issue tracker.
