### ISSUE TITLE
No index.html

### ISSUE THREAD

**Issue by MrChris123** [google/material-design-icons#113]
The readme.md refers to an index.html file to easily view the icons. Is there a reason this no longer exists?

**Comment by indexing** [comment]
I think this is the link you reference? (readme.md > What's Included? > ...live preview...)

http://google.github.io/material-design-icons/

This page is incredibly useful for searching all icons by name to find the one your need.

**Comment by jestelle** [comment]
This is the file it refers to, which is at the link mentioned above:
https://github.com/google/material-design-icons/blob/master/index.html

**Comment by MrChris123** [comment]
Thanks,

Amazingly fast turn around. I expected the file to be part of the download, otherwise you have to remember to update your local version are new releases become available.

**Comment by MrChris123** [comment]
Okay I see this was a Windows extractor issue, and the index.html is in the download. Thanks

**Comment by jestelle** [comment]
Curse that Windows extractor bug!  Glad you figured it out!
