### ISSUE TITLE
outlined_flag isn't always outlined

### ISSUE THREAD

**Issue by RoelN** [google/material-design-icons#1130]
Filled:
![image](https://user-images.githubusercontent.com/4570664/105728414-6f927100-5f2c-11eb-8aa2-a0c71d7ac9e3.png)

Outlined:
![image](https://user-images.githubusercontent.com/4570664/105728448-7620e880-5f2c-11eb-9e4b-9c49b2d8bf6a.png)

Rounded:
![image](https://user-images.githubusercontent.com/4570664/105728474-7b7e3300-5f2c-11eb-8589-af6258b0538c.png)

Two-tone:
![image](https://user-images.githubusercontent.com/4570664/105728500-820caa80-5f2c-11eb-92a8-93953d378c31.png)

Sharp:
![image](https://user-images.githubusercontent.com/4570664/105728514-8638c800-5f2c-11eb-9809-ec6bb6ebbdd0.png)

**Comment by tphinney** [comment]
At some point since, this was fixed!
Go here: https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=flag&icon.style=Outlined
And try clicking the different styles. All looks good now!
