### ISSUE TITLE
Sharp and non_sharp version of "action::contact_support" are (99%) identical in SVG, not as a font.

### ISSUE THREAD

**Issue by NicolasBonduel** [google/material-design-icons#1133]
https://github.com/google/material-design-icons/blob/master/src/action/contact_support/materialicons/24px.svg
https://github.com/google/material-design-icons/blob/master/src/action/contact_support/materialiconssharp/24px.svg

Here is a diff: https://editor.mergely.com/gaaxqvrO/

On the website / as a font, they are different.

https://material.io/resources/icons/?search=contact_support&style=baseline
https://material.io/resources/icons/?search=contact_support&style=sharp

**Comment by RoelN** [comment]
If I'm viewing them side by side, I don't see any difference?

<img width="1531" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/106596303-17272900-6555-11eb-87ef-b57b7db924d6.png">

**Comment by RoelN** [comment]
@NicolasBonduel Could you perhaps elaborate on where you see the difference, as both the SVGs and the fonts seem to have the exact same icon?

**Comment by NicolasBonduel** [comment]
Hi @RoelN 

This is correct, they are currently the same. They were slightly different as font when I created the issue.

**Comment by RoelN** [comment]
Ok, hopefully that solves the issue! :-)
