### ISSUE TITLE
Advanced export invalid scaling

### ISSUE THREAD

**Issue by TheChilliPL** [google/material-design-icons#1135]
I tried to export an icon with these settings:  
![image](https://user-images.githubusercontent.com/18823939/106146601-26822d00-6177-11eb-8382-2f312757e7e5.png)
Yet the actual icon is way smaller than that:
![newspaper](https://user-images.githubusercontent.com/18823939/106146648-369a0c80-6177-11eb-882b-5264f047dad0.png)

**Comment by RoelN** [comment]
Is this on https://materialdesignicons.com/custom?

**Comment by TheChilliPL** [comment]
No, it's right there
![image](https://user-images.githubusercontent.com/18823939/106881773-3b624180-66de-11eb-8d12-7049d893b6cd.png)

**Comment by cyberalien** [comment]
That website is for different icon set, not Google's set.

Their GitHub repository is here: http://github.com/Templarian/MaterialDesign

**Comment by TheChilliPL** [comment]
Right, I have no idea how I confused it. Closing the issue
