### ISSUE TITLE
'no_accounts' codepoint is missing

### ISSUE THREAD

**Issue by carlosanjos** [google/material-design-icons#1136]
The codepoints files are missing some icons like 'no_accounts'. Therefore there isn't an easier way of finding what is the glyphs code.

The files sit here [https://github.com/google/material-design-icons/tree/master/font](https://github.com/google/material-design-icons/tree/master/font)

**Comment by JanMalch** [comment]
Also icons like `open_in_new` and `logout` (related to #1132 ?) are missing in the iconfont files. Is there a workaround?

**Comment by odysseus654** [comment]
FWIW I just checked this repo out and did an "npm install" "npm run build" and got updated files in the "dist" folder, including the "no_accounts" icon

**Comment by Download** [comment]
@JanMalch Yes it is. This repo was once published to NPM and the instructions in the material design developer guide still tell you to install ir, but in fact it hasn't been updated in years, causing much grief with issues like this one.

For now: you should `npm uninstall --save material-design-icons`, download the iconfont and css and self-host it, or use the google web font. But not this package.

I feel this package *should* be on NPM. It was and those that did that did good work imho. But the current maintainers don't seem to 'get' NPM or Javascript development so they don't think updating the NPM package is worth their time.  Maybe you can join the discussion in #1129 and let us know what you think: should this package be published to NPM on each release?

**Comment by ViRuSTriNiTy** [comment]
@JanMalch I always wondered why some icons are not working but I did not spent to time to investigate it ... and now i'm reading your comment about the NPM package being not updated for years. That is really sad. For sure it should be on NPM, you have my vote!

**Comment by tphinney** [comment]
codepoints files are up to date these days, and updated with new font updates
NPM has its own issue
So, I *think* everything from this issue is either resolved, or covered more clearly/specifically elsewhere. Let me know if you think I am mistaken!
