### ISSUE TITLE
Request: offer new icons of "paste&search" , "paste&go"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#1138]
No idea how those will look like, but maybe paste icon together with maginifier-glass for "search", or together with left-to-right arrow for "go".

**Comment by jalpadoshi** [comment]
The 'content_paste_search' and 'Content_paste_go' are now available on https://fonts.google.com/icons

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi Interesting. Thanks.
