### ISSUE TITLE
Please line+axis graph icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#1143]
The one we have is a bit like lightning:

![image](https://user-images.githubusercontent.com/5357526/109065972-0e111e00-76f5-11eb-8448-d0a3ed0eae63.png)

I'd prefer to have a more known illustration of a graph, with about the same content, but with axis too.

**Comment by jalpadoshi** [comment]
This icon 'line_axis' is now available on https://fonts.google.com/icons

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/129679895-b08921d9-26f0-4bef-93c0-d25cd80cef30.png)
