### ISSUE TITLE
Request: please add ECG icons

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#1144]
There are various nice ones, and Android has some support for heart rate monitoring, so I think it's a good thing to have it too, even in various forms.

**Comment by jalpadoshi** [comment]
Thank you for your request, the ECG (monitor _heart) icon is now available at https://fonts.google.com/icons

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi This:
https://fonts.google.com/icons?icon.query=monitor+heart
?
Please also without the rectangle.
