### ISSUE TITLE
Request: Brands & Services

### ISSUE THREAD

**Issue by zigojacko** [google/material-design-icons#1147]
Paypal, WordPress, WooCommerce, Magento, Shopify, Google, Twitter, LinkedIn, Instagram, Pinterest

Tons of icons like this really needed - is there any plans for these ?

**Comment by brmscheiner** [comment]
+1, also a Github icon would be really nice. I'm confused about why some of these icons are available as [React Material Icons](https://material-ui.com/components/material-icons/) but not here. Could someone shed some light on what differences to expect?

**Comment by ridhwaans** [comment]
also, the IMDB icon

**Comment by jalpadoshi** [comment]
At this point we are not able to add any 3P Brand icons to our library due to legal implications.

**Comment by earboxer** [comment]
There are currently a number of brand icons included in this font in various formats, e.g. [svg](https://github.com/google/material-design-icons/blob/master/src/social/facebook/materialicons/24px.svg). For whatever reason, they aren't searchable in https://fonts.google.com/icons?selected=Material+Icons

@jalpadoshi Should these brand icons be removed from this project? (I feel like brand icons don't belong in a general-purpose icon-pack).
