### ISSUE TITLE
Icon listing page, needs view all option

### ISSUE THREAD

**Issue by robertbaker** [google/material-design-icons#115]

**Comment by Alien1993** [comment]
I totally support this, the old layout was much more useful and simple.

**Comment by hatemsh** [comment]
+1

**Comment by indexing** [comment]
+1

I miss the option to see all icons at once for browsing. I don't find it necessary to see all sizes of the icon on this page, as this information is apparent when viewing assets at the file level.

I also miss being able to search the full set based on asset name.

**Comment by robertbaker** [comment]
I like the sizes, but it would be better implemented via a slider control like FontAwesome.

I like the new page but it needs some features.

**Comment by DanDixon** [comment]
Agreed. The old page was better.

**Comment by KevinLaRosa** [comment]
+1

**Comment by KyleDBoyd** [comment]
+1

**Comment by gitfdy** [comment]
+1

**Comment by Ugoku** [comment]
+1
The old page was much more useful.

**Comment by jestelle** [comment]
Sorry this temporary page was less useful all, it was in preparation of our updated documentation and our new library launched this morning:

https://www.google.com/design/icons/

Keep the feedback coming and let us know how we can improve the site.

**Comment by MGaetan89** [comment]
It looks great now! Good job!

I have one suggestion: would it be possible to select multiple icons to download at once?

**Comment by robertbaker** [comment]
Looking at the new library. It had a view all and search option. So I'm closing this issue.

**Comment by Ugoku** [comment]
Awesome, looks great now :)

**Comment by jestelle** [comment]
@MGaetan89 We considered that in our design, but found the simplicity of single selection to be advantageous in some ways.  It's not something we're strictly tied to though, so let us know your particular work flow that would be aided by multiselection and multidownload, and we'll take it into consideration for future updates.

**Comment by MGaetan89** [comment]
I agree that single update should stay as easy as two clicks.
Maybe use <kbd>ctrl</kbd> + <kbd>click</kbd> (<kbd>cmd</kbd> + <kbd>click</kbd>) to select multiple icons? It's a common shortcut for multi-selection.
And why not add the ability to expand the bottom bar to see all selected icons?
