### ISSUE TITLE
Typekit Support

### ISSUE THREAD

**Issue by somratpro** [google/material-design-icons#1152]
Is there any way to add material icons with Typekit? like we add google fonts via Typekit

```
WebFont.load({
    google: {
      families: ['Roboto']
    }
  })
```

**Comment by RoelN** [comment]
I don't think Adobe will carry Google's icons :-) But you can use them through Google's own services: https://fonts.google.com/icons

**Comment by somratpro** [comment]
Actually, I found a way to add Google Icons via Typekit. Thanks anyway...
