### ISSUE TITLE
Social Icon Request

### ISSUE THREAD

**Issue by somratpro** [google/material-design-icons#1153]
We need all the social icons like Twitter, Github, Linkedin, Youtube etc...

**Comment by SalahAdDin** [comment]
This issue has two months, it is crazy to see there is no a Google Icon, come on, these are Google Fonts, hahahaha.

Also, for Apple ID and others, it would be great to have them here.

**Comment by jalpadoshi** [comment]
Hello, At this point we are not able to support any third party brand icons in our icon library due to legal implications.
