### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Calinou** [google/material-design-icons#116]
The README.md says this:

> We'd love attribution in your app's about screen, but it's not required. The only thing we ask is that you not re-sell the icons themselves.

Not only using CC BY 4.0 *requires* attribution, but it also doesn't allow the licensor to forbid selling like this.

**Comment by jestelle** [comment]
Hi Calinou,

I'm not a lawyer so I won't speak to the legal details – but our intention is to keep these icons free and make them easy to use.

We had lots of questions about attribution, so we're trying to make it clear that you can omit it if you want, and we won't mind.

As for reselling, we're aware the license doesn't specifically forbid this, but it's something we're asking folks not to do.

If things are still confusing, we'll revisit our licensing.

**Comment by Calinou** [comment]
> If things are still confusing, we'll revisit our licensing.

The “no selling” clause is incompatible with some sites like [opengameart.org](http://opengameart.org/), which is why I would like to get it removed.

[This article](http://freedomdefined.org/Licenses/NC) is somehow relevant to this issue, too.

**Comment by dessant** [comment]
@jestelle, could you reopen this issue?

There can't be an explicit requirement in a license and anecdotal 'we don't mind' on the other hand.
This creates confusion and also liability for some developers.
Please either update the readme about the attribution requirement, or pick a license that suits your real intentions.

**Comment by jestelle** [comment]
Feel free to strictly follow the CC-BY license.  That is what these icons are licensed under.

Some aspects of that license are vague however, e.g., attribution, and when asked for clarity, we've clarified by saying we don't actually care that much about the attribution.

That said, we hear the confusion, and we'll keep talking about it with our product consul to see if we can find a better solution, I just can't guarantee it'll change soon.
