### ISSUE TITLE
Request: stop_circle_filled and stop_circle_outline

### ISSUE THREAD

**Issue by SlvrEagle23** [google/material-design-icons#1160]
Play and Pause already have these variants in the material icon set, but unfortunately the current `stop_circle` in the filled collection is literally filled, as in it's just a complete circle. I'm not sure if this is an error or if this was intentional, but it's certainly not possible to distinguish the character from a filled circle.

It would be especially helpful to have the `_filled` and `_outline` variants of the Stop icon alongside the current variants for player controls.

**Comment by tphinney** [comment]
I think this has since been addressed!
Certainly in the Material Symbols version (including the variable font), it is working as expected
https://fonts.google.com/icons?icon.set=Material+Symbols&icon.query=stop+circle&icon.style=Outlined
