### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by ashleedawg** [google/material-design-icons#1170]
Documentation located at [google.github.io/material-design-icons](https://google.github.io/material-design-icons) has several outdated/broken links, including:

Anchor Text | Broken Link
-- | --
_sprites directory of the git repository_ | https://github.com/google/material-design-icons/tree/master/sprites
_maps/svg/production_ | https://github.com/google/material-design-icons/tree/master/maps/svg/production
_material design icons guidelines_ | https://www.google.com/design/spec/style/icons.html#icons-system-icons
_autoMirrored attribute_ | https://developer.android.com/about/versions/android-4.4.html#DrawableMirroring

**Comment by ashleedawg** [comment]
<sub>_(I'm surprised that neither Google nor GitHub have an automated process to catch things like this!)_</sub>

**Comment by tphinney** [comment]
Funny, I was just asking about that doc site myself a few days ago! Apparently it is an old deprecated site, and Google has no links going to it. But it should probably be removed from public viewing, or else folks like us will continue stumbling across it.
