### ISSUE TITLE
New icon suggestion: f(x) (Function)

### ISSUE THREAD

**Issue by liesislukas** [google/material-design-icons#1173]
Not sure if it's a correct place to add such suggestion, yet, here it is:

Seems like a general purpose icon needed by quite a bit technical products. I personally missed it multiple times through years of using material. Icon would mean "function" or "custom function".All image would be just F(x) or similar. Adding sample icon. This sample is not following material design guidelines for icon, but it's just a reference for more context.

![image](https://user-images.githubusercontent.com/2733862/117798574-f0fedc80-b259-11eb-8ae8-b8f40288ac10.png)

**Comment by tphinney** [comment]
Although the files in the repo have not been updated to reflect this yet, the live Google Symbols font has been updated with this, and it can be browsed online at https://fonts.google.com/icons?icon.query=function

**Comment by tphinney** [comment]
@EsoFromTheEast please close when you have updated the repo with both SVG and TTF

**Comment by tphinney** [comment]
This was done

**Comment by liesislukas** [comment]
awesome, thanks for update :)
