### ISSUE TITLE
The getter 'sell' isn't defined for the type 'Icons'

### ISSUE THREAD

**Issue by j-j-gajjar** [google/material-design-icons#1174]
I think [this ](https://fonts.google.com/icons?selected=Material+Icons:sell) icon is deprecated.

And I used [`local_offer`](https://fonts.google.com/icons?selected=Material%20Icons%3Alocal_offer)  instead, which is like that!

**Comment by jayesh-srivastava** [comment]
Hi, I would like to work on this issue, can you please guide me through what you want to be done for this issue.

**Comment by tphinney** [comment]
"sell" exists in both Material Icons and its successor, Material Symbols

**Comment by tphinney** [comment]
https://fonts.google.com/icons?icon.query=sell
