### ISSUE TITLE
Two Tone icon color not apply

### ISSUE THREAD

**Issue by dropways** [google/material-design-icons#1176]
https://fonts.google.com/icons
![image](https://user-images.githubusercontent.com/38377336/118394110-4f63fa80-b660-11eb-9f07-ca65aff2eaa1.png)
![image](https://user-images.githubusercontent.com/38377336/118394126-6571bb00-b660-11eb-8b53-63e0dfcfcab2.png)

**Comment by Simon-live** [comment]
I have the same trouble with that, I want to know how to solve this problem, could you find the way?

**Comment by rsheeter** [comment]
To alter the color of two tone you need to use CSS features specific to color fonts, see https://www.w3.org/TR/css-fonts-4/#color-font-support.

https://bugs.chromium.org/p/chromium/issues/detail?id=1170794 tracks support for these in Chrome.

As this will be solved by user agent support and not by a change here I am closing this issue.

**Comment by tphinney** [comment]
See https://www.w3.org/TR/css-fonts-4/#at-ruledef-font-palette-values for more details. (Pretty sure the fonts do not have multiple color palettes, and even if they did to get arbitrary colors one needs support for user-defined palettes.)

It appears to me that Chrome has just recently added such support in late May: https://bugs.chromium.org/p/chromium/issues/detail?id=1170794

Perhaps Firefox is the most major browser that does not yet do this.
