### ISSUE TITLE
Having trouble creating woff and woff2 versions

### ISSUE THREAD

**Issue by leoselbach** [google/material-design-icons#1188]
I need to create woff and woff2 versions to support older versions of Android/iOS. What I'd usually do is upload the ttf file to whatever font converter website and then I'd download the files I needed. However, this simply isn't working anymore with the new MaterialIcons-Regular.ttf. Most sites will say the font is corrupted, even though it's working well on dev and I've tried uploading it from different PCs/internet connections. 
What should I do?

**Comment by leoselbach** [comment]
For some weird reason, Font Squirrel worked for me today, even though it didn't work yesterday. That's good enough for me. Thank you for your time.

**Comment by rsheeter** [comment]
For future reference, https://github.com/fonttools/fonttools or the woff2 commandline utility (ref https://rsheeter.github.io/font101/#compression) should be able to make you a woff2 of these fonts; if they don't that is a bug we would fix.

**Comment by leoselbach** [comment]
Thank you for the info!
Also here for future reference: Fontsquirrel will set the webfont generation setting as optimal, and that will still break with material font. The only way to make it work is to set processing to Basic, as shown here.
![image](https://user-images.githubusercontent.com/86311807/122995383-ed459600-d37f-11eb-9a09-0a3fedfe014e.png)

**Comment by jpike88** [comment]
why not just create woff/woff2 version in this repo?
