### ISSUE TITLE
Icon request : wired network

### ISSUE THREAD

**Issue by abond** [google/material-design-icons#119]
![ethernet-icon2-300x225](https://cloud.githubusercontent.com/assets/869562/7877581/c2f5abce-05e5-11e5-83d3-e97f4f09ffed.png)

**Comment by wildhart** [comment]
+1

**Comment by jalpadoshi** [comment]
We currently cannot provide 3P product icons/logo in our catalogue.

**Comment by jalpadoshi** [comment]
Icon is available at fonts.google.com/icons. Similar to sitemap
