### ISSUE TITLE
Touch gestures

### ISSUE THREAD

**Issue by Malvoz** [google/material-design-icons#1192]
A humble request for touch gesture icons:

Touch Gesture Reference Guide: https://www.lukew.com/ff/entry.asp?1071
(PDF: https://static.lukew.com/TouchGestureGuide.pdf)

https://github.com/google/material-design-icons/issues/890 is related.

**Comment by tphinney** [comment]
There are a whole set of these now!
Here’s what they look like in our font source:
<img width="1028" alt="Screen Shot 2022-04-23 at 10 45 53 PM" src="https://user-images.githubusercontent.com/6548266/164958452-acfe6f02-d046-40a8-8620-1f9add2d264d.png">

Is there anything important missing?
