### ISSUE TITLE
Handshake icon

### ISSUE THREAD

**Issue by mothegoat** [google/material-design-icons#1194]
Hello.
First of all thanks for the gorgeous list of icons. I would like to recommend adding a handshake icon. I wanted to add an icon to show deal and agreement and couldn't find a decent icon for that.
Thank you.

**Comment by tphinney** [comment]
There is such an icon now! Called simply "handshake"
In the fonts it is encoded at U+EBCB (or use the ligature to access it)
https://fonts.google.com/icons?icon.query=handshake

**Comment by alexgyger** [comment]
Hi @tphinney 
Thanks for all these great icons!
As I am currently looking for a "handshake" icon in a business context I had a closer look at your version, so I noticed that your implemented version has two **LEFT hands** doing the handshake. 
As it might be possible that there are cultures or groups of people (e.g. "scout handshake") that uses their left hands to greet, I could imagine this seems a bit strange for the majority of the people in a general (business) context (such as the West, India, Europe,...).
As I plan to use your version, I will just flip the SVG horizontaly before giving it to my devs.
You could either:
- Just flip the current design horizontally, so it looks that right hands are shaking hands which seem more natural e.g. common
- publish a Left and a Right version

Thank you
<img width="1403" alt="Bildschirmfoto 2023-07-25 um 13 43 33" src="https://github.com/google/material-design-icons/assets/29924259/52c7c084-6eec-4a26-be6c-13af69e75298">
