### ISSUE TITLE
Add twitter icon

### ISSUE THREAD

**Issue by Chandler-Zhu** [google/material-design-icons#1197]
There is already a facebook icon, I hope there will be a twitter icon as well

**Comment by PaulTodd** [comment]
I have a need for the twitter icon for my social media button area to be consistent.

**Comment by Whip** [comment]
Where's the facebook icon? I can't find it here: https://fonts.google.com/icons

**Comment by tphinney** [comment]
Apologies for the confusion this has created; Google has been eliminating 3rd-party app icons from Google Symbols, which are generally trademarks of the companies involved.
