### ISSUE TITLE
Problem trying to unzip the zipped file after downloading from the git repository

### ISSUE THREAD

**Issue by sabino4857** [google/material-design-icons#1198]
After clicking on the link and downloading the file, when trying to unzip you are asked for the password. The error occurs when the download is done using the zip download button, or when clicking on the source code option link.

zip download button:
![01](https://user-images.githubusercontent.com/69438033/126880372-82e612af-2f56-4cce-8c9b-9a679b0d25d7.jpg)

source code option link:
![03](https://user-images.githubusercontent.com/69438033/126880377-5f9be383-ba93-448b-a661-a1b6ea38d042.jpg)

message requesting password to unzip:
![02](https://user-images.githubusercontent.com/69438033/126880376-fed8515a-06ac-4574-8097-a67f159dc2b0.jpg)

**Comment by tphinney** [comment]
I believe this has been long since fixed.
