### ISSUE TITLE
SVG icons: 24px.svg versus 20px.svg

### ISSUE THREAD

**Issue by user72356** [google/material-design-icons#1214]
I've noticed that in the SVG folder, some icons have more than 1 file in their folder. 24px.svg appears to be the standard file, and I sometimes see 20px.svg and 18px.svg. The SVG markup isn't the same across the different files (same icon look but different markup). For example the "android" icon.

Does that mean I should use 20px.svg or 18px.svg rather than 24px.svg when displaying at these smaller sizes? Are these alternate files better optimized for icons displayed at less than 24px?

Thanks

**Comment by tphinney** [comment]
In the current svg files, mostly the outline designs are optimized for that *specific* px size. Outlines may fall on exact pixel boundaries, at least some of the time, when using the 24 px icon at exactly 24 px.
