### ISSUE TITLE
Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

### ISSUE THREAD

**Issue by farukranabappy89** [google/material-design-icons#1216]
Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). delete

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

_Originally posted by @googlebot in https://github.com/google/material-design-icons/issues/605#issuecomment-298988471_

**Comment by tphinney** [comment]
So, is the problem that you don’t understand the message?
Or did you sign the CLA and are waiting?
Or...?
