### ISSUE TITLE
I had this bug as well and can confirm that the fix worked without any issues so far.

### ISSUE THREAD

**Issue by maryfranharper** [google/material-design-icons#1218]
I had this bug as well and can confirm that the fix worked without any issues so far. 

Fedora 34
clang version 12.0.0 (Fedora 12.0.0-2.fc34)
Target: x86_64-unknown-linux-gnu
Thread model: posix

_Originally posted by @sitemoth in https://github.com/google/googletest/issues/3550#issuecomment-918517703_

**Comment by d3feld** [comment]
Same same here for us! VOTE UP FOR FIX!
