### ISSUE TITLE
How to obtain MaterialIcons-Regular.ttf with all codepoints displayed by https://fonts.google.com/icons

### ISSUE THREAD

**Issue by rjhyde58** [google/material-design-icons#1219]
I have used URL https://fonts.googleapis.com/icon?family=Material+Icons in chrome to obtain the URL of the woff2 resource that contains the codepoints displayed by URL https://fonts.google.com/icons. Following other advice, I used the same URL in IE 11 to obtain the woff resource which also seems up to date.

My issue is that I cannot seem to get a version of the MaterialIcons-Regular.ttf with a matching set of codepoints. The version that I can download from URL https://github.com/google/material-design-icons/tree/master/font is missing codepoints like "ads_click", "cottage", "crib", "houseboat", "iron" to name a few.

Is this resource available? If yes, please provide the necessary details.

**Comment by hbugdoll** [comment]
This public GitHub repo is not automatically synchronized with Google Fonts.
Last manually update was in May 2021, see https://github.com/google/material-design-icons/commits/master/font

**Comment by tphinney** [comment]
The fonts have been updated since, should be OK by now.
(Apologies, I know the bug was filed a long time ago.)
