### ISSUE TITLE
Regular (Baseline) version looks corrupted from Win7 latest browsers

### ISSUE THREAD

**Issue by davidtaubmann** [google/material-design-icons#1220]
I really don't understand the problem, but I've been able to replicate it on another Win7 64bit machine nearby.

Firefox (v92) sends no relative error in the console, but Google Chrome (v93) states:
```
Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
OTS parsing error: Unable to instantiate font face from font data.
```

Using Google hosted (https://fonts.googleapis.com/css2?family=Material+Icons+...) alternate versions (Sharp, Outlined, Round or Two+Tone), they still don't work but in those cases I get no error in the Google Chrome console. 

**PARTIAL SOLUTION: When downloading the exact same files pointed from Google hosted CSS's and using them hosted on my own servers, I DO can make them work, just not the Regular/Baseline version.**

I can even see the error on both computers from the Incognito Mode window in the official developers.google.com website and the official icon set using the baseline or "Filled" version ( https://fonts.google.com/icons?selected=Material+Icons ) , 

I'm including an image of how developers.google.com looks, where you can appreciate the icons being replaced by their text:
![image](https://user-images.githubusercontent.com/6922384/133369774-abc959cc-50ce-4c4a-b880-a1cf45eaebd8.png)

**Comment by HimanshuSingh2308** [comment]
facing the same issue 
![invoice](https://user-images.githubusercontent.com/40028955/133385045-235fccfc-33bf-4edf-9d8e-9c934201cfd1.png)

**Comment by SnaiCrys** [comment]
same issue on win7

**Comment by nicenerd** [comment]
same!

**Comment by VladimirDyachenko** [comment]
Same issue. On Windows 10 in same room works fine. On all Windows 7 machines in all browsers getting this error. 

> Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
> icons:1 OTS parsing error: Unable to instantiate font face from font data.
> 

![image](https://user-images.githubusercontent.com/26563392/133395751-57c3dec2-4e8d-4c69-b3b3-93461b4d6eb0.png)

**Comment by wordsire** [comment]
![FontIssue](https://user-images.githubusercontent.com/40787109/133398127-321ee05f-f68f-47bc-9214-9e7bf5df50c5.PNG)

same issue.

`Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
OTS parsing error: Unable to instantiate font face from font data.
`

**Comment by chongma** [comment]
Same issue here too
```
Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
OTS parsing error: Unable to instantiate font face from font data.
```
![Screenshot from 2021-09-15 10-47-59](https://user-images.githubusercontent.com/6253322/133410188-467d55e6-740a-4ede-8b51-957f2e39e546.png)

**Comment by ViniciusMargotti** [comment]
Same problem , only Windows 7
```
Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
OTS parsing error: Unable to instantiate font face from font data.
```


![58641984-1a37-4cf6-bc52-9835bdef2f65](https://user-images.githubusercontent.com/26387908/133422914-b3485fe8-fafc-4973-9ec1-a1c68e73b794.png)

**Comment by KicKerBNU** [comment]
We have the same problem here... Windows 7 not showing material-icons

**Comment by oneart-dev** [comment]
+1

**Comment by rsheeter** [comment]
Thank you, it will be rolled back.

Reporting your exact OS version and browser version would be helpful; thus far we're having trouble reproducing.

**Comment by garretrieger** [comment]
Rollback just completed for the fonts. Can you confirm if the OTS errors have gone away (be sure to reload with cache disabled or clear your cache)

**Comment by ViniciusMargotti** [comment]
@rsheeter , resolved!! 

Browser version  Chrome: version 93.0.4577.63
OS version   : Windows 7 Ultimate Service Pack 1

**Comment by davidtaubmann** [comment]
> Thank you, it will be rolled back.
> 
> Reporting your exact OS version and browser version would be helpful; thus far we're having trouble reproducing.

@rsheeter , THANKS! ALSO RESOLVED IN HERE (with a Hard Refresh [Ctrl+F5])

Computer 1: 
- Firefox: 92.0 (64-bit)
- Chrome: Versión 93.0.4577.82 (Build oficial) (64 bits)
- OS version : Windows 7 Ultimate Service Pack 1

Computer 2: 
- Firefox: 72.0.20 (64-bit)
- Chrome: Versión 93.0.4577.82 (Build oficial) (64 bits)
- OS version : Windows 7 Ultimate Service Pack 1

Anyways, I'm backing up the current Font files, for any case, and for LAN usage. Nice day!

**Comment by garretrieger** [comment]
I'm trying to narrow down the change that introduced the OTS failure and we haven't been able to reproduce on our test machines yet. Would you be able to try out this test page: https://cdpn.io/garretrieger/debug/WNOXKRE/nqMwvzxbxDyk and let me know if the house icon beside fails to render for either of the A or B line?

**Comment by leovarmak** [comment]
@garretrieger the codepen link expired. can you share a new one?

**Comment by ViniciusMargotti** [comment]
@garretrieger 
Hello, the problem reoccurred in Win7, was there any update?

**Comment by garretrieger** [comment]
Try this one: https://codepen.io/garretrieger/pen/WNOXKRE

**Comment by garretrieger** [comment]
@ViniciusMargotti try clearing your cache you may be getting css files cached at the previous version.

**Comment by ViniciusMargotti** [comment]
@garretrieger , We forced the cache to clear, however, we checked that there were temporary files in the %temp% folder, and it solved our problem, so far so good, thanks
