### ISSUE TITLE
Merge latest changes from Google Fonts is necessary

### ISSUE THREAD

**Issue by erneandroid** [google/material-design-icons#1221]
- [x] When releasing V5 of material Design icons get it from Fonts by Google is hard one by one.

**Comment by tphinney** [comment]
I am assuming this has long since been addressed, correct?
If not, please explain a bit more clearly what your concern is, as I am not sure I understand from that question.

**Comment by erneandroid** [comment]
Sorry I understand now that is not necessary to wait for a release when we can get the content directly from the source code.
Btw latest icons updates changes that were pushed at good fonts are not into the latest icon font.

**Comment by tphinney** [comment]
Sorry, I don’t understand that last sentence. Can you be more specific as to _exactly_ where you are seeing the “good fonts” and where you are not seeing the latest? URL or directory? Much appreciated!

**Comment by erneandroid** [comment]
By "good fonts" I meant "google fonts", (sorry autocorrect of keyboard did it)

Sure I'll give you the link: https://fonts.google.com/icons?icon.set=Material+Icons

I was referring that those are the latest icons and its changes have been not merged with the latest icon font

**Comment by tphinney** [comment]
Aha. So, there are really two sources here. Material Icons (the “classic” version) and Material Symbols (the “new” version with the variable font source, and where Google is putting its focus moving forward). So use the drop-down menu at left to switch, or change the last word in the URL from "Icons" to "Symbols"

If you enter the URL without specifying an icon set (https://fonts.google.com/icons), you will get Material Symbols.  :)

**Comment by tphinney** [comment]
@erneandroid does that address your concerns?

**Comment by erneandroid** [comment]
Yes, it's time to close the issue
