### ISSUE TITLE
weight icon?

### ISSUE THREAD

**Issue by tommyhome** [google/material-design-icons#1227]
Hi,
would love to see a weight icon, something like:
![weight@10x_black](https://user-images.githubusercontent.com/546576/134821435-661d03e2-56ba-4194-98eb-13977e635755.jpg)

**Comment by MrTechHunter** [comment]
Hi mate 😊,
This is my PR: https://github.com/google/material-design-icons/pull/1228
Hope to solve the issue 🎉

Sincerely,
Mahdi Hamldar

**Comment by MrTechHunter** [comment]
Hello!
Please merge my PR to main😊
@rsheeter

**Comment by MrTechHunter** [comment]
Hi mate 😊 @rsheeter,
This is my PR: https://github.com/google/material-design-icons/pull/1230
Hope to solve the issue 🎉

Sincerely,
Mahdi Hamldar

**Comment by MrTechHunter** [comment]
> Hi, would love to see a weight icon, something like: ![weight@10x_black](https://user-images.githubusercontent.com/546576/134821435-661d03e2-56ba-4194-98eb-13977e635755.jpg)

Done :)
https://github.com/google/material-design-icons/pull/1230

**Comment by manavsiddharthgupta** [comment]
is this issue has been resolved?

**Comment by MrTechHunter** [comment]
> is this issue has been resolved?
> 

Yeah😊

**Comment by tphinney** [comment]
This was added just recently
