### ISSUE TITLE
Can't find the "percent" glyph on the .otf file

### ISSUE THREAD

**Issue by gustavoapoca** [google/material-design-icons#1231]
I have the oft font installed to use it in my project mock-ups, but the ligature for the `percent` glyph is not displaying the icon in Figma. I tried searching for the code point, but could not find it as well. The glyph also cannot be found on the glyphs preview of macOS' Font Book.

However, the ligature does seem to be working just fine on https://fonts.google.com/icons

**Comment by tphinney** [comment]
I think your problem may be that you are expecting it to be encoded at the normal unicode for "percent"

As a symbol/icon font, Material Icons encodes all its icons in the Unicode “Private Use Areas.” So percent is at U+EB58 (60428 in decimal), rather than U+0025 as one might expect.
