### ISSUE TITLE
Please add a generic "Bot" icon

### ISSUE THREAD

**Issue by tryngl** [google/material-design-icons#1235]
Please add a generic "Bot" or "Chat Bot" icon: this can be used when building messaging clients, to inform end-users that they are chatting with a machine rather than human. It would be good to have two flavors:
1. a traditional "robot" type of face
2. a more abstract generic "computer" type of machine (like an old macintosh for example)

Thank you!

**Comment by tryngl** [comment]
Hi 👋 any chance this can move forward?

**Comment by LadyK-21** [comment]
@manavsiddharthgupta

**Comment by tryngl** [comment]
Hi there 👋 any update on this one? Having a Bot icon seems like pretty important gap to address.

**Comment by mathtimesjoy** [comment]
@tryngl We do have a robot icon face: smart_toy. Does that work?

**Comment by tryngl** [comment]
@mathtimesjoy I feel that "smart_toy" was meant for other usage (as the name of the icon suggests) than what I'm looking for. I would need this mostly for usage in conversational messaging UI, to be used as icon that embodies the chat bot participant. I would ask for two variations:
1. One traditional "humanized bot", with two eyes (perhaps a "smiling" mouth, but not mandatory), something [like this](https://materialdesignicons.com/icon/robot).
2. One more abstract conceptual icon that resembles a "machine", something like early generation iMac, or HAL 9000 (something that doesn't try to look human).

As a side note, I see even Google Chat uses a different icon when having conversation with a brand via business Chat inside Maps (see image attached).

![image](https://user-images.githubusercontent.com/25770415/170673724-5b3ae76e-7e11-4b98-b1a1-3d8b796457e1.png)

Thanks!

**Comment by tryngl** [comment]
Hey there 👋 Any plans on this one? With the global industry focusing on digital chat-bot assistants, this would be great improvement for Google Material Design iconography.

**Comment by tryngl** [comment]
Hello! Almost a year has passed since the first request: I'm hoping this can be moved to in-progress soon. Thank you!

**Comment by tphinney** [comment]
This has been done. There is a distinct and different /robot icon as well as /smart_toy — use whichever works best for your needs

**Comment by tphinney** [comment]
<img width="201" alt="Screenshot 2022-11-12 at 12 51 18 PM" src="https://user-images.githubusercontent.com/6548266/201494070-713a5c8a-0713-46d2-97ac-2ca2fe73b504.png">
