### ISSUE TITLE
Update repo with missing icons

### ISSUE THREAD

**Issue by bennetfabian** [google/material-design-icons#1246]
Dear contributor and maintainer team,
could you please update this repository with all the new icons that are already available on [Google Fonts Icons Page](https://fonts.google.com/icons)?

Unfortunately, this repo hasn't been updated in what feels like forever.
Just an example of an icon that is missing here but can be found on Google Fonts: `question_mark`.

I would like to ask you to get this repo to be more active and up to date again. That is because Material Design Icons are iconic (pun not intended) in the whole design world. The reasons for that are their accessibility and them being open source.

**Comment by rsheeter** [comment]
Apologies, we will fix and seek to ensure it doesn't fall so far behind again.

**Comment by reallaty** [comment]
Repo has been updated

**Comment by bennetfabian** [comment]
> Repo has been updated

Amazing thank you very much. 👍🏼
