### ISSUE TITLE
Bug when accessing fonts.google.com/icons from google.com 

### ISSUE THREAD

**Issue by kristine-sl** [google/material-design-icons#1248]
Steps to reproduce: 

1. Google "material icons" 
2. Click "Icons - Google Fonts" link
3. Observe that "\ assignment" is automatically filled in in the search field, and that it shows "No icons found for ‘\ assignment’", and "assignment_returned" as a header in the side nav header

<img width="1904" alt="Screenshot 2021-11-15 at 15 27 26" src="https://user-images.githubusercontent.com/3509839/141798663-063e2948-69e5-4d40-bea4-cc2a742074a1.png">

Tested this in two different Macbooks, both using Chrome, and both had the same issue.

**Comment by tomasdev** [comment]
@rsheeter what's the proposed solution / expected behavior?

For starts, we can ensure that the sidenav doesn't open if the icon doesn't exist.

But regarding Google crawling no-matches-results and putting them as first result, I'm not sure.

**Comment by tomasdev** [comment]
@kristine-sl Thank you for reporting this! We'll work on fixing it.

**Comment by tphinney** [comment]
@tomasdev any update on this?

**Comment by tomasdev** [comment]
@tphinney https://fonts.google.com/icons?selected=Material+Icons+Outlined:assignment_returned&icon.query=%5C+assignment renders the icon properly and disappeared from the first page of results. However, I'm not seeing fonts.google.com anywhere when looking for "material icons" 🥇

**Comment by tphinney** [comment]
The top link I find from a search on “material icons” is to https://google.github.io/material-design-icons/ which is an obsolete documentation page. Working on getting that page killed, as well.

**Comment by tphinney** [comment]
But seems like the original issue is gone. The other issue I mentioned above is captured in #1170 so I am closing this one.
