### ISSUE TITLE
Add google icon

### ISSUE THREAD

**Issue by hsul4n** [google/material-design-icons#1252]
I found Facebook, WhatsApp icons unless google icon.

**Comment by maxistviews** [comment]
I think theyre trying to move away from branding icons, but Im not associated with the project.

**Comment by bernaferrari** [comment]
They are adding and removing brand icons every week. No one knows why.

**Comment by tphinney** [comment]
Moving forward, Google is avoiding icons for third-party trademarks. So at this point they have all been removed and the intent is that they will stay that way.
