### ISSUE TITLE
Icon request: Duo battle

### ISSUE THREAD

**Issue by dipanshparmar** [google/material-design-icons#1260]
It's a request to add the duo battle icon that is two swords.

**Comment by tphinney** [comment]
Ah, I know this one. More specifically, it is two crossed swords. You can get a lot of exemplars from this search: https://www.google.com/search?q=crossed+swords

I think pointed up rather than down is the most… “iconic” and has a more active feel.

**Comment by tphinney** [comment]
It’s coming! Should be available within the next few weeks, if I am correctly understanding the latest production workflow.

**Comment by tphinney** [comment]
Sorry I missed closing this, but it was done.  :)
