### ISSUE TITLE
outlined icons not working

### ISSUE THREAD

**Issue by pietrobanana** [google/material-design-icons#1263]
Hey everyone, 
I am trying to use the outlined version of notifications. 
I can use the normal filled version but the outline version is not working. 

We're hosting the font family in our design system code (we're not using the link tag in the header method) and I added the material-icons-outlined to the font family:

`@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'), local('MaterialIcons-Regular'), local('Material Icons Outlined'), url(MaterialIcons-Regular.woff2) format('woff2'),
    url(MaterialIcons-Regular.woff) format('woff'), url(MaterialIcons-Regular.ttf) format('truetype');

  font-display: swap;
}

.material-icons{
  font-family: 'Material Icons Outlined', 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px; /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}`

This is the code in our TSX:
` {this.materialIcon ?         
          <div class="adl-dynamic-banner__icon-wrapper adl-grid__col-md-2 adl-grid__col--center-content">
            <i class="material-icons-outlined dynamic-banner-icon">{this.materialIcon}</i>
          </div> 
        : ''}
`

This is the HTML:
`material-icon="notifications"`

This is the CSS:
`.material-icons-outlined.dynamic-banner-icon {
  font-size: 6rem;
  color: $brand-primary;
}`

I will attach the end result with the rendered code (screenshot)
![Screen Shot 2022-01-27 at 9 07 51 AM](https://user-images.githubusercontent.com/42623545/151386031-e2ead9dc-a169-4645-bfd1-c071e86f74f7.png)

This is a screenshot with normal filled icons:
![Screen Shot 2022-01-27 at 9 09 29 AM](https://user-images.githubusercontent.com/42623545/151386385-a9df5c9c-8158-4366-a780-994871213c06.png)

**Comment by peppogit** [comment]
I suppose the repo only hosts regular type; missing outlined, sharp and so on
I'm looking for other types too

**Comment by Mahendran** [comment]
I am facing similar issue with icon **close** outlined, it is not working.
<span class="material-icons-outlined">close</span>
Below is my code
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Icons</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet" />
</head>
<body>
    <span class="material-icons-outlined">done_outlined</span>
    <span class="material-icons-outlined">pan_tool_outlined</span>
    <span class="material-icons-outlined">close_outlined</span>
</body>
</html>

**Comment by rohanmathur91** [comment]
> I am facing similar issue with icon **close** outlined, it is not working. close Below is my code
> 
> <title>Icons</title> done_outlined pan_tool_outlined close_outlined

For using the outlined version of icons you have to include that in your import 

HTML import
```html
<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round"
      rel="stylesheet">
```

OR

CSS import
```css
@import "https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round";
```

**Comment by tphinney** [comment]
I am assuming this resolved the problem; if not please reopen or comment.

**Comment by peppogit** [comment]
Hi, I think the problem comes with the "offline" way. It was clear to me the online way with query string options. Unfortunately it's not always possible to download the font; for example i'm working for a bank where for security reasons, a lot of systems do not have internet access.
So... how can I select the proper style loading the font from my application and not from cdn?
Thanks

**Comment by abhisheksarkar444** [comment]
It is working for me with this solution:

**Import the style as @rohanmathur91  mentioned:**
`<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round"
      rel="stylesheet">`
      
Also if you are using **<Icon>** to render the icons dynamically as mentioned in the [MUI docs](https://mui.com/material-ui/icons/) you need to add the classname
`<Icon className="material-icons-outlined">dashboard_outlined_icon</Icon>`
