### ISSUE TITLE
Please make icons for Logistics and Supply Chain Management

### ISSUE THREAD

**Issue by adedzine** [google/material-design-icons#1268]
In your next set of icon designs it would be great to see icons related to warehouses and facilitation centers. Bar Code Scanners, Conveyor Belts, Trolley, Fork Lift, Pallet, Front Loader, Shelves, Refrigeration, Scales etc...

**Comment by Vedsaga** [comment]
Yaa, that is great

**Comment by tphinney** [comment]
We did many of these! Available in the live version of Google Symbols.
conveyor_belt
forklift
front_loader
pallet
shelves
trolley
