### ISSUE TITLE
Add Pen to Square edit icon

### ISSUE THREAD

**Issue by pavankjadda** [google/material-design-icons#1272]
Please add edit icon pen to square icons. This is one of the most commonly used icon. See the example here https://fontawesome.com/search?q=edit&s=solid%2Cbrands

**Comment by tphinney** [comment]
Thanks for your patience.
But... that's a link to a showing of 221 different icons. Can you be more specific as to which one(s) of those you are interested in?

**Comment by pavankjadda** [comment]
`pen-to-square` icon

**Comment by tphinney** [comment]
But also things like calendar-pen, etcetera?

**Comment by pavankjadda** [comment]
> But also things like calendar-pen, etcetera?

Sure. It would just prevent us loading additional library for the icons

**Comment by Rajputhunyaar** [comment]
i am facing the same issue

**Comment by tphinney** [comment]
At least the basic square edit icon is in the works.

**Comment by pavankjadda** [comment]
> At least the basic square edit icon is in the works.

Thanks. Please update the issue when it's added.

**Comment by MCErtan** [comment]
This has not been added yet. Edit square exists in Material Symbols. But this is useless because we need to add the material symbol library as well. Pen edit icon looks bad in some places. We really need the square edit icon.

**Comment by pavankjadda** [comment]
Any update on this?
