### ISSUE TITLE
Rounded.Timer breaks icon consistency

### ISSUE THREAD

**Issue by zoltish** [google/material-design-icons#1277]
_(in the context of rounded icons)_ 

In the latest release (brought in by Jetpack Compose 1.2.0-alpha05) the timer icon now rocks a filled look. It was previously a combination of outlined & rounded, which I think looked much better. 

Every UI is different so I can only speak for my own case, but Im seeing a too strong contrast when the timer is placed next to other icons (e.g. alarm in my scenario). 

Obviously the icon now matches what google fonts displays, and mirrors the timer-off variant, which are both good things. Perhaps an alternative version can be created? 

For reference, heres my UI containing the icon before & after the change. Ive shown this to 5 people and their reactions have pretty much exactly mirrored mine. 

![Screenshot_1646895117](https://user-images.githubusercontent.com/4264531/157605549-bb800e01-92e4-4b93-bad9-b19d603b522f.png)
![Screenshot_1646895049](https://user-images.githubusercontent.com/4264531/157605552-39c09179-0e90-49d9-9da7-0bb704a6b600.png)

**Comment by amoliski** [comment]
[ mdiTimerOutline ](https://materialdesignicons.com/icon/timer-outline)

**Comment by zoltish** [comment]
@amoliski Thanks - Im aware that exists, unfortunately the sharp edges dont blend well with all my other rounded icons.

**Comment by tphinney** [comment]
In the variable font versions of the icons, I believe you’ll find the variant you are looking for is available now:
https://github.com/google/material-design-icons/tree/master/variablefont
https://github.com/google/material-design-icons/blob/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf

See also:
https://fonts.google.com/icons?icon.style=Rounded&icon.set=Material+Symbols&icon.query=Timer

**Comment by zoltish** [comment]
Yes it is! Thank you for letting me know @tphinney!
