### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by aasim-syed** [google/material-design-icons#1279]
Improve aesthetics of readme.md

**Comment by tphinney** [comment]
Can you be more specific?
Not saying it can’t be improved, just looking for a little more guidance as for what you think is needed.  :)

**Comment by tphinney** [comment]
I did a bunch of expansion and more explanations in the readme! I felt it needed to clarify the Material Icons vs Material Symbols difference, mostly.

However, I am not convinced I have “improved the aesthetics” of the readme. I welcome any more feedback on what you’d like to see. But in the absence of any such feedback, I will close this—for now.
