### ISSUE TITLE
Vaccine icon?

### ISSUE THREAD

**Issue by therealbluepandabear** [google/material-design-icons#1286]
Why is there no vaccine icon?

**Comment by tj-commits** [comment]
why are you looking for a vaccine icon?

**Comment by therealbluepandabear** [comment]
I'm working on an app which helps find the nearest covid vaccine centers and a vaccine icon would be beneficial.

**Comment by abhinandvreddy** [comment]
Is this what you're looking for? https://github.com/google/material-design-icons/tree/master/src/social/vaccines

**Comment by therealbluepandabear** [comment]
NOICE
