### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by verlok** [google/material-design-icons#1289]
The links in documentation bringing to sprites and maps are broken.

<img width="838" alt="Screenshot 2022-04-04 at 13 15 11" src="https://user-images.githubusercontent.com/1127721/161532655-c445dadd-0e7a-4398-99d2-86a5bbc706c1.png">

**Comment by tphinney** [comment]
Yeah, we had a link to a totally old/dead version of the docs. Sorry about that. I have updated this repo’s Readme. Can you confirm that is where you found it and the links are good now?

**Comment by verlok** [comment]
Yes, they are
