### ISSUE TITLE
Animated Icons?

### ISSUE THREAD

**Issue by abhnva** [google/material-design-icons#1295]
I don't know if this is possible, but wouldn't it be cool if we could use animated material icons?

**Comment by tphinney** [comment]
You can, if you use the variable font that was just posted yesterday.
Indeed, the entire purpose of the Fill axis is for animation! No other point to in-between states on that axis.
All the other axes can be animated as well! (Although the need/utility may be lower.)
https://www.google.com/search?q=how+to+animate+variable+fonts+CSS

**Comment by abhnva** [comment]
Thanks
