### ISSUE TITLE
Material Icons Round file types - ttf and woff

### ISSUE THREAD

**Issue by mamo-muj** [google/material-design-icons#1300]
Hey there, I'm currently working on adding the rounded variants of the material icons on a Webflow project. Currently, I see there's only `.otf` file type available. Are there going to be `ttf` and `woff` files as well?

**Comment by tphinney** [comment]
The variable font version, Material Symbols, has `ttf` (but not `otf` or `woff`).

I am surprised that there are `otf` but not `ttf` versions, myself. (And I write that as a big fan of `otf` for dev purposes!) Will poke some Google colleagues.

**Comment by tphinney** [comment]
I totally believe you, because I have encountered such things on occasion, but can you tell us what particular app(s) or system(s) you are using that have this limitation?

**Comment by mamo-muj** [comment]
Oh, it's not a problem I'm running into but something I was wondering about if we can have a `ttf` version or not. I assumed there was a reason why `ttf` wasn't available but was checking in anyways. The icons do work fine in the project though

**Comment by tphinney** [comment]
Basically, it is a bit easier from an engineering perspective. The original native outlines are in cubic béziers, so there we have it. But we are open to reconsidering, depending on need/demand. As this is effectively a duplicate issue, I’ll close this one: see also #1163
