### ISSUE TITLE
❓ What font(s) are used in the icons?

### ISSUE THREAD

**Issue by AlbinoGeek** [google/material-design-icons#1306]
What font is used in the Material Icons that have letters in them?

## Examples

Small blocky font: `Abc`, `Atm`, `Co2`, `EightK`, `EightKPlus`, `EightMp`, `EighteenMp`, `EightteenthMp`, `ElevenMp`, `FiberDVR`, `FiberNew`, `FiberPin`, `FifteenMp`, `FiveK`, `FiveKPlus`, `FiveMp`, `FivteenMp`, `FourKPlus`, `FourMp`, `FourteenMp`, `Hd`, `HdrAutoSelect`, `HdrEnhancedSelect`, `HdrOff`, `HdrOffSelect`, `HdrOn`, `HdrOnSelect`, `HdrPlus`, `HighQuality`, `Hevc`, `Hls`, ...

Different small blocky font: `5G`, `FourGMobiledata`, `FourGPlusMobiledata`, `GMobileData`, `HMobileData`, `HPlusMobileData`, `LteMobileData`, `LtePlusMobileData`, 

Numbers: `Filter1`, `Filter2`, `Filter3`, `Filter4`, `Filter5`, `Filter6`, `Filter7`, `Filter8`, `Filter9`, `Filter9Plus`, `Looks1`, `Looks2`, `Looks3`, `Looks4`, `Looks5`, `Looks6`

Different Numbers: `Timer10`, `Timer10Select`, `Timer3`, `Timer3Select`, 

Currencies

Punctuation (a stretch): `AssignmentLate`, `Error`, `Help`, `QuestionMark`

## Context / Comments

After having a look through, it's actually amazing how inconsistent some of these are.

It feels like if these aren't fonts, they should be. There are clear "groups of similar symbols", whether this was intentional or not.

When it comes to the MobileData or brand names, sure, but otherwise, why are there at least three distinct sets of numbers?

**Comment by tphinney** [comment]
All the blocky ones are hand drawn on the icon grid. That includes the two things you labeled as “blocky font” but also the “filter” and “looks” series and “timer_select”

Most of these seem to me to be inconsistent simply because they are drawn at different sizes, and are working with a specific stroke thickness, so… it comes out a bit different. But when things were needed at the same size then the existing hand drawn numbers were reused.

Timer10 and Timer3 are something else, though. Looks like they perhaps made use of Google Sans?

**Comment by AlbinoGeek** [comment]
Thank you!

I was in need of typography icons and figured I would just create them from the font, but given there isn't one, I suppose the best course of action is what, making an issue of icon-request for the creation and inclusion of these?

Examples:

- h1
- h2
- h3
- h4
- h5
- h6
- caption
- subtitle
- paragraph

(Think: Icons you would see in Word or Google Docs)

**Comment by tphinney** [comment]
@AlbinoGeek Seems to me that this is ALMOST the same request as #1256 
I'm going to add the extra details to that one, and close this, OK?

**Comment by AlbinoGeek** [comment]
Thanks!

**Comment by tphinney** [comment]
I believe these are all added, btw! Most of them were some weeks ago, and the last couple were just done and should show up within the next week or two in the externally available font.
