### ISSUE TITLE
"Repeat On" icon from MaterialIcons-Regular.ttf is a black square

### ISSUE THREAD

**Issue by bleroux** [google/material-design-icons#1307]
Hey,
I downloaded the MaterialIcons-Regular.ttf from this directory : 
`[material-design-icons](https://github.com/google/material-design-icons)/font/`

The "Repeat on" icon (U+E520) is a black square in this file : 
![image](https://user-images.githubusercontent.com/840911/167206684-e13e3375-0a10-46cc-a01e-621c9da90d6e.png)

['Repeat On' on fonts.google.com](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Arepeat_on%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

**Comment by tphinney** [comment]
I believe you will find this has been fixed in the latest version of the font!
Although I note that the codepoint is U+E9D6... U+E520 is "piano off" (but still not a plain black square)
