### ISSUE TITLE
Request for "foot" icon

### ISSUE THREAD

**Issue by tphinney** [google/material-design-icons#1312]
This was done as a [pull request of the actual icon file](https://github.com/google/material-design-icons/pull/1269), which I have closed as Google does not take those kinds of pull requests for icons. But I wanted to preserve the idea, which is a “footprint” style icon, from a foot without a shoe. Like what you would see on the beach.

**Comment by Rajputhunyaar** [comment]
I dont understand

**Comment by tphinney** [comment]
Somebody designed an icon and requested that we add it, via a pull request. But that is not a legit route to adding new icons to Material Symbols or Material Icons, so I closed the pull request.

But it _IS_ a perfectly reasonable request that Google add such a symbol, so I opened a new issue for it.  :)

**Comment by tphinney** [comment]
We have an icon in the works, but it may be a while before it is released.

**Comment by tphinney** [comment]
both /barefoot and /footprint are available!
