### ISSUE TITLE
How do I copy icons?

### ISSUE THREAD

**Issue by 0xVERS** [google/material-design-icons#1316]
I am using Polybar. I want to embed Material Icons in the Polybar. But I don't know how to enter the icons.
I would appreciate it if you could help me. Thank you in advance.

**Comment by tphinney** [comment]
I know nothing about Polybar. If nobody else comments, maybe ask on the Polybar side?
Note that if you can use custom fonts with Polybar, you could always use either Material Icons or Material Symbols in font form, and access the characters that way. See https://fonts.google.com/icons

**Comment by 0xVERS** [comment]
Thanks for the reply.
I simply wanted to copy Material Icons as glyphs from the site you presented to the clipboard. However, I couldn't figure out how to do that, so I used a font viewer to solve the problem.

**Comment by tphinney** [comment]
Ah, that is more clear now!

Google could offer an option to copy the icon-as-text to the clipboard, either using the custom (PUA) Unicode value, or using the ligature-text method.
