### ISSUE TITLE
[Material Symbols] Person vs Person Filled

### ISSUE THREAD

**Issue by smelfungus** [google/material-design-icons#1317]
Hello! It seems like the `Person Filled` symbol is redundant since we have `Fill` control and `Person` is pretty much the same as `Person Filled` for both `Fill` modes.

![image](https://user-images.githubusercontent.com/3989453/169667909-c09e3f93-119a-4360-8007-7f9cf583ce41.png)
![image](https://user-images.githubusercontent.com/3989453/169667918-149dcf97-b5a4-41b1-ae78-4a0e05345514.png)

**Comment by tphinney** [comment]
Ah. You’re right, thanks for pointing that out.

The explanation of what is happening and how we fix it is probably only of interest to internal folks, but here it is….

The funny thing is, way behind the scenes the Material Symbols font… only has one of these two icons in the font: person.
BUT to make it easier for people to migrate old projects from Material Icons to Material Symbols we also have mechanisms to support “old” versions of the glyph names… so we do that for “person filled” by having the old separate codepoint and the old ligature code supported.

The web site just checks for glyph names by ligatures supported, and displays each of them. We can make the separate _display_ of “person filled” go away by adding it to the list of things to suppress from the site. @EsoFromTheEast is the person for that, I think.

**Comment by bryantmero** [comment]
I dont think its an issue of using same asset for different buttons, at least by that you are making the system efficient and fast!

**Comment by tphinney** [comment]
Yes, that is what I am saying: we have only one asset (icon) in the font. It supports both names, and so does the API. We could suppress “person_filled” from display in the public showing, though.  In reality, it would be a cosmetic difference—but it might be less confusing.
