### ISSUE TITLE
Icons cannot be customized in Firefox on Windows

### ISSUE THREAD

**Issue by kr-tukimi** [google/material-design-icons#1319]
Hello!

I could not customize the icons in Firefox (ver 100.0.2).
It appears to work in Chrome.

As for Optical Size, it worked fine in Firefox.

I've included a screen shot of my search using the same criteria:

# Screenshot
## Firefox
![2022-05-28 010751](https://user-images.githubusercontent.com/53429948/170737850-590f2b3f-2bf6-4cdc-8b72-3297d9109544.png)
![2022-05-28 010822](https://user-images.githubusercontent.com/53429948/170737870-e6344dab-d360-42a7-8a59-01cfe91d4625.png)

## Google Chrome
![2022-05-28 010901](https://user-images.githubusercontent.com/53429948/170738125-1be4b547-c5df-4d11-9702-75dfb2d0a760.png)
![2022-05-28 010932](https://user-images.githubusercontent.com/53429948/170738156-5ea32397-d28f-44b8-93f4-6644c31e3bad.png)

**Comment by chrishenke** [comment]
@kr-tukimi I was having this issue as well but after an update to Firefox this morning it looks like it has been fixed.

**Comment by kr-tukimi** [comment]
@chrishenke Thanks for the info!

**Comment by kr-tukimi** [comment]
It sure worked fine, so I'm closing the issue!
Thank you for all your help!

**Comment by kr-tukimi** [comment]
It appears to have relapsed again.

I think it is more likely to be an implementation issue on the Google Fonts side rather than a problem on the Firefox side.

![image](https://user-images.githubusercontent.com/53429948/172029507-a4e0dfa0-432f-4cbc-aa87-40666f41177d.png)

**Comment by tphinney** [comment]
What platforms are you all on?
I do not see a problem on Firefox Mac (version 101).

**Comment by chrishenke** [comment]
I'm on Windows 10 Firefox 101.0

**Comment by kr-tukimi** [comment]
I'm on Windows 11 Firefox 101.0

**Comment by rsheeter** [comment]
Apologies, we had to temporarily disable variable font delivery for Firefox on Windows. I do not have an ETA for turning it on again at time of writing.

**Comment by davelab6** [comment]
Sadly this bug in Firefox is their policy decision so it's unlikely to be fixed :(

https://bugzilla.mozilla.org/show_bug.cgi?id=1403299

**Comment by kr-tukimi** [comment]
Unless corrected on the Firefox side, this issue cannot be resolved and will be closed with "Close at not planned".

Thank you for all your help!
Have a great day!

**Comment by tphinney** [comment]
@kt-tukimi @davelab6 @rsheeter 
Reading the Mozilla bug discussion linked by Dave (https://bugzilla.mozilla.org/show_bug.cgi?id=1403299), I interpret it as meaning that Firefox-Windows _does_ support variable fonts on newer versions of Windows 10, and presumably Windows 11. Is this correct, or do they just mean that they _could_ (but don’t)?

**Comment by kr-tukimi** [comment]
Variable fonts have been available since Firefox 62, so there is a contradiction between usable but not usable...
What in the world is the problem...

https://twitter.com/mozhacks/status/1036982095850037248
