### ISSUE TITLE
Icon flight_outlined is not outlined

### ISSUE THREAD

**Issue by cedvdb** [google/material-design-icons#1320]
Icon flight_outlined is not outlined

**Comment by tphinney** [comment]
Where are you looking and seeing this icon?
I do not see this icon currently present in either Material Symbols or Material Icons.
https://fonts.google.com/icons?selected=Material+Icons&icon.query=flight&icon.set=Material+Symbols
https://fonts.google.com/icons?selected=Material+Icons&icon.query=flight&icon.set=Material+Icons

**Comment by cedvdb** [comment]
It is the second icon in your second link

**Comment by tphinney** [comment]
Ah, you must mean if one also clicks on the "Outlined" button there. 
In our nomenclature, that’s just “flight,” but in the outlined style. There is no glyph named “flight_outlined” the way there is “flight_class” and “local_airport”
Sometimes there are glyphs whose actual glyph name is (for example) "flight_outlined" — which is distinct from the "flight" glyph _in the outlined style_.

In any case, the stroke thickness for outlined glyphs is 2 px at 24 ppem. The entire thickness of that plane fuselage is 3 px, so there is no way to have that  be hollow with a 2 px interior border. In fact, this is true for most of the glyphs at that link, for the same reason. So, this is “as designed.”
