### ISSUE TITLE
 <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round" rel="stylesheet"> not returning icons

### ISSUE THREAD

**Issue by saiashok** [google/material-design-icons#1323]
Looks like icons api is down. I am not able to see icons on my apps since this afternoon..!

 <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Round" rel="stylesheet">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">

![image](https://user-images.githubusercontent.com/28112776/171746424-e140ef9d-622b-4d2e-94b8-08a3533f454f.png)
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/28112776/171746497-d0c078e4-6484-4ef4-acf6-12e356b752e2.png">

Can you please help?

**Comment by tphinney** [comment]
So sorry to see there was some sort of outage! How long did it last? Things were up maybe an hour later when I looked at them.

**Comment by saiashok** [comment]
I still see the issue this morning, it works on mobile app but failing on web browser.

**Comment by hossein13m** [comment]
it seems it is working correctly now @saiashok 
could you please check your internet connection if you still have this issue?

**Comment by tomasdev** [comment]
Does the request https://fonts.googleapis.com/css2?family=Material+Icons&family=Material+Icons+Outlined&family=Material+Icons+Round work for you @saiashok ? It seems to be a problem between your ISP and the API at a glance.

**Comment by saiashok** [comment]
It is working now. There seems to be an issue with my ISP which is now resolved. Thanks for all the help.

**Comment by saiashok** [comment]
Closed. Thanks to everyone for quick response and followup.
