### ISSUE TITLE
icon font only release

### ISSUE THREAD

**Issue by akash1810** [google/material-design-icons#133]
Installing `material-design-icons` via `bower`, `npm`, `jspm` etc pulls down the svgs and other artefacts, which is pretty big (26.9MB). Can there be a release that includes just the icon fonts themselves?

Its possible to reference the [google web font url](http://google.github.io/material-design-icons/#icon-font-for-the-web) but that creates an external dependancy.

**Comment by Jossef** [comment]
+1 this will improve development experience

**Comment by siulung4073** [comment]
+1 the same in my case. 

I dont know how you do it, but in our CI it takes forever (10 min aprox) to copy all the icons for every format from the cache to the bower_components directory every time it runs bower install.

Its over 36MB and 77.500 files.

Maybe every format could have its own repo.

**Comment by FezVrasta** [comment]
+1

**Comment by shyndman** [comment]
Reasonable request. I'll see if I can get this going for our next release.

**Comment by FezVrasta** [comment]
Ah yea it would be awesome :D

**Comment by FezVrasta** [comment]
Any news about this feature?

**Comment by r0b-** [comment]
+1

**Comment by gonzofish** [comment]
@Jossef thanks for doing that as a stopgap.

**Comment by litzebauer** [comment]
Hey we using that too!

**Comment by jamesminotte** [comment]
How do I install the app password for gmail I thought this was it sorry if u have to keep it in lamens terms but I am in awe of ur billance

**Comment by lukengda** [comment]
Any news?
I would need a bower font release that keeps up to date from the material design icons team. All the third party font releases with bower are not updated regular enough.

**Comment by tklepzig** [comment]
+1

**Comment by artimeg** [comment]
+1

**Comment by aastrouski** [comment]
+1

**Comment by ShadowManu** [comment]
+1

**Comment by gwicksted** [comment]
+1

**Comment by CharlyRipp** [comment]
+1

**Comment by tkarls** [comment]
+1

**Comment by ShadowManu** [comment]
3rd party package to solve ths 1 year isssue I guess?

**Comment by MisterY** [comment]
And the size is not 26MB any more but 32 nowadays. Not extremely significant, of course, but still terribly slow when run via git.

**Comment by ddyrcz** [comment]
![image](https://cloud.githubusercontent.com/assets/20314986/23250164/2f3c47fe-f9a8-11e6-8bab-6b1364ccb956.png)

**Comment by vikshv** [comment]
+1

**Comment by FezVrasta** [comment]
Hey Google, can we close this issue since it looks like a "wontfix" to me?

You have something like 300 billion of billion of dollars and you can't spend 1 hour on this thing? If you don't want to fix it, say it, so we can forget about it and move in a different direction.

**Comment by ShadowManu** [comment]
@FezVrasta the thing about open source is that it is open. So, as frustrating as it may be, you have to remember what open means. And that includes the good and bad. The good when google publishes the icons and the community, like @jossef, can help on what users want. The bad, when even maintainers can't help on what users want.

I only say this not because your last paragraph was nonconstructive, the thing I most dislike in open source discussions.

Anyway, I'm following this thread and I would also like to have an official statement about this issue. We can safely consider it 'wontfix' after a year and a half, I guess. @shyndman?

**Comment by FezVrasta** [comment]
I don't say that they *have* to fix this issue, but damn it, they are one of the biggest companies in the world, at least add a stupid label to the issue and close it!

**Comment by rmacklin** [comment]
Thanks for your package @jossef. It sped up our node module installation by a factor of ~4.5. Hopefully the official package can provide this eventually.

**Comment by agavazov** [comment]
+1
89 815 Files, 8 002 Folders :(

**Comment by pashkasan** [comment]
+5

**Comment by MisterY** [comment]
Having 50K unneeded files under source control was killing our team. Now we've removed the material icons from all our projects and went back to Font Awesome. Problem solved.

**Comment by jaguileram** [comment]
+1

**Comment by ChenArno** [comment]
+1

**Comment by browne0** [comment]
+1

**Comment by ciceropablo** [comment]
+1

**Comment by rogerluiz** [comment]
+1

**Comment by Robula** [comment]
+1

**Comment by michieldewilde** [comment]
+1

**Comment by florin05** [comment]
+1

**Comment by krystof-k** [comment]
I've created [similar fork](https://github.com/cloudaper/material-design-icons) as @jossef that contains just production SVGs so that you can create your own SVG sprites: [cloudaper/material-design-icons](https://github.com/cloudaper/material-design-icons). Hopefully someone will find that useful.

**Comment by RoelN** [comment]
We're gathering all feedback and suggestions regarding updating the npm package in a central issue: https://github.com/google/material-design-icons/issues/1129 Please have a look and see if the package, as published in the way suggested there, would suit your needs.
