### ISSUE TITLE
Material Symbols Rounded - Interpolation Issue - add_reaction

### ISSUE THREAD

**Issue by kenmcd** [google/material-design-icons#1333]
File: MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf  (v2.531, 2022-03-21)
From here: https://github.com/google/material-design-icons/tree/master/variablefont
Glyphs: `add_reaction (E1D3)` and `add_reaction.fill`
Appears the element order is different in: `:fi=0,gr=0,op=20,wt=400`

![2022-06-24_12-25-12](https://user-images.githubusercontent.com/844920/175654194-187f48f7-ebcc-499a-8b71-c3293263abc5.gif)

**Comment by tphinney** [comment]
Whoops. Well, that is embarrassing. Thanks for catching this!

The two “eye” contours are both fine individually, but the contours are in a _different order_ in the 20 px master design. Just the one out of the 14 masters This is, well, a Rather Bad Thing if one animates the transition, or wants to use an in-between size.

I have fixed it in source, unfortunately just after a daily variable font build. But it will be in the next one after.

**Comment by tphinney** [comment]
I did an extra build tonight just so I could have it checked in, in time for the next weekly pull.

**Comment by tphinney** [comment]
So, the “live” version of the font on fonts.google.com should be all better now.
The variable font here in the repo will also get it with the next update, whenever that is.

**Comment by tphinney** [comment]
The updated font was posted to the repo some time back, so this is done.
