### ISSUE TITLE
Material Symbols `diversity_1` with weight of `100`-`300` is deformed

### ISSUE THREAD

**Issue by aisgbnok** [google/material-design-icons#1334]
### Description

The heart symbol in the background of the `diversity_1` Material Symbol with a weight of `100`-`300` becomes deformed.  This is apparent no matter the Grade, Optical Size, Fill, or Shape (rounded, outlined, sharp).

### Steps to Reproduce

1. Go to **[fonts.google.com/icons](https://fonts.google.com/icons)**.
2. Ensure you are using the **Material Symbols** icon set.
3. Search for **diversity 1**.
4. Under **Customization**, change the weight parameter to any weight from `100` to `300`.
5. Diversity 1 (`diversity_1`) icon becomes deformed.

https://user-images.githubusercontent.com/10838153/175748977-a90a8264-aece-4e44-b090-a2512b23c2b1.mp4

The downloaded `SVG` and `PNG` are also deformed.
![diversity_1_FILL1_wght300_GRAD0_opsz48](https://user-images.githubusercontent.com/10838153/175749052-39884927-11a4-4630-a6fb-b450f7dd7f85.svg)

**Comment by aisgbnok** [comment]
### Update

Upon closer inspection, this is apparent in weights `100` and `200` as well. `100` to `300` is affected.

**Comment by tphinney** [comment]
Thank you for reporting this! 

The video was helpful as well as the other info. Made this very easy to investigate.

Also: Ouch! Yes, I see what has gone wrong in the font source. The startpoint of that top contour is inconsistent across the masters—specifically in the Thin (100 wt) and Thin Filled masters.

**Comment by tphinney** [comment]
Fixed in source, checked in for next build

**Comment by aisgbnok** [comment]
Thanks, @tphinney! 

Will this issue automatically get closed once the fix is in production or should I close this now? Thanks again! 👍

**Comment by tphinney** [comment]
I will write something here once I verify that it is live.

**Comment by aisgbnok** [comment]
Okay great.

**Comment by tphinney** [comment]
I did an extra build tonight just so I could have it checked in, in time for the next weekly pull.

**Comment by aisgbnok** [comment]
@tphinney, thanks for all the help! It seems to be working now.

https://user-images.githubusercontent.com/10838153/177062656-6de98db2-501d-4633-8c6f-5b1edb0be4ae.mp4

**Comment by tphinney** [comment]
Yes, the version of the font that is live on fonts.google.com is good. We still need to update the TTFs available here in the repo, though.

**Comment by aisgbnok** [comment]
@tphinney, it seems this was fully fixed in c764ca99a5f24cfca7f97d98a92b259b92f903da. It's been live on fonts.google.com for a while now, and as of c764ca99a5f24cfca7f97d98a92b259b92f903da the ttfs are working properly too.

Can this issue be closed?

**Comment by aisgbnok** [comment]
Thank you! 🎉
