### ISSUE TITLE
Material Icons do not load in other language

### ISSUE THREAD

**Issue by Akshay-Katariya** [google/material-design-icons#1337]
I am using material icons which is working as expected in the English language, but when we change the language or use google translate and use some other language (other then English) the icon does not loads up on screen.

 I already tried the German/Hindi language for some of my targeted audiences.

**Expected output**

<img width="465" alt="Screenshot 2022-06-26 at 11 42 23 AM" src="https://user-images.githubusercontent.com/11885459/175801987-87782be8-5b1a-472c-906e-b9f46afd8f35.png">

**Actual output**

<img width="1414" alt="Screenshot 2022-06-26 at 11 39 34 AM" src="https://user-images.githubusercontent.com/11885459/175801931-02084276-f1cf-471b-a312-f622239103a7.png">

<img width="1189" alt="Screenshot 2022-06-26 at 11 40 33 AM" src="https://user-images.githubusercontent.com/11885459/175801959-27efec21-7a6b-4ff9-ba2d-483f93c96e09.png">

**Comment by tphinney** [comment]
Don’t translate the names of the icons. The icon names are simply an access method to get the icon to show up.

If you want to translate ALL the text, then _do not use the icon names at all_; instead use their custom (Private Use Area) Unicode codepoints.

Every icon has a glyph name. That name is also used as the input for a “ligature”—a means to type the name in the icon font, and get the icon to show up. Every icon also has a Unicode value. You can use either method to access any icon.

It would be… impractical to support all the world’s languages for the ligatures. Plus, you’d get conflicts: “chat” in English means to talk, and in French it means a kitty cat. “Home” means where you live in English, but in Catalan it means a man (male person).

**Comment by Akshay-Katariya** [comment]
The issue is with google translate and not with localization, anyways I got the point can you please point me to some example/code sample on how to use glyph names?

**Comment by tphinney** [comment]
Where it says “inserting the icon,” `keyboard_alt` is the glyph name.

**Comment by Akshay-Katariya** [comment]
I am using the same `span` tag to display my icons something just like this but it gets translated by google translator.
So for now I am using html5 property `translate='no'` which is working in my case, but if there is a better solution I would definitely like to implement it 😁 

**Current Implementation:**
```
export const GoogleIcons = ({ name }) => (
	<span translate='no' className='material-symbols-rounded google-icon'>
		{name}
	</span>
)
```

**Comment by tphinney** [comment]
I don’t know of a better solution—that seems entirely appropriate!
