### ISSUE TITLE
Location On - Material Symbols

### ISSUE THREAD

**Issue by rubiomiguel06** [google/material-design-icons#1341]
Under Material Symbols we have the Location Off icon, but there is not the Location On icon. 

On Material Icons exist both.

Is the Location On icon missing on Material Symbols or there is no intention on supporting it?

![image](https://user-images.githubusercontent.com/19507731/176856080-448606ef-cc15-4cd3-8ed8-a01dbd566d27.png)
![image](https://user-images.githubusercontent.com/19507731/176856151-7e28a2ab-3d98-41d2-8c5a-6a2d63f62e86.png)

**Comment by tphinney** [comment]
Ah, I see the problem.

In Material Icons, there are two different pin shapes for map-pin icons.
In the newer Material Symbols, these were amalgamated into one shape only.
(None of this counting the _other_ shape used by Google internally for map-pin icons.)

location_on and room should then be identical to place, in Material Symbols. But instead, location_on got dropped entirely

However, the amalgamation in Google Symbols should be improved by keeping support for the old codepoint and glyph name (as a ligature only, not a separate physical glyph). From a user point of view, “location_on” would be a duplicate of “place” and then look like the other.

In fact, we tried to do that, but… the code in the relevant file has an error, so it isn’t working right. Correcting that now. (Interesting question, will the correction be fast enough to get into the build that is already underway? Place your bets!)

**Comment by tphinney** [comment]
Yes, it made it into the last (internal) font build 2.582, with https://github.com/googlefonts/google-symbols/commit/f5beaa397091dc3c710c7aed457fbe4d5638b8ed
Should be in the next released build, whenever that is.

**Comment by rubiomiguel06** [comment]
Now it is there! Thanks for solving this issue
