### ISSUE TITLE
Material Symbols count discrepancy

### ISSUE THREAD

**Issue by IshanJ25** [google/material-design-icons#1343]
Hi, nice work.

I do have a concern, that on the Google Fonts webpage, it is mentioned that there are over 2500 glyphs, but this repository has only 1903 glyphs.

![image](https://user-images.githubusercontent.com/86649457/177263302-bf7c2478-4198-4d9e-88da-393efbbcd7e2.png)
![image](https://user-images.githubusercontent.com/86649457/177263523-8532044c-bf72-4bef-9d26-d52771aeb19e.png)

Where are the rest of them? It an upload due?

**Comment by IshanJ25** [comment]
Example: the "Timer" symbol is not present in this repo, as I can see

**Comment by tphinney** [comment]
Two causes for the discrepancy, I think:
- I think the repo only has unique icons, so if one is duplicated it won’t show up here the way it does on the web site.
- It appears that the repo fonts have not been updated since April 22. Not sure why, assigning to the person who does those updates.

**Comment by elitastic** [comment]
644 out of 2501 symbols are missing in repo, have a look at https://github.com/google/material-design-icons/issues/1304#issuecomment-1177258459

**Comment by tphinney** [comment]
I used to be responsible for SVG generation for some of these fonts, and was doing it with some open source utilities and a bit of scripting, as best as I recall.

Assigning this to @EsoFromTheEast as this seems to be in his domain now.

**Comment by IshanJ25** [comment]
Okay, I can see some new files are added, but it still sums up to 2095 icons
I believe at least 406 symbols are still missing.
![image](https://user-images.githubusercontent.com/86649457/177906687-3483156a-7fe3-48d0-b772-c67c0709062a.png)

I have 2 concerns:
 - Estimate time by which the symbols will be added
 - How I can ***locally create the symbols*** using the ttf font file.

The later problem is related to the situation that I am unable to clone the repository on desktop, shows a bunch of errors. I just want the `Symbols/web` folder for my project. So it would be appropriate that I create the symbols from the font file instead of downloading the whole repo zipped with about 4 million small files (saves a lot of time)

**Comment by elitastic** [comment]
UPDATE:

Thanks @EsoFromTheEast for the repo update. Unfortunately, 177 out of 2270 symbols are still missing compared to the visible symbols on the [website](https://fonts.google.com/icons?icon.set=Material+Symbols). If you're still working on it, ignore this! :-)

Missing icons:
```
123
abc
add_card
adf_scanner
audio_file
auto_mode
balance
bedtime
bedtime_off
blinds
blinds_closed
boy
broadcast_on_home
broadcast_on_personal
candlestick_chart
cell_tower
co_present
commit
content_paste_go
content_paste_search
contrast
css
currency_exchange
currency_franc
currency_lira
currency_pound
currency_ruble
currency_rupee
currency_yen
currency_yuan
curtains
curtains_closed
data_thresholding
deblur
density_large
density_medium
density_small
diamond
display_settings
domain_add
egg
egg_alt
elderly_woman
electric_bolt
electric_meter
energy_savings_leaf
event_repeat
factory
fax
filter_alt_off
filter_list_off
flag_circle
foggy
forest
fork_left
fork_right
gas_meter
girl
groups
heart_broken
heat_pump
hexagon
hls
hls_off
html
insert_page_break
install_desktop
install_mobile
javascript
join_full
join_inner
join_left
join_right
key
key_off
keyboard_command_key
keyboard_control_key
keyboard_double_arrow_down
keyboard_double_arrow_left
keyboard_double_arrow_right
keyboard_double_arrow_up
keyboard_option_key
keyboard_voice
lan
line_axis
lock_person
lock_reset
logo_dev
man
merge
mode_night
move_down
move_up
nest_cam_wired_stand
oil_barrel
pentagon
percent
phishing
php
pinch
playlist_remove
propane
propane_tank
push_pin
question_mark
ramp_left
ramp_right
rectangle
rocket
rocket_launch
roller_shades
roller_shades_closed
rotate_90_degrees_cw
roundabout_left
roundabout_right
route
satellite_alt
save_as
scale
send_time_extension
sensor_door
sensor_window
shopping_cart_checkout
signpost
snowing
solar_power
sports_martial_arts
square
ssid_chart
stadium
start
straight
sunny
sunny_snowing
swipe_down
swipe_down_alt
swipe_left
swipe_left_alt
swipe_right
swipe_right_alt
swipe_up
swipe_up_alt
swipe_vertical
sync_lock
terminal
text_decrease
text_increase
token
turn_left
turn_right
turn_sharp_left
turn_sharp_right
turn_slight_left
turn_slight_right
u_turn_left
u_turn_right
vertical_shades
vertical_shades_closed
video_file
view_comfy_alt
view_compact_alt
view_cozy
view_kanban
view_timeline
vpn_key_off
wallet
warehouse
watch_off
webhook
width_full
width_normal
width_wide
wifi_channel
wifi_find
wifi_password
wind_power
zoom_in_map
```

**Comment by IshanJ25** [comment]
Any update please?

**Comment by 7PH** [comment]
Hi there, letting you know that I am also very interested in any update regarding this issue. `airwave` seems also to be missing from the list.

**Comment by IshanJ25** [comment]
@tphinney Hi I just wanted to know if this problem is still being looked into. There are still numerous glyphs missing.

**Comment by tphinney** [comment]
That's a question for @EsoFromTheEast 
I did a quick spot check of the first few on the list, and all exist, by that name, in the upstream font source.

**Comment by tphinney** [comment]
Last font updates to the repo were December 5. So, the repo was updated with new fonts shortly after y’all were asking.

We had a bit of a holiday break and not a lot more work on icons from mid-December to early January, but have been full tilt the last three weeks… so there should be more updates soon.
