### ISSUE TITLE
laptop_chromebook broken at small optical size

### ISSUE THREAD

**Issue by foxt** [google/material-design-icons#1350]
https://user-images.githubusercontent.com/12257112/180453755-f43c601c-f242-425e-b8d5-86591c3df291.mov

Screen is slanted & has broken weight scaling

**Comment by tphinney** [comment]
Wow, that is pretty awful. Luckily it is quite easy to fix.

(In case anybody cares about the technical details, this looks like a common kind of bug: the masters are all OK, _except_ that the startpoint of the outer contour differs between masters, causing problems in interpolation and vector addition that play out when more than one axis is at non-default values. Make startpoints consistent in the non-synthetic masters and this will go away. Some of the synthetic masters will display/embody the problem, but are not the ultimate source of it.)

**Comment by tphinney** [comment]
My supposition about the nature of the problem was correct. I fixed it for the font build I just completed… will close after the fix is out there.

**Comment by tphinney** [comment]
As it turned out, my initial fix was about 90%. The big part is better, but there is a less obvious problem with the little contour of the notch or hinge or whatever it is at the bottom of the screen of the chromebook. Fixing now for this coming week’s build.

**Comment by tphinney** [comment]
Addendum: Both these problems would only be an issue at optical sizes _in between_ 20 px and 24 px. Either standard size was fine, it was just the interpolations that were bad. Fix is checked in for next build.
