### ISSUE TITLE
Icon request: trophy

### ISSUE THREAD

**Issue by nwalters512** [google/material-design-icons#136]
This would be good for representing a winner, awards, etc.

**Comment by jesusignazio** [comment]
+1

**Comment by mismith** [comment]
+1

**Comment by stephengardner** [comment]
+1

**Comment by sharpless512** [comment]
+1

**Comment by technocf** [comment]
+1

**Comment by ziyafenn** [comment]
Pleaseee!!!!!

**Comment by normalhh** [comment]
Haven't update for months.....
Pleaseeeeeee! Really need this.

**Comment by luciddr34m3r** [comment]
Would be very nice to have the icon from the Google Opinion Rewards notification added to the icon set, with and without the star.

**Comment by tehcojam** [comment]
+1

**Comment by enricodelazzari** [comment]
+1

**Comment by Baneeishaque** [comment]
+1

**Comment by nwalters512** [comment]
Please +1 react the issue instead of commenting.

**Comment by Thlenzi** [comment]
?

**Comment by downhiller** [comment]
It's not the same, but I've had a look through our available icons and gone with "bookmark" for my use-case; placing an icon alongside a list of results to show gold/silver/bronze for the top three.  

https://material.io/icons/#ic_bookmark

**Comment by natasha-robarge** [comment]
+1

**Comment by ecrona** [comment]
There's  the "emoji_events" icon, looks a lot like a trophy :)

**Comment by downhiller** [comment]
Perfect, thank you!  I've switched my site from "bookmark" to that immediately!

Not sure if this has always existed or been added recently, but either way, thanks.

**Comment by Errechydy** [comment]
This request is made in 2015, 5 years and still no trophy icon, that's something

**Comment by downhiller** [comment]
> This request is made in 2015, 5 years and still no trophy icon, that's something

emoji_events is a trophy, it's just hard to find if you don't know what you're looking for!

**Comment by Shakle** [comment]
Icons.emoji_events does not find an icon for some reason. Flutter 1.12.13

**Comment by RoelN** [comment]
Closing this issue in favor of https://github.com/google/material-design-icons/issues/403

**Comment by mhbdev** [comment]
> > This request is made in 2015, 5 years and still no trophy icon, that's something
> 
> emoji_events is a trophy, it's just hard to find if you don't know what you're looking for!

That name is so lame :)

**Comment by tphinney** [comment]
Nowadays new icons are mostly named for their appearance rather than some abstract intent.

In the meantime, you have your trophy icon.  :)
