### ISSUE TITLE
Delete outlined svg Symbols icon does not match the one in website

### ISSUE THREAD

**Issue by ldsenow** [google/material-design-icons#1361]
Hi there,

I just discovered that the svg icon in the repo doesnt match the one in the website. Which one is correct?
![image](https://user-images.githubusercontent.com/177045/183364836-20d72583-754c-449c-8a73-f108b00a3766.png)

![image](https://user-images.githubusercontent.com/177045/183365010-0f199ec9-d610-4339-a5c9-269b3141a511.png)

**Comment by tphinney** [comment]
The version on the website is correct, and the version in the repo is older/out of date.

Google had a different version for the internal version of the icons. In recent updates this is one of several changes made to bring the external (Material Symbols) icons closer to the internal (Google Symbols) icons.
