### ISSUE TITLE
WhatsApp icon is not been shown

### ISSUE THREAD

**Issue by DickyMacias** [google/material-design-icons#1365]
Today I realized that my apps that used the whatsapp icon with material-icons, are not showing it anymore. I verified the icon in Material Symbols to verify if it is still there but also are gone.

**Comment by tphinney** [comment]
Google made a global change to delete all third-party logos, due to rights/trademark issues.
It has been discussed at some length, even has its own issue label (“3rd-party logos”).

**Comment by DickyMacias** [comment]
Thank you for your quick answer @tphinney. I will look a similar icon then to avoid this issue.
