### ISSUE TITLE
WhatsAPP Icon is not displaying anymore

### ISSUE THREAD

**Issue by ronaldgemao** [google/material-design-icons#1366]
<img width="1315" alt="Screen Shot 2022-08-16 at 11 22 42 AM" src="https://user-images.githubusercontent.com/110227959/184791657-ad729879-ebc4-47bf-bcf2-979e6a933cae.png">

**Comment by tphinney** [comment]
Currently, Google does not include 3rd-party logos among the Material Symbols or Material Icons due to legal reasons. Some 3rd-party logos that were included in the past have since been removed.
