### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by carla-1234** [google/material-design-icons#1368]
They are very cute ,simple and beautiful, but they have no color 😕

**Comment by tphinney** [comment]
Hi Carla,

Thanks for the feedback.

Just my own thoughts here, _not_ speaking officially for Google.... Overhauling the icon designs as full-color icons would be a massive redesign. In Material Symbols they have not even re-issued the old two-tone icon variants.

For two-tone or color fonts, there are font technology/standards issues. (Two-tone fonts would be best done using a color font technology; regular fonts just have inked and clear parts.) The COLR table looks like the winner among the four competing color font approaches, but Chrome for Android only started supporting it about two weeks ago, and color _variable_ fonts are more bleeding edge than color fonts in general.

For full color icons, redesigning the existing variable icons to make good use of color would be a truly massive redesign, on the order of the existing Google Symbols variable-font rework, multiple person-years, for sure. Both the design work and the production/engineering work would be immense.

**Comment by carla-1234** [comment]
If icons have google colors they will be very beautiful 
Thank you so very much

**Comment by rsheeter** [comment]
Speaking of color, COLRv1 works in Firefox nightly as of this week, I'm stoked!

> If icons have google colors they will be very beautiful

I vigorously agree but sadly no such work is planned at this time.
