### ISSUE TITLE
Fruit icons

### ISSUE THREAD

**Issue by Carla-12345** [google/material-design-icons#1374]
Have a look at these pictures 
https://github.com/Carla-12345/Blubbery

**Comment by tphinney** [comment]
Ah, assorted fruit icons. Do people need fruit icons? Is there a particular purpose/point?
Of course, any ones selected would need to be remade in the Material style
Thanks for the suggestion!

**Comment by Carla-12345** [comment]
People need foods and fruits icons.
Ho can I remade them?

**Comment by NowDev** [comment]
I don't think we should have an icon for every fruit.
Why we couldn't just use emojis? 😅

**Comment by tphinney** [comment]
As I explained in another thread, and is in the Readme, Google takes suggestions as to what icons you might need, but not submissions of specific graphics to adopt for those icons. See: https://github.com/google/material-design-icons#icon-requests

**Comment by Carla-12345** [comment]
Yes ,we don't need icon for every fruit, but I have an idea.
But we can make all fruit icon in a bowl (fruit salad)

**Comment by tphinney** [comment]
So… what kinds of apps or websites need a “fruit salad” or “assorted kinds of fruit” icon? What is the use case for this?

If you are a grocery store, sure. But they need a whole lot of things… and maybe icons are not the best route for that. I looked at Safeway, Kroger (Fred Meyer’s) and WalMart — none of them rely on icons for labeling their departments/sections. Two use just text and the other uses text plus photos.

**Comment by Carla-12345** [comment]
Yes emoji is a better idea
