### ISSUE TITLE
Use a BSD-style license (or public domain) for code samples

### ISSUE THREAD

**Issue by scottywz** [google/material-design-icons#138]
Right now, code samples (e.g. HTML/CSS snippets in the documentation) appear to be licensed under CC-BY 4.0 since there's nothing that says otherwise.  However, [Creative Commons licenses are not appropriate for use with software](https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).  It would be good to have a more software-friendly license for these.

**Comment by shyndman** [comment]
We're moving to a software license in the next release. Closing this off because licensing issues are being talked about elsewhere.
