### ISSUE TITLE
R

### ISSUE THREAD

**Issue by WesamAlharbi** [google/material-design-icons#1383]

**Comment by WesamAlharbi** [comment]
>

**Comment by WesamAlharbi** [comment]
Run

**Comment by tphinney** [comment]
Can you be more specific? Are you looking for an icon? Suggesting an icon?
This one already exists in Material Symbols:
<img width="98" alt="Screen Shot 2022-09-07 at 8 19 46 PM" src="https://user-images.githubusercontent.com/6548266/189026665-dc6f1fde-5dc7-4a98-b00e-22c1769a01d9.png">

**Comment by tphinney** [comment]
For lack of a clear request/problem, I am closing this issue.
