### ISSUE TITLE
Add Chrome's Incognito icon to the "brand" section

### ISSUE THREAD

**Issue by exoRift** [google/material-design-icons#1384]
## Icon request
I want to use Chrome's incognito icon in a project I'm working on. Would it be feasible to include that possibly in the "brand" section?

![icon](https://static.thenounproject.com/png/404950-200.png)

**Comment by tphinney** [comment]
We should be able to do this! Apologies if it is a bit late for you to hear this, though.

**Comment by tphinney** [comment]
This is now in progress. I believe it has just missed the cutoff for next week’s release; perhaps the week after.

**Comment by exoRift** [comment]
> This is now in progress. I believe it has just missed the cutoff for next week’s release; perhaps the week after.
> It is a slightly different version of the incognito icon than what you showed, but definitely the same idea. Hat and glasses.  :)

If you're going generic, you could name it "sleuth"

**Comment by tphinney** [comment]
It will definitely be called “incognito”

We already had the icon in the internal Google version of the icon set, so it had a name already. Just have to add round and sharp versions, and set it to not be proprietary.

**Comment by exoRift** [comment]
What ever happened to this?

**Comment by exoRift** [comment]
Any updates? 💀

**Comment by tphinney** [comment]
Sorry to say that after revisiting it, I learned today that this is remaining a private Google icon.

The massive majority of all Google’s icons are publicly available. But a few are kept for exclusive Google use. Mostly this is for obvious reasons, like they are Google product logos.
