### ISSUE TITLE
I'm unable to reproduce this on:

### ISSUE THREAD

**Issue by shaoqint** [google/material-design-icons#1387]
I'm unable to reproduce this on:
a) a V100 cloud machine
b) a T4 cloud machine with CUDA 11.7
c) a desktop 1080 GPU with CUDA 11.4

So there must be something different about your environment.

I'm also curious if the value of `x` is changing between calls.

_Originally posted by @hawkinsp in https://github.com/google/jax/issues/12298#issuecomment-1241969164_

**Comment by hawkinsp** [comment]
Looks like this might have been opened by accident. Close it?

**Comment by shaoqint** [comment]
Yeah that’s wrong click, sorry about the inconvenience.



________________________________
