### ISSUE TITLE
Wrong shadow effect

### ISSUE THREAD

**Issue by srats** [google/material-design-icons#140]
Hi, 

About the Communication/forum image,

![ic_forum_black_48dp](https://cloud.githubusercontent.com/assets/3450113/8059881/89b701b0-0ec2-11e5-8f01-a6a1dab4d51a.png)
(ic_question_answer)

upper bubble has a rounded bottom-right corner,
shouldn't it be a rounded shadow effect on the lower bubble?

**Comment by shyndman** [comment]
This is by design. You'll notice all of our overlapping icons have the same effect.
