### ISSUE TITLE
Duplicate code name 'flourescent'

### ISSUE THREAD

**Issue by juliettef** [google/material-design-icons#1404]
The duplicate 'flourescent' (sic) define triggers warnings (see [IconFontCppHeaders/issues/27](https://github.com/juliettef/IconFontCppHeaders/issues/27)). 
This is a similar issue to #1082.
https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIcons-Regular.codepoints#L818-L820

**Comment by tphinney** [comment]
At the font level, we have a single glyph (wb_iridescent) that supports those glyph names via ligation as well as its own.
It supports the codepoints. F00D, E436
It does not support EC31

@rsheeter is the font correct? Should your codepoint registry change?

**Comment by wollac11** [comment]
This is still an issue and it appears it is not isolated to just the codepoints. I have inspected the included font file (https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIcons-Regular.ttf) and there actually appears to be two identical glyphs for codepoints EC31 and F00D and ligatures for both 'fluorescent' and 'flourescent' (sic) respectively.

On Google Fonts, on the correctly spelt version exists (https://fonts.google.com/icons?selected=Material+Icons:fluorescent) but not the typoed version (https://fonts.google.com/icons?selected=Material+Icons:flourescent). If you follow the working link on Google fonts it lists the codepoint for 'fluorescent' as EC31.

So, it appears that version on line 820 is correct and 818 and 819 are both wrong. Alternatively you could argue they are all wrong and it should be "fluorescent f00d" and in which case the font, codepoints file and Google Fonts are all somewhat inaccurate.

It is also worth noting that similar issues exist in the other variants of this font but not consistently. For example in MaterialIconsOutlined-Regular there is just one occurance of each spelling but both are mapped to F00D :
https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIconsOutlined-Regular.codepoints#L807-L808

**Comment by tphinney** [comment]
Fundamentally, there is one glyph in the font.
A bunch of names work (via ligature code) to point at that glyph. fluorescent, flourescent (sic), wb_iridescent

Because it was _once_ misnamed, Google still supports the “bad” mis-spelled name in the font and by the API. They try to avoid ever dropping a name so that old code will work in the future.

But they don’t go out of their way advertise that “bad” name on the website, even though it works.
