### ISSUE TITLE
"circle_check" icon doesn't display correctly when inserted via <span> or <i>

### ISSUE THREAD

**Issue by colinwilson** [google/material-design-icons#1405]
Currently, when inserting the `circle_check` icon using `<span class="material-symbols-outlined">check_circle</span>` I see the following:

![2022-10-21 12_27_10-Unorthodox Cases 🦄 _ Lotus Labs Documentation — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/197186278-de84d0a0-9ff2-4858-a666-089a605bf767.png)

If I use the **code point** (`e86c`) in CSS the icon appears to display correctly. e.g. `content: '\e86c';`

![2022-10-21 12_49_59-Lotus Labs - Cloud Agnostic Kubernetes — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/197189364-d8ea8270-2be1-469a-a8b6-7b180292c000.png)

Can anyone confirm is they're experiencing the same with this particular icon?

**Comment by colinwilson** [comment]
Just realised I searched for and found `check_circle`:

![2022-10-21 12_56_29-Material Symbols and Icons - Google Fonts — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/197190473-7f0dfe0b-6998-409c-8fc1-18a557688af3.png)

"circle_check" works/displays correctly. Is the icon just incorrectly named on Google Fonts?

**Comment by tphinney** [comment]
Yes, the icon you want is named "check_circle"
What source do you have that ways "circle_check" is a correct name? I see "check_circle" is also what is used for the older Material Symbols.

If a longer icon has a name, its name takes precedence over any shorter component names, for the ligation behavior of the font. But of course if there is no "circle_check" ligature, then "circle" and "check" can show up. Which is what we are seeing here.

**Comment by colinwilson** [comment]
Thanks for the update.

I don't know if I'm tired or going mad but I'd swear blind, opposite to what I stated above, I searched for (and found) `circle_check`.

Just [searched again](https://fonts.google.com/icons?icon.set=Material+Symbols&icon.query=circle+check&icon.platform=web) and `circle_check` is definitely not listed. So my mistake.

> If a longer icon has a name, its name takes precedence over any shorter component names, for the ligation behavior of the font. But of course if there is no "circle_check" ligature, then "circle" and "check" can show up. Which is what we are seeing here.

☝️  BTW thanks for this explanation. ☝️
