### ISSUE TITLE
'Shuffle' / 'Shuffle On' Icons broken

### ISSUE THREAD

**Issue by esdete2** [google/material-design-icons#1406]
The Icons `Shuffle` and `Shuffle On` are broken when the weight value is above 400.

https://fonts.google.com/icons?icon.query=shuffle

![shuffle](https://user-images.githubusercontent.com/34043608/197480432-d67d9c52-bcea-4041-bce2-4c771208b669.png)

**Comment by Nuel0** [comment]
Fixed!

https://www.figma.com/file/enHk1nzO6yPYNbzKJqmeaa/Untitled?node-id=1%3A6

**Comment by tphinney** [comment]
Yes, sorry I didn’t reply, but I saw the issue JUST before the cutoff for the weekly build, and managed to flag it for my colleague to address it. Luckily something like this, although it _looks_ horrendous, is actually a pretty easy fix (start point in the contour was inconsistent between masters, in this case regular vs bold masters, including their filled counterparts).

We won’t always be that fast—got lucky on the timing and ease of fix, both! Anyway, should be all better now.  :)
