### ISSUE TITLE
[Material Symbols] event_seat displays wrong icon

### ISSUE THREAD

**Issue by Crashdoom** [google/material-design-icons#1410]
The icon `event_seat` appears to have been replaced with a filled variant of the `picture_in_picture_alt` icon, specifically in the Material Symbols font. Material Icons provides the correct icon.

**Material Symbols**:
![image](https://user-images.githubusercontent.com/575410/198136686-80db0192-b49f-424f-a760-e5a68970b467.png)

**Material Icons**:
![image](https://user-images.githubusercontent.com/575410/198136773-c28a30a0-26ef-4b67-90f2-916764482ebb.png)

**Comment by tphinney** [comment]
Wow, that is super broken. Messed up in the source as well. I was hoping it was just errant ligature code, but no, the icon itself was replaced, at least as far back as mid-August. Will get that fixed ASAP!

**Comment by tphinney** [comment]
Actually, this has been broken for a VERY long time in Google Symbols. Possibly every public release, even. Thanks for reporting it!
(Note to self: see 671 in the internal repo)

**Comment by tphinney** [comment]
This was eventually fixed.  :)
