### ISSUE TITLE
Icon request: "database"

### ISSUE THREAD

**Issue by dupeg** [google/material-design-icons#1411]
Is it possible to add "database" icon please ?

Thanks ! :)

**Comment by tphinney** [comment]
@dupeg What would a database icon look like, in the Material style?

**Comment by MCErtan** [comment]
> Is it possible to add "database" icon please ?
> 
> Thanks ! :)
This icon already exists. You should be more specific about what you want.

```
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<span class="material-symbols-rounded">database</span>
```

**Comment by tphinney** [comment]
Gosh, yes!
Not available in Material Icons, but is present in Material Symbols

<img width="519" alt="Screen Shot 2022-10-29 at 9 24 11 AM" src="https://user-images.githubusercontent.com/6548266/198842441-8de46ef9-77bd-4821-82ec-abc1514efe1a.png">

**Comment by dupeg** [comment]
Sorry ! To be more specific, I work with icons using the font.
When I searched for the database icon, I saw that it was present in the material symbol but not in the font (codepoint file) :/
If it is possible to have the same design as the one in the material symbol, it will be great :)
Thanks !

**Comment by tphinney** [comment]
Material Symbols is (a set of) fonts just as much as Material Icons. Arguably more so, as it is also available as variable fonts. The codepoint for “database” in the Material Symbols fonts is U+F20E.

In general, I recommend Material Symbols over Material Icons, as it is the newest and most extensive offering. But perhaps you have some particular need for the older version?

**Comment by dupeg** [comment]
I'm currently working on a C++ Qt application on a closed network with no outside access. To avoid having images for each of my icons, I found that Qt could load a font (.ttf) and retrieve the symbol using the codepoint, that's why I used this method. I can't use the recommended "Getting started", if there is a better way to do it with the latest version of the icons, I'm up for it :D But I haven't found a solution so far :/

**Comment by MCErtan** [comment]
> I'm currently working on a C++ Qt application on a closed network with no outside access. To avoid having images for each of my icons, I found that Qt could load a font (.ttf) and retrieve the symbol using the codepoint, that's why I used this method. I can't use the recommended "Getting started", if there is a better way to do it with the latest version of the icons, I'm up for it :D But I haven't found a solution so far :/

I didn't understand what you said, I guess because I don't know C++. If you want to use it as a font, I leave an example here. Maybe it helps.

```
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<i class="exp-icon database"></i>
```

```
.exp-icon {
  font-family: 'Material Symbols Rounded';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    line-height: 1;
    letter-spacing: normal;
    text-transform: none;
    display: inline-block;
    white-space: nowrap;
    word-wrap: normal;
    direction: ltr;
    -webkit-font-feature-settings: 'liga';
    -webkit-font-smoothing: antialiased;
}
.exp-icon.database::before {
  content: '\f20e';
}
```

Here is the working example: https://codepen.io/lastofdead/pen/VwdjQME

**Comment by dupeg** [comment]
Oh thanks for the link ! I was searching in the wrong folder (https://github.com/google/material-design-icons/tree/master/font).
I think I will use the one you said 😄
Thanks again !

**Comment by hajimehoshi** [comment]
I failed to find a PNG image in the png folder for the database icon/symbol. Is there a reason we don't have this? Thanks,
