### ISSUE TITLE
Icons missing from git that exist on https://fonts.google.com/icons

### ISSUE THREAD

**Issue by njminchin** [google/material-design-icons#1414]
Example: social/water_voc
Am I missing something, or are some icons missing from this repo?

**Comment by tphinney** [comment]
That icon was just added to the live font in October.
Different deliverables in the repo are currently updated independently. The variable fonts for Material Symbols are currently the least frequent—last was about seven months ago.

**Comment by Nek-12** [comment]
Where can we find the most frequently updated source for the icon fonts or at least svgs? I need to batch-process these.

**Comment by tphinney** [comment]
Icons were updated again at the end of November and beginning of December (depending on which variant you are looking at).

I hope that at some point these updates will become more automated.
