### ISSUE TITLE
Icon Request "external-link"

### ISSUE THREAD

**Issue by MCErtan** [google/material-design-icons#1415]
Title. I couldn't find it in the Icons or Symbols.

https://i.imgur.com/zVwl1EJ.png

https://fontawesome.com/icons/arrow-up-right-from-square?s=solid&f=classic

**Comment by tphinney** [comment]
https://fonts.google.com/icons?icon.query=open+in+new
It is in both the old Icons set and the new Symbols set

**Comment by MCErtan** [comment]
> https://fonts.google.com/icons?icon.query=open+in+new It is in both the old Icons set and the new Symbols set

Oh, thanks. I think I used the wrong keywords while searching
