### ISSUE TITLE
README

### ISSUE THREAD

**Issue by bcapd7363q** [google/material-design-icons#1416]
UNABLE TO USE IT ON README.MD FILE PLEASE TAKE A RE-FREANCES FB:emojisense

**Comment by tphinney** [comment]
Sorry, I simply do not understand this request/issue

**Comment by bcapd7363q** [comment]
Halo [tphinney](https://github.com/tphinney) 
I am working on a project called JUPITER and creating a os for banking and healthcare  system .
need nessary help from  Symbols(material)[material,banking,healthcare]

**Comment by tphinney** [comment]
OK. What “necessary help” exactly?

If I understand correctly, you also mentioned being unable to use the icons on a “readme.md” file.
Either you need to insert the icons as graphics (Github-flavored markdown supports SVG now, which I would recommend as the graphics format), or as a font. I am not clear if the Github flavor of Markdown supports custom fonts — not finding any recent info on it makes me suspect not.

Are there also specific icons you are wanting for banking and health care, which are not present? If so, what are those icons?

**Comment by bcapd7363q** [comment]
```
Thank you, @tphinney, for your valuable time. I am finding difficulty to explain my client with expression .
 `.Symbols{ 
      .material{ ## for opretions and management 
        🍎:apple,
        📁:folder,
        🦄:unicorn
      }
      .healthcare{ ## for diagnostics 
       💉:injection,
       🩸:blods,
        :medic
        :Tablets
      }
      .banking{ ## currency converter
        💸:mony
        🏧:atm
        🏦:bank
        :wallet
        :loan 
        :emi
        :checkbook

      }
 
}
}`
```

**Comment by tphinney** [comment]
So, of those 14 icons, almost half I think exist already.
- folder
- injection (=vaccines)
- blood (=bloodtype or = water_drop)
- medic ? (=local_hospital)
- money
- wallet

What is EMI? Equated Monthly Installment?

**Comment by bcapd7363q** [comment]
> So, of those 14 icons, almost half I think exist already.
> 
>     * folder
> 
>     * injection (=vaccines)
> 
>     * blood (=bloodtype or = water_drop)
> 
>     * medic ? (=local_hospital)
¬ Hospital Management (HMS) 
>     * money
> 
>     * wallet
> 
> 
> What is EMI? Equated Monthly Installment?
¬
# global declaration

| Ttttle | name    | prifix    |
| :---:   | :---: | :---: |
| product | Volkswagen | Virtus |
| Min Tenure | 5 year | -- |
| Mid Tenure | 6 year | -- |
| Max Tenure | 7 year | -- |
| Interest   | 9.5%   | -- |
| Salary     | ₹ 5,00,000| per month |
| FMP     | ₹ 21,394| ( Min Tenure: EMI For 5 Years ) ## Fixed monthly payments |
| PLA     | ₹ 10,18,710| Principal Loan Amount |
| TIP     | ₹ 2,64,930 | Total Interest Payable |
| TAP     | ₹ 12,83,640 | Total Amount Payable |
| EMI     | ₹ 21,394    | Equated Monthly Installment |


# negotiation(HDFC-BANK)

| AMOUNT | CMD    | PRICE    |
| :---:   | :---: | :---: |
| On-Road Price | ORP | ₹ 14,22,000 /-[🚗] |
| booking Down Payment |BDP| ₹  4,03,064 /-[📚]|
| NET Price Equated    |NPE| ₹ 10,18,936 /-[🏦]|
-----------------------------------------------------------------------------------------------------------------------------------------------

# budget (Min Tenure)
 

| Ttttle | cmd| calculations|
| :---:   | :---: | :---: |
| Liabilities Financial Obligation | MLFO | ₹ 4,83,018 /-(Salary-₹ 16,982.26=FMP/Min Tenure*12=60 month) |
| Equated     personal  Obligation | MEPO | ₹ 4,78,606 /-(Salary-₹ 21,394.00=FMP/Min Tenure*12=60 month) |
| ENT | MLFO-MEPO | ₹ 4,412 /-(rental+₹ 16,982.26=21,394.26/MinTenure*12=60 month) |
| Instalment | EMI |₹ 16,982+4,412 |
| TOTAL-COST | RENT*12*5+ORP       |2,64,720+14,22,000=`16,86,720` |
| Interest   | MEPO/9.5%       |₹ 4,78,606/9.5 = 4,198.29 + 213.71(SERVICE TAX) |
| FMP   |(EMI)[%]       |₹    21,394*60 = 1,283,640/14,22,000[🚗] (% 0.9) |
| FMP   |(EMI)[-]       |₹    21,394*60 = 1,283,640-14,22,000[🚗] (- 138,360) |
| FMP   |(EMI)[*9.5]    |₹    21,394*60 = 12,194,580-14,22,000[🚗] (-10,772,580) |

**Comment by tphinney** [comment]
I'm sorry, but you really need to communicate with words rather than massive tables of data.
The simple answer to my question was “yes”; please don’t make me navigate all this material to find that.

Are the icons I mentioned useful to you, do they meet your needs?
I should add that we have "atm" as well.

**Comment by bcapd7363q** [comment]
need healthcare and banking related icons @material .
