### ISSUE TITLE
SVG <defs> sprite generator

### ISSUE THREAD

**Issue by stryju** [google/material-design-icons#142]
I made a previous PR with those sprites and was asked about automation, so here it is:

https://gist.github.com/stryju/139a41a31df5fca8f1fc

1. merges all the icons from folders that match `*/svg/production` pattern
2. puts `<clipPath>`s in `<defs>`
3. merges `<defs>`s
4. adds id-suffix to avoid ID conflicts

would it make sense to make a PR with that?

---

ps

please excuse the horrific line 14 - i'm new to `make` and learning as I go

**Comment by shyndman** [comment]
Closing because we now offer SVG sprites in various flavours.
