### ISSUE TITLE
Icon Request: Passkey

### ISSUE THREAD

**Issue by ePirat** [google/material-design-icons#1422]
It would be great to have an Icon for Passkey, the upcoming authentication mechanism that aims to replace passwords.

Attached is a example of what it could look like, inspired a bit by the icon Apple uses for Passkey:

<img width="324" alt="Bildschirmfoto 2022-11-17 um 23 48 18" src="https://user-images.githubusercontent.com/323210/202576612-c268114d-5ff6-4e6b-b053-65d2455997f6.png">
<img width="324" alt="Proposed Passkey icon showing the outline of a person with a key next to it" src="https://user-images.githubusercontent.com/323210/202576465-058d31a7-9faa-4b7a-a8f8-8d6a50d00b0b.svg">

**Comment by tphinney** [comment]
this was done.
