### ISSUE TITLE
[Material Symbols] Circle icon rounded

### ISSUE THREAD

**Issue by HenriqueSphera** [google/material-design-icons#1427]
Hi everyone, I recently noticed that the **"Circle"** icon from Material Symbols when applied in the **Rounded** style, is getting filled. Different from the behavior illustrated in https://fonts.google.com/icons

![image](https://user-images.githubusercontent.com/46767843/205201048-b7a58843-2536-4974-9976-80aec9ea6986.png)
![image](https://user-images.githubusercontent.com/46767843/205201124-eb5d6e1e-d97f-4a54-a2b1-33b5701cd1b0.png)

**Comment by tphinney** [comment]
The latest fonts have this fixed already.
(However, the repo still has 8-month-old font files for the variable fonts, and two-month-old ones for the non-variable.)
