### ISSUE TITLE
Icon request: Internet of Things icons

### ISSUE THREAD

**Issue by kplanz** [google/material-design-icons#144]
It would be nice to have some Internet of Things related icons like a **light bulb** or a **thermostat**.

I really liked the icons from the Android-Brillo/Weave preview (right screen):
![image](https://cloud.githubusercontent.com/assets/278960/8104768/9e638756-1033-11e5-91fb-0727a81a5086.png)

_Btw: Thanks for all those great icons :)_

**Comment by RoelN** [comment]
Bulbs and thermostats have been added in the meantime. Hoping these satisfy your needs, I'm closing this issue.
