### ISSUE TITLE
Icon Request Google

### ISSUE THREAD

**Issue by ARASHz4** [google/material-design-icons#1445]
Add Icon for Google
G icon

**Comment by tphinney** [comment]
Sorry, but we are not in general adding icons for Google products/services. If there were a clear general-purpose use (e.g. if it were a social media service owned by Google) then maybe it would be different? But in general, icons for Google products/services are reserved for Google’s internal use.

**Comment by ARASHz4** [comment]
I just want to use this icon for google sing button
Should add this in google icon it is useful
