### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ibrahimmemonn** [google/material-design-icons#1447]
Name
Ibrahim Memon

Github Username 
ibrahimmemonn

Google Developer Profile
g.dev/ibrahimmemon

Additional Context
Just want to be part of this awesome community :)

**Comment by tphinney** [comment]
I am unclear what you mean, but:

- if you mean an organization for Github itself, you are in the wrong place.

- there is no “community organization” for Material Design Icons at this repo. This repo is run by Google, with some maintenance from Google contractors (like me). It is a place for Google to post content, and users to report bugs and make requests using the “issues” mechanism in the repo. You do not need an invitation to use the issue tracker to post an issue: you just created one.

**Comment by ibrahimmemonn** [comment]
> I am unclear what you mean, but:
> 
> * if you mean an organization for Github itself, you are in the wrong place.
> * there is no “community organization” for Material Design Icons at this repo. This repo is run by Google, with some maintenance from Google contractors (like me). It is a place for Google to post content, and users to report bugs and make requests using the “issues” mechanism in the repo. You do not need an invitation to use the issue tracker to post an issue: you just created one.



> I am unclear what you mean, but:
> 
> * if you mean an organization for Github itself, you are in the wrong place.
> * there is no “community organization” for Material Design Icons at this repo. This repo is run by Google, with some maintenance from Google contractors (like me). It is a place for Google to post content, and users to report bugs and make requests using the “issues” mechanism in the repo. You do not need an invitation to use the issue tracker to post an issue: you just created one.

How can I join Google organization could you please help me out.

**Comment by tphinney** [comment]
There is no specific role for volunteers here. You can contribute general ideas for icons you would like to see by posting them as issues, one per idea.

If you are looking to be employed by Google, see https://careers.google.com/how-we-hire/
