### ISSUE TITLE
Sizing and coloring CSS missing in initial font request

### ISSUE THREAD

**Issue by wcjr** [google/material-design-icons#145]
I was hoping to see the following rules included in the initial request to https://fonts.googleapis.com/icon?family=Material+Icons:

```
// Rules for sizing the icon.
.material-icons.md-18 { font-size: 18px; }
.material-icons.md-24 { font-size: 24px; }
.material-icons.md-36 { font-size: 36px; }
.material-icons.md-48 { font-size: 48px; }

// Rules for using icons as black on a light background.
.material-icons.md-dark { color: rgba(0, 0, 0, 0.54); }
.material-icons.md-dark.md-inactive { color: rgba(0, 0, 0, 0.26); }

// Rules for using icons as white on a dark background.
.material-icons.md-light { color: rgba(255, 255, 255, 1); }
.material-icons.md-light.md-inactive { color: rgba(255, 255, 255, 0.3); }
```

Is each project responsible for duplicating these rules locally or are these simply missing?

**Comment by shyndman** [comment]
Each project is responsible for including these rules, if they choose to. They're only samples. Our icon font API is deliberately as general as possible.

I recommend you include classes that are contextually appropriate for your application.
