### ISSUE TITLE
md-font-icon attribute is not updating icon based on expression

### ISSUE THREAD

**Issue by naveednazarali** [google/material-design-icons#146]
md-font-icon is not updating icon when ternary expression is used. It evaluates that expression only once.

Here is the code to demonstrate the issue:

http://codepen.io/anon/pen/Kpqogj

**Comment by shyndman** [comment]
Hi there. This is the repository for the Material Design icon set. Your issue looks like it's regarding [Angular Material](http://www.github.com/angular/material). I suggest you repost there.
