### ISSUE TITLE
Devices_off icon is missing in the .ttf file

### ISSUE THREAD

**Issue by KaZiUpl** [google/material-design-icons#1469]
### Description
When using font explorer available on [this Google Fonts site](https://fonts.google.com/icons?icon.set=Material+Symbols&icon.query=devices+) there is an icon "Devices off" available. 

However there is no such glyph in the font available in [this repository](https://github.com/google/material-design-icons/blob/master/font/MaterialIconsRound-Regular.otf) or at least in the rounded version.

**Comment by tphinney** [comment]
Yes, there are quite a few new or updated icons in the Google Fonts version, in the 5 months since the last update to the repo. Pinging @EsoFromTheEast

**Comment by tphinney** [comment]
It is now available in the repo—although afaik only in Material Symbols, not the older Material Icons.

**Comment by KaZiUpl** [comment]
> It is now available in the repo—although afaik only in Material Symbols, not the older Material Icons.

Will that update be also propagated to the fonts available in this repository? I see that the fonts in the `symbols` directory were updated but cannot see any update to the files available in the `fonts` directory.
