### ISSUE TITLE
Beverage icons

### ISSUE THREAD

**Issue by bravilordesign** [google/material-design-icons#1471]
Hello all!

I noticed that there are little food and drinks related icons compared to other categories. I'd love to see (or some of) these icons:

- milk/dairy
- milk/dairy free
- coffee bean
- some different types of cups/mugs (small-medium-large perhaps?)
- grain
- grain/gluten free
- filter coffee
- decanter

Thanks!

**Comment by firedragonironfist** [comment]
![milk_icon](https://user-images.githubusercontent.com/91149240/221367073-ee2a3ade-704d-4301-a81d-e5f3e169ead4.png)

**Comment by firedragonironfist** [comment]
Hey bravilordesign can you please elaborate if you want the icons in SVG format or else just an image as I commented above

**Comment by firedragonironfist** [comment]
![milk_icon](https://user-images.githubusercontent.com/91149240/221367229-0b5d9cd4-7ed3-4ff4-a82f-52fc0851d3ec.svg)

**Comment by firedragonironfist** [comment]
This is the SVG format that I got but if you want exact specifications for an svg icon then please mention the following details
width and height in pixels
any color filter (if required)
DPI 
black and white threshold
and speckels threshold
or if you have any other specification please mention them so that I can commit accordingly

**Comment by tphinney** [comment]
First, it is cool that y’all want to contribute! Yay!

But broadly speaking, Google’s Material Icons have a very particular style and approach, which is radically different than the design above. They are designed to work at the default size of 24 px, and potentially even smaller, with strokes that are much thicker than you are showing, and without the fine detail: mostly 2 px on the 24 px grid.

See also https://github.com/google/material-design-icons#icon-requests

**Comment by firedragonironfist** [comment]
Thank you for your input and clarification on the design style for Google's Material Icons. As a contributor, I appreciate your guidance and would love to explore other open source projects or organizations that align with my interests and skillset. Are there any particular ones that you would recommend and think highly of? I am eager to continue my contributions and expand my knowledge in the tech community.

**Comment by bravilordesign** [comment]
@firedragonironfist that is more of an illustration in my opinion. It would need to fit with the current Material Design icons. They have a guidelines page on this very subject: https://m3.material.io/styles/icons/designing-icons

**Comment by tphinney** [comment]
@firedragonironfist — @bravilordesign is correct. That is not at all the style being used in the icons.

I log all these requests with an appropriate tag. When time permits, the icon design team goes through the backlog of external requests and does some! We saw quite a few requests fulfilled last year. But in general there are many more outside requests than could possibly be fulfilled.
