### ISSUE TITLE
`home health` and `help clinic` icons do not render properly in Material Icons

### ISSUE THREAD

**Issue by akc42** [google/material-design-icons#1474]
I am building a large app based on custom elements (based around lit).  I wrote my self a custom element wrapped around material icons and use it all over my application very successfully.  I was looking for some new icons to represent the word "clinics" and came across "home health".  This looked ideal.

I render the icons by including the code for them in the light dom of my custom element (ie the default slot) so for instance I have `<pas-icon>view_timeline</pas-icon>`  to get the "View Timeline" icon.  
The following picture shows my rendered toolbar, with the one with a red box round it being "home_health". (and the one to the right of it the view_timeline
![newicon](https://user-images.githubusercontent.com/368238/221590274-a0a11dfc-cd0c-4de5-9729-ec8b596ed4a0.png)

As can be seen, we get the "Home" icon, together with what I interpret is some text that does not render, but takes space on the page.

For information, this is how `<pas-icon>` is defined (with `--pas-icon-size` set to its default value of 24px)
```
import { LitElement, html, css } from '../libs/lit-element.js';

const link = document.createElement('link');
link.rel = 'stylesheet';
link.type = 'text/css';
//eslint-disable-next-line max-len
link.href = 'https://fonts.googleapis.com/icon?family=Material+Icons&display=swap';
document.head.appendChild(link);

class PasIcon extends LitElement {
  static styles = [css`
      :host{
        font-family:"Material Icons";
        font-weight:normal;
        font-style:normal;
        font-size:var(--pas-icon-size, 24px);
        line-height:1;
        letter-spacing: normal;
        text-transform:none;
        text-rendering: optimizeLegibility;
        display:inline-block;
        white-space:nowrap;
        word-wrap:normal;
        direction:ltr;
        font-feature-settings:'liga';
        -webkit-font-smoothing:antialiased;
        background-color: transparent;
      }
    `];
  
  render() {
    return html`
    <slot></slot>
    `;
  }
}
customElements.define('pas-icon', PasIcon);
```

**Comment by tphinney** [comment]
What you are not showing us is, what the string of text is, that is being rendered. That is the likely source of the trouble.

You are using the ”ligature” approach to displaying the icons, which is fine. _But if you get the string wrong, it doesn’t work._  That is _very likely_ what you are seeing here. Check your underlying text string.

The “old” Material Icons font just shoots blank spaces in place of text, when you are doing text entry. For the “new” Material Symbols I thought “hmm, this can be really confusing” so I added glyphs for the basic alphabetic characters. This means when you do not have a ligature working, it displays the letters—making it easier to see onscreen if you have a typo in the glyph name, or the like.

**Comment by akc42** [comment]
@tphinney I don't understand your comment.  The string of text I am trying to render is "home_health", as you can see in the screen shot of that, where I seem to end up getting is a "home" icon, followed by a number of other characters that I can't see, but which take up space.  If I look in dev-tools the raw text is shown as "home_health".  It is supplied to the customElement through a default slot.

**Comment by tphinney** [comment]
Aha. Apologies, I understand the problem now.

This icon is not present at all in Material Icons. It is available in the newer icon set/font, Material Symbols. So, my best advice is, switch to the newer font.

**Comment by akc42** [comment]
OK I think I got something wrong.

I have to change font-family to "Material Symbols Outlined" as well in my `:host` declaration.

Now it works and I get `home_health` displaying properly.

Should I close this issue, or do you want to leave it open to keep an action to add the font to the Material Icons.
