### ISSUE TITLE
Icons are no longer showing in https://fonts.google.com/icons

### ISSUE THREAD

**Issue by sabinebarrera** [google/material-design-icons#1477]
This is what I see:

![Screen Shot 2023-03-02 at 9 49 21 AM](https://user-images.githubusercontent.com/1494577/222512128-c776a56d-4b29-4403-9094-02746bb5096c.png)

**Comment by tphinney** [comment]
That sucks! Not what I am seeing. I checked using my laptop with Chrome over CenturyLink broadband, and iPhone with Safari over 5G T-Mobile. Both were loading icons just fine. So while it may be that other people are having problems, whatever you are seeing is not universal.

If you can, I would suggest:
- try the same device, but over a totally different internet connection
- try a different device, over the same internet connection

See if either (or both) of those works

**Comment by tphinney** [comment]
Given the site traffic and nobody else complaining, and the fact that I couldn't replicate the issue across multiple devices/browsers/ISPs, I am closing the issue.
