### ISSUE TITLE
`family=Material+Symbols` css URL in 'Using a font' section of README.md returns 404 error

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1478]
Within the *Using a font* section of the [`README.md`](https://github.com/google/material-design-icons/blob/master/README.md) file the URL recommended for accessing the Material+Symbols css now 404's when requested.
The URL given for the Material+Icons does work correctly.

Excerpt from README.md:
-------------------------------------------
The font and variablefont folders contain pre-generated font files that can be included in a project. This is especially convenient for the web; however, it is generally better to link to the web font hosted on Google Fonts:

```
<link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Material+Symbols"      <<<<<<<<<<<THIS returns 404
      rel="stylesheet">
```

The [https://fonts.googleapis.com/css2?family=Material+Symbols](https://fonts.googleapis.com/css2?family=Material+Symbols) link returns a 404.

**Comment by andri** [comment]
How is this not fixed yet?

**Comment by tphinney** [comment]
It is fixed now
