### ISSUE TITLE
Can I resell Icons if built upon in a new pack

### ISSUE THREAD

**Issue by RyanAGKnight** [google/material-design-icons#1479]
Would it be breaking the terms of use to create a pack of the materials icons but animated for use in products, and sell this as a stand alone pack. The resell terms are a tad confusing because of course materials is fine to use even when selling within a "product" however its clear this is referring to product as an application or website. Does anyone have any clarity on this?
Thanks in advance!

**Comment by tphinney** [comment]
Google’s Material Icons and Material Symbols are Apache 2.0 licensed. This is a permissive open source license that allows you to do a very wide range of things, including what I would interpret as exactly this kind of commercial use. BUT I am not a lawyer and cannot offer legal advice. (Nor am I a Google employee!)

There **are**, however, some notice requirements that come with Apache 2.0, about what you need to include with your software.

There are many resources available online explaining Apache 2.0 license terms. Google search is your friend here.  :)

**Comment by tphinney** [comment]
Here is the license https://github.com/google/material-design-icons/blob/master/LICENSE
At least right now, that is the Apache 2.0 license; here’s the header:

```
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

```

**Comment by RyanAGKnight** [comment]
On further questioning I got this response, I cannot sell animated icons based on the google material ones because:
"No, you cannot sell an animated icon pack that is made using the icons from the Google Material Icons pack. The Apache License 2.0, which governs the use of the Google Material Icons pack, allows for the icons to be used, distributed, and modified, but it does not permit the icons or any derivative works that incorporate them to be sold without adhering to the terms of the license.

This means that while you can use the Google Material Icons pack to create an animated icon pack, you cannot sell it as your own work without complying with the terms of the Apache License 2.0. If you wish to sell an animated icon pack that incorporates the Google Material Icons, you would need to release the pack under the same license and make it freely available to others."

**Comment by davelab6** [comment]
Ryan, can you forward that response to me? dcrossland@google.com
