### ISSUE TITLE
Open Dyslexic font breaks material icons get back alt text instead

### ISSUE THREAD

**Issue by specCon18** [google/material-design-icons#1484]
![image](https://user-images.githubusercontent.com/3745190/223286348-9e74c255-2540-40ec-aca6-099af2fb48ae.png)

all sites using the icon set look like this.

**Comment by tphinney** [comment]
So, the "icon set" is… a font. This is *not* something that can be fixed on our side in the icon font.

You are doing something to tell your browser to use Open Dyslexic to override ALL fonts on the web page. So… that includes the icons-as-font.

Part of the way the Material Icons / Material Symbols fonts work is, any icon may be specified one of two ways:
- by use of a single Unicode codepoint
- by typing the text name of the icon, which then gets automatically handled as a ligature for the icon

This page is using the second method. I suspect _both_ methods might be broken by the way you are using Open Dyslexic, but whether the first method is also broken by your override depends on exactly how the override mechanism handles missing codepoints and whether the original icon font is in the fallback stack.

It would be lovely if whatever function you are using had some way to say “override all fonts EXCEPT fonts with names including” and then a list of common fonts used for user interface purposes (Material Icons, Material Symbols, Font Awesome, etc.).

**Comment by specCon18** [comment]
Thank you for that information I will continue to look into the issue working with the extension creator. I had zero clue where to even start with such an interaction.

**Comment by tphinney** [comment]
Feel free to put them in touch with me or point them at this thread. I would be happy to have a more involved conversation with them, or just give them more detailed implementation thoughts, if that might help.
