### ISSUE TITLE
Add SVG font format

### ISSUE THREAD

**Issue by puzrin** [google/material-design-icons#149]
Please, add SVG font format. Existing TTF/Woff can not be opened in FontForge to convert.

__update:__

FF from PPA open font, but SVG export produce broken file.

**Comment by shyndman** [comment]
Hi Vitaly,

Why can't the file be opened?

**Comment by puzrin** [comment]
Because fontforge shows error instead of open it :( . I don't know why.

**Comment by puzrin** [comment]
I've installed latest FontForge from PPA, and it open font. But SVG export in fontforge is still broken.

Reported to https://github.com/fontforge/fontforge/issues/2369

Possible solution is:

- use commercial font editor to convert data
- write script to fix bad FF output

**Comment by puzrin** [comment]
https://github.com/fontforge/fontforge/issues/2369#issuecomment-111970157

One more comment. If you are not sure you really need xero descent, set it to ~15% from the bottom.

**Comment by katgironpe** [comment]
@puzrin you are right. I think a commercial font editor is needed. I tried webify and it did not work.

**Comment by grimen** [comment]
Any status on this? Out of the list of ~50 icon fonts I summarized "Material Design Icons" is the only icon font library that have no compiled SVG Font (i.e. `iconfont/MaterialIcons-Regular.svg`).

**Comment by grimen** [comment]
Seems to work great to do the conversion: `ttf2svg` (https://github.com/qdsang/ttf2svg)

**Comment by katgironpe** [comment]
@grimen if it works, test SVG output with fontello and create a pull request. Thank you!

**Comment by grimen** [comment]
@katgironpe I actually found a unicode-related bug in the output so ended up writing my own script that works well with Fontello too: https://github.com/grimen/svg-fontglyphs2svg/blob/master/script/ttf2svg. OK, will create a pull request soon then.

**Comment by katgironpe** [comment]
@grimen thank you!

**Comment by grimen** [comment]
@katgironpe I could not find any build step for the fonts - are the fonts generated externally? If so should I add the `.svg` font as pull request, or should I add the build step somewhere?

**Comment by katgironpe** [comment]
@grimen Since we use gulp, it might help to add the task for converting the ttf version to svg. That makes most sense although it is not documented. 

Everything goes here: https://github.com/google/material-design-icons/tree/master/iconfont

**Comment by katgironpe** [comment]
@grimen And is your update to `ttf2svg` available through npm? That may be best too.

**Comment by grimen** [comment]
@katgironpe 

#1: OK, then I know - will add a Gulp task then.

#2: That is a good idea, I will need to package it and release under another name to avoid clashes with existing one - something like `fonteditor-ttf2svg-cli`.

**Comment by grimen** [comment]
Finished (2): https://github.com/grimen/fonteditor-ttf2svg-cli

**Comment by grimen** [comment]
@katgironpe Any input on the PR?

**Comment by katgironpe** [comment]
@grimen gave one suggestion. I think this is mostly good. Thank you!
