### ISSUE TITLE
Icon request: gears

### ISSUE THREAD

**Issue by HilkopterBob** [google/material-design-icons#1496]
Moving gears
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_90849648_gears-icon-working-symbol-flat-design-vector.html&psig=AOvVaw1_HM7ruNWWiLVIqoAgCRpc&ust=1680095210882000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCKCepMPY_v0CFQAAAAAdAAAAABAE

**Comment by tphinney** [comment]
At the moment, we have a single gear, but not two gears.
https://fonts.google.com/icons?icon.query=gear

**Comment by HilkopterBob** [comment]
yeah and its a great icon, and i used it. but multiple gears would, IMHO show more of that working or work aspect than one, wich mainly stands for settings

**Comment by hbugdoll** [comment]
What about https://fonts.google.com/icons?icon.query=manufacturing ?

**Comment by HilkopterBob** [comment]
Yes! Thats a Great Icon for my use-case. I think the name may be a little odd our could use Gears as an alias, but all in all  great solution! Issue closed!
