### ISSUE TITLE
Show icon with CSS :after :before

### ISSUE THREAD

**Issue by ChumburidzeGio** [google/material-design-icons#150]
How to embed font using css content tag to show it in :after and :before ?

**Comment by estelle** [comment]
::before {
  content: "\E87C";
}

::after {
  content: "face";
}
http://codepen.io/estelle/pen/MwvOjd

**Comment by Angelmmiguel** [comment]
On this [CSS file](https://github.com/Angelmmiguel/material_icons/blob/master/app/assets/stylesheets/material_icons_unicode.css.erb#L85-L3265) you have the full unicode CSS classes for these icons. This is only for unicode version.

**Comment by shyndman** [comment]
I'm marking this closed. We're not currently generating CSS, and it looks like the linked file is perfect for your needs.

**Comment by kmturley** [comment]
You can achieve it by doing the following:

    .material-icons {
        direction: ltr;
        display: inline-block;
        font-family: 'Material Icons';
        font-size: 24px;
        font-style: normal;
        font-weight: normal;
        letter-spacing: normal;
        line-height: 1;
        text-transform: none;
        white-space: nowrap;
        word-wrap: normal;
        -webkit-font-feature-settings: 'liga';
        -webkit-font-smoothing: antialiased;
    }

Then using SASS you can extend it and set the content using pseudo css elements:

    ul
        &:before {
            @extend .material-icons;
            content: 'label';
        }
    }

**Comment by wzup** [comment]
@estelle share source of codes would be nice

**Comment by wzup** [comment]
@Angelmmiguel 
what you post is wrong! your codes has nothing to do with icons. This should be envelope for `email` icon, but it is not.

```
.material-icons.email:before,
.mi.email:before {
  content: '\e0be';
}
```

![envelope - google chrome 2016-06-26 00 07 16](https://cloud.githubusercontent.com/assets/3880497/16357773/15843e46-3b32-11e6-9822-8c6418840c2c.png)

**Comment by Angelmmiguel** [comment]
I will check it @wzup. I get these codes from [codepoints](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints#L258) and `email` code is `\e0be`.

**Comment by zerobytes** [comment]
The unicode code of the icons is exactly the same code you can find in https://design.google.com/icons/ but replacing the &#x for \
example
&#xE5CD;
\E5CD

**Comment by Willibaur** [comment]
Thank you very much @zerobytes I was struggling with this issue all weekend.
Clear explanation

**Comment by chandanndeep** [comment]
@estelle 
Thanks it's working

**Comment by mcansh** [comment]
@estelle add font-family: "Material Icons"; the ::before and ::after

**Comment by ifdouglas** [comment]
`::before {font-family: "Material Icons";
                        content: "\E876";
                    }`

**Comment by AlexVentura** [comment]
How to do the same if I have [Materialize](https://github.com/Dogfalo/materialize) included in my project?

**Comment by VeeK727** [comment]
I use it like this?

```
:before{
    font-family: 'Material Icons';
    content: 'chevron_left'
}
```

**Comment by saschaende** [comment]
@VeeK727 This does not work with Edge or Internet Explorer. This only works with firefox and chrome.

**Comment by telalwar** [comment]
@saschaende Did you find a way to fix it on Edge or Internet Explorer?

**Comment by Cartman0** [comment]
I find char code list in https://material.io/tools/icons/. where?

**Comment by rogerza** [comment]
Here are the Material Design Icons with char codes - https://cdn.materialdesignicons.com/1.8.36/

Note: You also need to specify the `font-family`, as stated here:  https://github.com/Templarian/MaterialDesign/issues/1945

So, as an example, a  sort icon could look like

```
th[aria-sort="ascending"] .mat-sort-header-button:after {
  content: '\f062';
  font-size: 24px;
  margin-left: 0.5rem;
  font-family: 'Material Design Icons';
}
```

**Comment by Cartman0** [comment]
@rogerza thanks!

**Comment by charleslukes** [comment]
I noticed a nuance here.
What if we want to add some other text with the icon?

::after { 
      font-family: "Material Icons";
       content: "\E876  this is the other content";
      }

The Icon only shows and the content words are not displayed since they are not part of a Material icon family.
How do you handle this scenario?

**Comment by maltfield** [comment]
It looks like the codepoints are no longer available? Where do you all find the resources that lists the unicode codepoint for each of the characters in this icon set in 2020?

**Comment by felipegenuino** [comment]
> On this [CSS file](https://github.com/Angelmmiguel/material_icons/blob/master/app/assets/stylesheets/material_icons_unicode.css.erb#L85-L3265) you have the full unicode CSS classes for these icons. This is only for unicode version.

New codes => Materials icons full unicode CSS https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

**Comment by kellyblaire1** [comment]
Use it like this:
```
:before {
	font-family: "Material Design Icons";
	content: "\F13CD" /* this can be gotten from the cheatsheet here: https://pictogrammers.github.io/@mdi/font/5.4.55/ */
}
```

**Comment by kellyblaire1** [comment]
Use it like this:
```
:before {
	font-family: "Material Design Icons";
	content: "\F13CD" /* this is the icon code which can be gotten from the MDI cheatsheet here: https://pictogrammers.github.io/@mdi/font/5.4.55/ */
}
```
