### ISSUE TITLE
cant center minimize icon 

### ISSUE THREAD

**Issue by ryzen322** [google/material-design-icons#1502]
here is the code 
 the icons works properly accept this minimize

<div class="parent">
 <span class="material-symbols-rounded"> minimize </span>
</div>

**Comment by tphinney** [comment]
You wrote “here is the code” but did not provide any code.

The existing minimize icon is centered left/right, but is not centered vertically—but that is the point! The icon indicates “minimize” by being far below the normal midpoint of the icons.
