### ISSUE TITLE
Scratch Offline Editor for Windows does not show icons properly

### ISSUE THREAD

**Issue by gharehyazie** [google/material-design-icons#1506]
Hello everyone.
I have installed Scratch on my Windows laptop for my son to use. However, the application is not displaying icons properly. Is there a fix to this issue?

![image](https://user-images.githubusercontent.com/5271738/236459603-eb48b98f-5c4d-4605-b774-4323e4a64092.png)

**Comment by Mickmick2012** [comment]
this isn't related at all from material design, post your issue at the official Scratch repostery : https://github.com/scratchfoundation/scratch-gui

**Comment by tphinney** [comment]
Agree
