### ISSUE TITLE
Icon request: Brand account

### ISSUE THREAD

**Issue by Craftplacer** [google/material-design-icons#1512]
It would be nice if the icon set included the brand account icon once used for Google+

Reference:
![image](https://github.com/google/material-design-icons/assets/22963120/c153f99a-b4db-4d1d-8831-5dbeafef2a89)

**Comment by nadernasery** [comment]
***@***.***باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Crafti ***@***.***>تاریخ: پنجشنبه ۱۸ مهٔ ۲۰۲۳،‏ ۷:۱۶به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: [google/material-design-icons] Brand account (Issue #1512)
It would be nice if the icon set included the brand account icon once used for Google+
Reference:
