### ISSUE TITLE
Material icons emoji_events missing from material symbols?

### ISSUE THREAD

**Issue by brandonburkett** [google/material-design-icons#1514]
In material icons there was an icon called `emoji_events` that looked like a trophy.  We are upgrading to material symbols and I don't see `emoji_events`.  Has it been removed completely?

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Brandon Burkett ***@***.***>تاریخ: پنجشنبه ۱۸ مهٔ ۲۰۲۳،‏ ۲۳:۲۲به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: [google/material-design-icons] Material icons emoji_events missing from material symbols? (Issue #1514)
In material icons there was an icon called emoji_events that looked like a trophy.  We are upgrading to material symbols and I don't see emoji_events.  Has it ben removed completely?

**Comment by Carmenlopezq** [comment]
> ***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Brandon Burkett ***@***.***>تاریخ: پنجشنبه ۱۸ مهٔ ۲۰۲۳،‏ ۲۳:۲۲به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: [google/material-design-icons] Material icons emoji_events missing from material symbols? (Issue #1514) In material icons there was an icon called emoji_events that looked like a trophy. We are upgrading to material symbols and I don't see emoji_events. Has it ben removed completely? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

/

**Comment by tphinney** [comment]
`emoji_events` was a clone of `trophy`.

The name and PUA Unicode codepoint for `emoji_events` is still supported in Material Symbols, but the duplicate icon is not shown in the website UI for Material Symbols.

**Comment by brandonburkett** [comment]
Thanks for the update!   `trophy` doesn't work for me either (and also doesn't show in the website UI).  I only see `military_tech` show up when searching for `trophy`.

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Brandon Burkett ***@***.***>تاریخ: جمعه ۱۹ مهٔ ۲۰۲۳،‏ ۱:۴۲به: google/material-design-icons ***@***.***>گیرنده کپی: nadernasery ***@***.***>, Comment ***@***.***>موضوع: Re: [google/material-design-icons] Material icons emoji_events missing from material symbols? (Issue #1514)
Thanks for the update!   trophy doesn't work for me either (and also doesn't show in the website UI).  I only see military_tech show up when searching for trophy.

**Comment by brandonburkett** [comment]
I spent a lot of time testing and I suspect the icon is missing.  This only shows a box with an X in it: `<i class="material-symbols-outlined" aria-hidden="true">&#xea23;</i>`

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Brandon Burkett ***@***.***>تاریخ: دوشنبه ۲۲ مهٔ ۲۰۲۳،‏ ۱۸:۲۳به: google/material-design-icons ***@***.***>گیرنده کپی: nadernasery ***@***.***>, Comment ***@***.***>موضوع: Re: [google/material-design-icons] Material icons emoji_events missing from material symbols? (Issue #1514)
I spent a lot of time testing and I suspect the icon is missing.  This only shows a box with an X in it: <i class="material-symbols-outlined" aria-hidden="true">&#xea23;</i>

**Comment by tphinney** [comment]
The design work and font production has been done, I imagine it will most likely be available some time this month.
The glyph names will be trophy and emoji_events
