### ISSUE TITLE
The variable fonts and codepoints are outdated and need to be updated with new icons

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1517]
The codepoint and TTF icon files found at https://github.com/google/material-design-icons/tree/master/variablefont are outdated and do not include all icons shown at [the material symbols browser](https://fonts.google.com/icons?icon.style=Outlined&selected=Material+Symbols+Outlined:pip:FILL@0;wght@400;GRAD@0;opsz@48)

Examples of missing icons that have been reported at issue [1](https://github.com/timmaffett/material_symbols_icons/issues/3) and issue [2](https://github.com/timmaffett/material_symbols_icons/issues/4)  for the flutter material symbols icons package are 
|icon    |        codepoint|
|-------|-----------------|
|`pip`  |           `f64d` |
|`page_info` | `f614` |

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Tim Maffett ***@***.***>تاریخ: دوشنبه ۲۲ مهٔ ۲۰۲۳،‏ ۲۱:۲۷به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: [google/material-design-icons] The variable fonts and codepoints are outdated and need to be updated with new icons (Issue #1517)
The codepoint and TTF icon files found at https://github.com/google/material-design-icons/tree/master/variablefont are outdated and do not include all icons shown at the material symbols browser
Examples of missing icons that have been reported at issue 1 and issue 2  for the flutter material symbols icons package are
iconcodepointpipf64dpage_infof614

**Comment by hunterbreathat-wk** [comment]
The code point for  `page_info` is actually `f64d`

**Comment by timmaffett** [comment]
I can confirm that yesterdays update (6/5/23) to the variable fonts has fixed this issue.

**Comment by tphinney** [comment]
Great! Thanks.
