### ISSUE TITLE
Bug in Fill=1.0 of Outlined and Sharp material symbols Variable font versions of `nest_clock_farsight_analog` icon

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1518]
The Fill=1.0 of the icon `nest_clock_farsight_analog` does not work correctly for the outlined and sharp  versions of the material symbols variable true type fonts found in https://github.com/google/material-design-icons/tree/master/variablefont

It does fill correctly for the ROUNDED version of the font.

Here is an image from Adobe photoshop

![bug_report_material_symbols_icons](https://github.com/google/material-design-icons/assets/3639881/8d5bd55b-414c-4391-b744-47b941e642dc)

NOTE: This does work correctly for the WOFF2 versions of the font used at [google fonts page](https://fonts.google.com/icons?icon.style=Sharp&selected=Material+Symbols+Sharp:nest_clock_farsight_analog:FILL@1;wght@400;GRAD@-25;opsz@48&icon.query=nest_clock_farsight_analog)

You can also see the fill problem occur in this flutter application which uses the material symbols icons true type variable fonts:
![Untitled-1 @ 100% (Sharp, RGB_8#) _ 5_22_2023 1_49_09 PM](https://github.com/google/material-design-icons/assets/3639881/0c7944de-86b4-49e9-bb49-bb99b09fc758)

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Tim Maffett ***@***.***>تاریخ: سه‌شنبه ۲۳ مهٔ ۲۰۲۳،‏ ۰:۲۶به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: [google/material-design-icons] Bug in Fill=1.0 of Outlined and Sharp material symbols Variable font versions of `nest_clock_farsight_analog` icon (Issue #1518)
The Fill=1.0 of the icon nest_clock_farsight_analog does not work correctly for the outlined and sharp  versions of the material symbols variable true type fonts found in https://github.com/google/material-design-icons/tree/master/variablefont
It does fill correctly for the ROUNDED version of the font.
Here is an image from Adobe photoshop

NOTE: This does work correctly for the WOFF2 versions of the font used at google fonts page
You can also see the fill problem occur in this flutter application which uses the material symbols icons true type variable fonts:

**Comment by timmaffett** [comment]
I can confirm that yesterdays update (6/5/23) to the variable fonts has fixed this issue with the filling of the `nest_clock_farsight_analog` icon.

**Comment by tphinney** [comment]
Thanks Tim!
