### ISSUE TITLE
Folder outline is bugged

### ISSUE THREAD

**Issue by cyberalien** [google/material-design-icons#1522]
In the latest version of Material Symbols, `folder` icon is bugged: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/folder/default/24px.svg

It shows `bedtime_off` icon instead of `folder`.

**Comment by tphinney** [comment]
Hmmm. The SVG file is wrong, but the variable font seems to be just fine in this regard. @EsoFromTheEast can you look at this?

**Comment by EsoFromTheEast** [comment]
Fixed

**Comment by EsoFromTheEast** [comment]
Give it couple of hours to propagate
