### ISSUE TITLE
Why are SVG viewBox values set so high for symbols? Every symbol is "0 96 960 960"

### ISSUE THREAD

**Issue by fmotion1** [google/material-design-icons#1523]
The width and height values are set correctly and correspond to the correct symbol size. But viewBox values are huge (960px). Will this affect web usage at all? Can I just ignore the viewbox?

Any input appreciated.

**Comment by cyberalien** [comment]
`viewBox` is not width/height, it tells browser which part of icon to render. Do not remove it or it might lead to unexpected results.

Width/height attributes tell browser what size to render. Use them to resize icon.

**Comment by tphinney** [comment]
cyberalien is right. The viewBox ensures the desired positioning, without that the icons would not have consistent visual centering.

**Comment by fmotion1** [comment]
I understand that the viewbox ensures positioning. I know what the viewbox value is. 

In illustrator, the viewbox is the size of the artboard. By having a viewport of say `0 0 24 24`, the icon will sit on a 24x24px artboard. This allows the creator of the icon to ensure that the icon is pixel perfect at that size. The really large `viewbox` here confuses me because it signifies that the icon was designed at very large dimensions _without_ pixel perfection in mind, or a target display size. 

This is a google product though, so I'll give the benefit of the doubt. 

Can someone explain to me the target size in pixels that these icons were made to be rendered at?

**Comment by tphinney** [comment]
The target size in pixels varies, because there is a size axis, so they explicitly cover anywhere from 20 px to 48 px.

**Comment by fmotion1** [comment]
Ok. Thanks for providing some more information. If you find out anything else about the "magic" size in pixels that a certain set or grade of icons will render at, it would be most helpful. I realize that the variable stroke width and various optical sizing options will make them render more precisely at different sizes, but I'd at least like to know what combination of grades/optical properties/weights/etc. correspond to pixel perfection at X size. If that's not possible, I understand. I might just dive in and resize them all myself and make corrections for specific sizes. 

Any further information welcome.

**Comment by tphinney** [comment]
I have a pretty good idea, seeing as I build the fonts and spec the transformations of the axes....

Basically, the only pixel-perfect versions are at Regular (400) weight, when you have no adjustment to Grade either. At those settings, the 20 and 24 sizes are perfectly grid-aligned at 20 and 24 px. The 40 and 48 px sizes are not.

* Actually there are still some 20 px icons that are not yet perfectly grid-aligned in Google Symbols. That is a work in progress, but mostly done. I think 73% last time I checked.

**Comment by fmotion1** [comment]
Awesome! Thank you so much for the information. I know your time is valuable and I appreciate your attention to this issue. This is really good to know.

**Comment by markgrambau** [comment]
I'd love to see this reopened and addressed if possible. I'm the first do admit I'm a designer, not a dev, so the subtleties of this are a bit over my head, but it's causing me grief with my developer partners. Some of the symbols have the bizarre "0 96 960 960" viewbox, others don't have a viewbox defined at all, *just* width/height. Devs don't know what to do when I hand over assets that _should_ be constructed similarly but aren't. I end up having to rebuild them.

**Comment by Hai-San** [comment]
I'm having trouble with this at the moment. 
The sizes within the viewbox being different from the sizes in the width and height attributes is already a problem for development issues. But even worse is the Y axis with -960, this is really disturbing. Several other libraries leave the axes at the zero point, so it's easy to adjust.

**Comment by sammyaxe** [comment]
I really don't understand why negative -960 is required?

viewBox="0 -960 960 960"

this leads to even more unexpected issues.
