### ISSUE TITLE
Icon Request: Nearby

### ISSUE THREAD

**Issue by Sxxov** [google/material-design-icons#1529]
There are already [`nearby_off`](https://github.com/google/material-design-icons/tree/master/src/device/nearby_off) & [`nearby_error`](https://github.com/google/material-design-icons/tree/master/src/device/nearby_error).

Would be nice to have a `nearby` with the same diamond icon but without the status.

**Comment by tphinney** [comment]
This was just added. It is currently in Symbols but not in Icons, though.
Symbols is the more up-to-date and larger set.
