### ISSUE TITLE
"more vert" not correct from GWF

### ISSUE THREAD

**Issue by MusikDK** [google/material-design-icons#153]
I get the wrong icon when using the "more vert" icon through Google Web Fonts. Is this a known bug?

**Comment by shyndman** [comment]
No, it isn't, but I can't reproduce. Take a look at this pen:

http://codepen.io/anon/pen/doVmjv

**Comment by shyndman** [comment]
Feel free to re-open if you're still running into issues.

**Comment by MusikDK** [comment]
I still have that issue. Really weird. I've attached an image here.
![skaermbillede 2015-06-22 kl 10 41 13](https://cloud.githubusercontent.com/assets/2795052/8278412/4f2c5f1e-18cb-11e5-9192-2dc528c89f2e.png)

**Comment by shyndman** [comment]
I think you got it (because your comment is gone). You were missing an underscore.

**Comment by MusikDK** [comment]
@shyndman: 100% correct :)
