### ISSUE TITLE
Question: Possible to load some icons only through Google Fonts?

### ISSUE THREAD

**Issue by MusikDK** [google/material-design-icons#155]
With the normal Google Fonts is it possible to import a few characters only and since I feel using icons as webfonts are simpler than SVG's this would be a very good option, when not using more than 5-15 icons.

**Comment by shyndman** [comment]
That's something we've been thinking about, but we don't have anything to announce yet.

For now, I've engaged fontello.com to include our icons as one of their base sets, and they're working on getting that going in fontello/fontello#417

**Comment by MusikDK** [comment]
Thanks! Both solutions would be great :)
