### ISSUE TITLE
'blinds' symbol is not rounded on Material Symbols Rounded

### ISSUE THREAD

**Issue by Loewe111** [google/material-design-icons#1550]
![grafik](https://github.com/google/material-design-icons/assets/78087018/e44659fb-3df8-46f7-b17f-fbd2ad3b8a75)
unlike other icons like `curtains` the `blinds` icon is not rounded or on the sides
![grafik](https://github.com/google/material-design-icons/assets/78087018/7956b131-4c17-421a-bfc7-65d2abcf369d)
![grafik](https://github.com/google/material-design-icons/assets/78087018/24f95bdb-0946-4c44-9c17-651048a93737)

**Comment by tphinney** [comment]
What’s funny is, /blinds_closed has a rounded version, but /blinds does not. Definitely a bug on our end. Thanks for reporting it!

**Comment by tphinney** [comment]
Done in source, will percolate through to the fonts “soon”
