### ISSUE TITLE
Threads Icon

### ISSUE THREAD

**Issue by fredroo** [google/material-design-icons#1553]
Please add threads.net a meta social network

![threads-seeklogo com-2](https://github.com/google/material-design-icons/assets/6863089/352d7a2c-1b82-4088-9bef-d3a256b6e056)

**Comment by tphinney** [comment]
https://github.com/google/material-design-icons#third-party-logos

tl;dr 3rd-party logos are not currently included in the icon sets, as a matter of policy, for legal reasons.
