### ISSUE TITLE
Kwai Icon

### ISSUE THREAD

**Issue by fredroo** [google/material-design-icons#1554]
Please add kwai.com social network icons
![kwai-logo](https://github.com/google/material-design-icons/assets/6863089/ce5166b2-6fd3-4b96-9561-d9339e13d964)

**Comment by tphinney** [comment]
https://github.com/google/material-design-icons#third-party-logos

tl;dr 3rd-party logos are not currently included in the icon sets, as a matter of policy, for legal reasons.
