### ISSUE TITLE
X Corp Icon

### ISSUE THREAD

**Issue by fredroo** [google/material-design-icons#1555]
X corp new app from ELON MUSK
![X_logo_2023](https://github.com/google/material-design-icons/assets/6863089/5a69093d-b178-4dbd-a61d-7f7eecfeca73)

**Comment by tphinney** [comment]
https://github.com/google/material-design-icons#third-party-logos

tl;dr 3rd-party logos are not currently included in the icon sets, as a matter of policy, for legal reasons.
