### ISSUE TITLE
 icon arrow side error

### ISSUE THREAD

**Issue by TechD-Robin** [google/material-design-icons#157]
in "editor/drawable-hdpi" directory's 
ic_format_indent_decrease_black_18dp.png
ic_format_indent_decrease_black_24dp.png
ic_format_indent_decrease_black_36dp.png
ic_format_indent_decrease_black_48dp.png

ic_format_indent_decrease_white_18dp.png
ic_format_indent_decrease_white_24dp.png
ic_format_indent_decrease_white_36dp.png
ic_format_indent_decrease_white_48dp.png

these image's arrow side at left or right are not equal like below : 
ic_format_indent_increase_black_18dp.png
ic_format_indent_increase_black_24dp.png
ic_format_indent_increase_black_36dp.png
ic_format_indent_increase_black_48dp.png

ic_format_indent_increase_white_18dp.png
ic_format_indent_increase_white_24dp.png
ic_format_indent_increase_white_36dp.png
ic_format_indent_increase_white_48dp.png

and, has the same program in "editor/drawable-mdpi", "editor/drawable-xhdpi" and "editor/drawable-xxhdpi",

**Comment by shyndman** [comment]
Thanks @TechD-Robin. I've reported the issue to our designers.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
