### ISSUE TITLE
Class based version. (Non ligature)

### ISSUE THREAD

**Issue by crdeutsch** [google/material-design-icons#158]
Is there a style sheet anywhere that defines classes (like Bootstrap) instead of ligatures.

The Ligatures tend to look horrible on slow network connections.

I get they're for accessibility, but I'd rather have my own "placeholder" text then the long names Google has picked.

Example of broken UI waiting for the font to download:
![hideous](https://cloud.githubusercontent.com/assets/404765/8334511/f529556e-1a5d-11e5-9abf-7ffbee47c709.png)

**Comment by shyndman** [comment]
Hey @crdeutsch,

No, we don't have a stylesheet, but you could avoid the FOUT by using a font loader like [typekit/webfontloader](https://github.com/typekit/webfontloader) or [bramstein/fontloader](https://github.com/bramstein/fontloader).

**Comment by cloud-walker** [comment]
Still seems a bad design decision to me... using a font loader will slow down the load of the font binding the loading process to javascript. The best solution in my opinion remain to stop support ligatures solution and start using something better.

**Comment by malkyfaith** [comment]
I am dealing with the same problem. I spend a full day to avoid FOUT. I have even used webfontloader to integrate the material design icon font - but I don't see much effect. Agreed with cloud-walker. There should be some other way other than using ligatures.

**Comment by Montesdodgers13** [comment]
Help me figure out how to install my G Suite service on my iPhone

**Comment by atodd-geoplan** [comment]
Thanks to this guy I guess: http://zavoloklom.github.io/material-design-iconic-font/icons.html
