### ISSUE TITLE
[Material Symbols] circle_add icon broken

### ISSUE THREAD

**Issue by sream** [google/material-design-icons#1584]
I'm using the material symbols packaged by marella and this is what the circle_add icon looks like in the latest version:

![image](https://github.com/google/material-design-icons/assets/7093176/8b8fab44-114e-4c7d-be7a-24e09f57b696)

**Comment by tphinney** [comment]
The icon you are looking for is called "add_circle" not "circle_add"

Because circle and add are both legitimate icons on their own, if you enter that non-working combo name, you get both of those, and the underscore in between.
