### ISSUE TITLE
Icon request: Filled star

### ISSUE THREAD

**Issue by andrewbaxter** [google/material-design-icons#1585]
Apologies if I'm missing something simple.

There's an outline/empty star, and a half full star, but no full star.  I'm not aware of any simple font tricks to fill one in automatically.  I couldn't find any discussions about this.

**Comment by tphinney** [comment]
The new font and icon set are called Material Symbols.
They font includes variable font axes, and one of them is a Fill axis. The overwhelming majority of the icons in the set are affected by the Fill axis, and thus go from hollow to filled. This absolutely includes the star icon.
Toggle the Fill on in the preview UI with bit circled in hot pink here:
<img width="924" alt="Screenshot 2023-10-02 at 9 51 48 PM" src="https://github.com/google/material-design-icons/assets/6548266/6652e2f4-fed2-4a25-a994-dcd522544ca3">

**Comment by andrewbaxter** [comment]
Ah thanks!  So I guess there's no way to use both with the static font, aside from including it multiple times.

**Comment by andrewbaxter** [comment]
And thank you for the detailed response! :bow:

**Comment by tphinney** [comment]
Yes, you would need to include a filled variant as well as the default hollow version.
And you’re welcome!  😊
