### ISSUE TITLE
MaterialIcons-Regular.ttf isn't a valid font file (Windows 8.1.1)

### ISSUE THREAD

**Issue by Shidell** [google/material-design-icons#159]
Windows 8.1.1 x64 informs me that MaterialIcons-Regular.ttf is not a valid font file. I'm unable to preview the font nor install it.

**Comment by Shidell** [comment]
Other users have implied that Windows does not recognize the font file as valid, Linux (Ubuntu) does, however.

**Comment by jestelle** [comment]
Odd.

Can you try http://www.google.com/design/icons/
and/or
http://google.github.io/material-design-icons/

On that Windows machine and let us know if the icons render correctly?

Also, have you tried any other icons fonts on that machine?

**Comment by Shidell** [comment]
I've browsed both pages, and I can view the icons on the web just fine (using Chrome 43.0.2357.130 m 64-bit). 

I followed your second link to the GitHub repository, which is where I originally sourced the MaterialIcons-Regular.ttf. Windows is informing me that it isn't a valid font file when I right click and select "Preview", and additionally will not let me install the font.

(Ultimately, I'd like to incorporate the icons into Visual Studio, but that too fails to render the icons--I can include the MaterialIcons-Regular.ttf as normal in a WPF project, trying to reference an icon by it's code presents nothing.)

I have downloaded the material-design-icons-2.0.0.zip archive, and all of those resources look and render appropriately. I would need to use a the font icon set, however, as Windows wants a lot of "strange" icon sizes (for example, 16 pt. font for menu icons, etc.)

I am using other icon fonts (FontAwesome), and I've experimented with Sergey Kupletsky's Material Design package (http://zavoloklom.github.io/material-design-iconic-font/index.html), both of which are working fine. Additionally, I'm using other fonts, including Open Sans (which you're probably aware is a Google Font, and hosted here: https://www.google.com/fonts). 

Open Sans previews and installs properly, as does FontAwesome 4.3.0, etc. I've only run into trouble with MaterialIcons-Regular.ttf, which is (as you said), odd.

Might it be that the font works on Linux/Unix and not Windows? I've asked coworkers (also running 8.1.1 x64) to test as well to ensure it isn't just my machine, and three others have the same result. I'm going to ask users on reddit.com/r/materialdesign to try previewing/installing the font and to post their results to collect more information across different OSes and architectures.

Is there anything else I can test or try to determine what the cause might be?

**Comment by jestelle** [comment]
Thanks for all the details Shidell.  

The first thing you were downloading I believe wasn't the font at all, but was actually the HTML for Github's details about that file.

Glad you got it worked out.

**Comment by erik-stunning** [comment]
Hi, I'm trying to use the ttf font on Mac (in Photoshop), but it's not working? Is the font even supposed to work locally on a computer? There is no info whatsoever about this on the Material Icons web page, and I have google all over without luck. 

Anyone that can help? I would really like to use the font to embed icons in my Photoshop designs and not have to open every single PNG icon just to use them.

**Comment by erik-stunning** [comment]
Ok I just found this page that solves the problem:
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html

Once you copy and paste the icon itself from that page and paste it into Photoshop with the font selected, then it works.

Just confused there's no info about how to do this anywhere? Whereas using the font in code/on a website is described into maximum detail.

**Comment by erik-stunning** [comment]
Says it's a font for designers but maybe Google really just see web developers as designers :-)
