### ISSUE TITLE
Icon Request: Unpin

### ISSUE THREAD

**Issue by aldman123** [google/material-design-icons#1595]
Related to https://github.com/google/material-design-icons/issues/450

I would love to have an icon to represent the opposite of the [push pin](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apush_pin%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) icon. If a user has pinned an item, this icon would represent a button to unpin it.

This could be as simple as a line cutting through the current push pin icon.  https://www.google.com/search?q=unpin+icon

**Comment by tphinney** [comment]
Ah, so like "location_off" only for "push_pin"—I understand.

**Comment by bilelz** [comment]
`pin_off` needed please
https://fonts.google.com/icons?icon.query=off

**Comment by tphinney** [comment]
This is in the works and will be available in the next update. Look for:

keep
keep_off
keep_public

(Requests for the old name or codepoint will still work, even though it won’t be shown in the icon listing.)

**Comment by passee** [comment]
Why is this not available on Material **Icons**?

**Comment by tphinney** [comment]
Material **Icons** is the classic icons set, which hasn’t been added to in at least a couple of years AFAIK. Material Symbols is where the action is!

**Comment by passee** [comment]
Thats new for me, then is there a way to use Material Symbols with <mat-icon>?

**Comment by tphinney** [comment]
Yes, see https://github.com/angular/components/issues/24845

**Comment by passee** [comment]
Much thanks! Works great 😄

**Comment by garg10may** [comment]
is this added?

**Comment by spauldhaliwal** [comment]
> is this added?

Yes. It's called [keep_off](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:keep_off:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=keep&icon.size=24&icon.color=%235f6368)
