### ISSUE TITLE
Please add ? and ◻ for font loaders that expect a glyph to represent "missing"

### ISSUE THREAD

**Issue by sowbug** [google/material-design-icons#1600]
See https://github.com/emilk/egui/issues/3526 for context. If a library loads a .ttf, it might load and cache ◻ or ? to have something to display when a glyph is missing. Unfortunately, the Material Icons TTF files don't include either of those glyphs, so the loading code crashes. While I'd say this is more of a bug in the library than in the TTF, I concede that it's extraordinary for a font family to have no representation of ◻, and especially ?, so I speculate that this particular library code isn't the only one failing to load this font.

Thanks!

**Comment by tphinney** [comment]
Fonts generally have a glyph called .notdef which is intended for fallback when some desired character is missing.
Usually a rectangular box, often with something in it, which is sometimes a question mark… or an X that goes right to the borders of the box.

Material Symbols has a .notdef
So I am not immediately inclined to start adding support for arbitrary non-standard fallback characters... just not sure where that ends, and there is an obvious answer of: use the standard thing.

**Comment by sowbug** [comment]
I did not know about that! I will see about enhancing the egui library to teach it about notdef. Thanks!
