### ISSUE TITLE
ic_location_searching_48.svg is wrong.

### ISSUE THREAD

**Issue by dlazerka** [google/material-design-icons#163]
Here's what I see when open the icon https://raw.githubusercontent.com/google/material-design-icons/50c4d857c61443b763344b7958326e68d20f6934/device/svg/production/ic_location_searching_48px.svg on my machine:
![screenshot from 2015-06-29 17 01 01](https://cloud.githubusercontent.com/assets/592184/8421198/51db53c2-1e80-11e5-90e5-4398a47fba45.png)

Problem seems to be in curve `c-8.34.92-14.96`: it's quite a strange coordinate -- `8.34.92`.

**Comment by shyndman** [comment]
Hey @dlazerka,

Looks alright over here. What's your OS/browser?

**Comment by shyndman** [comment]
And if you're opening the SVG in an image editing application, try using this file instead (note that `production` changed to `design`).

https://raw.githubusercontent.com/google/material-design-icons/50c4d857c61443b763344b7958326e68d20f6934/device/svg/design/ic_location_searching_48px.svg

**Comment by shyndman** [comment]
Quick explanation:
We run our SVGs through an optimization tool called svgo, which reduces bytes by getting away with all sorts of tricks, including what you're seeing there (which seems to take advantage of how the browsers' tokenize floats in paths). Everything that you find in the `production` directory has undergone this process, while the `design` directory has not.

**Comment by dlazerka** [comment]
Hey!
Actually, it's reproducible with `design` version as well.
I've reproduced it in both [GIMP](http://www.gimp.org/), and [Gnome Image Viewer](https://wiki.gnome.org/Apps/EyeOfGnome). It's *not* reproducible in Google Chrome though.
Adding a whitespace resolves the issue: `8.34 .92`.

Actually, reading the SVG [spec](http://www.w3.org/TR/SVG/paths.html#PathDataBNF) sounds like it's valid:

> The processing of the BNF must consume as much of a given BNF production as possible, stopping at the point when a character is encountered which no longer satisfies the production. 
> ...
> Similarly, for the string "M 0.6.5", the first coordinate of the "moveto" consumes the characters "0.6" and stops upon encountering the second decimal point because the production of a "coordinate" only allows one decimal point. The result is that the first coordinate will be "0.6" and the second coordinate will be ".5".
So I probably should file a bug report for GIMP and EOG.

**Comment by dlazerka** [comment]
Filed https://bugzilla.gnome.org/show_bug.cgi?id=751745

**Comment by shyndman** [comment]
Ah, my mistake. `design` has been run through svgo as well.

Thanks for filing that. I'm making note of this on my end as well. We may disable certain optimizations for the design versions in future versions.
