### ISSUE TITLE
IOS support for left side panel

### ISSUE THREAD

**Issue by bagavmarkiv** [google/material-design-icons#1638]
Address the mobile IOS support for the material icon and adjust the CSS based on its position.

**Comment by tphinney** [comment]
I don’t understand this request. Can you explain more clearly?
Is this a complaint about the Google website that displays the icons? Can you give a URL that is displaying badly on iOS mobile devices?

**Comment by tphinney** [comment]
Lacking any clear feedback, closing this issue for now. Could reopen if it is clarified, actionable, etc.
