### ISSUE TITLE
Fonts may be used in commercial printed books?

### ISSUE THREAD

**Issue by jdomingueza** [google/material-design-icons#1644]
May the fonts files be used for printed publications?

**Comment by tphinney** [comment]
The Material Symbols fonts are licensed under Apache v2.0.
This is one of the same licenses used in some Google Fonts.
I think you will find the answer to your question as the second item in the Google Fonts FAQ: https://developers.google.com/fonts/faq

**Comment by jdomingueza** [comment]
Thanks. I reviewed it in advance to my post here, and I couldn't find any explicit reference to "printed materials" in the Apache v2.0 license...

**Comment by tphinney** [comment]
Seems obvious to me, but I am not a lawyer, nor am I speaking for Google in interpreting their license.

**Comment by tphinney** [comment]
I will just note that as the Apache license was originally developed for software in general, not specifically for fonts, that is why it is not completely explicit on this point.

This discussion on Quora covers the same question, I think: https://www.quora.com/What-does-it-mean-for-any-font-to-have-an-Apache-2-0-license-Does-that-mean-I-can-use-that-font-freely-for-commercial-purposes
