### ISSUE TITLE
Unable to Install new Material Symbols .ttf files on mac

### ISSUE THREAD

**Issue by sahejclt** [google/material-design-icons#1648]
Trying to install the new material symbols update but FontBook is giving me this error:

**No Installable Fonts Selected**
_MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf contains no fonts that can be installed on macOS. Check your selection and try again._

I need to install the files locally so I can use them as icon fonts in Figma. The plugin doesn't work for me because my icon components are set up differently and I would like to keep it as is.

**Comment by tphinney** [comment]
What version of macOS are you running?
The current version of that file (from about 3 weeks ago) installs fine for me with FontBook on Sonoma 14.1.1
I am wondering if your download was incomplete or got damaged somehow. It should be an 8.3 MB file.

**Comment by sahejclt** [comment]
Hey, that worked! The files I downloaded were around 380kb each. I forked and downloaded this time and got the correct files. Thanks!

**Comment by tphinney** [comment]
Awesome, glad my suspicion was in fact the right answer!  :)
