### ISSUE TITLE
[font] star and star_half are vertically misaligned

### ISSUE THREAD

**Issue by nevir** [google/material-design-icons#165]
http://codepen.io/nevir/pen/mJxBeX :(

A `margin-top: -0.02em;` on a `star_half` can adjust for it as a workaround

**Comment by jestelle** [comment]
looks like a bug. will look into further and likely fix.

**Comment by jestelle** [comment]
The original designed asset has the bug, so it's not just the font.
Our designers will update them.

Might take a little while before we completely propagate the fix, but we're on it.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
