### ISSUE TITLE
Rounded version of Variable Font missing new icons from Dec14, 2023 release

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1655]
The Rounded version of the variable font is missing the new icons that have been added to the Outlined and Sharp version.
The Outlined and Rounded versions of the variable fonts released on Dec 14, 2023 have the following new code point/icons:
```
 f4f1  # brand_family
 f4f2  # media_output
 f4f3  # media_output_off
```
These are missing from the Rounded version of the font  (/variablefont/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf)

**Comment by timmaffett** [comment]
(You can easily see this in that the Outlined and Sharp versions of the files from the variablefont directory were released Dec 14, 2023 and the Rounded versions of the files have not been updated since the last release)

**Comment by tphinney** [comment]
Hmmm. Well, the Rounded version is always built at the same time, not sure why the others were released and not that one. @EsoFromTheEast ?

**Comment by timmaffett** [comment]
The fonts where re-generated 11 hours ago - and the **rounded** version IS STILL NOT BEING GENERATED. 
The file dates for the **rounded** version are still from last month, before the last version (when I originally reported this bug).

You can clearly see here:   https://github.com/google/material-design-icons/tree/master/variablefont

**Comment by timmaffett** [comment]
@EsoFromTheEast   Any news one why the rounded version of the fonts are no longer built during the update process ?

**Comment by timmaffett** [comment]
As of the Jan 11, 2024 update the rounded font has not been update and brought into sync with the outlined and sharp versions.  I am assuming that someone has fixed whatever was going wrong with the update process.. - but those scripts are not included in this repo so I can not personally verify that the issue is fixed or if it was manually resolved.

I will leave this open until a person with personal knowledge of the fix to generating the rounded font and know that the original issue causing this has been resovled.

Thank you!

**Comment by tphinney** [comment]
I am guessing from the tone and other elements of the message, that “not” is a typo for “now”?

I just produce the darn fonts, and the problem seems to be a bit downstream from me, and slightly mysterious. When the fonts are updated FULLY automatically, some of the automatic steps involved do not see the Rounded font as having been updated. But when the same automation is triggered manually, it works correctly. If you are saying “that makes no sense to me,” you are not alone, that is what everybody is saying. In any case, @EsoFromTheEast will be keeping a close eye on it next time he does an update.

**Comment by timmaffett** [comment]
@tphinney Sorry about the typo - that was confusing, yes I meant **now** - i edited the comment.
It does look like it is working again and it will be immediately apparent to me if it stops working again and I will create another issue.   Thanks again everyone!
