### ISSUE TITLE
Missing social icons (G+, FB, Twitter, etc.)

### ISSUE THREAD

**Issue by asadovsky** [google/material-design-icons#166]
These icons do appear to exist somewhere, e.g.
https://www.gstatic.com/images/icons/material/system/2x/post_gplus_black_24dp.png
https://www.gstatic.com/images/icons/material/system/2x/post_facebook_black_24dp.png
https://www.gstatic.com/images/icons/material/system/2x/post_twitter_black_24dp.png

They're also listed as Google-made icons on https://materialdesignicons.com/, e.g.
https://materialdesignicons.com/icon/facebook-box

However, they are nowhere to be found in this repo.

**Comment by LunarDevelopment** [comment]
.. Do we know where these are.. ?

**Comment by codingcampbell** [comment]
@jestelle did you mean to close this without an explanation?

**Comment by LunarDevelopment** [comment]
Boooooo
:-1: :-1: :-1: :-1: :-1:

**Comment by simodorg** [comment]
Need these icons, too.

**Comment by blackxored** [comment]
+1

**Comment by DrummerHead** [comment]
Google probably does not want to acknowledge the existence of other social apps.

However this snippet of code from the Templates section of mdl can be used:

https://github.com/google/material-design-lite/blob/master/templates/blog/styles.css#L348-L372

**Comment by as1ndu** [comment]
this is not good :(

**Comment by angelxmoreno** [comment]
seriously though why was this closed? please elaborate @jestelle

**Comment by w0rldart** [comment]
Could really use those extra icons.

Thanks

**Comment by jestelle** [comment]
Hi all,

I really wish we could provide a consistent set of these social icons, but unfortunately most companies have relatively strict trademark guidelines on how 3rd-parties can use their trademarks.

Here are some links that might help you track down brand assets for several of the social networks we originally wanted to include in this set:

**Instagram**
https://www.instagram-brand.com/

**Tumblr**
https://www.tumblr.com/docs/en/trademark_guidelines

**Pinterest**
https://business.pinterest.com/en/brand-guidelines

**Twitter**
https://about.twitter.com/press/twitter-brand-policy

**Facebook**
https://www.facebookbrand.com/guidelines?asset=2&media=1,2,3&platform=0

**LinkedIn**
https://brand.linkedin.com/visual-identity/logo

Hope that helps.

**Comment by angelxmoreno** [comment]
tyvm for the explanation @jestelle . Really appreciate it.

**Comment by jestelle** [comment]
Oops.  That above commit had nothing to do with this issue.  Sorry about that.

**Comment by netlander** [comment]
+1

**Comment by controversial** [comment]
Why are ionicons and Font Awesome allowed to include social icons but Google isn't?

@jestelle

**Comment by controversial** [comment]
Try searching `social` on ionicons.com:
![screenshot 2016-09-17 at 8 53 29 pm](https://cloud.githubusercontent.com/assets/10377391/18611954/d7adaafc-7d18-11e6-983c-aeaf9c61e72a.png)

**Comment by jestelle** [comment]
@controversial That's a question for each of the trademark holders.

We'd be happy to include social icons like this given the permission of those trademark holders, but at this time we haven't pursued getting that explicit permission.

Sorry for the inconvenience this might cause anyone.

**Comment by patrickml** [comment]
@jestelle can a community member attempt to get explicit permission from major social media platforms?

**Comment by jestelle** [comment]
@patrickml Maybe. We wouldn't necessarily be able to include something without getting the right lawyers to talk to each other and get the right permission in writing somewhere. But if a community member wanted to chase down contacts at non-Google organizations to and help set it up for us to be quick and easy to get done, that might help us.

**Comment by lukaskollmer** [comment]
Any updates on this? @jestelle @patrickml

**Comment by emanb29** [comment]
I'm no lawyer, but my understanding is that adherence to brands' trademark guidelines are the concern of the consumers of this icon set (i.e., the people actually displaying and using the logos), not the icon set itself. That said, it would be nice to get official permission for the set; I'm just not sure it's strictly necessary.

**Comment by MewX** [comment]
Well, I'm now using `Font-awesome brands` icons (officially separated), together with `Material Icon font`. It works fine, but not that perfect though

**Comment by thakyZ** [comment]
I would also like to know if there are any updates on this. Also if I could ask for a Steam icon for my website? (Steam as in Valve, Steam)

**Comment by englishextra** [comment]
That's unfortunate

**Comment by lizzymendivil** [comment]
Hi... I need social icons too. I found them here: https://materialdesignicons.com/
But I don't know how to import from my react project. Can anybody help me please? Thanks.

**Comment by lizzymendivil** [comment]
@englishextra thanks, But I already found how to :) thanks 

import { Google, Facebook, Twitter } from 'mdi-material-ui';

.
.
.
<Button variant="fab" color="primary" aria-label="Add">
        <Google />
 </Button>

**Comment by robert-king** [comment]
> @patrickml Maybe. We wouldn't necessarily be able to include something without getting the right lawyers to talk to each other and get the right permission in writing somewhere. But if a community member wanted to chase down contacts at non-Google organizations to and help set it up for us to be quick and easy to get done, that might help us.

If google lawyers can remove any red tape, it would be impressive and reflect well on google.

**Comment by jcwrightson** [comment]
As a sensible man, I'm pretty sure there would be no copyright infringement should Google decide to include social media icons within it's library. For a start, material-icons are free, so there's the "fair use policy". Anyway, for Google to not include these icons is a little ridiculous. How can you provide a contemporary icon library without them, everyone building for the web today invariably needs these icons, and we need to use these icons inline with other icons. So if Google cares about standardizing design language, please for the love of god... GIVE US THE GOD DAMN ICONS! Thanks :)

**Comment by jcwrightson** [comment]
*goes back to font-awesome with a big sigh*

**Comment by branditodesign** [comment]
> _goes back to font-awesome with a big sigh_

I have a feeling it all comes down to brand style guides, an area where you should tread lightly.

The reason social media companies don't really mind it is because they are gaining something from having the icon on your page, because you're linking from (or next to) that icon right? You're directing them back to them, not many people who use the social media icons will change them drastically in a way that they cannot recognise the social media site.

But explicit permission in writing should have been sought a long long time ago, no excuse with the amount of maintainers & contributors we have here.

Take JetBrains for an example (especially their rules with using other colours):
https://www.jetbrains.com/company/brand/

**Comment by alstracoin** [comment]
Someone please tell this google bunch that even in Africa, folks are dumping material icons for fontawesome. Like seriously I can't deal with this level of crap. Reminds me of Microsoft during the 90s. Thanks alot  for the extra work Google! Useless!

**Comment by englishextra** [comment]
i    am very sorry are you talking to me?

**Comment by englishextra** [comment]
ICON font is the    past   i use svg embedded

**Comment by mkeen** [comment]
Too bad when someone on a team puts up roadblocks for no reason. These icons fall under fair use and are included in several other icon libraries. There's no reason for this not to be included here other than pure laziness.

**Comment by taniacr** [comment]
No news in the horizon about this issue?

**Comment by jayarjo** [comment]
Common.

**Comment by nezlicodes** [comment]
duh it's almost 2020!

**Comment by apdrsn** [comment]
I really think you should consider adding those icons to your library. 
My guess is that nearly 100% who use you library also need to use social icons.

The consumer have two options:
1.  Use another library (might not be an option if design relies on material icons)
2. Add another library which have the needed icons = bad for performance

We don't need more unnecessary bytes on the internet – please add the icons!

**Comment by liesislukas** [comment]
i guess google won't add those icons to lib cause if they want to have a consistent view from other material design icons, logos need to follow material design guidelines. color, positioning, size, proportions etc. and those brands would not agree that such a big player as google would do that and would encourage everyone to use logos that do not follow official brand guidelines. meanwhile, everyone can easily find each of that icon as svg online for free and just use. I understand how it would be cool to have all in one lib but it's not a big deal to have icons directory and just drop in 5 or 10 svg icons found elsewhere. No need to import another full lib for that. there would be 0 extra bytes too, if imported correctly.

**Comment by vdegenne** [comment]
pretty pleaseeee

**Comment by aress31** [comment]
+1 the only reason why I have to import Font Awesome in most of my projects is only to get access to the social icon which is an overkill for only couple of social icons. I wish Google would do something about that!

**Comment by R-W-C** [comment]
Still the same problem in january 2021.

What I did was downloading SVG files from flaticon.com (https://www.flaticon.com/packs/social-media-logos-2?k=1610665942395). All the main social media icons are present. You can download the whole pack at once.
<img width="288" alt="IcoMoon" src="https://user-images.githubusercontent.com/36850866/104663179-bd0d1380-56cc-11eb-862e-57f5bac58051.png">


I just picked the ones I needed. After that I followed the guide on mediatemple.net (https://mediatemple.net/blog/design-creative/creating-implementing-icon-font-tutorial/) on how to create a font file. 

I created the font file as described on icomoon.io (https://icomoon.io/app/#/select)

After generating the font, a download started. In the downloaded file there is a demo.html file which exactly shows you how to use your generated font. Sweet!

I realize these are not Material Design icons, but they suited me well. It might be useful to you.

**Comment by singlesoup** [comment]
Let's see how long it goes?

**Comment by R-W-C** [comment]
Another source for perfect icons in svg format is https://logotyp.us. 
An example: https://logotyp.us/logo/facebook/

The site seems to contain the official brand logo's. 
Google plus is missing though. (It can be found here https://commons.wikimedia.org/wiki/File:Google_Plus_logo_2015.svg )

You can use the method I described in my previous message to create your own font file with the logo's.

But why are we looking for missing social icons in the Material  Design icons collection? Social media logo's are logo's and they do not meet the Material Design requirements by default. They just don't exist. We cannot expect Google to have their own version of other brands logo's.

So let's stop the quest. You cannot expect Google to add logo's which do not comply with their own guide lines and other brands don't want their logo's to be changed (malformed), and why would they? They could all decide to make a Material Design version of their logo, but that ain't gonna happen.

**Comment by bernaferrari** [comment]
Google has added Facebook icon, but not any other social network for now :( 
![image](https://user-images.githubusercontent.com/351125/111417879-72584980-86c5-11eb-9b3a-eb41b71233d3.png)

**Comment by taniacr** [comment]
So how's everyone doing during this pandemic?

**Comment by chirejaszy** [comment]
06-09 09:21:20.014 W/re-initialized>(12286): type=1400 audit(0.0:3667): avc: denied { read } for name="u:object_r:mtk_amslog_prop:sdk" dev="tmpfs" ino=8365 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:mtk_amslog_prop:rilitclass=file permissive=root

**Comment by aneesshameed** [comment]
> Google has added Facebook icon, but not any other social network for now :(
> ![image](https://user-images.githubusercontent.com/351125/111417879-72584980-86c5-11eb-9b3a-eb41b71233d3.png)

Someone from Google went to WhatsApp and Twitter to get the icons, but the bag they took was too small was not able to pick icons from there. Next time they will go with a bigger bag.

**Comment by bernaferrari** [comment]
Facebook was removed, but Wechat was added.
![image](https://user-images.githubusercontent.com/351125/132558147-1b081a3e-4567-44e7-a84e-15049b854872.png)

**Comment by jpoints** [comment]
Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhh!!!!!!!!!!! 
I was going to propose using this as part of some design tools, but the social icons are most extra super duper important. I'll have to handle social icons with a different system, if I decide to use this.

This is free, so I cannot complain too much that they are missing. But if there is some sinister Google master plan that is associated with widespread use of this icon library, the missing social icons is hindering adaptation. Pinky please explain to Brain that the social icons are most important.

**Comment by hicham-saddek** [comment]
For god's damn sake, please include these icons within your library, we've had enough, we really should think about going on strike because of those missing icons, we end up adding an other library just for social media icons, which are basically within the fair use policy, so no need to do this to us, you are hurting my eyes when i code, ending up importing more libraries, and writing inconsistent code, just because Google open source team doesn't want to add at least 4 ducking icons in their library, should really do a PR request and push it to be accepted :!!!

**Comment by bernaferrari** [comment]
Wechat was removed, Duo was added. What is going on?!
![image](https://user-images.githubusercontent.com/351125/147392964-d60a6e9d-dd60-4171-8b41-32d93c70cbde.png)

**Comment by hicham-saddek** [comment]
We still need the rest like facebook, or google icons... many devs are using them for social media login buttons for example...

**Comment by fkw** [comment]
I need to revert back to FA because these icons are missing...
If Google doesn't want to include them in Material Icons, could they be in a dedicated font on Google Fonts ?

**Comment by tphinney** [comment]
Currently, Google has a policy against including third-party icons in Material Icons / Material Symbols.
(Subsidiaries of Google are ok, though.)

**Comment by breck7** [comment]
My goodness.

Grow some f*cking balls and include the social media icons or abandon this f*cking project. Right now you are polluting the web with your project which gets the unsuspecting developer 80% of the way there and then f*cks them.

I just spent 2 hours integrating this thing and then realized you purposely broke it because you are afraid some uptight lawyer might give you a hard time.

You just wasted my f*cking time.

**Comment by vdegenne** [comment]
@breck7 Never learned about *respecting others' property* ?
It's not about doing whatever they want and waste money in lawsuits. Imagine "Google the big company that doesn't care about other big companies' copyrights" in the headlines.  
You're complaining here but it's not like the devs here have control over this..

**Comment by breck7** [comment]
@vdegenne you are brainwashed. It ain't "intellectual property", it's "intellectual slavery". Restricting what I can do with my own property is the very opposite of property rights. Watch some Stephan Kinsella to learn more.

I 100% agree that my comment erred on the side of mean and exaggerated and the devs have little control over it, I was just stating emotionally what everyone knows. Lots of lawyers are negative sum -- they make the world a worse place, and my anger here is distracted at them.

To me the Internet/code, this is a sports field and one should compete with passion and intensity. Offline I'm a lot less confrontational :).

**Comment by tphinney** [comment]
Other people’s trademarked logos are definitely not your property.
You can argue that trademarks are bad. But they exist, and that is the world we live in.

**Comment by breck7** [comment]
@tphinney  "Other people’s trademarked logos are definitely not your property."

I never said they are??

There is nothing wrong with me using my own pen and paper, or my own computer, to draw my version of the Facebook logo. There is nothing wrong with me distributing that. Obviously I can never claim that Facebook drew it, or use it to represent that I am Facebook, or have a relationship with Facebook.

It's just a symbol. Like a bathroom sign.

> that is the world we live in.

100% agree! And I speak up to nudge the world a little in the right direction.

**Comment by wesdevpro** [comment]
I guess one plus is you can stilly copy the SVG of the icon🤷‍♂️ However, I hope its on the road map for MDI to reincorporate all of these icons(but I guess that may be a money problem).

**Comment by nadernasery** [comment]
***@***.*** باصفا باشید ارسال‌شده از تلفن Huawei من-------- پیام اولیه --------از: Wesley Ford ***@***.***>تاریخ: پنجشنبه ۲۵ مهٔ ۲۰۲۳،‏ ۸:۵۶به: google/material-design-icons ***@***.***>گیرنده کپی: Subscribed ***@***.***>موضوع: Re: [google/material-design-icons] Missing social icons (G+, FB, Twitter, etc.) (#166)
I guess one plus is you can stilly copy the SVG of the icon🤷‍♂️ However, I hope its on the road map for MDI to reincorporate all of these icons(but I guess that may be a money problem).
