### ISSUE TITLE
Missing Icon in Flutter

### ISSUE THREAD

**Issue by mongoose13** [google/material-design-icons#1665]
There is a missing "camping" icon in Flutter - https://api.flutter.dev/flutter/material/Icons-class.html

The icon exists in 
- Google Fonts - https://fonts.google.com/icons?icon.query=camping and 
- Repo - https://github.com/google/material-design-icons/tree/master/symbols/web/camping

But if I navigate to the Google Fonts using the URL from the Flutter Dev reference - https://material.io/resources/icons I get redirected to the same Google Fonts URL (https://fonts.google.com/icons) but it does not have the "camping" icon. 

Can you please get the "camping" icon added to Flutter. Thank you for your help!

**Comment by tphinney** [comment]
That’s on the Flutter side of things; you should file an issue with them. The icon is available; it is up to them how often they integrate the latest icons.

**Comment by mongoose13** [comment]
> That’s on the Flutter side of things; you should file an issue with them. The icon is available; it is up to them how often they integrate the latest icons.

Thanks, Thomas for your input. I have created an [Issue](https://github.com/flutter/flutter/issues/142386) with Flutter for this. I will close this now.
