### ISSUE TITLE
Missing `person_edit` icon in Material Symbols downloaded .woff2

### ISSUE THREAD

**Issue by dlongodev** [google/material-design-icons#1669]
My project is currently using a downloaded version of `material-symbols-rounded.woff2` downloaded from the following link: `https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0..1,0`. We are trying to use the `person_edit` but it only add the `person` and `edit` icons with the underscore between:
<img width="175" alt="image" src="https://github.com/google/material-design-icons/assets/58197326/aaeeb9d8-9019-42df-869b-f24934b593f9">

I'm previewing the downloaded font file, I can't seem to find it anywhere:
<img width="2415" alt="image" src="https://github.com/google/material-design-icons/assets/58197326/bf570575-ddb4-40cd-b151-9cac0e5c4162">

I also looked through the list of code points in the repo, and I don't see `person_edit`
https://github.com/google/material-design-icons/blob/master/font/MaterialIconsRound-Regular.codepoints

But I do see in the Google Fonts: 
<img width="749" alt="image" src="https://github.com/google/material-design-icons/assets/58197326/c172edc0-bd73-4b02-9d0f-8e13f0ca9552">

**Comment by tphinney** [comment]
> but it only add the person and edit icons with the underscore between

What is “it” in that sentence?

I checked by downloading the WOFF2 file from that link, and it absolutely _does_ have an icon with the glyph name “person_edit” accessible from the codepoint U+F4FA (hexadecimal, or 62714 in decimal). It is at glyphID 4915 in the font file. Here it is:

<img width="357" alt="person_edit" src="https://github.com/google/material-design-icons/assets/6548266/f350f52a-9b08-4e83-b196-d59df999f5ed">

Some plausible possibilities:
- some process you are doing with the font after downloading is subsetting the font and stripping out the needed glyph(s)
- whatever is doing the ligation is processing the OpenType code in the font incorrectly

> I also looked through the list of code points in the repo, and I don't see person_edit
https://github.com/google/material-design-icons/blob/master/font/MaterialIconsRound-Regular.codepoints

That is “Material Icons” and NOT “Material Symbols”; the Material Symbols collection is newer and has at least many hundreds more icons.

**Comment by dlongodev** [comment]
Thank you for the answers. 
Just wanted to let you know "it" was referring to the code `person_edit` between the span tags `<span class="material-symbols-rounded">person_edit</span>`. 

For some reason, the version we downloaded a few months ago was missing that icon. I redownloaded and reinstalled the font and it worked. Sorry for the confusion and thanks for the quick response.

**Comment by tphinney** [comment]
Checking back, I think that icon was added in late November, at least internally. So that would explain that difference. I will remember to ask people if they are sure they have the latest font, and/or check the icon add date, next time.

External release frequency has been a bit more variable, but seems like it might be moving towards nearly-every-week. Nearly every release has had new icons, whether that is two icons or 20.
