### ISSUE TITLE
Icon request: Google Fit icons? (sports / activities)

### ISSUE THREAD

**Issue by CoDEmanX** [google/material-design-icons#167]
The Google Fit app has many great icons related to sports and activities, but I can't find them here:

![google fit icons](https://cloud.githubusercontent.com/assets/1309249/8632898/1df36d0a-27af-11e5-97c2-e252657b8ae2.jpg)

**Comment by CoDEmanX** [comment]
I'm still interested in those, they were not added in the latest update v2.1.0.

**Comment by jwir3** [comment]
:+1: I'm also interested in these.

**Comment by Empty2k12** [comment]
Third this!

**Comment by Kasijjuf** [comment]
See also #44

**Comment by strooooke** [comment]
Yep, interested here.

**Comment by jezza323** [comment]
Yes please

**Comment by brianith79** [comment]
Stop

**Comment by CoDEmanX** [comment]
@brianith79: this is not a mailing list. If you want to unsubscribe from notifications, turn them off on GitHub.

**Comment by adarshv90** [comment]
+1

**Comment by bpalermo** [comment]
+1

**Comment by motss** [comment]
:+1: +1:

**Comment by Gummientchen** [comment]
+1

**Comment by Empty2k12** [comment]
Are there updates on this? Many people are still interested in offering proper icons in fitness related apps.

**Comment by danielchh** [comment]
Still need them =)

**Comment by Levi-Lesches** [comment]
Might I suggest the `directions_run` icon? It's not exactly sporty, but it _does_ show someone running...

**Comment by Empty2k12** [comment]
> Might I suggest the directions_run icon? It's not exactly sporty, but it does show someone running...

**Comment by oniice** [comment]
Lets get these in

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
