### ISSUE TITLE
keep_off icon missing in Google Material+Icons but used in apps like Google Meet, which is opposite of push_pin

### ISSUE THREAD

**Issue by mattiLeBlanc** [google/material-design-icons#1674]
I am using Material Font icons for Angular with Angular Material Design components. I use push_pin to pin something, but I cant use keep_off which is available in google material icons used in apps like Google Meet. So there is no unpin icon available.
<img width="53" alt="image" src="https://github.com/google/material-design-icons/assets/5285035/01df5758-5174-4227-9621-29c5e1a2bc60">

Is it possible to add this icon to the collection?

**Comment by tphinney** [comment]
Oh wow. Yeah, that is being kept proprietary for Google, but I can’t see a good reason for it, given that the basic pin icon is public. Let me see what I can do.

**Comment by mattiLeBlanc** [comment]
Yeah, I thought the same. I had to you a CSS with pseudo selector option to create the same icon, so it would be great if it will become available.

**Comment by tphinney** [comment]
Well, I have made all the relevant source and metadata changes upstream and they will be in the next source variable font build I make. The next external release that is next week or later should pick that up. Also "keep_public" will be available externally.

Looking at that also caused me to notice that there is no proper rounded version of “keep,” so we will fix that soon as well, for those people using rounded variants.

**Comment by tphinney** [comment]
All that was in an upstream source build today, so at some point it should percolate to Material Symbols.

NOTE that this does nothing for the old Material Icons set, which is not so actively maintained. If that is what you are using, I can only encourage you to migrate to Material Symbols.

**Comment by mattiLeBlanc** [comment]
Thank you
