### ISSUE TITLE
Camera switching icons outdated? (front / rear)

### ISSUE THREAD

**Issue by CoDEmanX** [google/material-design-icons#168]
`ic_camera_front` and `ic_camera_back` in image category do not match with the icons used in Google Camera app:

![screenshot_2015-07-11-21-42-12 2](https://cloud.githubusercontent.com/assets/1309249/8635151/bb8c08da-2816-11e5-9825-d3302daf14e9.png)
![screenshot_2015-07-11-21-41-59 2](https://cloud.githubusercontent.com/assets/1309249/8635152/c3fe5432-2816-11e5-8f8b-7a47d79db6aa.png)
![screenshot_2015-07-11-21-48-09 2](https://cloud.githubusercontent.com/assets/1309249/8635153/caf5d418-2816-11e5-9dd0-7ccaf61d31b2.png)

**Comment by shyndman** [comment]
Nope, not outdated. Some teams choose to design their icons as they see fit. Thanks for the report though.
