### ISSUE TITLE
Missing Icon: frame_person_mic

### ISSUE THREAD

**Issue by christophe-g** [google/material-design-icons#1689]
Hey all, 

[`frame_person_mic`]( https://fonts.google.com/icons?icon.query=frame+person+mic) is present in  https://fonts.google.com/icons, but not in this repo (at least, not in the `web` folder). 

Thanks anyway for this awesome list.

**Comment by tphinney** [comment]
True. That icon just got added in early February. It should be available in the “web” folder soon.

The fonts being served (for people accessing via the API), and driving things at https://fonts.google.com/icons, gets updated as often as weekly.

The individual graphics files here, and in the web folder, currently get updated less often. Also true of the font files, although they may be more frequent? I can tell the font files got updated on Feb 1, must have just missed getting that icon.

**Comment by christophe-g** [comment]
Closing as icon is now present
