### ISSUE TITLE
Web symbol for `star` doesn't have a non-fill version

### ISSUE THREAD

**Issue by joshjhall** [google/material-design-icons#1702]
Entirely possible I'm missing something, but it appears the web version of the `star` symbol SVG is incorrect. Both the fill and non-fill versions have the fill SVG. The iOS and Android versions appear correct, so possibly limited to how the web SVG was generated. I also haven't noticed the issue with any other symbols, so it might be quite limited in scope. Note, `star_rate` appears correct.

For example, for `star` @ style=rounded, weight=400, fill=off, grade=normal, optical size=24dp
Expected
![CleanShot 2024-03-26 at 12 32 11@2x](https://github.com/google/material-design-icons/assets/50111/83c3a9c6-e283-45d4-a977-b30b77349137)

File in `symbols/web/star/materialsymbolsrounded/star_24px.svg` shows
![CleanShot 2024-03-26 at 12 36 10@2x](https://github.com/google/material-design-icons/assets/50111/d050be11-1258-4777-8621-6ca86f5aea5a)

**Comment by joshjhall** [comment]
The `edit` SVG also appears different than what's packaged in the font and such. Is the web SVG deprecated or out of date?

**Comment by tphinney** [comment]
Hmmm. I remember the default state for /star got changed a while back (as in, last year IIRC). Seems like maybe the SVG did not get regenerated.

/edit is also one that has been changed in the past year or so.

@EsoFromTheEast is this something you could address?

**Comment by joshjhall** [comment]
Found another one this morning, `emergency`. May help track down when the SVG stopped regenerating.

**Comment by joshjhall** [comment]
Thanks @tphinney and @EsoFromTheEast!

https://github.com/google/material-design-icons/issues/1531 might be the same issue. It appears the SVG for `pause` is still out of date compared with the font and Figma sources as well.

**Comment by joshjhall** [comment]
`edit_document` and `star_half` are also out of date

**Comment by tphinney** [comment]
This should at last be fixed now?

**Comment by tphinney** [comment]
I believe this is fixed. Let us know if not!

**Comment by joshjhall** [comment]
Confirmed it's fixed in the big update pushed `master` at the end of May a few days ago. I don't believe it'd been pushed to the branch until the update last week, but we're good to go now. Thanks!
