### ISSUE TITLE
The script to update this repo have been broken since February - All new icons since then are completely missing from the variable material symbols fonts ttf files.

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1706]
I received a [bug report](https://github.com/timmaffett/material_symbols_icons/issues/20) about a missing `keep_off` icon from the flutter material_symbols_icons package.  This was unexpected because the icon references are automatically generated from the material symbols icont ttf font files.
    
In investigating the problem I discovered that all of the 'keep' related icons are missing from the font files for the material symbols icons.  
Checking things further I see that `keep_public` was  present back in october, but in subsequent versions of the variable fonts files it went missing.  `keep` and `keep_off` seem to have never been included over that last ~year that I went back.

See icons here from [https://fonts.google.com/icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:keep_public:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=keep)

Examining the font ttf files with ttx will show that these icons are completely missing from the fonts.

**Comment by tphinney** [comment]
I am not finding an internal issue for this, but this is familiar, and I do see that the "keep" related icons were missing (from the external Material Symbols) for a while, and reappeared some time in February. Anything based on font builds from the past month should have them, though!

You can see them at https://fonts.google.com/icons?icon.query=keep as well

**Comment by timmaffett** [comment]
@tphinney  The variablefont directory's true type fonts have not been updated since Feb 1.  The fonts there currently do *not* have any `keep` related icons.  
Could we get another release there so that we are in sync with the internal versions and have the `keep` related icons ?

**Comment by tphinney** [comment]
there are plenty of new icons missing as well, then

**Comment by tphinney** [comment]
Looking into getting that unstuck

**Comment by timmaffett** [comment]
I have been wondering what was going on. 😆 Here's to hoping for getting the actions unstuck 🤞

**Comment by timmaffett** [comment]
@tphinney Any word on this ? 
I am sure you are also at the whims of the powers that be over this.. I was just hoping someone could trigger the job by now and we could get at all your wonderful new icons!

**Comment by tphinney** [comment]
I found an automated process that is not updating as it is supposed to, and am looking for help fixing it.

**Comment by timmaffett** [comment]
Thanks @tphinney - that is what I had gathered.  I am sure it is as frustrating to you as it is to all of us.

Is @EsoFromTheEast no longer available to help push things to the repo ?

My backup plan is to us the woff2 fonts from the `https://fonts.gstatic.com/s/materialsymbolsXXXX/` directories if this repo cannot be brought up to date in a reasonable timeframe.  At least that would allow us to move forward with using the updated fonts from some source we can access.

**Comment by EskelCz** [comment]
@tphinney Thanks, I'm waiting for these as well :)

**Comment by EskelCz** [comment]
@tphinney Please do you have an ETA on this? We have a release next week and I was hoping the pin icon would be available by then. Thanks

**Comment by jeanpaulattard** [comment]
Hello gentlemen, was there any progress on this please? Thank you!

**Comment by EskelCz** [comment]
`mail_off` is missing as well :(

**Comment by timmaffett** [comment]
@EskelCz  There are actually a number of icons that are missing now as the pipeline to update the external repo has been broken now since the beginning of February.

@tphinney I know that this is not in your control but is there anyone from google that we could add to this thread to try and get this fixed ? :pray:   I would be willing to do whatever work was required to figure this out but am I correct in thinking that the problem is in an google internal repo's actions that are failing and not updating this repo ?

**Comment by timmaffett** [comment]
@tphinney Are you still working on Material Symbols Thomas ?  I was just wondering with all the shake ups we here about with Google.  I understand everyone is probably under increased stress under the circumstances, but it has now been 1/4 of a year since we had the benefit of the pipeline supplying your work to this repo.  This there any hope that we can get this resolved ?  

I have investigated writing a program to extract the TTF font from the (still being updated) WOFF fonts on https://fonts.google.com/icons .  It is possible but I have to map symbol names from the ttf files back to symbol names used for the icons.  For new icons this is not entirely ideal - but perhaps this will be the only way to get the updated icons going forward ?

**Comment by tphinney** [comment]
@timmaffett Yes, I am still here (as a contractor, not a Google staffer per se).

By coincidence, right at the same time you wrote that, I was listing this very issue for some other folks. No ETA yet.

**Comment by timmaffett** [comment]
@tphinney That's great news - if you could please let us know when you find anything out.  I feel like this must be a quick fix 🤞

**Comment by tphinney** [comment]
All done. Thanks TO @EsoFromTheEast

**Comment by EskelCz** [comment]
> All done. Thanks TO @EsoFromTheEast

It works! Thanks a lot to both of you.

**Comment by timmaffett** [comment]
Thank you @tphinney for all your continuing work on the material symbols icons  - and for motivating @EsoFromTheEast to take a look at the bug that was preventing the pipeline from working!

I really hope that it runs smoothly from here on out :wink:

I have finally been able to publish a new release of the flutter material_symbols_icons package that is now up to date with version 2.741 of the official ttf fonts.

**Comment by jeanpaulattard** [comment]
Thank you all for fixing this. Really appreciate all the effort!
