### ISSUE TITLE
Why use <i> over <span>?

### ISSUE THREAD

**Issue by josh18** [google/material-design-icons#171]
Of course there is a lot debate about whether it is ok to use `<i>` for icon fonts and I'm curious to know the thought process of why you chose to use it.

Is it:
a. You think that icon fonts are relevant to the specs of `<i>`
b. Ignore semantics, `<i>` is quicker to write, takes up less space, and icon starts with i so it makes sense
c. There are no better alternatives
d. Some other reason

**Comment by shyndman** [comment]
I hadn't realized that HTML5 attached semantics to `<i>`. I just read it over, and it doesn't seem like our use is appropriate.

Can you link to any debates?

**Comment by josh18** [comment]
Stackoverflow question: [Should I use \<i> tag for icons instead of \<span>?](http://stackoverflow.com/questions/11135261/should-i-use-i-tag-for-icons-instead-of-span)

Somewhere between Bootstrap 2 and 3 they changed from recommending `<i>` to `<span>` but I can't seem to find any discussion about it.

Maybe not as much debate as I first thought... It's not really a big deal, it was more to satisfy my curiosity then anything. However my interpretation of the spec was that it wasn't appropriate so I was interested to know the thought process from someone more experienced than me.
