### ISSUE TITLE
Missing Icons from Material Symbol Variable Fonts: contextual_token, contextual_token_add

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1719]
It has been brought to my attention that there are at least these icons missing from the Material Symbols Icons variable font ttf files. (There may be more ?)
@AkanshDivker discovered that these icons are available [at https://fonts.google.com/:](https://fonts.google.com/icons?icon.style=Outlined&icon.query=contextual&icon.size=24&icon.color=%235f6368) and I have verified that these code points are missing from the [variable font ttf files in the repo](https://github.com/google/material-design-icons/tree/master/variablefont).  (Code points f485 and f486 for contextual_token and contextual_token_add respectively)

Any ideas @tphinney ?  Are these newer icons that have been recently added to symbols ?

They also seem to be missing from https://github.com/google/material-design-icons/tree/master/symbols/ (in addition to the ttf files found in https://github.com/google/material-design-icons/tree/master/variablefont )

Thanks everyone!

Cross referencing  https://github.com/timmaffett/material_symbols_icons/issues/26

**Comment by tphinney** [comment]
Yes, these are newer icons. They first appeared in test build about mid-April, and made it to production after the build that was the source for the most recent big repo update.

**Comment by timmaffett** [comment]
@EsoFromTheEast Is this sync/update something that you can push out ?

**Comment by tphinney** [comment]
*IF* I understand correctly, the automation is fixed and you should start seeing regular sync of the repo with the same source that goes into the externally-available font and [https://fonts.google.com/icons](https://fonts.google.com/icons)

**Comment by timmaffett** [comment]
@tphinney Is there something we need to (or can) do to get the current changes pushed out ? 
(repo still shows not updated for 2 weeks)

**Comment by timmaffett** [comment]
Sweet the repo has been updated and we can now see the two new icons contextual_token and contextual_token_add 

Here's hoping the auto updating keeps working and thanks for the help!
