### ISSUE TITLE
Position issue of the "arrow_back_ios" icon

### ISSUE THREAD

**Issue by soromii** [google/material-design-icons#1724]
<img width="319" alt="스크린샷 2024-05-30 오전 10 01 46" src="https://github.com/google/material-design-icons/assets/63584217/fb9151a0-c3c8-4f93-8707-7f822a15c69b">
  
  ----
<img width="314" alt="스크린샷 2024-05-30 오전 10 00 45" src="https://github.com/google/material-design-icons/assets/63584217/4c85cc41-cc74-4cac-a256-8ba350e024a9">

<img width="314" alt="스크린샷 2024-05-30 오전 10 00 57" src="https://github.com/google/material-design-icons/assets/63584217/696ecd93-e784-4c04-9f25-05bc7621764f">

Compared to the arrow_forward_ios icon, it is positioned to the left rather than in the center.

**Comment by tphinney** [comment]
Yes. That’s why there is _also_ “arrow_back_ios_new”

Unfortunately, the original was not allowed to have such a large change, but at least there is also a version that is better centered.
