### ISSUE TITLE
Bugged eye tracking icon

### ISSUE THREAD

**Issue by KTibow** [google/material-design-icons#1730]
Eye tracking (rounded) is not completely rounded. This bit is sharp:
![image](https://github.com/google/material-design-icons/assets/10727862/e498aeed-ab1c-4334-9488-7c56baf6a41f)

**Comment by tphinney** [comment]
Oops! Whoa, surprised we hadn’t caught that earlier. Thanks for pointing that out.

**Comment by tphinney** [comment]
Fixed in upstream source today! That may be a while before it percolates out, but it WILL happen.  :)
