### ISSUE TITLE
Icon request: empty, placeholder

### ISSUE THREAD

**Issue by reuse-ay** [google/material-design-icons#1739]
It has same size to other icons, but has no content. It will be used when we hide an icon but want to preserve area.

**Comment by tphinney** [comment]
If you were using the Material Symbols font, you could just use the space character. Would that be enough?

If you want an icon that is available in SVG and other graphics formats as well, we would have to make it available as a standard icon as well.

**Comment by reuse-ay** [comment]
Sorry. I didn't realize that I could use the space character, which is all I need for my project. Thank you for information.
