### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by SebastienDaniel** [google/material-design-icons#174]
Just a question, I couldn't find the answer on Google.

Why do your "production" SVGs have 2 `<path>` elements?
- in "design" SVGs there is only 1 `<path>` (albeit much more complex)
- the additional `<path>` in "production" SVGs doesn't seem to render anything on screen. It also has `fill=none`by default.
So what is this second `<path>` used for?

thx :)

**Comment by shyndman** [comment]
Hey @SebastienDaniel,

I think you have it backwards. Our production SVGs have single paths, and design contains two. Without the second `path` in the design SVGs, the positioning/size of the icon is misrepresented by illustration tools.

If you're seeing production SVGs with two paths, it's a bug. If you could point me to a specific file I'll take a look. Please reopen if this is the case.

**Comment by SebastienDaniel** [comment]
@shyndman thx for answering this. Below is an example.

This was grabbed from the [material design icon library] (https://www.google.com/design/icons/#ic_save)

```html
<svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h24v24H0z" fill="none"/>
    <path d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/>
</svg>
```

This is the "save" icon, it's one of many examples.

Unless I'm mistaken and the Material Icons Library is meant to share "design" icons?

**Comment by SebastienDaniel** [comment]
Unfortunately I can't re-open this issue. I'd have to make a new one (*uselessly redundant*)

**Comment by shyndman** [comment]
Weird that you can't reopen. Hadn't realized it worked that way.

You are correct that the icons site is meant to share "design" icons. It is intended to be friendly for designers.

If you'd like to go through a workflow of grabbing SVGs from the icons site and using them in your web apps, I'd recommend adding [svgo](https://github.com/svg/svgo) into your build pipeline (which is how we arrive at our production SVGs).

If we're good, please close this off.

**Comment by SebastienDaniel** [comment]
Well then that explains it all!

Might want to mention somewhere that they are "DESIGN" icons, not compressed for production.

Thank you for looking into this, much appreciated!
