### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by senina4** [google/material-design-icons#1741]
Hello,
I found that ```[yyyy]``` ```[name of copyright owner]``` in [LICENSE](https://github.com/google/material-design-icons/blob/master/LICENSE#L190) file has not changed!

**Comment by tphinney** [comment]
I don’t understand. That text in the file is explaining how you should word your copyright notice_ if you want to use the Apache license yourself. I don’t see anything wrong or incorrect.

**Comment by senina4** [comment]
> I don’t understand. That text in the file is explaining how you should word your copyright notice_ if you want to use the Apache license yourself. I don’t see anything wrong or incorrect.

This blank should be filled with year and owner

**Comment by tphinney** [comment]
No. It the blanks are occurring in the _appendix_ section, which is explaining how to use the license yourself.

This may be clearer if you view the license in use on the Apache web site with all the nice formatting around it, setting off the extra section:
https://www.apache.org/licenses/LICENSE-2.0

The text of the extra section is slightly different; not being part of the license proper, it can change while still hanging out with the Apache license v2.0.

**Comment by davelab6** [comment]
I agree with @tphinney
