### ISSUE TITLE
Different shapes of icons rotate_90_degrees_cw and rotate_90_degrees_ccw

### ISSUE THREAD

**Issue by fil146** [google/material-design-icons#1749]
- Gaps between shapes differ
- Rhombus sizes differ
- Shapes of arrow tips differ

Please don't mind the blue measurement, it's just for display.

![image](https://github.com/user-attachments/assets/b7be4e37-9176-47cc-8bfb-fab850ff475b)

**Comment by tphinney** [comment]
This has been fixed. Also, the arrowheads were different, now match.
