### ISSUE TITLE
NumberFormatException with ic_system_update_black_24dp.xml on Android

### ISSUE THREAD

**Issue by MGaetan89** [google/material-design-icons#176]
I am using the following icon in my Android application: https://github.com/google/material-design-icons/blob/master/notification/drawable-anydpi-v21/ic_system_update_black_24dp.xml ![ic_system_update_black_24dp](https://raw.githubusercontent.com/google/material-design-icons/master/notification/drawable-mdpi/ic_system_update_black_24dp.png)

But when using it on Android 5.0, the application crash with the following exception:

> java.lang.NumberFormatException: Invalid float: "1.1.9"

The XML version of that icon contains "1.1.9" and I guess Android 5.0 does not handle it well. I don't have the issue on Android M (Developer Preview 2).
Is it possible to fix that icon?

**Comment by shyndman** [comment]
Thanks for the report. We'll take a look.

**Comment by MGaetan89** [comment]
Any news on this yet @shyndman ?

**Comment by MGaetan89** [comment]
Any news @shyndman?

**Comment by jestelle** [comment]
Sorry for the delay on this all.

The Android team updated their tooling for generating Vector Drawables, and we've updated our assets.  These updates will be included in our next push, which will be soon!

In the meantime, Android Studio 1.4 has been released:
http://android-developers.blogspot.com/2015/09/android-studio-14.html
with improved Vector Drawable support.

You can now drop our SVGs directly into Android Studio and it'll generate the PNGs and Vector Drawables for you.

**Comment by MGaetan89** [comment]
Thanks for the feedback. I look forward this new release.

I just update my project to use this new feature in Android Studio 1.4, that's why I asked for news. Does it work for SVGs too? My understanding was that it only works for vector drawables.

**Comment by MGaetan89** [comment]
Any news on the new release of the icons @jestelle?

**Comment by shyndman** [comment]
Hey MGaetan,

Sorry for the wait. I'm looking on getting a release out the door this week or next. Stay tuned.

**Comment by MGaetan89** [comment]
Thanks for the news.

**Comment by MGaetan89** [comment]
Thanks for this update @shyndman & @jestelle!

I don't have an Android 5.0 device to test if my issue is fix, but from the new vector drawable file, it looks like it is. I will give a proper feedback soon.

**Comment by shyndman** [comment]
You should be good to go.
