### ISSUE TITLE
Bug: Icons take up large amounts of space during loading

### ISSUE THREAD

**Issue by FlorisSchippers** [google/material-design-icons#1760]
Because the icons are made using a font, they use font properties during loading and rendering. Properties like `font-display` are used to manage this. This property is not set on the `@font-face`, therefore the default of `auto` is used which in most cases implements the `block` strategy. This results in the font being displayed invisible during loading but it does take up space. This created unwanted issues as you can see here:
<img width="721" alt="image" src="https://github.com/user-attachments/assets/715bee02-e728-4238-b0f3-2aa63924b932">
Here you can see why the large space is reserved:
<img width="721" alt="image2" src="https://github.com/user-attachments/assets/423638bb-a8e5-4f19-8550-46c24fd4315f">
After rendering it looks like this:
<img width="721" alt="image3" src="https://github.com/user-attachments/assets/80db3e44-4208-4657-820d-977c73b182b5">
This creates a "jumping" effect when the font is finally loaded, which you can see here:
https://github.com/user-attachments/assets/c226567a-f7c0-4903-88d3-68027f714650

Is there a way to prevent this? Or is there a way to let the font not take up space during loading? I'd love to hear your ideas!

**Comment by tphinney** [comment]
There are two methods to refer to a given icon. The more intuitive one is by name, as you are doing now. However, names are long and will take up horizontal space during loading, as you see.

BUT you can also use the icon code point instead! Code point info available in the info on fonts.google.com [example](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:shopping_cart:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368&icon.query=shopping), or if you have a local copy of the font, you can get it from just about any character picker utility.

e8b6 search
e8cc shopping_cart
e7fd person

**Comment by FlorisSchippers** [comment]
Hi @tphinney, this worked beautifully! I made an Enum in typescript to map all the available icons so I can still address them by name. And the icons indeed only take up 1 HTML character in space during loading 👍🏻
