### ISSUE TITLE
Where can I find the Material Symbol categories?

### ISSUE THREAD

**Issue by alexstyl** [google/material-design-icons#1763]
I like the way the icons are categorized on https://fonts.google.com/icons. 

Do you publish those categories with which icons they contain anywhere?

<img width="307" alt="Screenshot 2024-08-16 at 15 48 14" src="https://github.com/user-attachments/assets/c9c2adaa-a813-4078-add5-4b1e4bf7db46">

**Comment by tphinney** [comment]
Not currently *planned*, but this is one of several pieces of metadata that would be helpful to external users, and I am thinking about how best to handle them all together.
