### ISSUE TITLE
arrow_back_ios is noticeably not centered.

### ISSUE THREAD

**Issue by ciukstar** [google/material-design-icons#1767]
```arrow_back_ios``` is noticeably not centered.

**Comment by tphinney** [comment]
Yes!

Due to massive use and stability issues, we ended up not changing it... which is why there is also `arrow_back_ios_new` which is better centered.  :)

**Comment by ciukstar** [comment]
Thank you

> Yes!
> 
> Due to massive use and stability issues, we ended up not changing it... which is why there is also `arrow_back_ios_new` which is better centered. :)

Thank you.
