### ISSUE TITLE
Stat 3 not rounded

### ISSUE THREAD

**Issue by RocksteadyDog** [google/material-design-icons#1789]
Hello! 

The upper arrow in the "Stat 3" icon is not rounded

<img width="572" alt="Снимок экрана 2024-09-14 в 19 17 32" src="https://github.com/user-attachments/assets/5a83cb80-893b-4bf0-8000-de9dbe749394">

<img width="213" alt="Снимок экрана 2024-09-14 в 19 17 27" src="https://github.com/user-attachments/assets/62ad0e2a-71b9-481b-be97-1e9e8a635b1c">

**Comment by tphinney** [comment]
That’s a pretty basic oversight, sorry about that.
It will get fixed pretty quick, but will be a couple of weeks before you see it live, externally.
