### ISSUE TITLE
Request: Codepoint with list of all available symbols

### ISSUE THREAD

**Issue by EnricoCecchini** [google/material-design-icons#1794]
Can we please get a list of all available symbols, similar to the codepoints for the icons in the "fonts" directory, that gets updated when new symbols are added?

**Comment by abhishek-junghare** [comment]
Are you referring to codepoints in this directory - [https://github.com/google/material-design-icons/tree/master/variablefont](https://github.com/google/material-design-icons/tree/master/variablefont) ? I think these are the ones for 'symbols'.

Though, could someone please confirm if this is the file we would use to fetch the latest list of available symbols? I am confused about whether the file above is correct, or if it's this one - [https://github.com/google/material-design-icons/blob/master/update/current_versions.json](https://github.com/google/material-design-icons/blob/master/update/current_versions.json)

**Comment by EnricoCecchini** [comment]
That's exactly what I was looking for. Thank you!

**Comment by tphinney** [comment]
> Are you referring to codepoints in this directory - https://github.com/google/material-design-icons/tree/master/variablefont ? I think these are the ones for 'symbols'.
> 
> Though, could someone please confirm if this is the file we would use to fetch the latest list of available symbols? I am confused about whether the file above is correct, or if it's this one - https://github.com/google/material-design-icons/blob/master/update/current_versions.json

They are both correct, and it looks like they are automatically updated. But they serve different purposes.

One gives category metadata, and sometimes includes the same icon in multiple categories; therefore an icon can be duplicated in that file. The other just has icon and codepoint, so every icon only appears once.

Thus one file has about 3670 entries, and the other has about 5980 entries.
