### ISSUE TITLE
moped icon missing

### ISSUE THREAD

**Issue by liquid2026** [google/material-design-icons#1797]
The moped icon is missing in the web section. On the src it is stil available.

**Comment by tphinney** [comment]
Hmmm, certainly seems like a bug. I will see what I can do.

**Comment by tphinney** [comment]
This has been fixed for the next build, one of 13 icons that were being suppressed without a deliberate reason. It may take a week or more to percolate out, externally, but should be this month, I expect.

**Comment by tphinney** [comment]
It is back
https://fonts.google.com/icons?icon.query=moped
