### ISSUE TITLE
Changing SVG icon colors

### ISSUE THREAD

**Issue by riotcku** [google/material-design-icons#18]
At the moment, coloring the SVG icons dynamically is very difficult. 

Issue is that it uses the svg icons as a background-image, which cannot be directly manipulated by the DOM. As a developer, this limits the use of the material-design-icons compared to, say, bootstrap glyphicons, which are powerful because they're treated in css as fonts. 

Could there be an easy way to inject the SVG directly in-line to the HTML? At the moment I have to directly edit the XML or the SVG file itself to achieve the results I'd like.

**Comment by AndreLion** [comment]
Webfont! Webfont! Webfont!

**Comment by riotcku** [comment]
Yay! Thank you Google :)

**Comment by mohamedYehia041** [comment]
2015-02-05 18:10 GMT+02:00 Andre <notifications@github.com>:

> Webfont! Webfont! Webfont!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-icons/issues/18#issuecomment-73072740>
> .
>



-- 
Mohamed Yehia
Service Internet & Network
Mob:+2 01144588894
