### ISSUE TITLE
Icons not shown on Android browser 4.3

### ISSUE THREAD

**Issue by cnyyk** [google/material-design-icons#180]
Material Design Icons works perfectly on Android browser 4.1.1, but not shown on 4.3.

<img width="527" alt="qq20150726-1 2x" src="https://cloud.githubusercontent.com/assets/275233/8890362/f483e1ec-3330-11e5-8938-983144dae179.png">

![image](https://cloud.githubusercontent.com/assets/275233/8890335/94de6c80-3330-11e5-9aa5-b0b2815c08a8.png)

<img width="527" alt="qq20150726-3 2x" src="https://cloud.githubusercontent.com/assets/275233/8890374/264eda56-3331-11e5-9e0e-a46cf6a15eac.png">

It's OK on 4.1.1.

<img width="527" alt="qq20150726-4 2x" src="https://cloud.githubusercontent.com/assets/275233/8890391/9813bec2-3331-11e5-8fb7-039bae465718.png">

<img width="527" alt="qq20150726-5 2x" src="https://cloud.githubusercontent.com/assets/275233/8890392/9bd5b722-3331-11e5-89ce-29be7bc33859.png">

**Comment by otachasak** [comment]
text-rendering: optimizeLegibility; in css seems to cause this problem in Android browser (http://caniuse.com/#search=text-rendering)

**Comment by jonathanbarton** [comment]
any update on this?

**Comment by jonathanbarton** [comment]
FYI - using unicode values instead of the glyph names still seems to work

**Comment by elia-c** [comment]
Still not work if the icon name or glyph code went from $scope variable:

example: 
    $scope.icon = 'account_balance'; // or     $scope.icon = '&#xE84F;';
    <i class="icon material-icons">{{icon}}</i>

**Comment by c-w** [comment]
Until this problem gets fixed, you might want to consider switching to [ZMDI icons](http://zavoloklom.github.io/material-design-iconic-font/index.html).

**Comment by nueverest** [comment]
Is there a way to use both the unicode/hex value `&#xE5D2;` and `menu` so that I can keep track of what it is and still be backward compatible?

Searching for `&#xE5D2;` on the site yields zero results.

**Comment by cnyyk** [comment]
Agree with you.
Unicode hex is not readable for codecoder.
😭

**Comment by kh0o0li5** [comment]
hfkhfj

**Comment by RoelN** [comment]
Closing this because it's an ancient issue. Apologies for leaving it open for so long. If you feel it's still relevant, feel free to reopen or create a new one with updated information!
