### ISSUE TITLE
Idea for a new feature

### ISSUE THREAD

**Issue by Phil5841** [google/material-design-icons#1802]
Would it be possible to create an action when mouse-clicking on submenu's or menu's icon? 
That mains a sort of a default action for common menu's or sub-menu's sub-actions instead of exit kando. 
In fact this can shortcutting when you don't want to go in details. It means that when you click in center : default action. And when you slide your mouse on the sub-actions : do the normal thing.
Sorry for my bad english

**Comment by tphinney** [comment]
This site is for the icons and their designs.

It seems like your request is related to something called kando, and might be better directed to their site.
