### ISSUE TITLE
Add the partial battery/wifi/power icons to the font

### ISSUE THREAD

**Issue by diosney** [google/material-design-icons#181]
Some icons in the icon font have issues, see `battery_20` for an example, it doesn't ouput anything. Maybe this is related to the transparency issue related above?

Thanks

See some thoughts in https://github.com/google/material-design-icons/issues/1

**Comment by shyndman** [comment]
Hey @diosney,

Those icons don't show up because we removed them from the icon font. You'll notice they don't appear on [the icon directory](http://www.google.com/design/icons) anywhere.

We're currently looking at redesigning these to work properly with the format. 

I'll keep this open as an icon request.

**Comment by diosney** [comment]
@shyndman Ok, good to know.

**Comment by Keats** [comment]
Hey @shyndman any update on that?

**Comment by shyndman** [comment]
No, no update yet. It's not high priority on our end, but it has been reported to the design team.

**Comment by WuerfelDev** [comment]
Hi @shyndman 
its been a really long time now. What happened?

Also I don't really understand why the icons are removed. As long as there is no redesign it would be great for us users at least to be able to use the icons.
Also if the argument is the loading time then I'd like to see something like a "Material Icons Extended"-font.

**Comment by xGouley** [comment]
Hello @shyndman ,
You noticed previously: "You'll notice they don't appear on the icon directory anywhere...."
Well, now on that link, you HAVE battery_20 and a lot of other icons that are not in the font. When the font will be released with all the new stuff?
It's a 2 years old font we have now...
Thanks

**Comment by Poeschl** [comment]
Hi @shyndman 
I guess nothing happend since last year?

**Comment by diosney** [comment]
I stopped using this a while ago and switched to https://materialdesignicons.com/, highly recommended, for all that stumble upon this.

**Comment by paulsmithkc** [comment]
These icons are required for the Android Developer Fundamentals 5.1 codelab homework assignment. How are students supposed to complete this now? 
https://developer.android.com/codelabs/android-training-drawables-styles-and-themes?index=..%2F..%2Fandroid-training#11

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
