### ISSUE TITLE
Icon Request: database

### ISSUE THREAD

**Issue by jimmywarting** [google/material-design-icons#182]

**Comment by JesterXL** [comment]
+1

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <Re: [material-design-icons] Icon Request: database (#182)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by alexpaluzzi** [comment]
+1

**Comment by adarshv90** [comment]
+1

**Comment by pablim** [comment]
+ 1 

![database-16](https://cloud.githubusercontent.com/assets/11844740/18490487/a9b0dd10-79d8-11e6-9afc-39e021f31981.png)

**Comment by Laurensvdw** [comment]
+1 (amazed that it is not yet existent..)

**Comment by vv7v7** [comment]
+1

**Comment by AndreaCioccarelli** [comment]
+1

**Comment by soetz** [comment]
+1

**Comment by NicholasPedroso** [comment]
+1

**Comment by leandroluk** [comment]
+1

**Comment by tmikeschu** [comment]
+1

**Comment by CheyenneForbes** [comment]
+1

**Comment by krisfris** [comment]
+1

**Comment by bchoubert** [comment]
@krisfris : There is now a database icon that was included in Font-Awesome v5.0.0 : https://fontawesome.com/icons?d=gallery&q=database

**Comment by vv7v7** [comment]
bumb

**Comment by CheyenneForbes** [comment]
We need to get some placards and protest outside google's HQ for our database icon  😂😂😂

**Comment by prijindal** [comment]
I use the dns icon, it looks like a server rack. But they should provide a database icon

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by F8ER** [comment]
> Icon available at: https://fonts.google.com/icons

May I ask what's the exact tag? Currently, results in "No icons found for ‘database’".

However, something similar is shown in another resource: https://materialdesignicons.com/icon/database
