### ISSUE TITLE
When will you add all the Google Font Icons?

### ISSUE THREAD

**Issue by bp-cos** [google/material-design-icons#1825]
When will you add all the Google Font Icons with a new release.

There are many missing google font icons in the current 3.0.1 release.

**Comment by tphinney** [comment]
I think you are looking at Material Icons. They are NOT being updated in general and are not current, years out of date. Look at Material Symbols instead. (See also the various readmes.)

The currently “live” Material Symbols version on both google.com servers _and_ here in the repo in /variablefonts is 2.791, which I built the source for on October 11th. So it is completely up to date with the live font!
