### ISSUE TITLE
Google Icon font some of them are not woriking

### ISSUE THREAD

**Issue by RapurHarishBabu** [google/material-design-icons#183]
I new to google font icons... 

google icon font is cool but some of them are not working well... like which has space in it. like ( arrow back, check circle ) plz help me out plz... what do i put in that space in php

**Comment by shyndman** [comment]
You put an underscore:

check_circle, arrow_back, etc.

If you look at [the icon directory](http://www.google.com/design/icons/), when you select an icon and press the icon font button it will show you the correct HTML to use.
