### ISSUE TITLE
expansion_panels and expension_panels icons are same code point

### ISSUE THREAD

**Issue by timmaffett** [google/material-design-icons#1832]
In the new Oct 17, 2024 release of the variable fonts the codepoint files have these duplicate entries:

```
expansion_panels ef90
expension_panels ef90
```

Is this intentional ? It would appear that expension may just be a misspelling of expansion as 'expension' is not a word...

I just thought I would point it out so it could be fixed if it was not intentional.

**Comment by tphinney** [comment]
Originally it was a typo or a spelling error, yes. But it shipped.  :(  I caught the error later, after it was too late to change. Once something ships, it is usually still supported forever, even if not displayed in the front end interface.

There is only one actual glyph in the font. Both ligature names point at that one glyph.

For some weird technical reasons to do with Google’s processing and support, I am surprised there is only one codepoint in that file. But the font part of it doesn’t care, as there is only one glyph. (That glyph actually has two codepoints! EF90 and E600).

**Comment by tphinney** [comment]
Verified that as long as both ligatures point at the same font glyph (which they do) the back end is ok with it as well.  :)
