### ISSUE TITLE
Icon request: Satellite dish

### ISSUE THREAD

**Issue by mrleblanc101** [google/material-design-icons#1845]
Something like this:
![Image](https://github.com/user-attachments/assets/4928f119-d3f8-4e06-b646-f69729881558)

More exemples:
https://www.google.com/search?q=satellite+dish+icon&sca_esv=face10566ce46e9f&udm=2&biw=2544&bih=1279&sxsrf=ADLYWIJvfgBVyDu7G3PeDw4KD7OMBVDRIA%3A1733694578582&ei=chRWZ_meI8aoptQPpJOcuAE&ved=0ahUKEwj5n4XMk5mKAxVGlIkEHaQJBxcQ4dUDCBA&uact=5&oq=satellite+dish+icon&gs_lp=EgNpbWciE3NhdGVsbGl0ZSBkaXNoIGljb24yBxAAGIAEGBMyBxAAGIAEGBMyBxAAGIAEGBMyBxAAGIAEGBMyBhAAGBMYHki4K1AAWN8pcAB4AJABAJgBmgGgAdIJqgEEMTQuMbgBA8gBAPgBAZgCD6AC8gnCAgQQIxgnwgILEAAYgAQYsQMYgwHCAg4QABiABBixAxiDARiKBcICCBAAGIAEGLEDwgIKEAAYgAQYQxiKBcICDRAAGIAEGLEDGEMYigXCAgUQABiABMICBBAAGB7CAggQABgTGAgYHpgDAJIHBDE0LjGgB9BN&sclient=img#vhid=il2w8N_juF9cEM&vssid=mosaic

**Comment by sphars** [comment]
Also looking for something like this, see my request in #1699

**Comment by tphinney** [comment]
Oops, good point. Closing this as a duplicate.
