### ISSUE TITLE
Request to Update the Syrian Flag Emoji

### ISSUE THREAD

**Issue by Omaaar90** [google/material-design-icons#1846]
## Context
Recent political developments in Syria have led to the overthrow of President Bashar al-Assad's government. The new leadership has reinstated the "Independence Flag," symbolizing the nation's transition and aspirations for the future. This flag, featuring three horizontal stripes of green, white, and black with three red stars in the white stripe, has been adopted as the official national flag. ([Source: Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Syria))

## Request
We request the update the Syrian flag emoji to reflect the newly adopted national flag design. This update will ensure that digital communications accurately represent Syria's current national symbols.

## Details
- **New Flag Design:**
  - *Description:* The flag consists of three horizontal stripes—green (top), white (middle), and black (bottom)—with three red five-pointed stars centered in the white stripe.
  - *Adoption:* Following the fall of Assad's regime, the "Independence Flag" has been raised within Syria and at Syrian embassies worldwide. ([Source: Reuters](https://www.reuters.com/world/middle-east/syrian-rebel-supporters-hoist-flags-embassies-abroad-2024-12-08/))

- **Geopolitical Context:**
  - *Overthrow of Assad's Government:* Syrian rebels have taken control of major cities, leading to the collapse of the previous regime. ([Source: Reuters](https://www.reuters.com/world/middle-east/syria-rebels-celebrate-captured-homs-set-sights-damascus-2024-12-07/))
  - *Adoption of New Symbols:* The new leadership has introduced national symbols, including the updated flag, to mark a new era. ([Source: Firstpost](https://www.firstpost.com/explainers/syria-rebel-flag-official-bashar-al-assad-fall-13842906.html))

- **Importance:**
  - *Accurate Representation:* Updating the emoji ensures that digital platforms reflect Syria's current national symbols, maintaining cultural and political accuracy.
  - *Public Sentiment:* The new flag holds significant meaning for Syrians and supporters worldwide, symbolizing hope and change.

## References
- [Syrian rebels topple Assad who flees to Russia in Mideast shakeup](https://www.reuters.com/world/middle-east/syria-rebels-celebrate-captured-homs-set-sights-damascus-2024-12-07/)
- [Syrian rebel supporters hoist flags at embassies abroad](https://www.reuters.com/world/middle-east/syrian-rebel-supporters-hoist-flags-embassies-abroad-2024-12-08/)
- [After fall of Assad, will Syria get a new flag?](https://www.firstpost.com/explainers/syria-rebel-flag-official-bashar-al-assad-fall-13842906.html)

## Action Needed
1. **Update the Syrian Flag Emoji:** Modify the existing Syrian flag emoji in the Noto Color Emoji set to reflect the new design.
2. **Coordinate with Platforms:** Ensure that platforms using Noto Color Emoji incorporate the updated flag design in their systems.

Thank you for considering this request. I am available to provide further information or assistance to facilitate this update.

**Comment by RedCloud2** [comment]
This is such an important and meaningful request. Updating the Syrian flag emoji to match the newly adopted "Independence Flag" is more than just a design change—it’s about honoring the hope, resilience, and transition of an entire nation. The flag is a powerful symbol of Syria’s new chapter, and making sure it’s accurately represented online is essential for Syrians and their supporters around the world. This update will help people express their identity and solidarity while showing that digital platforms value cultural and political accuracy. Thank you for pushing for this important change!

**Comment by lawand-allo** [comment]
Updating the Syrian flag emoji to the "Independence Flag" honors Syria's journey and fight of the syrian community for democracy and independence.

**Comment by tphinney** [comment]
This issue was filed in the wrong repository. This is not the repository for Noto Color Emoji. That repo is at https://github.com/googlefonts/noto-emoji

What seems like the same issue was already created in that repo: https://github.com/googlefonts/noto-emoji/issues/495

(This repo is for Google’s Material Symbols, formerly Material Icons, which do not cover specific national flags at all.)
