### ISSUE TITLE
Google Mobile and Ligatures With Underscores

### ISSUE THREAD

**Issue by daniel-nagy** [google/material-design-icons#186]
Hi,

I have a Nexus 4 that I am using to test my application on. To my surprise, the font icons are not displaying properly.

**Device Info**
- Android Version: 4.4
- Chrome Mobile Version: 30.0.1599.105

It appears any ligature with an underscore in its name does not display properly. So I tried the numeric character reference and that did work; however, interpolating the numeric character reference in Angular does not work, i.e.

``` html
<i class="material-icons">{{icon}}</i>
```

I don't care about any browsers older than IE 10 (not that I really care for IE 10 or 11 :stuck_out_tongue_closed_eyes:). Anyway I think it is a shame that I can't use the ligature syntax just because it is not working in Chrome Mobile especially considering, as far as I can tell, interpolating numeric character references does not work.

**Comment by surfjedi** [comment]
+1 having issues on samsung galaxy s5, 4.4.2, and others in that range.  Nor will ascii characters work with or without material design

**Comment by tibomahe** [comment]
+1

**Comment by JacobTheEvans** [comment]
+1 Same problem with with any samsung devices

**Comment by odbol** [comment]
I'm having this issue as well, using Android 4.4 on an emulator (in a Cordova WebView). Here's some screenshots to illustrate. This is the problem code (using MDL library):

````
                <!-- This works -->
                <button class="mdl-button editTriggersButton mdl-js-button mdl-button--icon">
                    <i class="material-icons">edit</i>
                </button>

                <!-- This does not work -->
                <button id="demo-menu-lower-right"
                        class="mdl-button mdl-js-button mdl-button--icon">
                  <i class="material-icons">more_vert</i>
                </button>
````

Expected (Android 5.1):
<img width="338" alt="screen shot 2015-10-23 at 4 21 57 pm" src="https://cloud.githubusercontent.com/assets/550985/10707100/9a073288-79a2-11e5-80b5-3e76e9b3b6d9.png">

Actual (Android 4.3 and 4.4):
<img width="389" alt="screen shot 2015-10-23 at 4 20 26 pm" src="https://cloud.githubusercontent.com/assets/550985/10707099/9a03e790-79a2-11e5-93e4-0b3acef3cc88.png">

**Comment by odbol** [comment]
I don't know if it's really in-scope to try to support awkward outdated Android browsers, but perhaps an actionable item would be to update the documentation with a compatibility list and a warning with @daniel-nagy 's workaround with the numeric reference.

**Comment by RoelN** [comment]
This was caused by no support for ligatures. If this issue is still relevant, updating your code to use Unicode codepoints will solve the issue (e.g. `&#xABCD;`). Find the codepoints here: https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
