### ISSUE TITLE
look at SVG symbol file?

### ISSUE THREAD

**Issue by brynnd** [google/material-design-icons#187]
Hi - I'm not sure if this is the proper place to ask for help or not.  But it's the only place I can find to send a message.

I installed a bunch of MDI icons files several months ago, by placing the SVG files in the share/symbols directory of Inkscape.  And they work just fine in Inkscape and I'm happy to have them!

I wanted to look at some of the icons in the SVG file, to see how the artist made them.  Just trying to learn on my own.  But now when I open those SVG files, they are empty!

Do I have to go and download fresh SVG files, to see them?  Why, and maybe more importantly how, can they be empty?

Thanks for your help.

Edit
Because I've opened the SVG files for other icon sets, and those images are visible and selectable, and editable, if I wanted to edit them.  But if I delete one of these empty MDI icon SVG files, the icon set disappears out of the Symbols dialog.

So what's the story with these icon sets?  TA  :-)

**Comment by shyndman** [comment]
I had our local inkscape user test against our newest (non-symbol) svg sprite sheets, and he says they work great. Check them out.

https://github.com/google/material-design-icons/blob/master/sprites/svg-sprite/svg-sprite-alert.svg
