### ISSUE TITLE
Popup and dropdowns opening cause blank bottom portion of body

### ISSUE THREAD

**Issue by neryams** [google/material-design-icons#188]
When the user is scrolled down on the page, a negative top positioning is being applied on the body element when opening popups and dropdowns. This causes a blank space on the bottom of the page, or the entire page turns blank if the user is scrolled down far enough.

**Comment by phillcunliffe** [comment]
I had the same issue

**Comment by shyndman** [comment]
@rfru

**Comment by RoelN** [comment]
The site has been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
