### ISSUE TITLE
same icon for component and composite

### ISSUE THREAD

**Issue by Datafridge** [google/material-design-icons#19]
Why is the icon for "settings input composite" and "settings input component" exactly the same?

**Comment by jestelle** [comment]
We've decided for now this is working as intended.
If you have a particular need to use both these icons, and they need to be visual distinct, please reopen this issue, that I'll mark now as an icon request.

**Comment by Xaviju** [comment]
I was going to make the same question, but found this already answered. :)

**Comment by dfliess** [comment]
whats the intention ? it would be useful to have a one cable icon.
