### ISSUE TITLE
Some icons are in the folders but not in the codepoints

### ISSUE THREAD

**Issue by nah0y** [google/material-design-icons#190]
There is some icons that we can find in the folders "communication", "device" etc... but they are not present in the codepoints file, nor the MaterialIcons-Regular.ijmap file (and so maybe not in the font file?).

The one I have missing are: 
- contact_mail
- battery_20 
- battery_30 
- battery_50 
- battery_60 
- battery_80 
- battery_90 
- battery_charging_20
- battery_charging_30
- battery_charging_50
- battery_charging_60
- battery_charging_80
- battery_charging_90
- signal_cellular_0_bar
- signal_cellular_1_bar
- signal_cellular_2_bar
- signal_cellular_3_bar
- signal_cellular_connected_no_internet_0_bar
- signal_cellular_connected_no_internet_1_bar
- signal_cellular_connected_no_internet_2_bar
- signal_cellular_connected_no_internet_3_bar
- signal_wifi_0_bar
- signal_wifi_1_bar_lock
- signal_wifi_1_bar
- signal_wifi_2_bar_lock
- signal_wifi_2_bar
- signal_wifi_3_bar_lock
- signal_wifi_3_bar

**Comment by shyndman** [comment]
Hi @nah0y,

Those icons are two-toned (black and gray), so their inclusion in the icon font is currently not (technically) possible. 

We've been talking about creating single-tone replacements, but there's nothing to announce yet.

**Comment by nah0y** [comment]
Hum... Okay I see for all of these icons, except one: contact_mail
For what I can see, the contact_mail icon is in white and black (as the contact_phone that is include in the font).
