### ISSUE TITLE
Ctrl+F does not work in the library overview

### ISSUE THREAD

**Issue by PhilLab** [google/material-design-icons#191]
Both Firefox and Chrome used on several Windows machines cannot reliably use the page search function (Ctrl+F) to discover icons in the library overview https://www.google.com/design/icons/

E.g. open the page and search for "star" - it won't find it although it is on the very bottom. If you scroll down and try the search again multiple times, the star will eventually be found. This makes finding the right icon hard.

**Comment by bleush38p** [comment]
Happens on Chrome/OS X too. Why is this an issue, though—can you not use the search bar provided?

**Comment by PhilLab** [comment]
pressing Ctrl+F is that much faster than searching for the bar on an unknown site. To be honest it took me some days to notice it. It is an universal UX feature one gets used to

**Comment by quangv** [comment]
yeh, it's weird. Only some Icons, (I think the ones one top?) can you use Ctrl+F ...

ctrl+f is an easy way to search for availability of icons. Is there an alternative?

Is there another "index" of all the icons, that we can search...

**Comment by bleush38p** [comment]
It's because the icons don't actually all exist yet - they're dynamically added to and hidden from the page as you scroll up and down.

![scrolling](https://cloud.githubusercontent.com/assets/7422958/9499452/25321044-4be5-11e5-8261-32c1fc52f89a.gif)

**Comment by PhilLab** [comment]
@bleush38p : awesome, thanks for investigating! BTW, which addon/software did you use for capturing the browser?

**Comment by bleush38p** [comment]
That's [LICEcap](http://www.cockos.com/licecap/)—it records your screen to a .GIF, automagically.

**Comment by quangv** [comment]
duh, I didn't realize there was a search feature on https://www.google.com/design/icons/ which works marvelously...

**Comment by RoelN** [comment]
CTRL-F/CMD-F searching is now supported on https://material.io/resources/icons/?style=baseline
