### ISSUE TITLE
youtube-play missing

### ISSUE THREAD

**Issue by boustanihani** [google/material-design-icons#192]
Why are essential icons like **youtube-play** (https://materialdesignicons.com/icon/youtube-play) not included by default in this repo (http://www.google.com/design/icons/) ?

**Comment by RoelN** [comment]
Various play icons have been added in the meantime: https://material.io/resources/icons/?search=play&style=baseline

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
