### ISSUE TITLE
Icons request: add "folder" and "recursive folder" icons

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#193]
Suppose I have a screen for choosing folders, and I have a FAB to add a folder or a recursive one (via an animated menu), this should be handy. :)

**Comment by dcversus** [comment]
Add folder icon :)

<?xml version="1.0" ?><svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M18,4h-8L8,2H2C0.896,2,0.01,2.896,0.01,4L0,16c0,1.104,0.896,2,2,2h16c1.104,0,2-0.896,2-2V6C20,4.896,19.104,4,18,4z   M17,12h-3v3h-2v-3H9v-2h3V7h2v3h3V12z"></path></svg>

**Comment by AndroidDeveloperLB** [comment]
@dcversus I don't understand.

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi Can't find. Tried to also search "recursive" and got nothing:
https://fonts.google.com/icons?icon.query=recursive

**Comment by jalpadoshi** [comment]
Icon name:folder_copy

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi But that's about copying a folder.
I asked for choosing a folder, and choosing a recursive folder (scanning in them).
For example, if you create an app to search for file/s of some type, and you allow the user to choose which folders to search in, and also some to search recursively, that's the icons I'm looking for
