### ISSUE TITLE
Icon request: newspaper

### ISSUE THREAD

**Issue by TheChen5** [google/material-design-icons#194]
Hello,
Can a newspaper icon please be added to material icons.
I need it for a "news" section
thanks

**Comment by javmarina** [comment]
It's really strange. Some Material icons created by Google are not available here, but at https://materialdesignicons.com/

One of them is the "newspaper" icon, which is the one you're looking for:  https://materialdesignicons.com/icon/newspaper

**Comment by TheChen5** [comment]
thx for telling me 
but i'd rather do it the "easy" way with HTML

**Comment by JAJP** [comment]
Is this ok? I can use "newspaper"(https://materialdesignicons.com/icon/newspaper) for website?

**Comment by adarshv90** [comment]
+1

**Comment by LabLayers** [comment]
👍

**Comment by jac-usai** [comment]
Please, add the icon to the web-font!

**Comment by conan06** [comment]
Please add it

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
