### ISSUE TITLE
power_settings_new is missing from the sprites

### ISSUE THREAD

**Issue by roxeteer** [google/material-design-icons#197]
The [power_settings_new](https://www.google.com/design/icons/#ic_power_settings_new) icon ![power_settings_new](https://raw.githubusercontent.com/google/material-design-icons/master/action/1x_web/ic_power_settings_new_black_24dp.png) is missing from the PNG and SVG sprites:

![Latest PNG sprite](https://raw.githubusercontent.com/google/material-design-icons/master/sprites/css-sprite/sprite-action-black.png)

**Comment by shyndman** [comment]
It's in there now:
https://github.com/google/material-design-icons/blob/master/sprites/css-sprite/sprite-action-black.png
