### ISSUE TITLE
Icon request: double chevron

### ISSUE THREAD

**Issue by un-quebec-independant** [google/material-design-icons#198]
Double chevrons would be useful for page navigation (e.g., first page, last page).

**Comment by pieterwillaert** [comment]
+1

**Comment by Kasijjuf** [comment]
As of version 2.2 there are now dedicated first page and last page icons.

https://design.google.com/icons/#ic_first_page
https://design.google.com/icons/#ic_last_page

**Comment by Miindaugas** [comment]
Would be useful for "Move All" for dual lists.

**Comment by dota2Pro** [comment]
Something like this https://fontawesome.com/icons/arrows-alt-h?style=solid

**Comment by shuegelm** [comment]
Thought more of these: <<    or   >>
![image](https://user-images.githubusercontent.com/12783126/70311495-0fb1a600-1812-11ea-83f8-614f15a01655.png)

**Comment by danieldanielecki** [comment]
Bump +1

**Comment by gabiionut** [comment]
+1 something like [this one](https://icons-for-free.com/arrows+double+arrow+doublechevronleft+left+icon-1320185729725994033/)

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
