### ISSUE TITLE
Icon request: Network ping

### ISSUE THREAD

**Issue by dcolebatch** [google/material-design-icons#199]
We're looking for an icon that represents a network ping (an ICMP echo request).

e.g. If a user sees this icon next to an IP address (say, 8.8.8.8), they should expect the application to execute 

```
➜  ~  ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=55 time=15.546 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=18.624 ms
```

cc/ @shyndman

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
