### ISSUE TITLE
Missing icon: Tachometer

### ISSUE THREAD

**Issue by josh18** [google/material-design-icons#201]
![icons](https://cloud.githubusercontent.com/assets/5900962/9398358/77762b0e-47fa-11e5-86ab-1cb3d5bbb661.png)

The tachometer seems to be in the preview image but I can't seem to find it in the list (or I am just blind + not searching for the right terms). Any idea what happened to it?

**Comment by EvanWieland** [comment]
I've noticed this as well. Would love to be able to use it.

**Comment by elioqoshi** [comment]
Any update on this?

**Comment by shyndman** [comment]
Hi there,

This icon is not part of our public icon set. Sorry.

**Comment by josh18** [comment]
That seems a little strange, is there any reason why the icon isn't part of the public set? Are there plans to add it in the future?

If possible it would be nice if you could remove it from the preview image so that people don't search for it for ages only to find that it doesn't exist.

**Comment by shyndman** [comment]
It may just be that a team has wanted to reserve its use. I poked one our design producers about it, and she's going to look into it.

**Comment by josh18** [comment]
@shyndman sorry to bother you but did you ever get an update on this?

**Comment by victorfern91** [comment]
Any update on this?
