### ISSUE TITLE
Material Icons - Vertical Align Doesn't work well alongside text

### ISSUE THREAD

**Issue by vayanis** [google/material-design-icons#206]
Hi,

Material icons doesn't seems to vertical align themselves when placed alongside any text.

**Issue:**

![image](https://cloud.githubusercontent.com/assets/10917140/9648615/ca658958-522d-11e5-9c0e-cebc254a7d5e.png)

![image](https://cloud.githubusercontent.com/assets/10917140/9648750/4d7c8b92-522f-11e5-8712-c6197e714228.png)

![image](https://cloud.githubusercontent.com/assets/10917140/9648625/e2effbb6-522d-11e5-8a1f-606d58a7c598.png)

I am using this code:
```html
<p><i class="material-icons">&#xE8B5;</i> Open 7 Days</p>
```

Let me know if I am doing anything wrong.

I am using Bootstrap v 3.3.5.

**Comment by thomas83** [comment]
This sounds more like a CSS issue.  Make sure the line-height are the same for both, and set the display to "inline" or "inline-block", and set "vertical-align: middle"

See if that works.

**Comment by chicagosky** [comment]
I had the same issue and was able to fix it by using the following CSS code

[code]
div.mdl-layout__drawer > nav.mdl-navigation > a.mdl-navigation__link {
    display: inline-flex;
    vertical-align: middle;
}
[/code]

**Comment by shyndman** [comment]
@chicagosky has the right idea. Write CSS that works for your use case.

**Comment by sylvainar** [comment]
Solved it with : 
`.panel-heading > i{
	vertical-align: middle !important;
}`

**Comment by nueverest** [comment]
I used the solution provided by @sylvainar, and still needed to add `padding-bottom-3` since it still wasn't lining up.

    .vertical-align-middle { 
        vertical-align: middle; 
    }

    .padding-bottom-3 {
        padding-bottom: 3px;
    }

    <i class="material-icons vertical-align-middle padding-bottom-3">chevron_left</i>
    <div class="inline-block">Previous</div>    

Interestingly enough, **I tried to put the adjacent text in a div and add padding to the div instead of the icon. Surprisingly, it added padding to both the icon and the div**.  That seems broken to me as the icon is outside of the div.  I'm using Zurb Foundation 5.5.

    <i class="material-icons vertical-align-middle">chevron_left</i>
    <div class="inline-block padding-bottom-3">Previous</div>

**Comment by Javid-Izadfar** [comment]
it's kinda crazy but in my experience, having `vertical-align: bottom` appears more _center_ than anything.

**Comment by gharia** [comment]
Following worked for me:

```
<li class="collection-item valign-wrapper">
	<i class="material-icons small valign">pool</i>
        <span>Swimming Pool</span>															 
</li>
```

**Comment by ShinDarth** [comment]
same problem here, for some reasons I solved using:

`vertical-align: top;`

**Comment by PankajPrakashh** [comment]
Anybody here could explain why `vertical-align: bottom;` worked for me instead of `vertical-align: middle;`. I am totally confused how it works.

**Comment by ShinDarth** [comment]
Same here, sometimes it works with `vertical-align: bottom / top / middle;` I have no idea why.

Strange thing is that in those context I have no problems with font awesome

**Comment by korneliuskristianr** [comment]
Hi, thanks. It worked for me `vertical-align: middle;`

**Comment by snolflake** [comment]
@chicagosky solution cover most scenarios

A general solution could be to always wrap your icons and text so they can be aligned using flexbox

```
<div class="valign-center">
  <span>My Text</span>
  <i class="material-icons">chevron_left</i>
</div>
```

```
.valign-center {
  display: inline-flex;
  vertical-align: middle;
}

.valign-center > * {
  align-self: center;
}
```

This seems to work well for any line-height, no matter which one is bigger, the icon or the text.

**Comment by elliot627** [comment]
There's also another option for `vertical-align` called `text-top` which worked the best for me.

**Comment by jmc265** [comment]
So I've come across this problem quite a bit. I have created a generalised solution which seems to work for the material icons in a number of different situations:

```
.material-icons {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    vertical-align: middle;
}
```

**Comment by danielhaim1** [comment]
Neither solutions worked for me :-/

**Comment by dpassis** [comment]
` <li  class="collection-item valign-wrapper"><i class="material-icons">done</i>Some Text</li>`

**Comment by simplethemes** [comment]
This "issue" appears to depend on how your baseline is set up. I usually rely on a 1em body font size with a 1.5 line-height, so this works best in my case:

```
i {
  // required
  font-family: 'Material Icons';
  font-feature-settings: 'liga';
  font-weight: normal;
  font-style: normal;
  font-size:inherit;
  line-height:inherit;
  vertical-align: top;
  display: inline-block;
  // resetters
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
  // optimizers
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
}
```

**Comment by danielhaim1** [comment]
I'll give it a try @simplethemes

**Comment by zzseba78** [comment]
This fix the problem for me:
i.material-icons { vertical-align: middle !important; }

**Comment by thekage91** [comment]
@chicagosky thank you, your solution work perfectly!! I can relax my head instead of :D :D 

![schermata 2017-06-18 alle 11 20 46](https://user-images.githubusercontent.com/4046770/27259659-48a87a76-5418-11e7-9b3e-14efc7a1ba5d.png)

![schermata 2017-06-18 alle 11 21 01](https://user-images.githubusercontent.com/4046770/27259658-3f6b537a-5418-11e7-8059-d3b5b7da479b.png)

![schermata 2017-06-18 alle 11 22 05](https://user-images.githubusercontent.com/4046770/27259664-707fba96-5418-11e7-9f3a-566c36dd6123.png)

http://imgur.com/Q3cUg29

**Comment by juloko** [comment]
One more solution, copied by Google.

>i.material-icons
> {
>   flex-flow: column;
>    display: flex !important;
>    justify-content: center !important;
>}

**Comment by clusteratlas** [comment]
```

.material-icons {
  vertical-align: middle !important;
  padding-bottom: 3px;
}
```

**Comment by sinedied** [comment]
While we can "fix" this issue using CSS, I still think that the icon-font baseline should be properly set, and that is a bug.
When using font-awesome or ionicons, icons have by default a proper baseline alignment and that's something related to the font, not the CSS.

**Comment by tushgraph** [comment]
fixed it by using the following CSS code

div.mdl-layout__drawer > nav.mdl-navigation > a.mdl-navigation__link {
    display: inline-flex;
    vertical-align: middle;
}

**Comment by tushgraph** [comment]
I had the same issue and was able to fix it by using the following CSS code

p > i { font-size:2.1rem; display: inline-flex; vertical-align: middle;}

**Comment by tushgraph** [comment]
Fixed by using below css
p i { font-size:2.1rem; display: inline-flex; vertical-align: middle;}

**Comment by dapojaja** [comment]
Material icon aligns well with text on desktop browsers but not with android webview on 4.4/5.1
`<mat-toolbar>
  <button><mat-icon>menu</mat-icon></button>
  <span>Angular Wordpress App</span>
</mat-toolbar>`

fixed with 
.mat-icon-button {
  line-height: 0;
}

**Comment by yresultadmin** [comment]
fixed with:

i.material-icons {display: inline-flex; vertical-align: top; line-height: inherit;}

**Comment by chriscarpenter12** [comment]
This seems to have worked best in my initial testing.

**Comment by levindoneto** [comment]
What worked for me was to work only on the _line-height_ property.
```javascript
.material-icons {
  line-height: 210%; /* manually adjusted to get the middle of the line*/
}
```

**Comment by PawelPleskaczynski** [comment]
For me, `transform: translateY(25%);` works just okay, but I guess it's a bit hacky solution.

**Comment by meftunca** [comment]
i.material-icons {
    display: inherit;
}

**Comment by jaymoh** [comment]
@jmc265 solution worked for me

**Comment by nacengineer** [comment]
For those coming to this at the 11th hour, i.e. future me, add a left or right to the element class, e.g. <i className="material-icons left">, and it'll float properly.

**Comment by TZanke** [comment]
I do not have any "left" class. Can you explain whats inside this CSS Class?

**Comment by nacengineer** [comment]
My apologies. I thought you were using these in conjunction with
materialize-css

**Comment by FabianPiconeDev** [comment]
`vertical-align: sub;` was my best choice.

**Comment by aesher9o1** [comment]
Worked for me
```
 position: absolute;
float: right; 
```

**Comment by LondonWebFactory** [comment]
> it's kinda crazy but in my experience, having `vertical-align: bottom` appears more _center_ than anything.

Many thanks. This worked for me.

` .material-icons {
 vertical-align: bottom !important;
}`

**Comment by theaemarie** [comment]
I'm still very lost at how to fix, here is reproduction: https://codepen.io/theaemarie/pen/ROvajg?editors=1100
Seems to just be a problem w/themes.

**Comment by MicMicMon** [comment]
Just switch to Iconify (see https://github.com/google/material-design-icons/issues/71, and https://iconify.design/) and forget about this nonsense forever :)

**Comment by progmars** [comment]
I'm too voting for `top`:

```
.material-icons {
    font-size: inherit;
    line-height: inherit;
    vertical-align: top;
}
```

While other solutions somewhat helped, still when I inspected it in Chrome, I saw that the font symbol is not exactly vertically centered with my other letters.  Top worked perfectly together with inheriting font size of the container.

**Comment by k-funk** [comment]
This is embarrassingly bad.

Most of the solutions in here include a bunch of flexbox rules that are doing nothing. 

`vertical-align: middle;` sorta works, but it often shifts the position of the text next to it as well, and it's not perfectly aligned either. How is this library so popular when something so simple is broken out of the box?

🗑

**Comment by hanabira80** [comment]
<style>
    .txt_width_icon {
       font-size:0;
    }
    .material-icons {
        vertical-align:middle;
        margin:0 0.4rem; /* if you need space */
    }
    .icon_text {
        display:inline-block;
        vertical-align:middle;
        font-size:1.2rem; /* change by your design */
    }
</style>

<div class="txt_width_icon">
    <i class="material-icons"> keyboard_arrow_left </i>
    <div class="icon_txt">SUB MENU</div>
</div>

**Comment by hanabira80** [comment]
```
<style>
    .txt_width_icon {
       font-size:0;
    }
    .material-icons {
        vertical-align:middle;
        margin:0 0.4rem; /* if you need space */
    }
    .icon_text {
        display:inline-block;
        vertical-align:middle;
        font-size:1.2rem; /* change by your design */
    }
</style>

<div class="txt_width_icon">
    <i class="material-icons"> keyboard_arrow_left </i>
    <div class="icon_txt">SUB MENU</div>
</div>
```

**Comment by harikru** [comment]
> it's kinda crazy but in my experience, having `vertical-align: bottom` appears more _center_ than anything.

This worked! \m/

**Comment by rifleby** [comment]
[SOLUTION] - I just switched from font-awesome, this fixes the vertical issue perfectly, simply apply this styling to your icons

font-size: inherit;
vertical-align: bottom;
line-height: inherit;

**Comment by jahidulhub** [comment]
.container **display:flex**
                  **align-items:center**
i(icon tag) **display:block**
And this work for me finally.

**Comment by HTD** [comment]
Geez, people! It's obviously something terribly wrong here if completely different and contradicting solutions work in different cases!

All kinds of `vertical-align` reportedly work. I tell you what: it all depends on the `font-size`, and this is clearly wrong! It shouldn't depend on the font-size. If it does, there is a bug in the font.

Of course it can be worked around with a CSS fix for each icon size, but this is going to break anyway.

**Comment by blackfatpig** [comment]
In my case, I changed my CSS like:
.my-button
{
        display: inline-grid;
        vertical-align: middle;
        text-align: center;
        align-items: center;
}
Hope this help.

**Comment by entrifis** [comment]
Depends on the size of the mat-icon. Inspect the height of the mat-icon, then add a line-height equal to it

{
    display: inline-flex;
    vertical-align: middle;
    line-height: <the size of the mat icon>
}

**Comment by matthewmav** [comment]
For whom, who tried everything, but didn't work any of the top solution as at my side, give a try to:
    float: left,
    font-size: 3.0em,
    margin-top: -0.1em,
Of course you can play with the values.

**Comment by paulghodgson** [comment]
This is a deal breaker for me, I really don't want to fight my fonts every time I use them not sure why this is closed.

**Comment by opedroaravena** [comment]
> Solved it with :
> `.panel-heading > i{ vertical-align: middle !important; }`

THIS WORKED FOR ME.

**Comment by HTD** [comment]
> This is a deal breaker for me, I really don't want to fight my fonts every time I use them not sure why this is closed.
Well, if you don't need many sizes in the app, or not many versions (mobile, desktop, etc) - they are still usable. But I agree - when they are a couple of sizes - the problem with vertical alignment is too much working around. There were many regular text web fonts that I was unable to use for the same reason. Original system fonts have no problem with vertical alignment, it just works in every browser, any text size and DPI settings, some of them get this wrong and it breaks.

**Comment by jscottPTC** [comment]
> This is embarrassingly bad.
> 
> Most of the solutions in here include a bunch of flexbox rules that are doing nothing, or require wrapping the icon in another div that will undo the alignment-flaw in the original font.
> 
> `vertical-align: middle;` sorta works, but it often shifts the position of the text next to it as well, and it's not perfectly aligned either. How is this library so popular when something so simple is broken out of the box?
> 
> 🗑

Yeah Angular is a pretty good framework.  But I quite often run into small but infuriating issues like this.  It happens enough to make me refer to Angular as a 'good but certainly not great' framework.

**Comment by xtance** [comment]
To anyone visiting in this future:
Just use emojis, they align perfectly and built-in on most platforms
On windows, you can press Win+Ю (period button) and select them there

**Comment by nacengineer** [comment]
Emojis don't always support screen readers in the way you intend. They have alt codes but typically these do not align with the way we use them. They have their use but in accessible web design the span approach is preferred because you can easily disable in aria.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by the1Riddle** [comment]
this worked well for me when i added it within the: `<span>`  it should also work well when added to the css file i guess.

```css
    style="position:relative; top:4px;"
```
