### ISSUE TITLE
Support for icons in CSS generated content

### ISSUE THREAD

**Issue by rhewitt22** [google/material-design-icons#207]
Is there an entity code list that I'm not seeing?  How can I use these icons in css generated content?  I tried the codes presented on the website that give support to IE9 without any luck.

```
.nav-link.has-children::after {
  content: ''; // some code
  font-family: 'Material Icons";
}
```

**Comment by rhewitt22** [comment]
https://github.com/Angelmmiguel/material_icons/blob/master/app/assets/stylesheets/material_icons_unicode.css.erb#L85-L3265

**Comment by oneezy** [comment]
This problem is back. they recently forgot to add the entity reference w/ the new site/icons upgrade. I created issue #785.

For now, the link posted above is the best we've got to go by.
