### ISSUE TITLE
CC-BY 4.0 License

### ISSUE THREAD

**Issue by lazolive** [google/material-design-icons#208]
Dear Google,

We are writing to request, the using and license conditions about your Google Material Icon Bundle.

I would be grateful if you can give me more information abour the CC-BY 4.0 License.

We would like to use your Material Icon Set on our article description page in our online shop and on ebay where we sell Google Android Smartphones and Tablet-Pc's and other smart devices of other manufacturers too.
Link to the icon bundle: https://github.com/google/material-design-icons

Because this icons are licensed under CC-BY 4.0 License, we only would like to change the colour of the icon, I would be great, if I don't have to give a back link to every icon, because only the color was changed.
If I have to give a link and a short description about the change of colour, our company would be happy, if we only write it in our imprint, if it is okay for you.

If we can be of any further assistance, please let us know.
We would appreciate receiving a prompt reply to our request.

Sincerely yours,
lazo-live

**Comment by shyndman** [comment]
Yup, no problem Lazo. That seems "reasonable", as described in the license text.
