### ISSUE TITLE
Fingerprint icon missing

### ISSUE THREAD

**Issue by CoDEmanX** [google/material-design-icons#209]
The official fingerprint icon isn't available, although you can find rendered versions of it in the MD guidelines:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B0iWdZjcphyMWEF1RlBXZnZKbWc/components_fp_11_state2.png

**Comment by jcady92** [comment]
+1 Much needed in the library.

**Comment by shyndman** [comment]
It's in!
