### ISSUE TITLE
Icon request: Flashlight on + Flashlight off

### ISSUE THREAD

**Issue by ozsay** [google/material-design-icons#217]
Something like this:
https://materialdesignicons.com/icon/flashlight
https://materialdesignicons.com/icon/flashlight-off

It would help,
Thanks.

**Comment by shyndman** [comment]
One half of your request: https://www.google.com/design/icons/#ic_highlight

**Comment by RoelN** [comment]
Now they're both in the set \o/

<img width="277" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108854516-44ad4280-75e8-11eb-9868-cff1d06419d9.png">
