### ISSUE TITLE
Star Icon 48px SVG assets missing

### ISSUE THREAD

**Issue by Anaphase** [google/material-design-icons#218]
Certain 48px SVG assets appear to be missing:

In the _toggle_ set:
[ic_star_24px](https://github.com/google/material-design-icons/blob/master/toggle/svg/production/ic_star_24px.svg)
[ic_star_border_24px.svg](https://github.com/google/material-design-icons/blob/master/toggle/svg/production/ic_star_border_24px.svg)
[ic_star_half_24px.svg](https://github.com/google/material-design-icons/blob/master/toggle/svg/production/ic_star_half_24px.svg)

Strangely enough, it also appears in the _action_ set too:

[ic_star_rate_18px.svg](https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_star_rate_18px.svg)

Both the design and production directories exhibit this discrepancy. Is there a reason for this or is it an oversight?

**Comment by Anaphase** [comment]
I tired to create the SVGs myself to submit a pull request, but apparently I have no idea what I'm doing.

**Comment by obskyr** [comment]
Technically, although being identical, the "star" and "star rate" icons are different icons. You're right, though - the "star rate" icon only contains the 18px version. That discrepancy's been responsible for a bit of trouble for me...
