### ISSUE TITLE
Invoice Icon 

### ISSUE THREAD

**Issue by EricaChua** [google/material-design-icons#220]
Requesting for an invoice icon please

**Comment by WagnerMoreira** [comment]
+1

**Comment by adarshv90** [comment]
@EricaChua you might be interested in: https://design.google.com/icons/#ic_receipt

**Comment by sefaYavuz** [comment]
+1

**Comment by kjostling** [comment]
+1

**Comment by RoelN** [comment]
<img width="194" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108854995-c43b1180-75e8-11eb-9780-2a8adb76c013.png">


Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
