### ISSUE TITLE
NumberFormatException with ic_sync_black_24dp.xml

### ISSUE THREAD

**Issue by stephanechorne** [google/material-design-icons#225]
https://github.com/google/material-design-icons/blob/master/notification/drawable-anydpi-v21/ic_sync_black_24dp.xml throws the following exception on Android 5+:

> java.lang.NumberFormatException: Invalid float: "-1.01.25"

Thanks for looking into it.

**Comment by malloth** [comment]
Actualy it only crashes on API 21. It works well on API 22 and API 23. There is a problem with vector drawable parser on API 21. To fix this you need to add two spaces. Proper icon definition will look like this:

<vector xmlns:android="http://schemas.android.com/apk/res/android"
	android:width="24.0dp"
	android:height="24.0dp"
	android:viewportHeight="24.0"
	android:viewportWidth="24.0">
	<path
		android:fillColor="#FF000000"
		android:pathData="M12 4V1L8 5l4 4V6c3.31 0 6 2.69 6 6 0 1.01,-.25 1.97,-.7 2.8l1.46 1.46C19.54 15.03 20 13.57 20 12c0,-4.42,-3.58,-8,-8,-8zm0 14c-3.31 0,-6,-2.69,-6,-6 0,-1.01 .25,-1.97 .7,-2.8L5.24 7.74C4.46 8.97 4 10.43 4 12c0 4.42 3.58 8 8 8v3l4,-4,-4,-4v3z"/>
</vector>

**Comment by stephanechorne** [comment]
Alright, thanks! Not sure if I should close this, though, as it's a bug on API 21.

**Comment by shyndman** [comment]
Fixed!

**Comment by EkirapaEmmanuel** [comment]
Hello Friends. How about for @drawable/ic_notifications_black_24dp and @drawable/ic_info_black_24dp
