### ISSUE TITLE
File-related icons not found

### ISSUE THREAD

**Issue by phidias51** [google/material-design-icons#226]
It would be useful if the file-related icons (seen in the Google Drive) application were also available as an iconset. In particular, the document, spreadsheet, slides, (and their MS Office equivalents), and a PDF icon.

Copied issue from here: https://github.com/PolymerElements/iron-icons/issues/22

**Comment by phidias51** [comment]
It would also be useful if we had icons for image, video, and audio file types.

**Comment by realappie** [comment]
This would be really useful as Im currently using fontawesome icons instead.

**Comment by bsinc** [comment]
this website combines google's material icons with icons of their own in the same style, includes a few different file types (.pdf, .doc, .ppt, etc.) 

[https://materialdesignicons.com/](url)

**Comment by wesleygoldsborough** [comment]
Not perfect, but I'm using these:

Image >> https://material.io/icons/#ic_photo_library
Video >> https://material.io/icons/#ic_video_library
Audio >> https://material.io/icons/#ic_library_music
PDF >> https://material.io/icons/#ic_picture_as_pdf
Text >> https://material.io/icons/#ic_library_books

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
