### ISSUE TITLE
Icon font CSS styles - add overflow: hidden

### ISSUE THREAD

**Issue by tortabevonas** [google/material-design-icons#232]
If I don't add an "overflow: hidden" declaration to my .material-icons class, my mouse sometimes "thinks" that the icons are much wider than they seem on screen. E.g. an 1cm icon has an additional 3cm long clickable rectangle on the right. It might be a webkit (or Bootstrap?) bug, as it works fine until I resize the window. But the mentioned CSS trick resolves the problem in any case.

**Comment by shyndman** [comment]
Browser/OS?

**Comment by shyndman** [comment]
And can you link to a codepen demonstrating the issue?

**Comment by tortabevonas** [comment]
OS X El capitan, Safari, Firefox, Chrome. Yes, I'll try to put together a codepen. Sorry for not doing it before opening the issue.

**Comment by tortabevonas** [comment]
I'm really sorry, but I haven't managed reproduce it in a codepen. I have to think that it was a special case, caused by my code. Excuse me for the false alarm!

**Comment by shyndman** [comment]
No problem. Thanks for getting back.
