### ISSUE TITLE
Skype icon would be nice

### ISSUE THREAD

**Issue by GustavSt** [google/material-design-icons#233]
There is already linkedin, facebook and icons for similar communication platforms. But not skype. A skype icon would be nice!

**Comment by bogodars** [comment]
Five years later... still actual :)

**Comment by GGorAA** [comment]
Yea) we need Skype icon!

**Comment by velezhanski** [comment]
please

**Comment by jalpadoshi** [comment]
We currently cannot provide 3P product icons/logos in our catalogue.

**Comment by ggoraa** [comment]
five years later, finally someone from the team responded lol
