### ISSUE TITLE
Distorted digits in some icons (ic_forward*, ic_replay*)

### ISSUE THREAD

**Issue by CoDEmanX** [google/material-design-icons#237]
The numbers found in all forward and replay icons are heavily malformed, looks like someone over-optimized the SVGs:

![forward_30_24px](https://cloud.githubusercontent.com/assets/1309249/11236284/aeca2da2-8dd8-11e5-90fa-82f946da8c3b.png)

Design and production versions are affected, as well as 24 and 48 pixel versions.

**Comment by RoelN** [comment]
Thanks for reporting, this seems to have been fixed in the mean time:

<img width="788" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108858272-4547d800-75ec-11eb-8e5b-3d401f7b4445.png">
