### ISSUE TITLE
Plain icon extremely wide for unknown reason

### ISSUE THREAD

**Issue by neoel** [google/material-design-icons#238]
Hi, 

I'm working on a react application, and I've been struggeling to get my icon show right. 
![image](https://cloud.githubusercontent.com/assets/1440704/11247958/cdd50d66-8e1e-11e5-95c2-dd0678ffca00.png)

I'm not sure where this comes from, but its a simple icon being rendered by react, in a mdl-datatable. Its really wide and I've checked all appropriate css, and cannot figure out what causes this. 
It is duplicatable on firefox as well.

Currently updating my dependencies, but I'm thinking this is some weird edgecase somehow.

In the image shown above, I've created two icons in a div, besides eachother, and the first one shows up the fault.

**Comment by shyndman** [comment]
I'd double check that the icon name is correct.

If that doesn't work, can you link to a codepen with a simple reproduction?

**Comment by neoel** [comment]
Sure, will do asap.

The icon name is correct, this is the html react created:
<div data-reactid=".0.2.0.0.1"><span data-reactid=".0.2.0.0.1.0">
</span><h1 data-reactid=".0.2.0.0.1.1">Test</h1><i class="material-icons"
data-reactid=".0.2.0.0.1.2">mode edit</i><i class="material-icons"
data-reactid=".0.2.0.0.1.3">person</i></div>

Dexter - DexterLabs.nl

**Comment by shyndman** [comment]
Ah, ligatures don't play nice with spaces, so we use underscores instead.

http://codepen.io/shyndman/pen/dYrzBg
