### ISSUE TITLE
Some icons of v2.1 are unseen

### ISSUE THREAD

**Issue by Angelmmiguel** [google/material-design-icons#240]
Hello,

I'm updating [material icons rails](https://github.com/Angelmmiguel/material_icons) library to use v2.1 icon version but some of the new icons don't appear:

![Materail Icons rails with v2.1](https://cloud.githubusercontent.com/assets/4056725/11265414/75c4719c-8e9c-11e5-8300-698003346362.png)

I see the problem happens in other websites like official [Material Design icon page](https://www.google.com/design/icons/):

![Material Design icon page](https://cloud.githubusercontent.com/assets/4056725/11265429/94d543b8-8e9c-11e5-8100-f9cf7ad942d8.png)

**Other teammates can see all icons**. I test it in my Mac OS X 10.11 El Capitan with Chrome 46.0.2490.80, Safari 9.0 (11601.1.56) and Firefox.

Thanks!

**Comment by addyosmani** [comment]
I haven't been able to reproduce this on Yosemite with Chrome 49 - are you seeing the icons not render correctly in all of the browsers you've tested?

**Comment by shyndman** [comment]
Hey @Angelmmiguel,

Do you have the font installed locally?

**Comment by Angelmmiguel** [comment]
@shyndman you are right. I uninstalled it and now it works.

The reason I installed the font is to use with a plugin in SketchApp. Thanks @addyosmani and @shyndman for your help! :)
