### ISSUE TITLE
Icon request: gender

### ISSUE THREAD

**Issue by nielsenramon** [google/material-design-icons#242]
I would love to have the female and male gender(sex) icons!
I can contribute them if needed.

**Comment by mcbeelen** [comment]
+1 for this request!

**Comment by adarshv90** [comment]
+1

**Comment by ValentinTaleb** [comment]
+1 :)

**Comment by thonyarifin** [comment]
+1

**Comment by shangab** [comment]
Wa wa Wee Wa, as Borat says :-)

**Comment by bauerd** [comment]
+1

**Comment by sithu** [comment]
+1

**Comment by ColdScream** [comment]
+1

**Comment by morriq** [comment]
+1

**Comment by nitin7dc** [comment]
+1

**Comment by zomco** [comment]
+1

**Comment by mkhahani** [comment]
+1
Would be very useful.

**Comment by bytemage** [comment]
Why is this still open? It's a small thing and pretty universally needed ...

**Comment by FilipMatys** [comment]
+1

**Comment by AkselsLedins** [comment]
+1

**Comment by dxacaniest** [comment]
+1

**Comment by ljcharles** [comment]
+1

**Comment by Luckino** [comment]
&#x2640; -> Female
&#x2642; -> Male
&#9890; -> Female Homosexuality
&#9891; -> Male Homosexuality
&#9892; -> Heterosexuality
&#9895; -> Transgender

**Comment by EricMartori** [comment]
+1

**Comment by jagomf** [comment]
+1 on gender (widely used in forms)

**Comment by powderham** [comment]
The icons have already been created too in the 'wc' icon..

**Comment by jagomf** [comment]
@powderham cool, so we just need to split it for 2 new icons.

**Comment by fspixelschubser** [comment]
+1 :)

**Comment by PhilippS93** [comment]
+1

**Comment by MichaelJLSchmidt** [comment]
+1

**Comment by DarkSouL11** [comment]
+1

**Comment by MrSong0607** [comment]
+1

**Comment by chlegou** [comment]
+1000 really useful

**Comment by SebasG22** [comment]
+1

**Comment by wesflo** [comment]
+1

**Comment by kingeight** [comment]
+1

**Comment by Raithfall** [comment]
This is a super basic request, and still needed and asked for 3 years now, WTF?

**Comment by AndroidNils** [comment]
+1

**Comment by flocsy** [comment]
+1

**Comment by mylogicniche** [comment]
+1

**Comment by FilipeOS** [comment]
Since 2015 this is still a request... lol

**Comment by tsirolnik** [comment]
2019 Represent

**Comment by shashank0708** [comment]
2019 30 August Still not available.

**Comment by grabillo** [comment]
Sep 2019 and still waiting

**Comment by brightest-dazes** [comment]
+1

**Comment by luclemo** [comment]
Designing a medical research app— this is pretty vital!
+1

**Comment by MTakashiMori** [comment]
+1

**Comment by quarhodron** [comment]
+1

**Comment by iamakhilashok** [comment]
+1

**Comment by ngtantai1001** [comment]
+1

**Comment by davehowson** [comment]
Almost 2020 and this is still not implemented!!

**Comment by brightest-dazes** [comment]
What can I do to help?

**Comment by brightest-dazes** [comment]
This is much needec

**Comment by gnujoow** [comment]
+1

**Comment by piyushdolar** [comment]
+1
20-01-2020 02:25PM Indochina time and still waiting for this icon by I suggest all of you to the move to font awesome icon it's far better than material icon.

**Comment by remusmp** [comment]
One way to get male/female icon is to clip the wc icon:

```
<mat-icon style="clip-path: inset(0% 50% 0% 0%);">wc</mat-icon> <!-- Male -->
<mat-icon style="clip-path: inset(0% 0% 0% 50%);">wc</mat-icon> <!-- Female -->
```

**Comment by Zenoo** [comment]
How is this still not implemented in 2020 ?

**Comment by travisjayday** [comment]
How has this been open for so long? Could it be @google-admin doesn't want to deal with adding 200 new icons to be PC and represent all genders... :-/

**Comment by piyushtnk** [comment]
Easy use font awesome.

[Male]
https://fontawesome.com/icons/male?style=solid

[Female]
https://fontawesome.com/icons/female?style=solid

[Transgender]
https://fontawesome.com/icons/transgender?style=solid

**Comment by xTumulus** [comment]
+1 

I love material icons, but instead am using font awesome. I really would like to use material icons for this.

As stated by others, it would be simple, you can be inclusive with male, female, and trans-gender icons, and it has been requested for YEARS. At the very least comment on the request and say it will never happen.

**Comment by onyxolu** [comment]
2021 and this is still pending?

**Comment by RoelN** [comment]
Icons for the original issue are in the current icon set:

<img width="275" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108853836-78d43380-75e7-11eb-9107-c4bc6ec840f6.png">

An issue for person icons, as requested later in this thread, can be found here: https://github.com/google/material-design-icons/issues/313

**Comment by idc77** [comment]
There is "transgender" but there is no icon for "disgendered"

**Comment by loolooii** [comment]
We need a non-binary icon as well. 
https://icon-sets.iconify.design/mdi/gender-non-binary/

**Comment by tphinney** [comment]
Please stop piling on to this closed issue about a specific request that was delivered two years ago.  :)

We delivered an agender icon in 2022, which I think covers “disgendered” #1322

I have created a new issue for a nonbinary icon #1446

**Comment by loolooii** [comment]
@tphinney Thanks for your response. I have seen that one, but apparently that's a material "symbol" and not an "icon"? For example, `agender` is not available in Flutter. See here: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.query=agender 
Sorry, if this is not the right place to discuss this.

**Comment by tphinney** [comment]
Please discuss in #1322 or #1446 as linked here and above.
