### ISSUE TITLE
Icon request: QR-Code Scanner

### ISSUE THREAD

**Issue by aleigood** [google/material-design-icons#244]
Sometimes you need to scan QR-Code by phone, it's very useful, thanks!

**Comment by adarshv90** [comment]
In the same vain, I'd like to raise a request for barcode & barcode scanner. The bellow examples from Austin Andrews & Cody from https://materialdesignicons.com/ are good starting points
![barcode](https://cloud.githubusercontent.com/assets/16303747/11808704/192baad4-a348-11e5-98bc-713ffb336ea9.png)
![barcode-scan](https://cloud.githubusercontent.com/assets/16303747/11808705/19302eba-a348-11e5-98af-efba2ddd438d.png)

**Comment by patatjenl** [comment]
This was aleady requested:
#7

**Comment by bpappin** [comment]
+1

**Comment by Temirtator** [comment]
on "react-native-vector-icons": "^6.6.0" barcode scan icon for some reason doesnt work.

**Comment by tphinney** [comment]
I just wanted to let people know 1D (linear) /barcode and /barcode_scanner icons have been approved for me to add them to Material Symbols. I will be adding them on the source side today. I know it has been a long wait! Thanks for your patience.
