### ISSUE TITLE
Icon request: polygon / polyline

### ISSUE THREAD

**Issue by Dahkon** [google/material-design-icons#245]
Polygon and polyline icons would be usefull for maps drawing.
Thanks,

**Comment by marcoiai** [comment]
I agree, it wold be very useful!

**Comment by smeijer** [comment]
I'm using this one now :)

https://materialdesignicons.com/icon/shape-polygon-plus

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
