### ISSUE TITLE
Bower installs not the latest version

### ISSUE THREAD

**Issue by dresslerit** [google/material-design-icons#247]
Hi, if you type in your terminal >>bower install material-design-icons<< bower fetches the following url >>https://github.com/google/material-design-icons/archive/2.0.0.tar.gz<< and not >>https://github.com/google/material-design-icons/archive/2.1.tar.gz<<. Maybe bower likes only 3 point version numbers? I hope you can fix that.

PS. I deletet also the complete cache via >>bower cache clean<<

Greetings Noah

**Comment by jb29** [comment]
+1, I can't update, too. 
Bower Docs says:
> Your package should use [semver](http://semver.org/) Git tags. The v prefix is allowed.


@dresslerit if you immediately need the new icons, you can install them with
`bower install material-design-icons#master --save`

**Comment by shyndman** [comment]
Just cut a 2.1.1 release. Give it a shot.
