### ISSUE TITLE
Chrome on Android fails to load bootstrap-style CSS

### ISSUE THREAD

**Issue by IvanSanchez** [google/material-design-icons#248]
I'm trying to use the CDN-hosted CSS file to enable MDI icons on a webapp.

It works fine in all browsers except Chrome on Android. When using the following line in my HTML...
```html
<link href="https://cdn.materialdesignicons.com/1.3.41/css/materialdesignicons.min.css" rel="stylesheet" type="text/css"/>
```
... the Chrome inspector shows up a `net::ERR_INSECURE_RESPONSE` error in the console.

There is a live demo at https://ivansanchez.github.io/Leaflet.Icon.Glyph/demo.html

**Comment by shyndman** [comment]
Hey @IvanSanchez,

That's not our CSS. :) Here's [the repo you're looking for](https://github.com/Templarian/MaterialDesign).
