### ISSUE TITLE
Developer Guide suggests invalid css.

### ISSUE THREAD

**Issue by ericgundrum** [google/material-design-icons#249]
In the [developer guide](http://google.github.io/material-design-icons/) section on _Styling icons in material design_, the guide includes a code block containing suggested CSS of the form
```
// Rules for sizing the icon.
.material-icons.md-18 { font-size: 18px; }
.material-icons.md-24 { font-size: 24px; }
```
The code comments in this CSS are invalid syntax. (See [section 4.1.9 of the spec](http://www.w3.org/TR/CSS2/syndata.html#comments).) A reader who naively pastes this suggested CSS into their site may become frustrated at not understanding why the CSS rules are ignored.

This problem is solved by changing the comments to the form
```
/* Rules for sizing the icon. */
.material-icons.md-18 { font-size: 18px; }
.material-icons.md-24 { font-size: 24px; }
```

**Comment by sryzycki** [comment]
Seems to be fixed now: http://google.github.io/material-design-icons/#styling-icons-in-material-design
