### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by EugeneHoran** [google/material-design-icons#253]
Login and Logout Icons. Looking to add a footer to the nav drawer with a login and logout option. Currently only using text and it looks awkward without an icon. Thanks for all of the updates, really makes our lives easier.

**Comment by CoDEmanX** [comment]
You may be interested in this icon:
https://materialdesignicons.com/icon/fax

**Comment by EugeneHoran** [comment]
Thanks for the link.

**Comment by LinkDinkin** [comment]
+1 (similar request in #250).

**Comment by adarshv90** [comment]
+1

**Comment by RoelN** [comment]
<img width="248" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108844340-47a23600-75dc-11eb-827b-3e979014354c.png">

They have been added in the meantime! \o/
