### ISSUE TITLE
Icons request: note

### ISSUE THREAD

**Issue by sabinebarrera** [google/material-design-icons#254]
You currently provide an ic_note_add:
![ic_note_add_black_48dp](https://cloud.githubusercontent.com/assets/1494577/11487176/4866b2ee-9772-11e5-858d-535404e648a1.png)

A note icon will be helpful when you just need to show in a **tile** that a particular entry has a note:
![ic_note_black_48dp](https://cloud.githubusercontent.com/assets/1494577/11487261/b7dd3350-9772-11e5-978a-ce588d9e1795.png)

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
