### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by anakin59490** [google/material-design-icons#256]
Hi,
can i use the icons in order to "decorate" a commercial software ?

License said : "The only thing we ask is that you not re-sell the icons themselves."

but CC 4.0 said : "Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use."

But i don't have "about section"  because it's a software, not a public web site.... 

Thank you in advance

**Comment by jestelle** [comment]
We've seen many apps using our icons provide a link to the license and attribution in some 'about' item in a settings menu or the like.

Something like that is fine with us.

**Comment by anakin59490** [comment]
OK, thank you
