### ISSUE TITLE
RSS icon request

### ISSUE THREAD

**Issue by toby3d** [google/material-design-icons#257]
Please add RSS icons for blogs-feeds, and other.

**Comment by jestelle** [comment]
Unfortunately most social icons we cannot provide due to the guidelines from the trademark holders.  In Issue #166 I point at where you can get assets for some of those.

I'll leave this open as a request for an RSS icon.

**Comment by RSSCOM** [comment]
The RSS icon is not trademarked and is free to use. It was created by Mozilla and given up by them for fair use.
