### ISSUE TITLE
Telefax icon request

### ISSUE THREAD

**Issue by janstieler** [google/material-design-icons#258]
Hi,
yesterday I added some contact information to an contactwebsite also with telefax.
But I to see there was no appropriate icon for it. 
I would recommended that also a icon for telefax will be deploy.
I know its a outdated technology but some one us it also in our times.

Cheers

**Comment by CoDEmanX** [comment]
You may be interested in this icon:
https://materialdesignicons.com/icon/fax

**Comment by DemigodCode** [comment]
Any chance to get that into the font?

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
