### ISSUE TITLE
give warning if injectTapEventPlugin() not called -> items not interacting with mouse

### ISSUE THREAD

**Issue by flyon** [google/material-design-icons#259]
Hey, just wondering if it would be possible to give a console warning if you didn't call injectTapEventPlugin.

I just started a new project and forgot to do that, and at some point discovered that nothing responded to my mouse input. (perhaps because my laptop also supports touch?)
Took me a while to figure out this was the missing part.

**Comment by shyndman** [comment]
Is this issue intended for the material-design-icons project? 

I'm closing this as unrelated, but feel free to reply if I'm mistaken.

**Comment by flyon** [comment]
sorry, yes wrong project
