### ISSUE TITLE
Simpler SVG Icon Names

### ISSUE THREAD

**Issue by CxRes** [google/material-design-icons#262]
Currently icons names in svg-sprites are of the format `ic_<name>_<size>px`, which become unwieldy when using dynamic names. Could this be simplified please, such as by dropping `ic_`. (Just one possible suggestion, any other ideas are welcome)

My motivation for this request is as follows. Say I am want to apply left for some reason when doing some dynamic templating (I am using angular & angular-material): I am required to convert some semantically derived name in my app like `navigation:left_arrow` to `navigation:ic_left_arrow_24px` which is a non-trivial (and avoidable) string manipulation.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, including filenames, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
