### ISSUE TITLE
Icon Request: Money

### ISSUE THREAD

**Issue by damonbauer** [google/material-design-icons#263]
I have a use case where I'd like to use an icon representing money.

Other tags could be "cash" or "dollar".

**Comment by MGaetan89** [comment]
What about https://www.google.com/design/icons/#ic_attach_money?

![ic_attach_money](https://raw.githubusercontent.com/google/material-design-icons/master/editor/drawable-xxxhdpi/ic_attach_money_black_48dp.png)

**Comment by adarshv90** [comment]
Something a bit more global would be appreciated. I seem to remember the below icon being used in google maps. An update for the icon font with it would be great.
![cash-100](https://cloud.githubusercontent.com/assets/16303747/11808612/75c47164-a347-11e5-9918-68779bd29a1d.png)

**Comment by damonbauer** [comment]
@MGaetan89, I was thinking something along the lines of what @adarshv90 posted.

**Comment by jsep** [comment]
+1

**Comment by amit1911** [comment]
+1

**Comment by HIRANO-Satoshi** [comment]
+1 Global one is needed.

**Comment by thinko** [comment]
a few icons in the money/finance family would make sense and be well used, I'd really like an icon to represent gratuity/tips... a hand with a dollar sign, coins, etc?

**Comment by lmenus** [comment]
Yup, still needed.

**Comment by GianPaoloBuffo** [comment]
+1

**Comment by Dylan-Buth** [comment]
+1

**Comment by sainture** [comment]
can we use attach_money icon instead of dollar?

**Comment by jpsantos7** [comment]
+1

**Comment by JeanAraujo** [comment]
+1

**Comment by Nodirbek3d** [comment]
please add finance industry related icons
