### ISSUE TITLE
Icon Request: Person search

### ISSUE THREAD

**Issue by Anubis88** [google/material-design-icons#269]
I'd like to request an icon for **searching for a user** or **person search** to distinguish it from the default search icon.
I needed one and had to draw it myself, feel free to use it if you need:

![ic_person_search_black_24dp](http://saved.im/mty4ndcyz3b5/ic_person_search_white_24dp.png)

Thanks.

**Comment by RoelN** [comment]
Thanks for sharing!

The set now includes this one:

<img width="196" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108845811-28a4a380-75de-11eb-9587-6f4dea753ecb.png">
