### ISSUE TITLE
Icon request: Eraser

### ISSUE THREAD

**Issue by adarshv90** [google/material-design-icons#270]
Please consider making an eraser icon. The bellow icon from Austin Andrew from https://materialdesignicons.com/ might be a good starting point
![eraser](https://cloud.githubusercontent.com/assets/16303747/11808266/6a27e112-a345-11e5-9256-0c93cdb8e1f8.png)

**Comment by alejost848** [comment]
+1

**Comment by camden-kid** [comment]
Agreed. Very surprised its not included.

**Comment by as00paf** [comment]
+1

**Comment by sebakerckhof** [comment]
+1

**Comment by Vorax** [comment]
Do the developers actually listen to our requests?

**Comment by andrewrabon** [comment]
+1

**Comment by romildojpaiter** [comment]
+1

**Comment by abalta** [comment]
+1

**Comment by sandorvasas** [comment]
+10000000000

**Comment by TypicalDarkness** [comment]
+1

**Comment by AleFons** [comment]
+1

**Comment by elharony** [comment]
Since 2015? :joy:
There's no change yet. I managed to use `clear` or `forever_delete` instead, but still, it's necessary to get the Eraser icon!

**Comment by ruskakimov** [comment]
+1
there is `brush`, `colorize`, but no `eraser` 😞

**Comment by mathaou** [comment]
Man, would really be nice to have an icon that indicates that I'm clearing information but not deleting the item.

**Comment by JakobJK** [comment]
I can't believe it has been more than five years and one still hasn't been added. :(

**Comment by jttuboi** [comment]
Whyyyy takes so longggg, ehehe. This is very useful for draw apps or similar. I really appreciate if they add this icon.

**Comment by supertiger1234** [comment]
:( i want my eraser

**Comment by ebarooni** [comment]
+1
So surprising that an eraser is not there!

**Comment by mypelz** [comment]
We neeeeeed an eraser!!!

**Comment by supertiger1234** [comment]
Yaaa

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by mypelz** [comment]
when will it be deployed, currently its not yet available?

**Comment by blindway** [comment]
@jalpadoshi wasn't it released yet?

**Comment by supertiger1234** [comment]
![Screenshot_2022-02-04-16-17-38-642_com android chrome](https://user-images.githubusercontent.com/8193841/152564061-b4988475-aff5-4fa9-980c-141a54f274fc.jpg)
Reopen..

**Comment by pulli23** [comment]
It seems this icon is not available, can this be reopened?

**Comment by tphinney** [comment]
Yes, something is off here. There exists a related icon in the Google-internal-only version of the font, but not in the public Material Symbols. This seems like an error.

**Comment by tphinney** [comment]
Actually, ink_eraser and ink_eraser_off are already on a list I assembled last year of formerly-proprietary icons that we are now empowered to make non-proprietary. They do still need their round and sharp variants made, however, else it would have been a simple toggle.

Unfortunately, we have quite a bit of higher-priority work ahead of this, so I expect any movement on this is likely at least a couple of months away right now. So, don’t hold your breath, but it is on the list.

**Comment by ssobob** [comment]
We need it. go go go :)

**Comment by loolooii** [comment]
Any idea when this will be available?

**Comment by tphinney** [comment]
This is continuing to inch toward the top of the to-do list. More urgent things are still in the way, but not all that many of them any more. This particular icon is at the top of the list of formerly-proprietary icons to make public!

**Comment by tphinney** [comment]
The design work and font production has been done, I imagine it will most likely be available some time this month.
The glyph names will be ink_eraser and ink_eraser_off

**Comment by Keerthan-HS** [comment]
Hi team, 

Can you please add the same icon for @mui/material-icon too.

**Comment by tphinney** [comment]
MUI is a separate and independent company. They rely on Material Icons, our older and less actively developed icon set.

**Comment by tphinney** [comment]
This is public now! Note that it is only in the Material Symbols set, not Material Icons.
https://fonts.google.com/icons?icon.query=eraser&icon.set=Material+Symbols

**Comment by elharony** [comment]
@tphinney Finally! Thanks a lot!! 👍😊

**Comment by tphinney** [comment]
“The mills of the gods grind slowly, but they grind fine.”

**Comment by ocarvente** [comment]
I want an eraser please.

**Comment by tphinney** [comment]
@ocarvente See above.

**Comment by CarlosEduR** [comment]
> I want an eraser please.

https://fonts.google.com/icons?icon.query=eraser

**Comment by BTGRCohen** [comment]
Please add an eraser to the base :(

**Comment by mploscar** [comment]
Can we get an eraser icon, please? :(

**Comment by tphinney** [comment]
https://fonts.google.com/icons?icon.query=eraser
It was added a year ago

**Comment by BTGRCohen** [comment]
> https://fonts.google.com/icons?icon.query=eraser It was added a year ago

But what about in here?
https://mui.com/material-ui/material-icons/

**Comment by CarlosEduR** [comment]
> > https://fonts.google.com/icons?icon.query=eraser It was added a year ago
> 
> But what about in here? https://mui.com/material-ui/material-icons/

@BTGRCohen you need to check this with them, here is their repository: https://github.com/mui/material-ui
