### ISSUE TITLE
Icon request: directions tram

### ISSUE THREAD

**Issue by rcknr** [google/material-design-icons#271]
Please add an icon for trams.
The one from Maps will do.
Thank you!

![Tram icon](https://maps.gstatic.com/mapfiles/transit/iw2/6/tram.png)

**Comment by shyndman** [comment]
https://design.google.com/icons/#ic_directions_transit

Does this work?

**Comment by rcknr** [comment]
Nope, because it's the same as subway icon.

**Comment by adarshv90** [comment]
+1

**Comment by RoelN** [comment]
<img width="169" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108845871-3eb26400-75de-11eb-8950-dbad1e24456a.png">

It's here!
