### ISSUE TITLE
ic_format_list_bulleted broken? (3rd circle smaller than the other two)

### ISSUE THREAD

**Issue by CoDEmanX** [google/material-design-icons#272]
![ic_format_list_bulleted](https://raw.githubusercontent.com/google/material-design-icons/master/editor/1x_web/ic_format_list_bulleted_black_24dp.png)

![ic_format_list_bulleted](https://raw.githubusercontent.com/google/material-design-icons/master/editor/2x_web/ic_format_list_bulleted_black_48dp.png)

**Comment by shyndman** [comment]
You are correct. I'm reporting this to our designers.

**Comment by shyndman** [comment]
We've got this fixed up internally. It will be seen in the next release.

**Comment by CoDEmanX** [comment]
It shipped, thanks!
