### ISSUE TITLE
Why are there not any github icons available in this?

### ISSUE THREAD

**Issue by abdulhannanali** [google/material-design-icons#278]
please can anyone make available github icons for star, fork and watch. also some social icons would be appreciated. :)

**Comment by shyndman** [comment]
How are these?
star: favorite, favorite_border
fork: call_split
watch: visibility, visibility_off

**Comment by abdulhannanali** [comment]
@shyndman thank you! 
this is clever! :smile:

**Comment by shyndman** [comment]
you're welcome :)
