### ISSUE TITLE
SVG Sprites have fill attributes specified

### ISSUE THREAD

**Issue by gmdavisux** [google/material-design-icons#281]
A few of the material-design sprites have a fill attribute specified which makes them unable to inherit fill color from css. This does not seem intentional. 

To verify this, use css to style the svg element
svg{    fill: currentColor; color: aliceblue; }

You will notice most svg elements as alice blue but some svg elements are black.  

The icons needed to be fixed:
svg-sprite-action-symbol.svg&i=ic_all_out_24px
svg-sprite-action-symbol.svg&i=ic_play_for_work_24px
svg-sprite-action-symbol.svg&i=ic_track_changes_24px
svg-sprite-av-symbol.svg&i=ic_art_track_24px
svg-sprite-av-symbol.svg&i=ic_fiber_manual_record_24px
svg-sprite-av-symbol.svg&i=ic_fiber_smart_record_24px
svg-sprite-av-symbol.svg&i=ic_web_asset_24px
svg-sprite-content-symbol.svg&i=ic_next_week_24px
svg-sprite-content-symbol.svg&i=ic_weekend_24px
svg-sprite-editor-symbol.svg&i=ic_strikethrough_s_24px
svg-sprite-navigation-symbol.svg&i=ic_arrow_downward_24px

**Comment by obskyr** [comment]
I'd like to add that a few of these (48px versions of fiber record icons, at least) seem to have the unnecessary `enable-background` attribute set on the SVG too, along with a very strange `viewBox` value.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
