### ISSUE TITLE
Misaligned text with flight_takeoff and flight_landing icons

### ISSUE THREAD

**Issue by jkrgr** [google/material-design-icons#285]
Text becomes heavily misaligned when using the flight icons, as shown here:

http://codepen.io/krgr/pen/OMpmVb

**Comment by shyndman** [comment]
Try using `vertical-align: bottom` on the icon. Should do the trick.

**Comment by jkrgr** [comment]
@shyndman If this isn't a bug, why doesn't `flight_landing` and `thumbs_down` behave the same?

**Comment by shyndman** [comment]
Fair point.

However, I'm going to keep this bug closed as it is difficult to fix this kind of problem without disrupting developers who have already worked around the alignment.

We'll keep this issue in mind for future icon fonts.

**Comment by jkrgr** [comment]
`vertical-align: bottom` on the icon does by the way not fix it for me. I'm in Google Chrome.

**Comment by jestelle** [comment]
FYI, the icon is "flight_land", not "flight_landing"
It may be that the "ing" is all that's throwing things off?

**Comment by jkrgr** [comment]
Indeed it was @jestelle - nice catch! Issue closed :)
