### ISSUE TITLE
#Login and #Signup icon

### ISSUE THREAD

**Issue by santoshban** [google/material-design-icons#286]
Is there any login and sign in icon in google material design icon? I am unable to find.

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <[material-design-icons] #Login and #Signup icon (#286)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by emirotin** [comment]
I'm here for +1.

This is an awesome project, thanks for making it free and OS. I've found all kinds of useful icons and that's why I was surprised there's no icon for login/signup/logout (I'm using "exit to app" for the latter atm).
Thanks in advance :).

**Comment by peterpetrekanics** [comment]
+1
It would be nice to have a login icon..
Thank you!

**Comment by maiakaat** [comment]
+1

**Comment by Captain-GaDo** [comment]
+1

**Comment by adarshv90** [comment]
+1. @emirotin I'm in the exact same scenario & do the exact same thing.

**Comment by pootzko** [comment]
+1 please

**Comment by EgorrodE** [comment]
+1

**Comment by patrick-cpka** [comment]
+1

**Comment by iBizzare** [comment]
+1

**Comment by KSkobeltsynStudio** [comment]
Font awesome is nice, but +1

**Comment by tarlepp** [comment]
+1

**Comment by Jimmy02020** [comment]
+1

**Comment by KiarashS** [comment]
+1

**Comment by luisjuniorj** [comment]
+1

**Comment by alexbyk** [comment]
+1

**Comment by CastixGitHub** [comment]
+1

**Comment by ColinFrapper** [comment]
+1

**Comment by Trodrige** [comment]
+1

**Comment by Frenchisman** [comment]
+1

**Comment by chittolina** [comment]
+1

**Comment by HenintsoaAdri** [comment]
+1

**Comment by littledumb** [comment]
+1

**Comment by awesomeful** [comment]
+1

**Comment by gabixdev** [comment]
+1

**Comment by pedro-lucas** [comment]
+1

**Comment by AbdallahBedir** [comment]
+1

**Comment by AbuMecom** [comment]
+1

**Comment by sabinebarrera** [comment]
*Icon request: sign in / sign out* #250

**Comment by ddyrcz** [comment]
+1

**Comment by Jakevin** [comment]
+1 ！！

**Comment by mishengchao** [comment]
+1

**Comment by brcinho** [comment]
+1

**Comment by rajabilal555** [comment]
+1

**Comment by ukyawsoe** [comment]
Nice.i like

**Comment by phamtuananh791994** [comment]
+1

**Comment by kn1ght99** [comment]
+1

**Comment by KG32** [comment]
+1

**Comment by szudi** [comment]
+2

**Comment by wincinderith** [comment]
+3

**Comment by KSingh1980** [comment]
+1

**Comment by andela-jomadoye** [comment]
+1

**Comment by massi08** [comment]
+1

**Comment by egeste** [comment]
+1

**Comment by milletf1** [comment]
+1

**Comment by mrdivyansh** [comment]
+1

**Comment by picklepilot** [comment]
+1

**Comment by narensgh** [comment]
+1

**Comment by spyhole** [comment]
+1

**Comment by sparsh** [comment]
+1

**Comment by heinunez** [comment]
+1

**Comment by kmsheng** [comment]
+1 plzzzzz

**Comment by dilonne** [comment]
+1

**Comment by bleuscyther** [comment]
Ionic : https://ionicframework.com/docs/ionicons/

Has a great proposition, just search for log-in

**Comment by Alexandru-Cambose** [comment]
+1

**Comment by oodgaard** [comment]
+1

**Comment by rzmogrovejo** [comment]
+1 lml

**Comment by dshamim** [comment]
+1 - how long does it take for google to implement basic icons ? there are requests that are open over 2 years old for basic things like logout

**Comment by barrymichaeldoyle** [comment]
+1

**Comment by bangive** [comment]
+1

**Comment by penrique** [comment]
+1

**Comment by vegarda** [comment]
+1

Need atleast something like exit_to_app with arrow pointing outwards

**Comment by juzraai** [comment]
+1

**Comment by rupakrockthecse100** [comment]
+1

**Comment by gabixdev** [comment]
Lol, just do it instead of `+1`-ing -_-

**Comment by VitaliyDemchuk** [comment]
+1

**Comment by azfartommy** [comment]
+1

**Comment by alex2005git** [comment]
+1

**Comment by bsided** [comment]
+1

**Comment by Deon588** [comment]
+1

**Comment by Iworb** [comment]
+1

**Comment by mrocabado** [comment]
+1

**Comment by sazedulhaque** [comment]
+1

**Comment by JairAviles** [comment]
+1

**Comment by dantrevino** [comment]
yes, please +1

**Comment by MoreKoo** [comment]
+1

**Comment by ticquique** [comment]
+1

**Comment by zhin2929** [comment]
+1

**Comment by ltwesley** [comment]
+1

**Comment by KevinStarWars** [comment]
+1

**Comment by napolar** [comment]
+1

**Comment by hansegucker** [comment]
+1

**Comment by montijr2007** [comment]
+1 

Where is the priority on this one?

**Comment by Betazoid** [comment]
+1

**Comment by gauravkukreja06** [comment]
+1

**Comment by Betazoid** [comment]
./signed
+1

**Comment by Springrbua** [comment]
Maybe [input](https://material.io/icons/#ic_input) could be used, looks very similar to Ionicons log-in icon on iOS.
Search for "log-in" on https://ionicframework.com/docs/ionicons/

**Comment by rbeer** [comment]
@dshamim 
Let me hijack the issue and its popularity to make this often overlooked fact about OpenSource:
It is **not** about "I request, you implement". Google doesn't have to to and surely never will implement something just because people ask for it. They create what they need and make it publicly available. That's it. People opening their code and works for others to use and improve upon does **not** come with any liability to act upon user's requests, nor should anyone held morally responsible for not doing it.

Please be aware of this often seen fallacy.

**Comment by dshamim** [comment]
@rbeer thats true , I guess we have veen spolied by actively maintained projects - which was kind of an assumption here

**Comment by wagnerperin** [comment]
+1

**Comment by Baneeishaque** [comment]
Agree with @rbeer , i think some designers will took the challenge.

**Comment by SeFeX** [comment]
+1

**Comment by Filip1986** [comment]
+1

**Comment by nickykiet83** [comment]
+1

**Comment by freddyamsterdam** [comment]
+1

**Comment by TyreseW** [comment]
+1

**Comment by Montesdodgers13** [comment]
Raidersvalle@aol.com

**Comment by rfrancois** [comment]
+1

**Comment by alexlevin81** [comment]
+100! actually I see no reason to use material design - it has nearly NO real-world needed icons

**Comment by PaulVCS** [comment]
+1

**Comment by andikangabriel** [comment]
+1

**Comment by adamgen** [comment]
+1

**Comment by bigzhu** [comment]
+1

**Comment by prodigeris** [comment]
Pls

**Comment by arikanorh** [comment]
+1

**Comment by rbeer** [comment]
You know guys, don't get me wrong; but this +1 thing is a really destructive habit.
All you are achieving with it is people unsubscribing from it, so they won't be notified if something of actual interest happens.
Even more importantly, who do you think gets annoyed by it first? That's right, the maintainers. You can give a thumbs up on the initial message and show that you have an interest in it.

I don't really care, so don't get any fantasies about me being mad. You are just not helping anyone. Not even yourselves.

Guess what I'm gonna do now...

**Comment by tarlepp** [comment]
@rbeer hmm, so is there a better way to complish this then?

**Comment by Springrbua** [comment]
@tarlepp as @rbeer said, you can upvote the issue.
Also, there is an alternative icon, which I am using at the moment (input). It looks similar to ionicons iOS icon for login.
Also, as @rbeer said earlier, this project is open source, so anyone could create a pull request for this icon.

**Comment by abinashmohanty** [comment]
Can't believe this request is still running more than 2 years, and Google is not even resolving this issue. I can see the logout icon on its own YouTube app. I wonder why they have still not included as part of their system icons. What's wrong in that!

**Comment by andreixk** [comment]
+1

**Comment by Alicote** [comment]
+1

**Comment by cdknight** [comment]
+1

**Comment by seanmavley** [comment]
**You can use these material icons in place of the sign up, logout and login**

So it's obvious they ain't adding the icon for login and sign up specifically any time soon. I know, it's not uncommon for big companies to just neglect a trivial, wont-take-24-hours-to-implement feature, just for the fun of it.

But until it gets added, here's what I use to represent Sign up, Login and Logout. That's my solution and workaround. Not perfect, but gets the job done, and I think my users do understand them enough. In any case, I add the `title="..."` attributes, so as last resort, users can hover to read what I *mean* by the icon.

**Sign up:** account_circle (https://material.io/tools/icons/?icon=account_circle&style=baseline): This is an account icon, which is good and close enough.

**Sign up**: person_add (https://material.io/tools/icons/?icon=person_add&style=baseline): This is also good and close enough. Just pick one that you like

**Login**: exit_to_app (https://material.io/tools/icons/?icon=exit_to_app&style=baseline): The exit to app looks like entering a box

**Logout**: power_settings_new (https://material.io/tools/icons/?icon=power_settings_new&style=baseline): The power button is an iconic button for turning things off/logging out of something. Think of the computer power button.

ps: If you think 2 years is long for something as trivial as this to be added, consider this from Bitbucket: https://bitbucket.org/site/master/issues/8586/support-task-lists-in-markdown-bb-9699

**Comment by prodigeris** [comment]
@seanmavley The technology just isn't there yet :)

**Comment by jamiejackherer** [comment]
There are about 100 people requesting these icons - that includes me - but I reckon Google have bigger and better things to be doing than to divert the attentions of a designer to just two icons. On teh flip side I do think they should be included...

**Comment by kgish** [comment]
+1

**Comment by Montesdodgers13** [comment]
Closed

**Comment by philfleck** [comment]
+1

**Comment by talkor** [comment]
+1

**Comment by CurityBoss** [comment]
+1

**Comment by georgebutler** [comment]
Wanting to switch away from font-awesome, it would be great if these icons were added!

**Comment by AlexPravdin** [comment]
Two and half yearf and still not icons for the basic website action??

**Comment by ctilley83** [comment]
+50

**Comment by rosnaib11** [comment]
+100

**Comment by AlexPravdin** [comment]
What I've learded from this issue - just use FontAwesone icons and don't even try to use any google's icon set. Because Google is acting like Microsoft - they know better what you need and just ignore any feedback.

**Comment by NodeSwapCeo** [comment]
> What I've learded from this issue - just use FontAwesone icons and don't even try to use any google's icon set. Because Google is acting like Microsoft - they know better what you need and just ignore any feedback.

I could not agree more ...

**Comment by Pushplaybang** [comment]
3y. wow.

**Comment by satishkumary80** [comment]
All icons found except login and logout..

**Comment by NodeSwapCeo** [comment]
Looking forward to see where is the % icon ...

**Comment by swdevbali** [comment]
Well, I use account_circle and person_add for this, as @seanmavley  suggested. Good enough

**Comment by TheOneWayTruth** [comment]
+1

**Comment by prodigeris** [comment]
This thread haunts me.

**Comment by diosney** [comment]
For anyone that stumble upon this, just use http://materialdesignicons.com/ or https://jossef.github.io/material-design-icons-iconfont/

**Comment by Lagicrus** [comment]
> For anyone that stumble upon this, just use http://materialdesignicons.com/ or https://jossef.github.io/material-design-icons-iconfont/

I would disagree as this is based around the Google material icons,  not community-based ones.

**Comment by diosney** [comment]
@Lagicrus Of course, that is your decision and I'm ok with that, but it is always good to have options to solve an issue in our profession, mainly an issue still unsolved from 2016.

**Comment by Lagicrus** [comment]
> @Lagicrus Of course, that is your decision and I'm ok with that, but it is always good to have options to solve an issue in our profession, mainly an issue still unsolved from 2016.

True I guess, something is better than nothing

**Comment by simonziegler** [comment]
+1

**Comment by Lagicrus** [comment]
I love how this thread continues to haunt so many of us
Here is hoping this gathering of ghosts at some point attracts the right people to actually implement this

**Comment by oleersoy** [comment]
Would be nice to now have to rely on FontAwesome for social login buttons.

**Comment by alexandrerosa56** [comment]
+1

**Comment by rigogsilva** [comment]
+1

**Comment by komnatadeveloper** [comment]
+1 :)

**Comment by sobolvb** [comment]
+1

**Comment by gyleg5** [comment]
+1?

**Comment by jefffortune** [comment]
+1

**Comment by michaelhodgins** [comment]
+1

**Comment by alexcambose** [comment]
This thread is like 4 years old

**Comment by vrapalis** [comment]
+1

**Comment by gianpierini** [comment]
+1

**Comment by sergiobogatsky** [comment]
+1

**Comment by rbeer** [comment]
There is going to be a big reveal with Apple like ceremony, when this issue hits 25 years.
We will have a login icon, guys! NEVER GIVE UP HOPE! :rofl:

**Comment by Daeamon** [comment]
+1

**Comment by surajmandalcell** [comment]
+1 Never say never I guess.

**Comment by elihugi89** [comment]
+1 ?

**Comment by Nortriptyline** [comment]
+1
The neverending issue. :roll_eyes:

**Comment by jefffortune** [comment]
This has to be a good inside joke by now when they see this with a +1 :)

**Comment by coreConvention** [comment]
> 
> 
> This has to be a good inside joke by now when they see this with a +1 :)

+1 XD

**Comment by rbeer** [comment]
> It does seem incredibly odd that they just left by far the most used icon out of this by default.

It's really not. Google wants your data. Google needs you to stay logged in. Always.

**Comment by biganth** [comment]
+1

**Comment by mortezaalizadeh** [comment]
+1

**Comment by DEMndz5** [comment]
+1

**Comment by medy36** [comment]
+++++++++++++++1

**Comment by dariomarciano** [comment]
+1

**Comment by Yori1** [comment]
+1

**Comment by Aryx0** [comment]
+1

**Comment by m00nyONE** [comment]
+1

**Comment by maxwell8888** [comment]
+1

**Comment by davidhin** [comment]
+1

**Comment by equillia** [comment]
+1

**Comment by kristic0** [comment]
+1

**Comment by niklissad** [comment]
+1

**Comment by hearmeroar** [comment]
+1

**Comment by reloadlife** [comment]
+1

**Comment by SirJosh3917** [comment]
*slaps roof of issue* this bad boy can fit so many +1s

**Comment by ilyago** [comment]
+1

**Comment by paulogenargue** [comment]
+1!

**Comment by rbeer** [comment]
If everyone that has "+1" this issue had painted just one single pixel on a canvas and passed it on to the next one, the icon would be half-way done by now.

**Comment by jldaggs88** [comment]
+1

**Comment by Aryqs-Ipsum** [comment]
Icons exists but isn't repertoried on the documentation (only login icon now)

```html
<i class="material-icons">login</i>
<i class="material-icons">logout</i>
```

**Comment by vellebelle** [comment]
+1

**Comment by Enethion** [comment]
+1

At this point I'm not even sure if I'm here for the first time...

**Comment by athilams** [comment]
Well, as I can see, I'm not the only one who expected to find these. +1

**Comment by RobSchilderr** [comment]
Wish it was added in 2016

**Comment by simonziegler** [comment]
There's now a `login` icon. Coupled with the `lock` icon for logging out, this feels like it's done.

**Comment by mikelpr** [comment]
missing is sign up (registering)

**Comment by gedkul** [comment]
Still missing Google icon on OAuth button...

**Comment by Jewcub** [comment]
+1..... 
wtf.......

**Comment by zzossig** [comment]
I believe [Person Add] is the sign up icon

**Comment by hungnguyen1995** [comment]
what happen? why not google oauth?

**Comment by rbeer** [comment]
🎉 🥳 Happy Anniversary 🥳 🎉

6 years; they grow up so fast, don't they? 🥲

Hope you guys had relaxing holidays.

See you next year! 😄

**Comment by rbeer** [comment]
🎉 🥳 Happy Anniversary 🥳 🎉

6 years; they grow up so fast, don't they? 🥲

Hope you guys had relaxing holidays.

See you next year! 😄

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by gedkul** [comment]
> Icon available at: https://fonts.google.com/icons

Still icon not found there… just that old ugly login icon…

**Comment by TZanke** [comment]
> Icon available at: https://fonts.google.com/icons

can you please send us the names of the icons you refer to? Just closing feels a little bit _conceited_. Thank you in advance.

**Comment by jalpadoshi** [comment]
login, logout, person_add_alt
