### ISSUE TITLE
Check Icon Request

### ISSUE THREAD

**Issue by EugeneHoran** [google/material-design-icons#287]
There are money icons and card icons but I believe we are missing a check icon.  Mainly for entering your bank account.

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <[material-design-icons] Check Icon Request (#287)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by RoelN** [comment]
The assets have been updated and expanded in the meantime. Various check icons are in there, please see if they suit your needs, @EugeneHoran. If not, feel free to reopen or create a new issue explaining how you want the icon to look.
