### ISSUE TITLE
Icon Request: Inventory (storage/warehouse)

### ISSUE THREAD

**Issue by jakircevic** [google/material-design-icons#289]
I cannot find any good icon to represent inventory in a manufacturing environment.
Something along these lines would be great:

![warehouse-512 custom](https://cloud.githubusercontent.com/assets/16789697/12438748/03cd1f7e-bf6d-11e5-8711-8b27ae90757a.png)

**Comment by uxblockers** [comment]
What about this... 
![warehouse-inventory-01](https://user-images.githubusercontent.com/30440227/28579266-0fae8f90-7154-11e7-9ad0-5f0a2cd4ce23.png)

**Comment by uxblockers** [comment]
adjusted with rounded edges
<img width="24" alt="warehouse-inventory-48" src="https://user-images.githubusercontent.com/30440227/28579737-6668b418-7155-11e7-8351-f248ef0e0146.png">

**Comment by jakircevic** [comment]
Would be perfect!!

**Comment by mdtausifiqbal** [comment]
Yes I was also searching for this icon. Because in business app we need this icon.

**Comment by KingDarBoja** [comment]
Any progress or PR for submitting this icon?

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
