### ISSUE TITLE
Most new icons are not showing up on Google Design site.

### ISSUE THREAD

**Issue by jraadt** [google/material-design-icons#290]
I've tried accessing the Google Design icon site (https://design.google.com/icons/) on both Chrome and Safari.  Most of the icons with a "New" label are not showing.  Any ideas?  Thanks!
<img width="527" alt="icons" src="https://cloud.githubusercontent.com/assets/457181/12453983/2bb6b8fe-bf5b-11e5-895a-f0c1d5c2139f.png">

**Comment by shyndman** [comment]
Do you by any chance have the font installed locally?

**Comment by jraadt** [comment]
Yep and when I removed my local copy, they all showed up.  I didn't realize that would mess it up.  Thanks for the quick help!
