### ISSUE TITLE
How to handle font fetch failure?

### ISSUE THREAD

**Issue by ardok** [google/material-design-icons#291]
Hello,

I'm currently using:

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
```

My web app has some actions that can only be triggered by an icon.
I'm just afraid that if somehow it fails to fetch the font, then no action can be taken.

Hence, is there a way to set some default text or image in case of fetch failure?
Or maybe how to make the required files live in my project?

**Comment by RoelN** [comment]
Hi @ardok, I hope you have been able to work around this in the meantime, seeing this is such an old issue. If not, feel free to reopen!
