### ISSUE TITLE
gulp wiredep includes both materialdesignicons.css and materialdesignicons.min.css

### ISSUE THREAD

**Issue by super-coder** [google/material-design-icons#293]
Looking at bower.json i see  "css/materialdesignicons.css" and  "css/*"

so is this a duplication? Because i end up with two links in my index file. I had to remove "css/*" from bower.json to make it wqork like a;; other packages

**Comment by shyndman** [comment]
Hey @super-coder,

Wrong project! [Templarian/MaterialDesign-Webfont](https://github.com/Templarian/MaterialDesign-Webfont) is what you're looking for.
