### ISSUE TITLE
Reducing SVG size by up to 50%

### ISSUE THREAD

**Issue by larsenwork** [google/material-design-icons#295]
The svg icons could be optimised quite a bit with negligible visual distortion (before vs after):
![screen shot 1](https://cloud.githubusercontent.com/assets/3859425/12650420/0ffccb4c-c5e3-11e5-878a-78ba8e4a614c.png)

```
Before:  576 bytes 
After :  304 bytes
Saved :  47.2%

BEFORE
<svg fill=”#000000" height=”24" viewBox=”0 0 24 24" width=”24" xmlns=”http://www.w3.org/2000/svg">
 <path d=”M0 0h24v24H0z” fill=”none”/>
 <circle cx=”12" cy=”4" r=”2"/>
 <path d=”M19 13v-2c-1.54.02–3.09-.75–4.07–1.83l-1.29–1.43c-.17-.19-.38-.34-.61-.45-.01 0-.01-.01-.02-.01H13c-.35-.2-.75-.3–1.19-.26C10.76 7.11 10 8.04 10 9.09V15c0 1.1.9 2 2 2h5v5h2v-5.5c0–1.1-.9–2–2–2h-3v-3.45c1.29 1.07 3.25 1.94 5 1.95zm-6.17 5c-.41 1.16–1.52 2–2.83 2–1.66 0–3–1.34–3–3 0–1.31.84–2.41 2–2.83V12.1c-2.28.46–4 2.48–4 4.9 0 2.76 2.24 5 5 5 2.42 0 4.44–1.72 4.9–4h-2.07z”/>
</svg>

AFTER
<svg viewBox=”0 0 96 96">
 <circle cx=”48" cy=”16" r=”8"/>
 <path d=”M76 52c0 0–11 1–20–8l0 14l12 0c5 0 8 4 8 8l0 22l-8 0l0–20l-20 0c-5 0–8–4–8–8l0–24c0–8 10–11 15–5l5 6c7 8 16 7 16 7l0 8ZM51 72l8 0c0 0–2 16–19 16c-11 0–20–9–20–20c0–16 16–19 16–19l0 8c0 0–8 3–8 11c0 7 5 12 12 12c9 0 11–8 11–8Z”/>
</svg>
```

A little less if you want to keep the xmlns, height, width and empty path (assuming this is for toggle-able reasons). 

The distortion we be even less visible if the viewbox was e.g. 144x144.

I wrote about it here: 

https://medium.com/larsenwork-andreas-larsen/optimising-svgs-for-web-use-part-2-6711cc15df46#.43tbff9lz

**Comment by RoelN** [comment]
New versions have been optimised in the meantime, thanks!
