### ISSUE TITLE
Black box on action/ic_reorder

### ISSUE THREAD

**Issue by gigsterdeveloper** [google/material-design-icons#298]
1.  Open extension.
2.  Select action/ic_reorder
3.  Select 24 or 48 dp
4.  View black box instead of icon

**Comment by shyndman** [comment]
Hey @gigsterdeveloper,

Which extension is that?

**Comment by easycheese** [comment]
Sorry, this was posted on the wrong github repo.  Should be the Material Icon Generator, I just downloaded these files and they appear to be fine.

**Comment by shyndman** [comment]
np
