### ISSUE TITLE
Optimize PNG images

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-icons#3]
We currently auto-generate many of the icons in the repo, but our PNGs could be optimized further. We definitely plan on doing this but want to work it into our asset optimization flow at Google first.

Side: at some point, we may well open-source the tooling process around the icons or add them to this repo but our current focus is on making sure the icons provided are as polished and consumable as possible.

**Comment by ilanbiala** [comment]
+1 optimization would be great at least for the released icons. Maybe have a Travis worker build these and do the release?

**Comment by shyndman** [comment]
We've ultra optimized everything, and will continue to do so.
