### ISSUE TITLE
Request to add new icons (tire-service, car-service)

### ISSUE THREAD

**Issue by KorsaR-ZN** [google/material-design-icons#300]
Please add icons:

**1. tire-service**

> e.g.:
> ![screenshot from 2016-02-09 11 14 03](https://cloud.githubusercontent.com/assets/579410/12910757/41bea26a-cf1e-11e5-8ac4-bdf7c6a9b7e4.png)

**2. car-service**

> e.g.:
> ![screenshot from 2016-02-09 11 13 24](https://cloud.githubusercontent.com/assets/579410/12910760/4668d678-cf1e-11e5-9b88-461ce448e207.png)

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
