### ISSUE TITLE
Icon fonts: Left and right spaces?

### ISSUE THREAD

**Issue by ghost** [google/material-design-icons#306]
When using icon fonts I see there is left and right spaces for icons that doesn't fit to the artboard width which makes the icons not aligned properly with the others. 

On the each image below I compared Material Design Icons (top) with Font Awesome (bottom), as you can see Font Awesome doesn't have those spaces.

![address](https://cloud.githubusercontent.com/assets/6900209/13002262/aea7f8bc-d19f-11e5-87ae-e3fb5c625570.jpg)
![pagenavi](https://cloud.githubusercontent.com/assets/6900209/13002265/b3a8e2c2-d19f-11e5-9b90-51268072ea1c.jpg)

For now I had to modify the width of each icons and create a custom icon fonts to remove the spaces.

**Comment by RoelN** [comment]
It's unavoidable that some icons have more whitespace in their design, as they're all drawn inside a square canvas. I think your best option here is to account for this with negative margins or a CSS transform.

Hoping this addresses your issue, I'm closing this.
