### ISSUE TITLE
icon request: de-select all (or clear selection)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#307]
just as we have "select all" icon:
https://romannurik.github.io/AndroidAssetStudio/res/clipart/icons/content_select_all.svg

we should also have "de-select all" , or "clear selection".

**Comment by Kasijjuf** [comment]
Do we really need one though? "Select all" saves us having to drag two selection handles by letting us tap one button instead. Tapping once anywhere outside of a selection is a much easier way to deselect all than tapping on a specific icon.

**Comment by AndroidDeveloperLB** [comment]
I don't understand your scenario.
I was talking, for example, of a toolbar with this action item, as there is a list of items to select from. There is no ability to click outside of anything in this scenario. 
Only similar thing that might fit and be an alternative is to use ActionMode, and the "up" button there will de-select the items, but this is not always the case.

**Comment by nkoenig** [comment]
+1. I could also use a de-select all icon.

**Comment by Kasijjuf** [comment]
@AndroidDeveloperLB If you are talking about a scenario like a email application on Android, if several emails are selected, pressing the Back button acts as a deselect all button.

**Comment by AndroidDeveloperLB** [comment]
@Kasijjuf That's what I wrote later when I mentioned "ActionMode".

**Comment by AndroidDeveloperLB** [comment]
@Kasijjuf  A good example of when this icon could be useful, is something like Google-Photos, inside the list of photos, when you can select all of photos of the same date, and then de-select them.
Currently, on Google Photos, it's just a circle with V in it, but in some apps I remember I saw it as the normal select-all icon, and then the same icon yet with a line on it, for de-select-all

**Comment by programmer1935** [comment]
I am looking for such an Button too, thinking about an button nearly relative to selectall to make it obvisible for users.

**Comment by rejhgadellaa** [comment]
+1

**Comment by Naveen3Singh** [comment]
Any update on this yet?

**Comment by jalpadoshi** [comment]
This Icon is now available.

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi Seems right. Got called "Deselect".
