### ISSUE TITLE
Request to add new male/female person icons

### ISSUE THREAD

**Issue by verengi** [google/material-design-icons#313]
Hi,
it would be great if the icons could be extended with new male, female, child(e.g. male/female) and children icon.
Cheers

**Comment by BMartinos** [comment]
+1

**Comment by marfago** [comment]
+1

**Comment by martineckardt** [comment]
I'm missing the common mirror (female) and circle+speer (male)

+1

**Comment by emiliofonseca** [comment]
+1

**Comment by EricMartori** [comment]
+1

**Comment by jagomf** [comment]
+1. Anyway this is a duplicate of #242

**Comment by RoelN** [comment]
#242 was for female and male gender (sex) icons, which have been added. Keeping this issue open for the request for male/female person icons.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
