### ISSUE TITLE
No "sentiment" icons in v2.2

### ISSUE THREAD

**Issue by Vayvala** [google/material-design-icons#317]
There are new set of icons (`sentiment_neutral`, `sentiment_satisfied`, etc).
They will work if you use link:

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

But if you use `material-design-icons` npm module, these icons do not exist.
*Note: old icons work just fine*

**Comment by ludalex** [comment]
:+1:

**Comment by schorsch** [comment]
Same for me, just spent an hour on my asset pipeline trying to find an error. But the icons do not seem to exist in the https://github.com/google/material-design-icons/tree/master/iconfont files

Btw. there is are no docs on how to build the fonts. After searching the gulpfile, i figure one must use  iconjar, but i have no Macintosh computer and rather stay with linux

**Comment by shyndman** [comment]
Sorry about that. Fixed by #311
