### ISSUE TITLE
There's a "pin" icon in google Inbox that should be included in this set.

### ISSUE THREAD

**Issue by mendyismyname** [google/material-design-icons#318]
<img width="37" alt="screen shot 2016-02-19 at 12 03 04 pm" src="https://cloud.githubusercontent.com/assets/6967813/13182715/0edd96d6-d701-11e5-8856-fe5e9aededa3.png">

**Comment by kib357** [comment]
+1

**Comment by designedbyDC** [comment]
+1

**Comment by bleush38p** [comment]
Would love to see this added as well. (The icon is on [materialdesignicons.com as pin](https://materialdesignicons.com/tag/pin))

**Comment by jolenekernick** [comment]
Seriously, though. What's it gonna take to get this added?

**Comment by KevinSpangler** [comment]
I was very surprised to not find this icon included in the set as well. +1 for adding it.

**Comment by fnlctrl** [comment]
In case anyone's interested, I just drew one myself.
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9 6v1h.5v5L8 13v2h3.5v4h1v-4H16v-2l-1.5-1V7h.5V6H9z"/></svg>
```

**Comment by mkhahani** [comment]
+1

**Comment by ghdrn11** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
