### ISSUE TITLE
Continue to Checkout icon

### ISSUE THREAD

**Issue by dwBH** [google/material-design-icons#319]
We created this icon to prompt users to checkout from cart; it seemed more appropriate for this interaction than any other icon I saw on https://design.google.com/icons/ . 
Feel free to use it!

[ic_checkout_black_48px.svg.zip](https://github.com/google/material-design-icons/files/142967/ic_checkout_black_48px.svg.zip)
![ic_checkout_black_48px](https://cloud.githubusercontent.com/assets/5684146/13258286/978aa718-da20-11e5-9a16-0cc11d54d463.png)

**Comment by edxtech** [comment]
Nice!

**Comment by NodeSwapCeo** [comment]
So happy to see this icon added to the main set already!

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
