### ISSUE TITLE
Icon Request: horizontal align (left|center|right)

### ISSUE THREAD

**Issue by acicali** [google/material-design-icons#322]
There currently exists under Editor a trio of vertical alignment icons, but no such horizontal counterpart exists. The 'keyboard tab' icon under Hardware seems to mirror what 'horizontal align right' would be, but that still omits left and center.

Note: These are different than format align (left|right|center|justify) in that the format align icons are for text, but the horizontal align icons are for aligning two or more elements to each other (child/parent or siblings).

**Comment by shankar101854** [comment]
- [sdfsdsdffsf ] sdfdfsdfsffsfsdff

**Comment by RoelN** [comment]
These look be what want. If not, feel free to reopen!

<img width="1525" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108842943-51c33500-75da-11eb-9fdc-5e54241b7106.png">
