### ISSUE TITLE
UTF codepoints in text param on Google Fonts CDN

### ISSUE THREAD

**Issue by garthkerr** [google/material-design-icons#323]
Hello folks. I have tried to utilize the UTF codepoints in combination with the `text` parameter on the Google Fonts CDN documented here:

https://developers.google.com/fonts/docs/getting_started#Optimizing_Requests

Either the `text` parameter is not supported with iconography, or I am encoding the characters incorrectly. Interestingly, using the parameter **does** seem to have an effect on the payload. Here is an example using the UTF code:

```
<link href="//fonts.googleapis.com/css?family=Material+Icons&text=%EE%A2%B6" rel="stylesheet"/>
```

This does not provide the intended icon. It would be nice to be able to specify the friendly `liga` name as part of the URL: `&text=account_box,alarm_on` or the UTF code.

Am I using the incorrect encoding? Can this be documented somewhere?

**Comment by shyndman** [comment]
Hey Garth,

I've asked someone on the Fonts team to take a look for you.

**Comment by garretrieger** [comment]
Which icon are you expecting to appear with the above link? From our link it looks like you're trying to get the search icon [search icon](https://design.google.com/icons/#ic_search).  Is that correct?

I set up a quick jsbin using the link you gave: http://jsbin.com/raqomobipu/edit?html,output.  I see the search icon as expected.

**Comment by garthkerr** [comment]
@garretrieger excellent! I was converting the representation incorrectly:

https://codepoints.net/U+E8B6

I tested with multiple codes `&text=%EE%A2%B6%EE%A3%89` and it works as expected. Thank you for taking the time to look into it.

**Comment by shyndman** [comment]
Closing this off, but one more thing @garthkerr. Is there any reason you aren't using

fonts.googleapis.com/**icon**?family=Material+Icons&text=%EE%A2%B6

**Comment by garthkerr** [comment]
@shyndman I actually had not realized the distinction. I was using a single request to fetch an additional font family as well. Both seem to work. I will use the `/icon` URI now since I'll need to make a separate request using the `text` param. Thanks again for the help.
