### ISSUE TITLE
Request: add tool/plugin to show thumbnails of the vector xml files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#324]
So that we can see them even inside "explorer"/"finder" of the OS.

Seeing just an XML file is very annoying to manage.
Only opening it in Android-Studio will show how it really look like.

**Comment by AndroidDeveloperLB** [comment]
Maybe even tell github to show the content as vectorized image too.

**Comment by RoelN** [comment]
Current Finder in macOS shows previews for SVG files. Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by AndroidDeveloperLB** [comment]
@RoelN The request is for the VectorDrawable XML files, not of SVG.

BTW, for Windows OS, for SVG, you can have this:
https://github.com/tibold/svg-explorer-extension/releases

And I can't re-open this request for some reason. I don't know why.

**Comment by RoelN** [comment]
@AndroidDeveloperLB I figured you mean the SVGs. What are the VectorDrawable XML files?

**Comment by AndroidDeveloperLB** [comment]
@RoelN Check all sub-folders of the current repository, in :

https://github.com/google/material-design-icons/tree/master/android

Meaning "...res/drawable/" .

Example:

https://github.com/google/material-design-icons/tree/master/android/action/3d_rotation/materialicons/black/res/drawable

A [VectorDrawble](https://www.google.com/search?q=VectorDrawable&oq=VectorDrawable) file is a file format (XML based) that Android has instead of SVG, because SVG is a much more complex thing to support, which might not be efficient in some cases.

Conversion between the 2 formats is usually possible, but for some cases it fails (or not done nicely) because various stuff are not possible on VectorDrawable, and the opposite. 

In the past, I remember the conversion was pretty bad, choosing wrong colors. Over time it became a bit better.

**Comment by RoelN** [comment]
Gotcha. I don't think this is the right place to ask though. If you want your explorer/finder to show previews for these files, I think its best to raise an issue for that with the OS you are using. This repo is for the icons, not for tools to preview them.

**Comment by AndroidDeveloperLB** [comment]
@RoelN Where could I request it then?
