### ISSUE TITLE
Add icon for 1d (linear) barcode please

### ISSUE THREAD

**Issue by ghost** [google/material-design-icons#33]
Similar to [this request](https://github.com/google/material-design-icons/issues/7), but for 1d (linear) barcodes.

**Comment by danielhickman** [comment]
Thanks to @templarian http://materialdesignicons.com/icon/barcode

**Comment by rbardini** [comment]
:+1: for barcode and QR code icons.

**Comment by wldpaul** [comment]
+1

**Comment by geofernz** [comment]
+1 on barcode icons request!

**Comment by ericmguimaraes** [comment]
+1

**Comment by seasox** [comment]
+1

**Comment by taaeng** [comment]
+1

**Comment by leandroxbr** [comment]
+1

**Comment by essaricy** [comment]
+1

**Comment by leogouveia** [comment]
+1

**Comment by arakno** [comment]
+1

**Comment by aravinds03** [comment]
+1

**Comment by Sapta7** [comment]
yes please..

**Comment by gubi** [comment]
+1

**Comment by dynamicbalaji** [comment]
+1

**Comment by filipehb** [comment]
+1

**Comment by Baneeishaque** [comment]
+1

**Comment by durvalrafael** [comment]
+1

**Comment by mairastorch** [comment]
+

**Comment by jeffdrumgod** [comment]
+1

**Comment by Chineis** [comment]
+1

**Comment by clivejefferies** [comment]
+1

**Comment by wazzu3000** [comment]
+1

**Comment by lucasmatoscc** [comment]
+1

**Comment by savnik** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by tphinney** [comment]
I just wanted to let people know 1D (linear) /barcode and /barcode_scanner icons have been approved for me to add them to Material Symbols. I will be adding them on the source side today. I know it has been a long wait! Thanks for your patience.

(Now to go paste this into the half-dozen other requests!)

**Comment by tphinney** [comment]
This was added and went live some time back.  :)
