### ISSUE TITLE
Request: please add various app-store icons, or at least the one of Google (Play Store)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#335]
Maybe something like this:

![ic_action_play_store_white](https://cloud.githubusercontent.com/assets/5357526/13553131/dc35bdde-e386-11e5-8ab2-3805a6197d86.png)

**Comment by RoelN** [comment]
It's here! \o/

<img width="114" alt="image" src="https://user-images.githubusercontent.com/4570664/107760278-c3bd9380-6d29-11eb-990f-0c03c18ae7b2.png">

**Comment by AndroidDeveloperLB** [comment]
Seems similar to what I showed.
Any others though, of other app-stores?

**Comment by RoelN** [comment]
No other app stores are in the icon set. If the generic logo doesn't suffice, would you mind opening a new issue with specifically the icons you want to see added?

**Comment by AndroidDeveloperLB** [comment]
@RoelN The question is if you can add of other popular app-stores, and not just of Google.
