### ISSUE TITLE
Material Icons web font not working on Android 4.4.4

### ISSUE THREAD

**Issue by zilions** [google/material-design-icons#336]
Have tested the official Google Material Icons web page on Android emulators (Genymotion and the one built into Android Studio). Both web browsers fail to load the web font and instead use the bundled icons, hence using the same icon for many different keywords. For example, the exact same clock icon is used for all the alerts. Many icons don't even display since they don't have an alternative/fallback.

<img width="353" alt="screen shot 2016-03-08 at 2 29 27 pm" src="https://cloud.githubusercontent.com/assets/6722591/13592071/4f1daa28-e53a-11e5-951d-185bd10b2ec4.png">
<img width="470" alt="screen shot 2016-03-08 at 11 09 11 am" src="https://cloud.githubusercontent.com/assets/6722591/13592072/4f241d86-e53a-11e5-9df2-e39a9d2a8faa.png">

**Comment by shyndman** [comment]
Hey.

Android has bundled icons?

**Comment by nicooprat** [comment]
Almost same problem here, with Android 6: icons are not rendered, bug the original text is (like "shopping_cart"). I guess the real issue here is that we're using the default stock browser (it doesn't support ligatures), which is "deprecated" in favor of Chrome.

I guess guys from Genymotion don't have the right to embed Chrome with their VMs (licenses issues I suppose).

To install Chrome on Genymotion, just [download an APK for the target version](http://www.apkmirror.com/apk/google-inc/chrome) and drag'n'drop it on the Genymotion window (when running). No need to install and connect Google Play Services (I struggled a few hours before figuring this out...).

Material icons are working fine on Chrome 49 with Android 4.4.4.

**Comment by vtellez** [comment]
https://github.com/google/material-design-lite/issues/1375

**Comment by ltfschoen** [comment]
I used [Crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) to get the Material Design Icons working on an Android Virtual Device (AVD) emulator using older Android versions such as to 4.1.2 (and including 4.4.2)

First I followed [this guide](http://google.github.io/material-design-icons/) to install Material Design Icons with Bower (latest version 2.2.3)
```
bower install material-design-icons#2.2.3
```

I then added the code shown in "Setup Method 2. Self hosting" of the guide at the above link into my Sass file. I made the URLs point to the library files relative to my locally compiled CSS directory i.e.
```
@font-face { 
... 
src: url('../lib/material-design-icons/iconfont/MaterialIcons-Regular.eot');
...
}

.material-icons {
...
}
```

I deleted the subdirectory /platforms/android

I then ran the Android AVD and deleted previously installed versions of the app. i.e. Menu > Settings > Apps > [Click Relevant App] > Uninstall

I then installed crosswalk following the steps at its [GitHub repo](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview)
```
cordova plugin add cordova-plugin-crosswalk-webview
cordova clean
```

I updated my manifest file (i.e. config.xml) and changed the minimum supported Android SDK version to 14 (i.e. Android 4.1.2)
```
<preference name="android-minSdkVersion" value="14"/>
<preference name="xwalkVersion" value="19+"/>
```

I re-added the android platform into subdirectory /platforms/android
```
ionic platform add android
```

I created an Android Virtual Device for Android 4.4.2 (API level 19)
```
android avd
```

I ran the emulator and the Material Design Icons now appear correctly
```
ionic emulate android -lcs --stacktrace --info --debug
```

**Comment by snowbreeze** [comment]
Cross walk is not a solution. It adds 10-30mb of junk

**Comment by ltfschoen** [comment]
@snowbreeze What "non-junk" alternative solution (i.e. <10mb) are you able to propose?

**Comment by snowbreeze** [comment]
I was able to get it working by using the unicode inplace of the full name of the icon.

@ltfschoen If I could propose a solution, i would have already

**Comment by campagna91** [comment]
@theavijitsarkar where's is possibile to find a complete unicode icons list?

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by Kaylen-sleepless786** [comment]
@RoelN https://lnkr.fun/45c209c
