### ISSUE TITLE
Crop icons do not agree with names/labels

### ISSUE THREAD

**Issue by bay879** [google/material-design-icons#338]
I noticed that the crop icon shapes don't agree with the labels.  From "most square" to "most elongated" the crops should be square, 5:4, 7:5, 3:2, 16:9.
Instead, 3:2 appears more square than 5:4, and 7:5 very narrow.

**Comment by tphinney** [comment]
I noticed this as well while working on the Material Symbols conversion.

**Comment by tphinney** [comment]
This has since been fixed!
