### ISSUE TITLE
Hosted woff font is ~21KB smaller than the one in this repo

### ISSUE THREAD

**Issue by hrvojelabtiva** [google/material-design-icons#340]
The woff file that is referenced in the hosted stylesheet (when using Safari):

http://fonts.googleapis.com/icon?family=Material+Icons

http://fonts.gstatic.com/s/materialicons/v12/2fcrYFNaTjcS6g4U3t-Y5RV6cRhDpPC5P4GCEJpqGoc.woff

is around 58KB, while the corresponding file in this repo:

https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.woff

is around 79KB.

Why is there such a big size difference?

Aside from the size difference, the hosted version works perfectly in Safari while using the version from this repo results in some icons being misaligned in Safari. I have yet to create a minimal example of this and will open a separate issue for it.

**Comment by shyndman** [comment]
The difference is that I produce the woff in the repo, and the Fonts guys produce the woff they serve (and clearly do a much better job of it).

I'm going to upload their version and figure out a better long-term strategy. Thanks for the report.

**Comment by shyndman** [comment]
Fixed, and cut a new 2.2.2 release.
