### ISSUE TITLE
Request: Maneuver icons for Directions

### ISSUE THREAD

**Issue by speshiou** [google/material-design-icons#341]
Here's a list of maneuvers that I found within Google Maps Apis:
- turn-sharp-left
- uturn-right
- turn-slight-right
- merge
- roundabout-left
- roundabout-right
- uturn-left
- turn-slight-left
- turn-left
- ramp-right
- turn-right
- fork-right
- straight
- fork-left
- ferry-train
- turn-sharp-right
- ramp-left
- ferry

That will be useful to the people who build their own UI of directions.
Thanks.

**Comment by rezja88** [comment]
Google

**Comment by harishankar-jayasakthi** [comment]
hi speshiou , good job what you did
plz see this images can you update 
following latest icon:
https://maps.gstatic.com/tactile/directions/text_mode/maneuvers-2x.png

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
