### ISSUE TITLE
[Icon Request] QR Code/Barcode (SKU) icon

### ISSUE THREAD

**Issue by ZakTaccardi** [google/material-design-icons#347]
Icon request:
- QR code
- barcode (SKU)

**Comment by redwolf2** [comment]
This was aleady requested:
#7

**Comment by shyndman** [comment]
And #33. Closing.

**Comment by tphinney** [comment]
I just wanted to let people know 1D (linear) /barcode and /barcode_scanner icons have been approved for me to add them to Material Symbols. I will be adding them on the source side today. I know it has been a long wait! Thanks for your patience.
