### ISSUE TITLE
Sprites linking to non-existant images

### ISSUE THREAD

**Issue by dmitriz** [google/material-design-icons#349]
This css file is only for Navigation icons but links to some external PNG files (why capital PNG?) that do not seem to be in the same repository:

https://github.com/google/material-design-icons/blob/master/sprites/css-sprite/sprite-navigation-black.css#L2

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

Sprite sheets have been removed from the current version.
