### ISSUE TITLE
Please add those icons: filter, storage, wrench, G+, Graph, ECG

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#35]
Would be great to have those.

**Comment by StringMon** [comment]
Returning to the OP, is there a wrench icon anywhere? I'm not having any luck finding one.

**Comment by schildbach** [comment]
I also thought the filter icon is designed a bit unlucky. I used it nevertheless for my app.

**Comment by AndroidDeveloperLB** [comment]
@schildbach What is your app, if I may ask? You can see my app. Sadly, because I have both sorting and filtering, they look very similar.

**Comment by Ellorah** [comment]
It's a search for posts bar for Facebook. You can search posts by time, place or date.

**Comment by schildbach** [comment]
@AndroidDeveloperLB My app is Öffi - https://play.google.com/store/apps/details?id=de.schildbach.oeffi (screenshots are not updated yet)

**Comment by AndroidDeveloperLB** [comment]
@schildbach Wow, nice. You've got more than 1,000,000 downloads !

**Comment by schildbach** [comment]
@AndroidDeveloperLB Thanks! Actually it's almost 5 Mio (-:

**Comment by HamsterCoder** [comment]
+1 please add wrench icon

**Comment by newmanw** [comment]
+1 for filter.  I am not always filtering a list, so current filter icon seems out of context.

**Comment by Poundex** [comment]
+1 for filter icon that users will actually recognise as meaning 'filter'

**Comment by habfast** [comment]
+1 for filter icon that users will actually recognise as meaning 'filter' (the funnel)

**Comment by dhiemstra** [comment]
+1 for filter icon, current icon doesn't express the meaning of the icon well.

**Comment by constantin-v** [comment]
+1 for filter icon with the funnel

**Comment by mattheiler** [comment]
+1 for filter/funnel icon, especially. I could/want to use everything in this list, too.

**Comment by moonkat** [comment]
+1 for funnel filter icon.

**Comment by chun2499** [comment]
.

**Comment by gitolog** [comment]
+1 for funnel!

**Comment by leonardodelfino** [comment]
+1 for funnel!

**Comment by afriestad** [comment]
:+1: for funnel

**Comment by r-lyeh** [comment]
+1 for funnel

**Comment by nonide** [comment]
+1 for funnel

**Comment by winterdesign** [comment]
+1 for funnel (it's much more recognizable)

**Comment by cjke** [comment]
I understand being consistent so using the existing would make sense - however, even the newly uplifted Google Sheets uses the funnel for its filter icon.... 

![image](https://user-images.githubusercontent.com/884065/28751415-8c7c33a4-7539-11e7-994f-cdf3ba9da055.png)

**Comment by Marknetic** [comment]
+1 for funnel

I think it wouldn't hurt to have both options.

**Comment by moonkat** [comment]
How hard is it to add the funnel (that looks like a funnel)? There's really no reason for every new design spec/library to reinvent well established and recognizable wheels (or funnels!)

So far, I haven't even come across the stock Material funnel being used in an app. Not by chance, so far anyway, so it can't be that pervasive yet.

**Comment by SbstnErhrdt** [comment]
+1 for funnel

**Comment by ikumani** [comment]
+1 for funnel ( few designs)

**Comment by Thalius** [comment]
+1 for funnel, it's a lot more recognizable.

**Comment by emiliofonseca** [comment]
+1 for funnel, it's a lot more recognizable.

**Comment by Schlesiger** [comment]
+1 for wrench

**Comment by ymgsmz** [comment]
## +1 for funnel

**Comment by kevinvos** [comment]
# +1 for funnel!

**Comment by fcanocapdepon** [comment]
## +1 for funnel

**Comment by julienreszka** [comment]
Yes, need this funnel icon guys

**Comment by kristopherchun** [comment]
+1 for funnel

**Comment by izyb** [comment]
+1 for funnel please

**Comment by tobiaswsmith** [comment]
+1 for funnel.

**Comment by roman-lyubimov** [comment]
+1 for filter

**Comment by moonkat** [comment]
<img width="478" alt="screen shot 2018-11-07 at 4 21 20 pm" src="https://user-images.githubusercontent.com/102142/48164807-3f0d8080-e2a9-11e8-9346-ff1279f085ca.png">

**Comment by etheodor42** [comment]
+1

**Comment by etheodor42** [comment]
I do the job for you kiss <3
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="?android:attr/colorControlNormal"
        android:pathData="M14,12V19.88C14.04,20.18 13.94,20.5 13.71,20.71C13.32,21.1 12.69,21.1 12.3,20.71L10.29,18.7C10.06,18.47 9.96,18.16 10,17.87V12H9.97L4.21,4.62C3.87,4.19 3.95,3.56 4.38,3.22C4.57,3.08 4.78,3 5,3V3H19V3C19.22,3 19.43,3.08 19.62,3.22C20.05,3.56 20.13,4.19 19.79,4.62L14.03,12H14Z" />
</vector>
```

**Comment by Grohden** [comment]
![image](https://user-images.githubusercontent.com/7496871/53958930-064baf80-40c1-11e9-875d-4d8d498b804a.png)

**Comment by aoriani** [comment]
+1 funnel

**Comment by lebnic** [comment]
Would be nice, indeed, to have a funnel icon :-)

**Comment by alexandrelc16** [comment]
+1 funnel

**Comment by okridgway** [comment]
Seriously google, this has been a problem for years now, even Microsoft excel uses the filter icon. Get with it.

**Comment by suchiksagar** [comment]
Please funnel 2020! :)

**Comment by spiriidk** [comment]
+1 funnel

**Comment by jcantais** [comment]
+1 for funnel

**Comment by nailgilaziev** [comment]
the decision to do nothing with it already since 2014 is the strangest decision I've seen in this repository! ))
We really need funnel icon out of the box. Tons of strange icon exist, but one of the commonly used doesn't.

**Comment by alskenobi** [comment]
+ 1 for funnel

**Comment by mgavaudan** [comment]
+1 for funnel

**Comment by m000v** [comment]
+5 for funnel..

**Comment by soniarojhwal** [comment]
funnel icon

**Comment by lebnic** [comment]
I don't think the funnel icon should be added! I know most of you will disagree but I have very good reasons... I am just kidding, +1 for the funnel icon. **This issue has been receiving consistent and persistent attention since 2014...** Home many hours wasting searching for a funnel icon were wasting by users of the material-design-icons ? Could this be taken care of please ?

**Comment by nailgilaziev** [comment]
maybe some reputable developer will mention someone from management team?

**Comment by MysticFragilist** [comment]
**+1 for funnel icon!**

**Comment by shelbykauth** [comment]
Found an easier solution!  Use Font Awesome instead.

jk.  That's not a real solution.  However it is the one I'm going with when I hit this sort of road-block.

**Comment by MilesParker** [comment]
Funnel Icon, please...! I can attest that my users are completely confused by the current icon. They feel it is very hard to distinguish from Sort icon, which is often placed right alongside it. It's hard to understand in what way it is a funnel at all.

**Comment by iamsureshsharma** [comment]
**funnel icon**

**Comment by THNgit** [comment]
Hi

**Comment by RoelN** [comment]
A funnel icon is in the current set:

<img width="683" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108865645-ba6adb80-75f3-11eb-9c95-57161460533d.png">

It seems that (most?) of the requests have been addressed in the meantime. @AndroidDeveloperLB mind if I close this issue, and if any icons are missing you create new issues for them? Preferably one (set) of icons at a time, so its easier to track if the icon has been addressed or not.

**Comment by AndroidDeveloperLB** [comment]
@RoelN Is the funnel now being used by Google and others?
It was years ago, and now users probably got more used to the non-funnel one, sadly.
What about the other icons (except sadly G+ as it's gone)?

**Comment by RoelN** [comment]
I don't know how the funnel is used. But it's here for everyone to use as they see fit now :-)

For icons you still feel are missing, please create new issues for them. Preferably one (set) of icons at a time, so its easier to track if the icon has been addressed or not.

**Comment by AndroidDeveloperLB** [comment]
@RoelN OK thanks. I've made requests for the others :
https://github.com/google/material-design-icons/issues/1143
https://github.com/google/material-design-icons/issues/1144
