### ISSUE TITLE
Icon Request: Construction/Equipment

### ISSUE THREAD

**Issue by BradSiegler** [google/material-design-icons#354]
Any icon(s) that represents construction would be great. Construction equipment (lift/excavator/etc.) would be most ideal.

**Comment by RoelN** [comment]
There's these now:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4570664/107760909-cf5d8a00-6d2a-11eb-8995-3abbf6a2ffd0.png">


<img width="195" alt="image" src="https://user-images.githubusercontent.com/4570664/107760937-da181f00-6d2a-11eb-8f6c-399af6fa248f.png">

Hoping this suits your needs. Apologies for the delay.
