### ISSUE TITLE
Icons Not Displaying Properly at https://design.google.com/icons/

### ISSUE THREAD

**Issue by retrospct** [google/material-design-icons#355]
For some reason there are a bunch of icons not showing up on the https://design.google.com/icons/ page.
Chrome: Version 49.0.2623.87 (64-bit)
OSX: 10.11.4
<img width="1228" alt="md-icon-page" src="https://cloud.githubusercontent.com/assets/1510356/14290549/4e9881e6-fb14-11e5-8c63-50e4b0df2ef7.png">

**Comment by shyndman** [comment]
Do you have the icon font installed locally?

**Comment by knilob** [comment]
I would say that he probably does have the font installed locally. I was having the same problem until I downloaded and installed the most recent TTF file from this repo. I'll have to remember to do that from now on after any updates. Thanks for pointing me in the right direction, @shyndman.
