### ISSUE TITLE
Icon Request: Label

### ISSUE THREAD

**Issue by leejimin1006** [google/material-design-icons#358]
![label](https://cloud.githubusercontent.com/assets/18396420/14425721/3aa17ce6-0024-11e6-9dad-b6efdaa51da5.PNG)

from gmail page.

please...!!!

I joined github site for only this request.

**Comment by FabianKoestring** [comment]
There is a `label`and `label_outline` icon.

```html
<i class="material-icons">label</i>
<i class="material-icons">label_outline</i>
```

**Comment by leejimin1006** [comment]
OK. I find.
<i class="material-icons">local_offer</i>
