### ISSUE TITLE
Chinese characters instead of icons in Android mobile

### ISSUE THREAD

**Issue by palsoft333** [google/material-design-icons#360]
I'm using the numeric code for icons to show up at the Samsung mobiles also, but recently a friend of mine showed me, that on his LG G4 device there are chinese characters instead of MD icons.

It's the default Android browser (from Samsung I think) with this user-agent string:

`Mozilla/5.0 (Linux; Android 6.0; LG-H815/V20d Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.2125.102 Mobile Safari/537.36`

**Comment by snowbreeze** [comment]
Change text-rendering: optimizeLegibility; - > text-rendering: auto;

**Comment by irkin333** [comment]
I have the same problem and setting text-rendering property did not help.

**Comment by brunonic** [comment]
Same problem, on Samsung smart TV

**Comment by irkin333** [comment]
I found interesting solution. It seems to me, that page settings are ignored and system language settings are used. On my tablet English(Zambia) language was chosen as default and since I changed it to English(United States), everything looks good.

**Comment by RoelN** [comment]
Thanks for sharing, @irkin333. Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
