### ISSUE TITLE
Google Maps Hiker icon

### ISSUE THREAD

**Issue by Simran-B** [google/material-design-icons#366]
Could you please add the hiking icon?

![google-icons2](https://cloud.githubusercontent.com/assets/7819991/14558970/f1a0bcde-0305-11e6-86f6-27173ea7135b.png)

**Comment by RoelN** [comment]
It has arrived! o/

<img width="199" alt="image" src="https://user-images.githubusercontent.com/4570664/107756671-d71a3000-6d24-11eb-92da-31a9b15b8137.png">
