### ISSUE TITLE
Icon request: Minimize, Maximize, and Restore

### ISSUE THREAD

**Issue by scooterzp** [google/material-design-icons#367]
These seem like easy icons that are usable for working with divs that behave like small windows in a UI.

**Comment by kurisubrooks** [comment]
I second this. Specifically something similar to what Chrome OS has.

![image](https://cloud.githubusercontent.com/assets/6291467/15167364/ab7e1df8-176b-11e6-814b-4488d25f7b03.png)

For now i'm using `remove`, `add` and `close`, but i'd prefer if the minimize icon was aligned to the bottom, and the maximize as a square. Currently there are no alternatives to this in the Icon pack, but Close is fine and doesn't need updating/replacing.

**Comment by dvlsg** [comment]
I agree, these would be very nice to have. I am making a [frameless](https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/frameless-window) application with material design, and icons to support any/all of these operations would be useful to me.

**Comment by Guichaguri** [comment]
Are these icons coming anywhere soon? I'd also like use them for my frameless desktop app.
The icons from Chrome OS are used in the Material Design specs (e.g. [System Bars](https://material.google.com/layout/structure.html#structure-system-bars)), but not included in the icon set :(

**Comment by kurisubrooks** [comment]
Hi @Guichaguri, I gave up on waiting for Google to make these and made my own. They follow Material Specifications, and you're free to use them if you want. 

Minimize: https://drive.google.com/open?id=0B4plslC0TxcnNURCaVVLd2ZHcEk
Maximize: https://drive.google.com/open?id=0B4plslC0TxcnWmxBbi12YTJ0VWs
Close: https://drive.google.com/open?id=0B4plslC0TxcnVlRaRVE4d1NjMG8

**Comment by Guichaguri** [comment]
@kurisubrooks Thank you :)

**Comment by Phoqe** [comment]
Are these coming anytime soon?

**Comment by Kazem-ma79** [comment]
> 
> 
> Hi @Guichaguri, I gave up on waiting for Google to make these and made my own. They follow Material Specifications, and you're free to use them if you want.
> 
> Minimize: https://drive.google.com/open?id=0B4plslC0TxcnNURCaVVLd2ZHcEk
> Maximize: https://drive.google.com/open?id=0B4plslC0TxcnWmxBbi12YTJ0VWs
> Close: https://drive.google.com/open?id=0B4plslC0TxcnVlRaRVE4d1NjMG8

How to add them in ?

**Comment by apriofrost** [comment]
@Kazem-ma79 Google has added this icon in the library: https://material.io/resources/icons/?search=minimize&icon=minimize&style=baseline

**Comment by jrj2211** [comment]
Is this going to be included anytime soon? Such a simple thing that would be highly used given Electrons popularity.

**Comment by RoelN** [comment]
Minimize:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/4570664/107757157-750dfa80-6d25-11eb-9be3-a07de0ecde11.png">


Maximize:

<img width="141" alt="image" src="https://user-images.githubusercontent.com/4570664/107757185-848d4380-6d25-11eb-8843-bddcff3de66a.png">

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4570664/107757203-8bb45180-6d25-11eb-91ca-6b030060e18b.png">

<img width="264" alt="image" src="https://user-images.githubusercontent.com/4570664/107757246-966ee680-6d25-11eb-8cd8-0330b0b2b5c5.png">

Close:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/4570664/107757280-a25aa880-6d25-11eb-94d6-2d2239d04162.png">

I hope this satisfies your needs! If not, feel free to re-open this issue.
