### ISSUE TITLE
'Invisible' shapes appear when importing

### ISSUE THREAD

**Issue by justincpollard** [google/material-design-icons#37]
Hi Josh,

I'm following up re the below issues because I have new information:

https://github.com/google/material-design-icons/issues/32
https://github.com/google/material-design-icons/issues/31
https://github.com/google/material-design-icons/issues/30

I've been in touch with Fontastic.me's Vincent Le Moign, and his response to the issue is pasted below. He's also asked if I could put you in touch with him so you two can discuss a solution in-depth. Vincent's email is vincent.lemoign@gmail.com. Feel free to CC me (jp@zumper.com) if needed:

All the icons which cause problems have a transparent shape that you don’t normally see, but that cause a problem when you import it.
(as the shape really exists even if invisible)

For example, I’ve fixed the magnifier icon you mentioned, and you can see that it’s imported without problem with Fontastic below:

![pastedgraphic-33](https://cloud.githubusercontent.com/assets/1743546/4873157/2a638bea-6204-11e4-8a9b-d8e5e6962eed.png)

I’ve attached to this email the original magnifier icon, and the fixed one.

Have a look and try to import, you’ll see.

This is actually a classic problem, and I detail how to fix in the Fontastic FAQ: http://fontastic.me/faq

![pastedgraphic-34](https://cloud.githubusercontent.com/assets/1743546/4873159/347511bc-6204-11e4-9ad0-14e276541bdd.png)

**Comment by jestelle** [comment]
Closing this out, as from the asset repo perspective, we don't have anything left to do to resolve this.

**Comment by justincpollard** [comment]
Thanks for taking a look at this, @jestelle!

**Comment by AndyOGo** [comment]
How can I download an SVG without this invisible shape from https://material.io/icons?
