### ISSUE TITLE
Icon request: Indian Rupee symbol

### ISSUE THREAD

**Issue by ashish0294** [google/material-design-icons#371]

**Comment by george3447** [comment]
+1

**Comment by iSanjayAchar** [comment]
+1

**Comment by yugalbagul** [comment]
+1

**Comment by chiru22** [comment]
+1

**Comment by vishalgoel** [comment]
+1

**Comment by iSanjayAchar** [comment]
It's been a year!

**Comment by smatt92** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
This is available from [materialdesignicons.com](https://materialdesignicons.com/) while you're waiting for Google to add it.

[![](https://materialdesignicons.com/icon/currency-inr)](https://materialdesignicons.com/icon/currency-inr)

**Comment by roshangade** [comment]
Any plan for this?

**Comment by azattaher** [comment]
+1

**Comment by iSanjayAchar** [comment]
It's been an year and yet no response

**Comment by sonupalak47** [comment]
Thanks

**Comment by Pulkit-Sharma** [comment]
Seems project is dead!!!

**Comment by grvv** [comment]
+1

**Comment by sdivakarrajesh** [comment]
While waiting for them to include the rupee icon, you can also use (in some cases) the unicode of rupee symbol with the Text widget.

`Text("\u20B9")`

**Comment by ruchir-rai** [comment]
> While waiting for them to include the rupee icon, you can also use (in some cases) the unicode of rupee symbol with the Text widget.
> 
> `Text("\u20B9")`

Yes this works in most cases, not some.

**Comment by Manishkumartomar** [comment]
\u20B9 
just type this and you will get it
this is the solution, i hope you get it and close this issue

**Comment by deepakkj6** [comment]
+1

**Comment by rathod-sahaab** [comment]
Copy (₹) its better for code quality than magic number 20B9

**Comment by rahulmamilla** [comment]
https://pub.dev/packages/material_design_icons_flutter

Icon(MdiIcons.currencyInr)

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by jaybharatgroup** [comment]
just use currency_rupee its working now

**Comment by tphinney** [comment]
Yes, this exists in both Material Icons and Material Symbols now.
glyph name (ligature text): currency_rupee
Unicode value: (U+) EAF7

Note that it is NOT encoded like a rupee character in normal text/fonts—that would be at U+20B9.
