### ISSUE TITLE
Add a button to download the 'drawable-anydpi-v21' xml icon directly from https://design.google.com/icons/

### ISSUE THREAD

**Issue by polmabri** [google/material-design-icons#372]
Add a button to download the 'drawable-anydpi-v21' xml icon directly from [https://design.google.com/icons/](https://design.google.com/icons/)

![design google icons](https://cloud.githubusercontent.com/assets/874881/14858280/b6d9b9ae-0c9f-11e6-8d31-3f6477756074.png)

**Comment by kfaraj** [comment]
+1

**Comment by polmabri** [comment]
temporary workaround: materialdesignicons.com

![workaround](https://cloud.githubusercontent.com/assets/874881/17674364/8807ef6a-6325-11e6-84ef-dabea388d203.png)

**Comment by RoelN** [comment]
A download button has since been put into place:

<img width="145" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108842477-a0240400-75d9-11eb-8840-6f23cc406426.png">
