### ISSUE TITLE
material icon user select none

### ISSUE THREAD

**Issue by thanush** [google/material-design-icons#374]
i'm using material icon's in table. but user want to copy individual row when user copy paste it's happening like this
`print  delete_forever  mode_edit   pageview    GIR1617-1   05-Apr-2016 985M001 M.k.d   993.65  Vinay   Vinay   05-Apr-2016 Vinay
`
you see above when user selecting including icons after paste that content it's giving like print,delet_forever.

i tried `user-select: none;` also but it's not working

**Comment by shyndman** [comment]
In this case, it's probably best to use entities. 

Instead of 

print delete_forever mode_edit

you should write

&#xE8AD; &#xE92B; &#xE254;

**Comment by thanush** [comment]
@shyndman thanks man best idea. i didn't think that way

**Comment by shyndman** [comment]
@thanush, did you get this worked out?
