### ISSUE TITLE
Icon request: sitemap

### ISSUE THREAD

**Issue by pakastin** [google/material-design-icons#377]
Sitemap icon would be great..
I mean: http://fortawesome.github.io/Font-Awesome/icon/sitemap/

Thanks for great icons! 👍

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by wawyed** [comment]
> Icon available at: https://fonts.google.com/icons

What is the name of it? I can't find it.

**Comment by tphinney** [comment]
Not sure about that exact layout, not immediately finding it. But, there are a bunch of icons that are similar to this. Check out:
- account_tree
- lan
- fanmily_history
- schema
- mitre

Is any of these useful?
