### ISSUE TITLE
Icon Request: Question Mark

### ISSUE THREAD

**Issue by xetrics** [google/material-design-icons#379]
Seriously? I hope this was overlooked and not ignored.

**Comment by shyndman** [comment]
Searching for "help" on https://design.google.com/icons yields several results. Do those work?

**Comment by Xetrics** [comment]
Not for all projects

**Comment by b3hrooz** [comment]
It helps to have the question mark without the circle surrounding it.

**Comment by AdityaAnand1** [comment]
Lol, I can't believe there isn't a plain question mark. The current circled icons look very weird on Android's toolbar.

For future googlers, you can find one from here temporarily https://materialdesignicons.com/

**Comment by AdityaAnand1** [comment]
Oh my god, it still hasn't been added?! Really?

I don't think I've ever seen a mature icon set without a plain question mark. Can we get an official response please? (@jestelle @shyndman)

**Comment by oneezy** [comment]
Yeah. Bump. Bump. Bump.

Where's the original question mark icon? 

I need to use it a FAB.

**Comment by vanSkyr** [comment]
Still no question mark? :(

**Comment by Jexah** [comment]
Bump. Would love this implemented!

**Comment by AdityaAnand1** [comment]
Airline seat recliner icon?

> Sure

Pregnant women?

> Here you go!

Where my hot tub icon at?

> Right here

...Que...Question mark?

> Kill yourself
> \- Google probably

**Comment by ASteinheiser** [comment]
Currently need this icon for a project, would be nice to have it implemented soon!

**Comment by slabo** [comment]
no comprendo señor

**Comment by andriychuma** [comment]
There are `help`, `help_outline`, `live_help` icons with a question mark inside. I hope that's exactly what has been looked for.

**Comment by netgfx** [comment]
It is not, what is requested is a plain question mark without a circle around it. `?`

**Comment by Bloemendaal** [comment]
+1

**Comment by xetrics** [comment]
Considering i opened this issue 4 years ago, I assume the latter of my original post is true.

**Comment by Roman-Simik** [comment]
I'm here and I'm still waiting for that :)

**Comment by azanoni** [comment]
Searching the same, no question mark yet!

**Comment by Dotrar** [comment]
I just got the original help in a circle and deleted the circle, you can use save this as a new .svg file:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg60"
   version="1.1"
   width="24"
   viewBox="0 0 24 24"
   height="24">
  <defs
     id="defs64" />
  <path
     id="path58"
     d="m 11,18 h 2 V 16 H 11 Z M 12,6 C 9.79,6 8,7.79 8,10 h 2 c 0,-1.1 0.9,-2 2,-2 1.1,0 2,0.9 2,2 0,2 -3,1.75 -3,5 h 2 c 0,-2.25 3,-2.5 3,-5 0,-2.21 -1.79,-4 -4,-4 z" />
</svg>
```

**Comment by mirkoaus** [comment]
Here to remind that a simple, without a circle or a square or a triangle, question mark is still relevant. No nothing, no background, no nothing. Just a simple good ol' question mark icon, please.

**Comment by Dotrar** [comment]
@mirkoaus just use the file I sent above. it's nothing

**Comment by sk3llo** [comment]
2021 and I'm still here...

**Comment by oneezy** [comment]
Google's guidelines are their for a reason and fit a much bigger picture.... I get it. We don't hate you Google we're just disappointed.

---

I personally had to make the switch over to [Material Design Icons](https://materialdesignicons.com/)

Here's a link to their [Cheat Sheet](https://pictogrammers.github.io/@mdi/font/5.8.55/)

```
<i class="mdi mdi-help">
```

![image](https://user-images.githubusercontent.com/7369575/106628661-a6c1dd00-653f-11eb-9ad2-c4c91a1239ce.png)

**Comment by ivanBell199** [comment]
Wow! I've always been so happy with Google Icons. But now I have a circle button that needs to have a question mark insite it. And that circle in the icon ruins everything. Never thought I'd have such a problem. Hope a simple question mark eventually gets there

**Comment by danger89** [comment]
I think it's just `question_mark`

**Comment by oneezy** [comment]
holy crap they did it!
![image](https://user-images.githubusercontent.com/7369575/141402665-d6428d3f-ac95-42b0-8506-2c19eb0ef290.png)

**Comment by xetrics** [comment]
Amazing

**Comment by danger89** [comment]
> holy crap they did it! ![image](https://user-images.githubusercontent.com/7369575/141402665-d6428d3f-ac95-42b0-8506-2c19eb0ef290.png)

Yes that is what I said 🎂👌

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
