### ISSUE TITLE
Include Icon request

### ISSUE THREAD

**Issue by ssmathivanan402** [google/material-design-icons#380]
Hi,
Have a nice days,
I suggest the icons to include the material design. Below, I attached the icon png file which is add into the material. If you need I am willing to
![map-pushpin-marker-icons](https://cloud.githubusercontent.com/assets/10130876/15041071/da53b9ce-12d6-11e6-8965-30e030c8dd82.png)
 share SVG File too.

**Comment by RoelN** [comment]
The push pin icon has arrived! \o/

<img width="140" alt="image" src="https://user-images.githubusercontent.com/4570664/107759632-dedbd380-6d28-11eb-9e8c-79f137355227.png">
