### ISSUE TITLE
Icon Request: Brain

### ISSUE THREAD

**Issue by meirbank** [google/material-design-icons#383]
Requesting a brain Icon.Something like this:
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.mindfulwebworks.com%2Fart-of%2Fbrain-icon.png&f=1

**Comment by RoelN** [comment]
@meirbank Not technically a brain, but would this icon suffice?

<img width="190" alt="image" src="https://user-images.githubusercontent.com/4570664/107745548-c5c92780-6d14-11eb-897e-b1a217090aba.png">
