### ISSUE TITLE
Icon Request: wb custom

### ISSUE THREAD

**Issue by PublicParadise** [google/material-design-icons#385]
Examples:

![dbecker-fig-2-whitebalance-omp](https://cloud.githubusercontent.com/assets/2541332/15119600/7e4d0c3c-15c6-11e6-8eea-5452289f7a49.jpg)

![wb_colortemp](https://cloud.githubusercontent.com/assets/2541332/15119603/810691dc-15c6-11e6-85eb-c027e6ec6e22.jpg)

![6-tips-white-balance-color-temperature-2](https://cloud.githubusercontent.com/assets/2541332/15119606/83d6e9ac-15c6-11e6-9dd9-d198e76d6f11.png)

**Comment by RoelN** [comment]
Closing this in favor of https://github.com/google/material-design-icons/issues/384
