### ISSUE TITLE
Please add a icon for navigation drawer avatar

### ISSUE THREAD

**Issue by floating-cat** [google/material-design-icons#39]
The navigation drawer left-top corner has a avatar. It would better to provide a default icon (when user hasn't logged or uploaded its own avatar) .

This icon is 64dp (I can't find its size in Google Material Design spec, so I measured it but still not sure) and `action -> account circle` or default rounded avatar in Gmail/G+ may be a good choice.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
