### ISSUE TITLE
Remove extra whitespace from closed_captions icon

### ISSUE THREAD

**Issue by feross** [google/material-design-icons#390]
Certain icons, (like `closed_captions`) have random extra whitespace to the left or right. This makes it really hard to use the icon font.

For example, here's what a video player UI looks like:

<img width="181" alt="0e9c1aa4-1869-11e6-9709-7a94ceab8d72" src="https://cloud.githubusercontent.com/assets/121766/15234790/2e585cda-186a-11e6-972e-54817b6eccd2.png">

Please fix these subtle inconsistencies as they make it really hard to work with this otherwise, excellent icon library.

**Comment by jestelle** [comment]
The icon name is "closed_caption", not "closed_captions"
http://jsbin.com/fenejob/1/edit?html,output

The extra space you're seeing is the icon font rendering the 's', which renders as nothing.

**Comment by feross** [comment]
You're right -- thanks for pointing this out, and sorry for the noise. Much appreciated.
