### ISSUE TITLE
Icon request: timeout

### ISSUE THREAD

**Issue by sabinebarrera** [google/material-design-icons#391]
Please provide an icon to represent when a process has timed out. It can be a web request or a task.

**Comment by jestelle** [comment]
I believe there may be a number of icons that might make sense for this use.  But if you can't find something appropriate...
---
We encourage folks to use the "Add reaction" to add a thumbs up and vote up icon requests.
Popular requests we will try to accommodate, but our turn around on new icon requests is likely going to be fairly slow.

**Comment by RoelN** [comment]
@sabinebarrera Several new time-related icons have been added, which I think address your issue. If not, feel free to re-open this issue!
