### ISSUE TITLE
Missing 24px and 48px SVGs

### ISSUE THREAD

**Issue by obskyr** [google/material-design-icons#395]
As mentioned in #218, the 48px assets for a few star-related icons are missing. I was curious to see, however, which other 48px and in particular 24px assets were missing, so I whipped up a quick script to check. These are the missing standard-size icons:
- `action`:
  - `ic_star_rate`, 24px
  - `ic_star_rate`, 48px
  - `ic_offline_pin`, 48px
  - `ic_help_outline`, 48px
  - `ic_zoom_in`, 48px
  - `ic_zoom_out`, 48px
  - `ic_camera_enhance`, 48px
  - `ic_gif`, 48px
  - `ic_reorder`, 48px
  - `ic_eject`, 48px
- `av`:
  - `ic_sort_by_alpha`, 48px
  - `ic_play_circle_filled_white`, 24px
  - `ic_hd`, 48px
- `communication`:
  - `ic_phonelink_erase`, 48px
  - `ic_phonelink_lock`, 48px
  - `ic_phonelink_setup`, 48px
  - `ic_phonelink_ring`, 48px
- `content`:
  - `ic_font_download`, 48px
- `editor`:
  - `ic_money_off`, 48px
- `hardware`:
  - `ic_device_hub`, 48px
- `image`:
  - `ic_vignette`, 48px
  - `ic_photo_size_select_large`, 48px
  - `ic_photo_size_select_small`, 48px
  - `ic_photo_size_select_actual`, 48px
  - `ic_collections_bookmark`, 48px
- `toggle`:
  - `ic_star`, 48px
  - `ic_star_border`, 48px
  - `ic_indeterminate_check_box`, 48px

There are 931 icons. 26 of those lack a 48px version, and only 2 lack a 24px version. This inconsistency creates problem in many cases, forcing a workaround to be written in some way. Extending this near-complete coverage of 48+24px versions to these remaining few icons would go a long way.

**Comment by jestelle** [comment]
I understand that the inconsistency may cause challenges for you, but this is mostly 'working-as-intended'

Usually, we design icons at 24px, and that is the only size we would provide an SVG for.  We might generate PNGs at other sizes, but they would all come from that 24px SVG source.

In some cases we revise the SVGs when designing at other sizes, in which case you may find additional designed SVGs.  This is why for some icons you find 48px and some you don't.

In reality, I believe we have 48px SVGs for many icons that we probably shouldn't have.  These are just duplicates of the 24px asset scaled up 2x.  If it's scaled up precisely 2x, there's no point in having a separate asset for it.

I'm going to keep this bug open, but likely the way we would address it is not by making sure we have 24px and 48px SVGs for all the icons, but more likely remove SVGs that we never intended to have.

The only SVGs we should have checked in are the specifically designed, pixel perfect sources.  Duplicates are not helpful.

**Comment by obskyr** [comment]
I see. Any chance of homogenizing the sizes on http://design.google.com/icons, then? Since that after all is a repository people generally get the icons from, it feels more natural that all the icons would be available in (at least some of) the same sizes.

**Comment by DanielRuf** [comment]
Would also like to see the missing 48px versions as Firefox produces some weird behavior when I scale an SVG up and animate it using Walkway.js.

**Comment by DanielRuf** [comment]
Also scaling up an SVG with a 24px viewbox makes problems in browsers as the strokes are more bold and not as in the 48px versions. So scaling does not work well in most cases when the outlines and strokes should not be changed.

**Comment by obskyr** [comment]
@DanielRuf As a potential fix for the stroke issue, try setting `vector-effect: non-scaling-stroke;` in the CSS. Might work for your use case!

**Comment by DanielRuf** [comment]
@obskyr Thanks, will try this later.

**Comment by DanielRuf** [comment]
> @DanielRuf As a potential fix for the stroke issue, try setting vector-effect: non-scaling-stroke; in the CSS. Might work for your use case!

Sorry for the late reply but this produces issues with Walkway so it is not an option for me. Generally upscaling also produced issues in Firefox for Android, not sure why but all other browsers were ok.

So I better wait for the final 48px versions =)

**Comment by RoelN** [comment]
Closing this because it's an ancient issue. Apologies for leaving it open for so long. If you feel it's still relevant, feel free to reopen or create a new one with updated information!
