### ISSUE TITLE
Icon request - icons for cars

### ISSUE THREAD

**Issue by AlinCG** [google/material-design-icons#397]
Icons for fuel, engine, transmission, mileage and others.  Thanks

**Comment by jestelle** [comment]
We encourage folks to use the "Add reaction" to add a thumbs up and vote up icon requests.
Popular requests we will try to accommodate, but our turn around on new icon requests is likely going to be fairly slow.

**Comment by RoelN** [comment]
@AlinCG Several new icons have been added that I would think address your request. If not, feel free to reopen this issue!
