### ISSUE TITLE
New Icons are empty. Also on Google site

### ISSUE THREAD

**Issue by thanuzz** [google/material-design-icons#399]
Several 'New' icons are missing. In my project as well as on https://design.google.com/icons/.

The label is there but there is no icon:

![image](https://cloud.githubusercontent.com/assets/4639885/15418803/2d047d02-1e62-11e6-961d-d07b318d6c66.png)

**Comment by jestelle** [comment]
You likely have an older version of the Material Icons font installed locally.
The icons site uses the font to render icons, and if you have it locally, there are optimizations to use the local copy.

Uninstall, disable, or update your local copy and it'll fix this issue.
