### ISSUE TITLE
Why all png files are black and white, no colors?

### ISSUE THREAD

**Issue by gclsoft** [google/material-design-icons#40]
It's not beautiful without colors. How to make it colorful?

**Comment by vijayrawatsan** [comment]
Install imagemagick
and try below command... works well for me 
convert ic_apps_white.png -fuzz 75% -fill red -opaque white ic_apps_red.png

**Comment by vincent-paing** [comment]
Anyone know how to resolve this for Android?

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
