### ISSUE TITLE
Icon request: create new file

### ISSUE THREAD

**Issue by TeemoWan** [google/material-design-icons#400]

**Comment by jestelle** [comment]
We encourage folks to use the "Add reaction" to add a thumbs up and vote up icon requests.
Popular requests we will try to accommodate, but our turn around on new icon requests is likely going to be fairly slow.

**Comment by TeemoWan** [comment]
i think:
https://design.google.com/icons/#ic_note_add

**Comment by jestelle** [comment]
Closing given you found what I believe would be an appropriate icon to use for this use.  Feel free to reopen if you believe something different is needed.
