### ISSUE TITLE
Missing device icon category in gulp task file

### ISSUE THREAD

**Issue by miaopeng** [google/material-design-icons#401]
gulpfile.babel.js:

/*\* Names of directories containing icons. */
const ICON_CATEGORIES = [
  'action',
  'alert',
  'av',
  'communication',
  'content',
  'editor',
  'file',
  'hardware',
  'image',
  'maps',
  'navigation',
  'notification',
  'places',
  'social',
  'toggle',
];

where is the 'device' category?

**Comment by jestelle** [comment]
Good question.  It looks erroneously left out.  Feel free to send us a pull request.
Or we'll eventually get to fixing this later.

**Comment by RoelN** [comment]
No gulp files anymore in the new repo :-)
