### ISSUE TITLE
Veterinarian icons #icon request

### ISSUE THREAD

**Issue by SamXDesc** [google/material-design-icons#407]
Dogs, bones, cat, and other pets for veterinarian websites and more. Thanks

**Comment by RoelN** [comment]
There is a generic pets icon:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/4570664/107749892-86520980-6d1b-11eb-846d-171ffd3c25c7.png">

I hope this satisfies your needs. If not, feel free to reopen this issue!
