### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by toddmotto** [google/material-design-icons#408]
Seems to be a few missing icons on the https://design.google.com/icons/ page, just a heads up.

<img width="527" alt="screen shot 2016-06-02 at 14 14 44" src="https://cloud.githubusercontent.com/assets/1655968/15746264/b82c6564-28cd-11e6-99f0-91c4a93347ef.png">

OS: Mac OSX
Browser tested: Chrome Version 51.0.2704.79 (64-bit)

**Comment by brospars** [comment]
Everything works fine for me *firefox 46.0* and *chrome 50.0*

**Comment by TheChrisPratt** [comment]
Make sure you don't have them installed locally.  If you do, it can only
show the ones you have installed.
  (*Chris*)

**Comment by toddmotto** [comment]
Ahhh I see. I have them installed locally.
