### ISSUE TITLE
icon request: filter

### ISSUE THREAD

**Issue by kenanokeefe** [google/material-design-icons#409]
http://fontawesome.io/icon/filter/

thx for all the other awesome icons!

**Comment by shyndman** [comment]
This is Material Design's equivalent:
https://design.google.com/icons/#ic_filter_list

**Comment by krftcz** [comment]
Icon 'filter_list' looks like icon for sorting, not for filtration. Don't see a reason for closing this issue while it remains unresolved.

**Comment by beto-rodriguez** [comment]
Even the google docs team are not using the suggested icon, notice their icons are based on this library

![untitled](https://user-images.githubusercontent.com/10853349/53650983-5c28df00-3c0b-11e9-84d2-34ec9686350d.png)

**Comment by leoplct** [comment]
+1

**Comment by CaptainDeadcode** [comment]
Is this resolved? Or filter_list is the final equivalent? @shyndman.
I am in need of the same icon @kenanokeefe mentioned. But I can not see it in the Material Icons website.
I can only see https://design.google.com/icons/#ic_filter_list

Any chance we will be getting this one ? http://fontawesome.io/icon/filter/

**Comment by phidias51** [comment]
You might try the filter-outline icon.

**Comment by CollinAlpert** [comment]
I would also love to see a material design equivalent to the fontawesome filter.
