### ISSUE TITLE
Thank you! :)

### ISSUE THREAD

**Issue by MeoMix** [google/material-design-icons#41]
These icons are absolutely fantastic and I'm putting them to use as I type this.

One question -- in a few scenarios I need 18px <svg> or 30px <svg> and there is not a corresponding element. If I apply a transformation to the element then Chrome anti-aliasing kicks in on the sub-pixels and causes an ugly blur. I resolved this by transforming the elements in InkScape and then apply PixelSnap, https://code.google.com/p/pixelsnap/, to the transformed path. This extension gracefully snaps the paths to the nearest pixel.

I'm surprisingly happy with the results, but I'm surprised that there's no easier way. I haven't worked extensively with graphics before, though. Is this just a fact of life, or did I make things overly complicated?

**Comment by jestelle** [comment]
Thanks for the detailed report MeoMix.
If you're finding you need to resize assets to make them feel 'right' together, you might present it to us as a bug.  Icons have been designed with their related icons in mind, but sometimes we miss certain pairings, or might not get it perfect.

I know you described some of the issues above, but if you could simplify your description of the bug, especially with some visuals, I'll take that back to our designers and have them review it to see if we think any change might be necessary.

We get similar feedback like this from Google product teams using these assets, and we're often able to correct issues that make things easier to use.

Reading your specifics above, it sounds like you found a solution, so I'll close this out, but feel free to file a new issue if you have specific asks for us.

**Comment by MeoMix** [comment]
I'll put something together this weekend or next week. I agree, visuals would help a lot. 

You'll be pleased to know the entire world saw your icon set and is heavily using it at this point. My Chrome extension music player was the #1 post on Reddit a couple of days ago and now has 200,000 people using your icon set. :)

![image](https://cloud.githubusercontent.com/assets/1380995/5870979/4ff4e026-a28b-11e4-8104-02b649d61b4f.png)

**Comment by jestelle** [comment]
Congrats.  It looks great.
