### ISSUE TITLE
Some icons are not visible when i visit the official webpage

### ISSUE THREAD

**Issue by fakiolinho** [google/material-design-icons#411]
I 've noticed that some icons are not visible when i visit the official [webpage](https://design.google.com/icons/). I 've tested with Chrome 51.0.2704.84 (64-bit) and Firefox 46.0.1 (after clearing cache) and i see this:

![f472fcdcdec14e01b17dc81683d6ce8c](https://cloud.githubusercontent.com/assets/2962687/15827575/567e8c30-2c14-11e6-9ebb-b32e76c0ef9a.png)

I am using Mac OSX 10.11.5.

**Comment by TheChrisPratt** [comment]
If you have it installed locally, the ones that are not showing up are the
ones you don't have installed (hence why your browser can't show them to
you).  You can either update your installation to the latest and greatest,
or uninstall it, to see the newly added icons.
