### ISSUE TITLE
Icon Request: Water Droplet / Rain

### ISSUE THREAD

**Issue by MatthewKosloski** [google/material-design-icons#412]
I noticed there are icons like [opacity](https://design.google.com/icons/#ic_opacity) and [location on](https://design.google.com/icons/#ic_location_on) that are in the shape of a droplet; however, I couldn't find one to adequately represent rain or water.  Maybe you could release a 100% filled in version of the mentioned icons?  Thanks!

**Comment by lifewcody** [comment]
I actually need this for a project and it has not been added yet :/ such a bummer

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
