### ISSUE TITLE
add .npmignore

### ISSUE THREAD

**Issue by zweifisch** [google/material-design-icons#413]
The npm package is too large to install... only files in `iconfont` is needed for application usage.

**Comment by BaoDelta** [comment]
+1. It also helps npm publish faster.

**Comment by BaoDelta** [comment]
Related to the 1-year issue #133.

@shyndman I can make a PR for this. What do you think?

**Comment by shyndman** [comment]
I've added this to the v2.3 milestone. I'm going to talk to the team about options.

**Comment by thisconnect** [comment]
Found this while waiting
```
time npm i material-design-icons
⸨             ░░░░░⸩ ⠋ extract:material-design-icons: sill doParall
```

instead of blacklisting via .npmignore you could whitelist the files that should go on npm

https://docs.npmjs.com/files/package.json#files

**Comment by thisconnect** [comment]
```
real	5m44.967s
user	4m23.039s
sys	1m6.336s

node --version
v6.5.0
npm --version
3.10.3

du -hs node_modules/material-design-icons/
356M	node_modules/material-design-icons/
```

**Comment by donaldpipowitch** [comment]
I literally can't install this module. It takes forever on my Mac. It works on others though. I guess it is my harddrive or something which just can't handle so many files :(

**Comment by controversial** [comment]
Any update, @shyndman?

**Comment by RoelN** [comment]
Thanks for pointing this out. The current NPM package is really bloated. We're gathering all feedback and suggestions regarding updating the package in a central issue: https://github.com/google/material-design-icons/issues/1129 Please have a look and see if the package, as published in the way suggested there, would suit your needs.
