### ISSUE TITLE
Add Currency icon, Donate icon,

### ISSUE THREAD

**Issue by Anandsoni14** [google/material-design-icons#414]
- There is symbol of any countries currency symbol.
- No icon for donate option . (As because I wanted to use it in FAB )

**Comment by shyndman** [comment]
I'm going to leave this open, because it would be nice to have currency symbols that match the material style. As an alternative, pasting "$€¥¢" into [Google Fonts](fonts.google.com) then pressing "Apply All" shows a pretty wide range of options.

**Comment by ogarvey** [comment]
Any chance of the UK £ (Pound) sign being added?

**Comment by Rolando-Barbella** [comment]
Would this one be implemented any day? is so essential

**Comment by mikehans9** [comment]
any updates?

**Comment by dirkteucher** [comment]
I hit this problem today and have just created the **UK Pound currency svg icon** - It's available on my profile as open source for anyone to use freely in any of their projects and should fit in nicely with existing material icons as it's 24 x 24  - https://github.com/dirkteucher/UK-Pound-Currency-SVG-MIT .

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
