### ISSUE TITLE
Duplicate icon rv_hookup

### ISSUE THREAD

**Issue by mbrookes** [google/material-design-icons#415]
`rv_hookup` appears in both the `notification` and `places` categories in the library (although the web search only displays it the places category).

**Comment by mindplay-dk** [comment]
This was slated for inclusion in the 2.3 milestone - we're now at 3.0 and still no release?

**Comment by mbrookes** [comment]
Closing as google apparently lack the resources to professionally maintain their OS projects.

**Comment by mindplay-dk** [comment]
@mbrookes follow #724, if you like - I'm working on a complete repackaging of these icons, it'll be announced in that thread when it's done.

**Comment by mbrookes** [comment]
I agree with everything in that thread, and I wish you the best of luck, but my experience with interacting with Googlers in related disciplines is that they are paid too much to care.

Don't get me wrong, it's great that we have use of these resources, but when the community puts time and effort into contributing back, and is completely disregarded? That's just ignorant.

**Comment by mindplay-dk** [comment]
> my experience with interacting with Googlers in related disciplines is that they are paid too much to care

@mbrookes that's not my experience at all, but this project does seem to be abandoned or severely neglected. I haven't been able to even get a reply in #724 so I'm also not trying to interact with the maintainers - instead, the repackaging I'm working on will come as a separate package with this one as a dependency. `¯\_(ツ)_/¯`

**Comment by mbrookes** [comment]
Great! Lets hope they actually publish the icons that are now shown in https://material.io/tools/icons/ it's a but odd to have icons shown that aren't actually available.
