### ISSUE TITLE
License on homepage

### ISSUE THREAD

**Issue by thebigb** [google/material-design-icons#417]
On your [homepage](https://design.google.com/icons/) there is mention of "Apache License Version 2.0", but everywhere else it's CC-BY-4.0. I'm assuming this is a remnant from a license change?

**Comment by stain** [comment]
This is confusing.. also confusing is that the home page (and README) says: 

> The only thing we ask is that you not re-sell these icons.

-- which goes against the [Apache License distribution rights](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution)

> You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
> ..

("do not sell" is also against the CC-BY license - see #424 )

**Comment by marcopashkov** [comment]
We updated the license.

**Comment by Zizouz212** [comment]
@marcopashkov May I inquire as to the change of license? Is their something wrong with CC BY? It would likely be better to have a media focused license (CC) than a software focused license (Apache), at least where my understanding is.

**Comment by jestelle** [comment]
Hi @Zizouz212 
We've had a lot of confusion about licensing of these icons.

We had initially chosen CC BY because of the good fit of a media focused license, and we generally like the ideas the CC supports and pushes through their licensing.

We chose to move to Apache2 to land on a more familiar license that the developers using our icons have likely had experience with before.

This also allows us to use the same license for other resources that we may release related to Material Design, when they aren't just media, but also include code.

I'm happy to talk more about this, especially if the new license causes anyone problems.

Our intention is completely to make it as easy as possible for everyone to use these icons in their applications.  

Cheers,
Josh

PS... I'm not a lawyer :)  If we really need to get into the legal details, I'll have to grab someone from our product consul to help.

**Comment by Zizouz212** [comment]
@jestelle I'm also not a lawyer, but I think the biggest concern is when someone not familiar with software grabs the icons, or modifies them (e.g. changing colours), or anything, looks at the licence and sees definitions such as "Source Code" and "Compiled Object Code" and so on.

Personally, I don't have any objections to changing the licence (I think the Material Design Icons are great, and you are all amazing to share them with everyone), however, I've seen many people confused with the licence. I don't know whether most of that arose from having mentions of different licences in different places (in the repo, and the design page), or whether there was confusion from the licence itself.

Thanks!

**Comment by stain** [comment]
Right, @Zizouz212 your concerns are exactly why Creative Commons were started, to be more media-centered licensed with a "human readable" aspect.  But the implications of CC licenses within a software settings can be confusing, as it then becomes unclear what "derivation" is.
 (particularly if the 'media' is more software-like, like an XML schema or specification).

However the Material Design Icons are made specifically for use in mobile apps - and although I can see potential for use in graphical design works, I am glad that the license now reflects their most common use.

It is something we struggle with within the Apache Software Foundation when [trying to use CC-licensed material](https://www.apache.org/legal/resolved#cc-sa), so I'm happy for this license change.

(BTW - tthere can be the same confusion the other way - e.g. using [Apache 2.0-licensed fonts](http://graphicdesign.stackexchange.com/questions/39592/using-apache-2-licensed-fonts-in-a-logo) in a [commerical work](https://lists.apache.org/thread.html/b812a5429b1b4626b2659c77db7e4f280591e7f5a7b3e579798e3674@1462536100@%3Clegal-discuss.apache.org%3E) - is the font a 'software' (which output is unregulated) or a template (which output is also paritalyl Apache 2.0-licensed)?

**Comment by stain** [comment]
The [index page](https://design.google.com/icons/) still  says 

> The icons are available under the Apache License Version 2.0. 

(no link to https://www.apache.org/licenses/LICENSE-2.0 ?)

> We'd love attribution in your app's "about" screen, but it's not required.

(but where do we put attribution then? Inside code is OK?)

> The only thing we ask is that you not re-sell these icons.

- which as I mentioned is against the Apache License if this is an additional legal reqiurement, but not if it's just a friendly request (in which case "ask kindly" is probably better).

The [README](https://github.com/google/material-design-icons/blob/master/README.md) still says similarly (this time with license link):

> We have made these icons available for you to incorporate them into your products under the Apache License Version 2.0. Feel free to remix and re-share these icons and documentation in your products. We'd love attribution in your app's about screen, but it's not required. The only thing we ask is that you not re-sell these icons.
