### ISSUE TITLE
Icon Request: Upper Left, Upper Right, Lower Left, Lower Right Arrows

### ISSUE THREAD

**Issue by kurisubrooks** [google/material-design-icons#418]
You currently have arrows for Left, Right, Up and Down, but surprisingly you don't have arrows that point Left and Up, Left and Down, Right and Up, nor Right and Down. 

I'd highly appreciate these.

**Comment by RoelN** [comment]
The have been added in the meantime! \o/

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4570664/107750209-feb8ca80-6d1b-11eb-81e1-6185bcebeb50.png">
