### ISSUE TITLE
Icon Request: Elevator, Escalator and Stairs

### ISSUE THREAD

**Issue by kurisubrooks** [google/material-design-icons#419]

**Comment by RoelN** [comment]
<img width="359" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108842706-f729d900-75d9-11eb-8b72-a8e346b0a517.png">

<img width="162" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108842719-fc872380-75d9-11eb-8a98-4b5221debb9e.png">

These have been added in the meantime! \o/
