### ISSUE TITLE
Are the names for ic_volume_off and ic_volume_mute swapped?

### ISSUE THREAD

**Issue by MeoMix** [google/material-design-icons#42]
Hey,

ic_volume_off shows a volume icon with a slash through it. ic_volume_mute shows a volume icon with no volume bars coming out of it and no slash through it.

I think it's common to see a slash through the volume icon when volume is muted. It surprised me to see this associated with 'off' and not 'mute.' Is this intentional?

**Comment by jestelle** [comment]
I believe this is intentional.

It may be to have consistency with things like "videocam" and "videocam off", where the slash definitely makes sense.
