### ISSUE TITLE
Recommended approach for notification badge numbers

### ISSUE THREAD

**Issue by kmturley** [google/material-design-icons#421]
Is there a recommended approach/standard to have an icon with badge numbers?

Example in Android status bar
![icon](https://cloud.githubusercontent.com/assets/1710493/16315946/3fbc05ae-3952-11e6-9f83-7b85dcf8831e.jpg)

Example on Android app icon
![icon2](https://cloud.githubusercontent.com/assets/1710493/16315947/416cd25c-3952-11e6-98af-8e9a4f1eaa21.png)

Obviously we can create these things custom by overlaying an element, or using a psuedo element. But would be great to create one we can all share.

**Comment by Ellorah** [comment]
I was the one who put up the android phone icons. I need someone to help these questions please. Working on an app and I am unable to answer

**Comment by shyndman** [comment]
@jestelle, do we have guidance on this?

**Comment by phidias51** [comment]
If you're using Polymer to develop progressive web apps, you can use the paper-badge component to decorate an icon.  https://elements.polymer-project.org/elements/paper-badge?view=demo:demo/index.html

**Comment by RoelN** [comment]
This would be solved by something outside the icon set of this repo :-) So I'm closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
