### ISSUE TITLE
License confusion: "don't resell the icons" but CC-BY 4.0

### ISSUE THREAD

**Issue by stain** [google/material-design-icons#424]
https://github.com/google/material-design-icons#license says:

> The only thing we ask is that you not re-sell the icons themselves.

but the [Creative Commons Attribution](https://creativecommons.org/licenses/by/4.0/) license says:

> You are free to:
> 
> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
> for any purpose, even commercially.

So if I've downloaded the icons ("the material"), then I should in theory also be allowed to share commercially those icons - at least according to your [LICENSE](https://github.com/google/material-design-icons/blob/master/LICENSE) and if I comply with the attribution requirements.

So is "we ask" in the README just a kind request rather than an additional legal requirement?

I am asking this not because I actually want to sell the icons, but because we want to use the icon in an Apache-licensed app (see apache/incubator-taverna-mobile#18), and a "do not sell" license is incompatible with the Apache License, as it would effectively making it a weak variant of Creative Commons Non-Commercial.

Adding to the confusion is also #417 which claims the license is Apache License instead of CC..

**Comment by Zizouz212** [comment]
It's just text. They don't want you to make money solely by selling their icon. But they want you to make commercial use of the icons within your own commercial software. If you use the icons in `my_software.app`, that's fine. They don't want you to be selling a `google_material_design_icons.zip` for $99.99.

The "do not sell" part is a wish. An intention. But not an actual licence. It's in no way a variant of the CC BY NC licence.

Go on and use them. CC BY 4.0, or Apache, the two of them are compatible.

Don't poison good wishes.

**Comment by aviau** [comment]
We may include some material design icons in Debian soon, and the "do not re-sell" clause would make them non-free.

Could this be clarified in the README?

**Comment by johnkhuong** [comment]
$$$ Hello All Customers On The Worldwide $$$

— I'm Silver.Leading (Hacker Anonymous RUSSIA),Back Private Sell CVV USA + UK
— Verified Business and Looking for Buy and Sell
— Always selling stuff high quality 
— We will share with you all what we have and you too
— I'm looking for good buyer for long time business and make money together..Please No bargain,work quickly. 
— I'm sure you will happy if bussiness with me.
— My business to the top prestige,cooperate with us you will have a better life

--------- PRODUCT LIST ----------

#1) Sell CVV,CCN,CVV2,With VBV,NON VBV,Bin, MASTER CARD | VISA | AMEX |DISCO
#2) Card Dumps Track 101 + 201 with pin ATM
#3) Sell Fullz Info SSN/DOB verified (Name + Adresss + City + State + Fone + SSN + DOB)

===========================
- CONTACT ME FOR SUPPORT:

—> ICQ: 710898851
—> SKYPE : JohnKhuong
—> GMAIL: khuongngocha91@gmail.com

- VISA + MASTER = 6$ per 1
- AMEX + DISCOVER = 8$ per 1
- BIN = 8$ per 1 
- FULLZ INFO = 60$ per 1

=> CREDIT CARD UNITED KINGDOM :

- VISA + MASTER = 12$ per 1
- AMEX + DISCOVER = 15$ per 1
- BIN = 17$ per 1 
- FULLZ INFO = 70$ per 1

=> CREDIT CARD CANADA :

- VISA + MASTER = 8$ per 1
- AMEX + DISCOVER = 10$ per 1
- BIN = 15$ per 1 
- FULLZ INFO = 60$ per 1

=> CREDIT CARD AUSTRALIA :

- VISA + MASTER = 15$ per 1
- AMEX + DISCOVER = 18$ per 1
- BIN = 20$ per 1 
- FULLZ INFO = 60$ per 1

==>> CREDIT CARD EUROPE:

- VISA + MASTER = 25$ per 1
- AMEX + DISCOVER = 28$ per 1
- BIN = 27$ per 1 
- FULLZ INFO = 60$ per 1

(Portugal/France/Germany/Spain/Italy/Norway/New Zealand/Turkey/Denmark/Switzerland/Sweden/Ireland/Belgium/Netherlands)

==>> CREDIT CARD ASIA :

- VISA + MASTER = 30$ per 1
- AMEX + DISCOVER = 34$ per 1
- BIN = 32$ per 1 
- FULLZ INFO = 60$ per 1

(Indonesia/Japan/Saudi Arabia/South Korea/India/Singapore/Malaysia/Philipines/Taiwan/China)

=> DEMO UNITED STATES:
5491237219943480|6/2018|615|KIMBERLY LAWHORN|234 Mountain meadow dr|TUSCOLA|TX|79562|United States|575-491-0455

=> DEMO UNITED KINGDOM:
4659411281146279|2/2019|252|Martin Sammtleben|16 St Leonards Way|Woore||CW3 9ST|United Kingdom|+44 (0)1630 647828

=> DEMO CANADA:
5193223700334182|6/2017|204|Jeff Alden|44 St. George st.|Aylmer|Ontario|N5H2M1|Canada|519 773 7434

=> DEMO AUSTRALIA:
4622390371373007|2/2017|330|margot watson|2 stanhope court|south yarra|vic|3141|Australia|+61 427256486

>>>>>DEMO CREDIT CARD FULLZ INFO USA

Name: Gina Burgess
DOB: 5/5/1971 (DD/MM/YYYY)
Email: gburgess@dentonisd.org ()
Password: allie5577
Address: 728 Dove Ridge, , 76266, Tx, United States
Name on Card: GINA BURGESS
Card: 5376880001394238
CCV2: 208
Expiry Date: 07 / 18
Card Issuer: (US)
Card Type: MASTERCARD CREDIT
Account No: 0572479
Account Sortcode: 111906006
Security Question: Mothers Maiden Name
Security Answer: Palumbo
Billing Telephone: 9402312238
SSN: 455257520
Client IP: 71.48.168.211 (United States)
Browser & OS: Apple Safari (mac)
Full Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1

>>>>>DEMO CREDIT CARD FULLZ INFO UK :

+ Personal Information
| Full name : dean jason warburton
| Date of birth : 06/06/1979
| Address : 33 hounsfield road, rotherham, s653qa
| Phone : 07583702511
| Email : warbodj@hotmail.co.uk | MMN : nixon
| National Insurance : jp476250c
| Driving No : warbu700669dj9wx
+ ------------------------------------------+
+ Billing Information
| Card BIN : 475128
| Card Bank : NATIONAL WESTMINSTER BANK PLC
| Card Type : VISA DEBIT
| Cardholders Name : mr dean j warburton
| Card Number : 4751280207870941
| Expiration date : 05 / 17
| CVV : 269
| Acc No : 14691485
| Sortcode : 60 - 18 - 02
+ ------------------------------------------+
+ Victim Information
| IP Address : 82.132.218.208 (82-132-218-208.dab.02.net)
| Location: , , United Kingdom
| UserAgent : Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 1320) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
| Browser : Safari
| Platform : Android

>>>>>DEMO CREDIT CARD FULLZ INFO USA

Name on Card: Susan Myers
Billing Address: 508-313 MacDonald Ave
City: Sault Ste. Marie
Zip/Postal code: P6B5Y9
Phone Number: 705.941-1785
Date Of Birth: October 03, 1975
Mothers Maiden Name: Khan
Social Insurance Number: 658862453
Drivers Liscense Number: 3956348
Years at Current Address: 16
Bank: CANADIAN IMPERIAL BANK OF COMMERCE
Card Type : CREDIT
Card Number: 4500030103551093
Expiration Date Year: 2016
Expiration Date Month: 04/2018
Cvv Code: 998
Latitude and Longitude 60 -95
Card Sub Brand
Card Category INFINITE
Query Time 305.805us

========= SELLING CARD DUMPS + TRACK 1/2 WITH PIN =========

Verified Business =>| http://sell-cvv-usa.forumprod.com/forum.php |

Types Card Dumps : (Visa) , (Master), (Amex), (Discoveri Gold)
(Master Standart) , (Platinum) , (Business Card)
(Cooperation Card) , (American Express) , (Debit Card)

- Dumps...Tracks 1&2 with PIN US = $100 per 1
- Dumps...Tracks 1&2 with PIN UK = $120 per 1
- Dumps...Tracks 1&2 with PIN CA = $120 per 1
- Dumps...Tracks 1&2 with PIN AU = $130 per 1
- Dumps...Tracks 1&2 with PIN EU = $140 per 1
- Dumps...Tracks 1&2 with PIN China = $150 per 1

Track 1: 4782009999506014^KOSNIEWSKI/PAMELA M^16111010000000208000000
Track 2: 4782009999506014=16111010000020800000
(101) - VISA CLASSIC - JPMORGAN CHASE BANK N.A.

Track1: 4266841355472976^BLANCHARD/MICHAEL ^17031011000011000000008240000001
Track2: 4266841355472976=170310110000824
(101) - VISA PREMIER - CHASE BANK USA N.A.
United States, TX, Austin, 78744

Pin: 4271, 4185, 5140, 5268...and many Pin other

We will check with high balance
Will send dumps to you immediately after we receive your payment for the order
I always replace bad, declined dumps
Replacement of invalid dumps can be made within 3days

- Demo Dumps - Track 1/2 :

DEMO :- Track1=5232556061018719WYATT/ROBERTSON1007101171410000271000000 
- Track2=5232556061018719=10071011000042400000 
Record #00928... 
Tue Oct 16 08:54:42 2012 
Track 1: B4313084818968669^techer/limicher^0809201000000000000002070000000 
Track 2: 4313084818968669=08092010000000000001 
PIN:5407

Record #00929... 
Tue Oct 16 08:56:05 2012 
Track 1: B5120255004093674^gorge linuz^0909201225000000000000000000000 
Track 2: 5120255004093674=09092012250000000000 
PIN:0843 
6011001020701234=19011011001602310902 ; B6011001020701234^MCCARTHY/TALENEK ^19011011001602310902
DEMO : 
4388576046879188=150410110000340

4388576045468579=150910119923287
4147202138234560=161010110000714
4342562053558183=16101010000000814
5462130086460032=17051010154300095500
4815821012014235=18031010000000000131
4147404101927374=161220110000341
CONTACT: 
4282087045352307=14101010000060800000
371535120241001=171210114011364200000
4833160058536472=17041010000007500000
4388576067952054=160610110000204
4264289830274116=16101010000040700100
CONTACT: 
5462130015128312=16051010696200084300
4815820058327238=18071010000000000500
4301790002901712=1703101467802380
CA

4815820034356160=17081010000000000937
4342562120649346=15021010000000772
CONTACT: 
4217642511183923=16011013366102600000
5115164025426656=16071210485115164025
4833160062338923=17061010000034000000
4833160050296430=17051010000066800000
CONTACT: 
4815830014824707=18071010000000000698

===========================
- CONTACT ME FOR SUPPORT:

—> ICQ: 710898851
—> SKYPE : JohnKhuong
—> GMAIL: khuongngocha91@gmail.com

**Comment by medicalwei** [comment]
I am also doing packaging for a project (https://github.com/trufont/trufont) which also uses one icon from this project and I am still wondering if "do not resell" part is part of the license or not, although this project itself lists the icon as CC-BY 4.0 (probably an old license?)

**Comment by RoelN** [comment]
Please follow this PR for progress on the issue: https://github.com/google/material-design-icons/pull/605
