### ISSUE TITLE
Sizes, Colors don't work? Am I missing something. 

### ISSUE THREAD

**Issue by rjain-pivotal** [google/material-design-icons#429]
```
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

</head>

<body>
  <div>
    This is a test page
    <p>
    <i class="material-icons">face</i>
    <i class="large material-icons">face</i>
    <i class="material-icons md-18">face</i>
    <i class="material-icons dark">face</i>
    </p>
  </div>
</body>
```

----
I see all the icons are same, there is not style applied. Am I doing something wrong or is this not working?

**Comment by shyndman** [comment]
Hi @rjain-pivotal,

Google Fonts will only send CSS containing the bare minimum to render the icon font (`@font-face` and `.material-icons` rules). If you want to style the icons, you'll have to do it in your own CSS.

**Comment by rjain-pivotal** [comment]
I got the answer, I have to use CSS like   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
