### ISSUE TITLE
Duplicte icons : ic_settings_input_composite and ic_settings_input_component

### ISSUE THREAD

**Issue by hfactor** [google/material-design-icons#431]
I can't visually find any difference between [ic_settings_input_composite](https://design.google.com/icons/#ic_settings_input_composite) and [ic_settings_input_component.](https://design.google.com/icons/#ic_settings_input_component) Any reason behind having a duplicate icon?

**Comment by tphinney** [comment]
You are right that they are/were duplicates! Both are still supported in Material Icons to this day.

However, this duplication (among many others!) was noted when we refactored the icons for Material Symbols, so in that version, there is only the "component" version. In the Material Symbols variable font the codepoint and name of the old one is still supported, although there is only one glyph that both versions go to.
