### ISSUE TITLE
Update Accessible Icon

### ISSUE THREAD

**Issue by LucyWilcox** [google/material-design-icons#433]
I think it would be really great if you updated your accessible icon to something more like this:

![blackicon](https://cloud.githubusercontent.com/assets/10675363/17004279/4b22b216-4ea2-11e6-8114-049fe5dc810c.jpg)

I don't know if your familiar with this icon, you can find more information on it here: http://accessibleicon.org/

I realize that there are a lot of factors that go into choosing icons, and that using this exact one may not work or need visual updates, though this icon is in the public domain.

This icon conveys movement. It conveys ability, unlike the frozen, incapable, meaning imparted by the current accessible icon. I think it's a lot more respectful of this community.

Anyways food for thought!

**Comment by sebastienvermeille** [comment]
:+1:

**Comment by RoelN** [comment]
Looks like this has been added!

<img width="404" alt="image" src="https://user-images.githubusercontent.com/4570664/107636435-e9389780-6c6c-11eb-9d04-6a0486238d0f.png">
