### ISSUE TITLE
Icon request: Wifi icons for different signal strengths

### ISSUE THREAD

**Issue by MarcelRobitaille** [google/material-design-icons#434]
It would be great to have a set of icons for wifi signals of 1 to 4 bars similar to what IcoMoon - Ultimate has as seen here: ![Example](http://i.imgur.com/ZOwcn7F.png)

**Comment by amerkurama** [comment]
YY也一样，，，，，，，

**Comment by WebMaestroFr** [comment]
```html
<i class="material-icons">signal_wifi_4_bar</i>
```
Icon for full signal works "fine", or at least like shown on https://design.google.com/icons/ (shape is filled, and does not actually shows "bars").
```html
<i class="material-icons">signal_wifi_3_bar</i>
<i class="material-icons">signal_wifi_2_bar</i>
<i class="material-icons">signal_wifi_1_bar</i>
<i class="material-icons">signal_wifi_0_bar</i>
```
These ones are all showing "three bars" and do not behave like "inline" elements. They seem to be here though : https://github.com/google/material-design-icons/blob/master/device/svg/production/ic_signal_wifi_3_bar_48px.svg. So maybe there is a trick ?

**Comment by NicholasAsimov** [comment]
Wonder this also, why actual font doesn't include signal_wifi_1-3_bar icons even though they're designed and available?

**Comment by tjmcclure0501** [comment]
Still seems to be th same any ideas for getting icons to show different strengths?

**Comment by NicholasAsimov** [comment]
@tjmcclure0501 what I did in the end is to import individual SVG icons and then writing a function that determines what icon to return as a JSX element. Here's an example 

```javascript
import WifiSignal0Icon from 'material-ui/svg-icons/device/signal-wifi-0-bar';
import WifiSignal1Icon from 'material-ui/svg-icons/device/signal-wifi-1-bar';
import WifiSignal2Icon from 'material-ui/svg-icons/device/signal-wifi-2-bar';
import WifiSignal3Icon from 'material-ui/svg-icons/device/signal-wifi-3-bar';
import WifiSignal4Icon from 'material-ui/svg-icons/device/signal-wifi-4-bar';

import WifiSignalLock1Icon from 'material-ui/svg-icons/device/signal-wifi-1-bar-lock';
import WifiSignalLock2Icon from 'material-ui/svg-icons/device/signal-wifi-2-bar-lock';
import WifiSignalLock3Icon from 'material-ui/svg-icons/device/signal-wifi-3-bar-lock';
import WifiSignalLock4Icon from 'material-ui/svg-icons/device/signal-wifi-4-bar-lock';

// Full filled wifi icons in case we couldn't determine network quality
import WifiIcon from 'material-ui/svg-icons/device/network-wifi';
import WifiLockIcon from 'material-ui/svg-icons/device/wifi-lock';

getWifiIcon = (wifiSpot) => {
        const quality = this.calculateWifiSignal(wifiSpot.quality);

        if (wifiSpot.isProtected) {
            switch (quality) {
                case 0:
                    return <WifiLockIcon />;
                case 1:
                    return <WifiSignalLock1Icon />;
                case 2:
                    return <WifiSignalLock2Icon />;
                case 3:
                    return <WifiSignalLock3Icon />;
                case 4:
                    return <WifiSignalLock4Icon />;
                default:
                    return <WifiLockIcon />
            }
        } else {
            switch (quality) {
                case 0:
                    return <WifiSignal0Icon />;
                case 1:
                    return <WifiSignal1Icon />;
                case 2:
                    return <WifiSignal2Icon />;
                case 3:
                    return <WifiSignal3Icon />;
                case 4:
                    return <WifiSignal4Icon />;
                default:
                    return <WifiIcon />
            }
        }
    };
```

And then you call this function to give you an icon to pass to a FlatButton, for a example.

```javascript
<FlatButton
    label="Example"
    icon={getWifiIcon(spot)}
/>
```

Not the most elegant solution but it works, until maybe we have this issue fixed.

**Comment by emouawad** [comment]
No Progress on this?

**Comment by aleki** [comment]
Will this be fixed?

**Comment by lepirlouit** [comment]
icons are there,. there are missing in the font.

**Comment by AnaRobynn** [comment]
Not sure if I should piggyback on this issue or create a new one.
The NetworkWifi icon: https://material.io/icons/#ic_network_wifi is exported as 
![ic_network_wifi_black_24dp_2x](https://user-images.githubusercontent.com/24815061/39698899-0a8e64fc-51f7-11e8-964e-5c855f015925.png).

If anyone can point me in the right direction I can fix it myself, but I'm unfamiliar with the repository and a quick github search for network didn't yield much results, besides styling.

**Comment by lepirlouit** [comment]
I don't know how the font is created.

**Comment by pflammertsma** [comment]
@shyndman I don't believe this is merely an icon request; `signal_wifi_0_bar` and others are listed on the material.io website but are missing from the package. Oddly, `signal_wifi_4_bar` is the only one of the set that is included.

Specifically, these are missing:

- signal_wifi_0_bar
- signal_wifi_1_bar
- signal_wifi_1_bar_lock
- signal_wifi_2_bar
- signal_wifi_2_bar_lock
- signal_wifi_3_bar
- signal_wifi_3_bar_lock
- signal_wifi_4_bar_lock

<img width="1132" alt="screen shot 2018-06-17 at 13 35 22" src="https://user-images.githubusercontent.com/286051/41507481-6eca2670-7233-11e8-8bd1-6015fbf86516.png">

**Comment by mazeeblanke** [comment]
any update ?

**Comment by selfcatering** [comment]
Same story with cellular icons, only signal_cellular_4_bar works

**Comment by Fmstrat** [comment]
Man I just spent a ton of time playing with the font to find this out. Ugh.

**Comment by Fmstrat** [comment]
I found this to be a useful solution: https://github.com/dcousens/material-wifi-icons

**Comment by bmxguy100** [comment]
https://github.com/google/material-design-icons/blob/master/iconfont/codepoints#L763
It looks like the icons should be at 0xE1D1 to 0xE1D7...
There is also space for the cellular icons.

**Comment by rikkertkoppes** [comment]
It is actually buggy now. If you for example use `signal_wifi_1_bar_lock` as an icon, you will end up with a `wifi` icon and a `lock` icon by the power of ligatures, with all the other letters as whitespace in between:

![image](https://user-images.githubusercontent.com/302821/45830338-34009000-bcfd-11e8-825e-a1184b22bc5e.png)

**Comment by RUSSCITY** [comment]
Please fix it. It still be wrong.

**Comment by aguegu** [comment]
not even included in 4.0.5, why?

**Comment by dmvvilela** [comment]
Nothing on this yet? Ive downloaded the SVG from material design website and made my own icons with fluttericon.com..

**Comment by zSucrilhos** [comment]
It'll be good to have that as well...

**Comment by rikkertkoppes** [comment]
It's a shame no one is addressing this, but I think the reason the icons are not included in the font is that it is a two-tone image, which is not possible for a font. This would also be the reason cellular and battery intermediate icons are also missing.

I see two options to solve this:

1. get rid of the semitransparent part and make the icon monotone
2. solve the two-tone with a css trick, by overlaying a pseudo-element with a different ligature and some transparency, something like this:

```
.material-icons.signal_wifi_2_bar::before {
    content: "signal_wifi_transparent_background";
    position: absolute;
    z-index: -1;
    opacity: 0.3;
}
```

Resulting in something like this: 
![image](https://user-images.githubusercontent.com/302821/59329260-c8c57680-8cee-11e9-9d56-19ae70c24291.png)

**Comment by dejwk** [comment]
> It's a shame no one is addressing this, but I think the reason the icons are not included in the font is that it is a two-tone image, which is not possible for a font. This would also be the reason cellular and battery intermediate icons are also missing.
> 
> I see two options to solve this:
> 
> 1. get rid of the semitransparent part and make the icon monotone [like these](https://github.com/dcousens/material-wifi-icons)
> 2. solve the two-tone with a css trick, by overlaying a pseudo-element with a different ligature and some transparency, something like this:
> 
> ```
> .material-icons.signal_wifi_2_bar::before {
>     content: "signal_wifi_transparent_background";
>     position: absolute;
>     z-index: -1;
>     opacity: 0.3;
> }
> ```
> 
> Resulting in something like this:
> ![image](https://user-images.githubusercontent.com/302821/59329260-c8c57680-8cee-11e9-9d56-19ae70c24291.png)

I don't think it's two-tone. These PNGs are actually present in 3.0.2, by the way. The lighter part is simply semi-transparent.

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons

**Comment by dmvvilela** [comment]
Awesome!

![Captura de Tela 2022-02-01 às 12 00 20](https://user-images.githubusercontent.com/8460696/151993186-12d1747b-b6b7-4ff4-aa75-bf137447b6f7.png)
