### ISSUE TITLE
Icon request: excel file

### ISSUE THREAD

**Issue by sabinebarrera** [google/material-design-icons#437]

**Comment by thormentor** [comment]
I wander if you have any timeline for this issue to be solved? There are any plans to add this icon to material design?

**Comment by Riz-waan** [comment]
I would also like a spreadsheet icon to be added.
I am having to use letters instead, for PDF as well.

**Comment by rockstarwebdesign** [comment]
Yes, Excel, Word and PDF document icons would be super useful.

**Comment by demiro** [comment]
YES, icons for file types like pdf, excel, word, html, etc.... are really needed

**Comment by RoelN** [comment]
Would any of these be sufficient to show a spreadsheet/Excel file?

<img width="311" alt="image" src="https://user-images.githubusercontent.com/4570664/107637238-189bd400-6c6e-11eb-8df4-596ca1f72d24.png">

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
