### ISSUE TITLE
Are there any plans for sport related icons?

### ISSUE THREAD

**Issue by alexdd55** [google/material-design-icons#44]
I love the set and it would be great if you could add some sports related icons like:
- Standings
- Scores
- Bench / Replacements /Substitutians
- Starters
- Trades
- Sign Player
- Release Player
- Team / Roster
- Injuries
- Draft

Just some ideas :)

**Comment by Kasijjuf** [comment]
See also  #167

**Comment by Fonsos** [comment]
I'm getting them from here: https://ssl.gstatic.com/heart/images/ic_SPORT.png
Where you have to change SPORT to the sport name you are looking for. Always in lowercase.
In case there is a two word sport use de underscore
Then you have to vectorize the png

Example: 
water polo
https://ssl.gstatic.com/heart/images/ic_water_polo.png

**Comment by Cottin** [comment]
@Fonsos nice :) I get almost everything I want.
What would the license be on these, I'm guessing we aren't really allowed to use them, right?

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
