### ISSUE TITLE
Icon request: word file

### ISSUE THREAD

**Issue by sabinebarrera** [google/material-design-icons#441]

**Comment by sabinebarrera** [comment]
Thanks @shyndman. How long does it take until you guys can publish an icon?

**Comment by shyndman** [comment]
Hey @sabinebarrera,

The icons we produce are by request for teams at Google. Occasionally we'll find the time to design a couple icons that have been requested on Github, but we can't make any guarantees that we'll get to this one.

**Comment by pordux** [comment]
this icon is ready to use from https://materialdesignicons.com/ take a look and search for  "word"

**Comment by demiro** [comment]
YES, icons for file types like pdf, excel, word, html, etc.... are really needed

**Comment by abohosam1772** [comment]
@

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
