### ISSUE TITLE
Icon ic_add_white in folder Content not white

### ISSUE THREAD

**Issue by joielechong** [google/material-design-icons#442]
Not every Icon ic_add_white in folder Content is white. Only in mdpi folder the icon is white. But in hdpi, xhdpi, xxhdpi, and xxxhdpi, the icon is white with black background.

**Comment by Abdullah2993** [comment]
+1

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
