### ISSUE TITLE
Icon request: Clear search or search off

### ISSUE THREAD

**Issue by vanshg** [google/material-design-icons#444]
Something that indicates that you wish to clear a search query or disable search. I was thinking the normal search icon with a slash through it

**Comment by pordux** [comment]
Normally for clear an input field you will use  the "cancel" or "clear" icon from https://design.google.com/icons/

**Comment by vanshg** [comment]
It doesn't suit my needs and doesn't make sense to have a cancel or clear button in my application's context

**Comment by jeffjonez** [comment]
We have some documents in our system that aren't OCRed or digital text, so they're unsearchable. I'd like a "search off" icon too, so the search function will show search isn't available.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
