### ISSUE TITLE
Icon Request: web technologies

### ISSUE THREAD

**Issue by cercos** [google/material-design-icons#445]
Icons for popular brands and icons for different web technologies (PHP, CSS, HTML, Javascript, etc..)

**Comment by RoelN** [comment]
Changing this issue to be about one subject at a time. Brand-related icon requests can be tracked in https://github.com/google/material-design-icons/issues/1147

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons

**Comment by tphinney** [comment]
That is, these icons are now in Material Symbols and Material Icons both.
