### ISSUE TITLE
SVG icons look bad for me

### ISSUE THREAD

**Issue by rpgdev** [google/material-design-icons#447]
I use ubuntu 14.04 and maybe something it's wrong with my setup but many svg icons look awful. Be it the ones downloaded from here or doing it via: https://design.google.com/icons/

This is how the search looks for me in both: http://i.imgur.com/7YbYeGL.png And there are many others that look defective like that.

**Comment by shyndman** [comment]
Hey @rpgdev,

Do they look that way in the browser?

**Comment by rpgdev** [comment]
That was on the default image viewer on ubuntu. I opened the icon on the browser and it looks fine both on firefox and chrome. It also looks bad on GIMP though so I don't know what could be the issue. I had never had any issues with any svg files before.

**Comment by shyndman** [comment]
Hey @rpgdev,

I'm afraid the issue lies with GIMP, not the SVGs. I recommend that you file a bug here: https://www.gimp.org/bugs/

**Comment by rpgdev** [comment]
@shyndman as I made clear it isn't only GIMP but also on the default image viewer but since you seem eager to ignore the issue then ok. Just ignore it.

**Comment by shyndman** [comment]
Hey @rpgdev,

Didn't mean to come off that way. I was just pointing out that the SVG is valid and that most software displays it correctly. The bug lies elsewhere. I imagine that the developers behind GIMP or the system viewer would be interested in getting their software fixed.
