### ISSUE TITLE
YouTube icon request

### ISSUE THREAD

**Issue by MalMinks35** [google/material-design-icons#448]
Could you please make a YouTube icon and maybe other Google services

**Comment by Akhilesh28** [comment]
@MalMinks35 I would like to try it. Any suggestion on where I could get started?

**Comment by MalMinks35** [comment]
@Akhilesh28 I found a bunch of good icons here.
https://materialdesignicons.com/icon/
Unfortunately as far as I could tell the easiest way to use them in a webpage was via SVG images. If there was some icons like youtube and other services in the Google material design icon library it would be nice cause they are really easy to use and act as text not an image like svg's do.

**Comment by Nar6** [comment]
I sugest to start here : https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by MahMoos** [comment]
No Youtube icon is available yet. I wonder why is that?!
