### ISSUE TITLE
Using with React-toolbox. Icons for buttons display incorrectly for the local copy.

### ISSUE THREAD

**Issue by nagarajay** [google/material-design-icons#449]
Any specific reason to keep weight: 1em and height: 1em for material-icons css class.
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /\* Preferred icon size */
  display: inline-block;
  width: 1em; --> Problems due to this and height in React-toolbox 
  height: 1em; -->
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

I removed the same and it works perfectly. Also the online link does not have these properties. Check https://fonts.googleapis.com/icon?family=Material+Icons.
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}

Thanks

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
