### ISSUE TITLE
Icon Request: Pin icon

### ISSUE THREAD

**Issue by jolenekernick** [google/material-design-icons#450]
Can you please create an icon for a "pushpin" just like the one you use to "pin" your emails in Google Inbox?

**Comment by kalehv** [comment]
Any update on this?

**Comment by mbritton** [comment]
+1

**Comment by kgcmd** [comment]
+1

**Comment by dustinpoissant** [comment]
+1

**Comment by mbreining** [comment]
+1

**Comment by mbritton** [comment]
I recreated the pushpin. Shall I push it?

**Comment by mkhahani** [comment]
+1

**Comment by nicholas-davis** [comment]
+1

**Comment by bduyng** [comment]
+1

**Comment by McUrbn** [comment]
+1

**Comment by francosioquim** [comment]
+1

**Comment by saschb2b** [comment]
+1

**Comment by am1n** [comment]
+1

**Comment by Sind** [comment]
+1

**Comment by conan06** [comment]
+1

**Comment by manuelrego27** [comment]
+1!

**Comment by canvasplay** [comment]
+1

**Comment by lillamiu** [comment]
+1

**Comment by LuisTr6** [comment]
+1

**Comment by ginlime** [comment]
+1

**Comment by mbritton** [comment]
I tried to push the push pin / But 'twasn't meant to be / Auto-generated are they / From something else, you see

**Comment by benoitbc** [comment]
+1

**Comment by jfuehner** [comment]
+1

**Comment by malikshahzad228** [comment]
+1

**Comment by jolenekernick** [comment]
Hey Google, how many people have to want this for you to make it happen???

**Comment by mbritton** [comment]
[Pin](https://github.com/mbritton/material-ui/blob/master/src/svg-icons/maps/push-pin.js)

**Comment by mkhahani** [comment]
@mbritton 
Thanks for the contribution. Would you please let me know how to use it? Just include the js file? Is there any dependencies?

**Comment by mbritton** [comment]
[Something like this](https://gist.github.com/mbritton/dfd24533e5b2ac5a1890aeeb20cafd52)

**Comment by mbritton** [comment]
My PR has already been declined.

**Comment by XvKnightvX** [comment]
any news on if this is going to happen? need an icon for pinned icons but cant find anything i can really use from the material.io site. As previously stated it has been used in google apps so is there another way to get the icon or have they simply not updated the site?

**Comment by joydeepsaha05** [comment]
Download the Google Inbox apk file and extract using any archive manager. The .png file should be under `res -> drawable`
There may be multiple "drawable" folders for different screen densities so check them all.

**Comment by kalehv** [comment]
@joydeepsaha05 I'd guess doing that would be a violation of license. Inbox app and it's not-open-source resources may not be free to use. Also, this repo is not only for Android icons.

**Comment by joydeepsaha05** [comment]
@kalehv Ah yes, forgot about licences, do check beforehand. I also had an SVG I'd made ultimately, will upload it.

**Comment by demisx** [comment]
Please, add it. Absence of pin icon forces us to use another icon library along with material icons.

**Comment by mbritton** [comment]
I tried and was denied. With enough encouragement, I'll try again.

**Comment by ginlime** [comment]
@mbritton I guess it is better to submit just an entity of SVG file...

**Comment by mbritton** [comment]
[Here's an SVG](https://gist.github.com/mbritton/cbb8bfeb022975fb96572766f68f0788)

**Comment by montijr2007** [comment]
+1 - I need a pin...

**Comment by ghdrn11** [comment]
+1

**Comment by mlchevallier** [comment]
+1

**Comment by ZiperRom1** [comment]
Why there is no "pin" icon srly ??

**Comment by jvalst** [comment]
Need that pin as well...

**Comment by misterbridge** [comment]
+1

**Comment by avidalnaquet-hiventy** [comment]
+1

**Comment by gchardon-hiventy** [comment]
+1

**Comment by DennisSangmo** [comment]
+1

**Comment by eurakilon** [comment]
+1

**Comment by googlechick** [comment]
+1

**Comment by AndreNalevaiko** [comment]
+1

**Comment by giraudvalentin** [comment]
+1

**Comment by mbritton** [comment]
Hey pin peeps! [This is the new pin hangout thread.](https://gist.github.com/mbritton/cbb8bfeb022975fb96572766f68f0788) Peace and love, peace and love.

**Comment by bjm88** [comment]
+1

**Comment by rgbskills** [comment]
+1

**Comment by caub** [comment]
Let me 📌 this thread for later, seriously material-ui, add it

**Comment by mahekmshah** [comment]
please add 📌

**Comment by marxlow** [comment]
Any updates or alternatives?

**Comment by jayalakshmi-rm** [comment]
+1

**Comment by skhalik** [comment]
Please add pin icon

**Comment by Luc-Olsthoorn** [comment]
Still want it

**Comment by anthonyekosky** [comment]
+1, please add a pin icon (📌)

**Comment by RoelN** [comment]
There's a push pin icon now! \o/

<img width="681" alt="image" src="https://user-images.githubusercontent.com/4570664/107620542-285aee80-6c55-11eb-972d-08cc5047ab79.png">

**Comment by bct-fbo** [comment]
Would be awesome if there was an unpin icon too!

**Comment by pbarber** [comment]
> Would be awesome if there was an unpin icon too!

Maybe you could use the outlined/unfilled icon to unpin?

**Comment by mesutyigit** [comment]
+1

**Comment by joelcoxokc** [comment]
I hate to ask more on this... 
But is there anyway you could also add unpin to the icon set. 

I noticed that it is in the material-symbols, but unpin is not in the icon font set

**Comment by tphinney** [comment]
Just to clarify, there are two icon font sets, for Material Symbols (the new/current set) and Material Icons (the classic set).

Unpin *is* in Material Symbols, both in the icon font and the set of individual icons.

It is not currently in Material Icons, though. Please open a separate issue if that is important to you.

**Comment by vishalpatel1327** [comment]
what about Unpin icon ?

**Comment by tphinney** [comment]
What about it?
See my comment from a year ago.

**Comment by dsl101** [comment]
I'm not seeing it, in either Symbols or Icons. Unless it has another name?

![image](https://github.com/google/material-design-icons/assets/900542/91258657-af43-404e-a698-86de9abad689)

**Comment by vishalpatel1327** [comment]
That's the common thing if you Pin something that you have to unpin also. any use cases. 
google uses it like Message App then why is it not providing in material icons?
