### ISSUE TITLE
Slow Motion Video Icon does not match Download File

### ISSUE THREAD

**Issue by SierraSchultz** [google/material-design-icons#451]
Downloading slow motion video icon PNGS file results in icon with wider, right facing arrow rather than the icon shown. See Image attached for file resulting from download.
![ic_slow_motion_video_black_24dp_1x](https://cloud.githubusercontent.com/assets/20111522/17752308/cdf3958a-6490-11e6-832c-598d82c98ac9.png)

**Comment by jestelle** [comment]
Interesting bug.
I actually think the downloaded asset is the intended icon, and what you're seeing in the gallery is a bug in our icon font.

We'll look into it.  @shyndman can you have a look?

**Comment by jestelle** [comment]
Confirmed.  The SVG and PNGs are correct.  The icon font is incorrect.

**Comment by damidina** [comment]
any progress on this? cc: @aboutjon

**Comment by tphinney** [comment]
Well, everything now matches the image shown above. So if that is "the intended icon” per jestelle’s comment, I believe at some point it was all fixed.
