### ISSUE TITLE
Getting callback error when installing via npm

### ISSUE THREAD

**Issue by gokulkrishh** [google/material-design-icons#453]
Installing via npm throws a cb() error

**node:** v5.9.1
**npm:** v3.7.3

**command:** npm i material-design-icons

**_screenshot:_** 
<img width="856" alt="screen shot 2016-08-18 at 1 47 41 pm" src="https://cloud.githubusercontent.com/assets/2944237/17766775/6060a4d0-654a-11e6-97c5-0e272c957da8.png">

**Comment by shyndman** [comment]
Hi @gokulkrishh,

This seems to be an issue with npm, not the repo. Take a look at http://stackoverflow.com/questions/15393821/npm-err-cb-never-called

I was unable to reproduce. I'm running:
node: v6.2.2
npm: v3.9.5
