### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by svachmic** [google/material-design-icons#455]
Seems like there is some inconsistency between license [in the repo](https://github.com/google/material-design-icons/blob/master/LICENSE) and license [on the web](https://design.google.com/icons/). Even though they might seem compatible at first sight, there are big differences under the hood and [are **not** compatible](http://programmers.stackexchange.com/questions/170185/is-creative-commons-license-compatible-with-apache-license). I believe this could be easily fixed, but I am not the one that can make the call which one to use. 😉

**Comment by marcopashkov** [comment]
We updated the license.
