### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by martinvano** [google/material-design-icons#457]
ic_notifications_white is missing svg and xml version, ic_notifications_off_white is missing also missing svg and xml versions. The latter one can be recreated from ic_notifications_active.xml by changing the color and removing a few paths like this:
`    <path
        android:fillColor="#FFFFFF"
        android:pathData="10.5h2c0.15,-2.65 1.51,-4.97 3.55,-6.42zM19.97,6.42zM18,11c0,-3.07 -1.64,-5.64 -4.5,-6.32L13.5,4c0,-0.83 -0.67,-1.5 -1.5,-1.5s-1.5,0.67 -1.5,1.5v0.68C7.63,5.36 6,7.92 6,11v5l-2,2v1h16v-1l-2,-2v-5zM12,22c0.14,0 0.27,-0.01 0.4,-0.04 0.65,-0.14 1.18,-0.58 1.44,-1.18 0.1,-0.24 0.15,-0.5 0.15,-0.78h-4c0.01,1.1 0.9,2 2.01,2z"/>
`

**Comment by jestelle** [comment]
SVGs are here:
https://github.com/google/material-design-icons/tree/master/social/svg/production

XML is here:
https://github.com/google/material-design-icons/tree/master/social/drawable-anydpi-v21
We only include the 'black' but you can use drawable tinting to change the color.
https://developer.android.com/training/material/drawables.html

Feel free to reopen if you still have questions
