### ISSUE TITLE
Icon request: rename

### ISSUE THREAD

**Issue by epelc** [google/material-design-icons#458]
The `rename-box`(possibly wrong name) seems to be missing.

![rename-box](https://cloud.githubusercontent.com/assets/5204642/17980871/40e46dd2-6acf-11e6-93b5-a1d469375f92.png)

It is like `rate_review` but without the chat bubble effect in the corner.
![image](https://cloud.githubusercontent.com/assets/5204642/17980892/54c026a2-6acf-11e6-9204-f3ba35363087.png)

Reference https://github.com/Templarian/MaterialDesign/issues/1465

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
