### ISSUE TITLE
The icon zip file is corrupted

### ISSUE THREAD

**Issue by rickdee88** [google/material-design-icons#46]
The zip file cannot be unzip.

**Comment by jestelle** [comment]
Please see issue #8 
You may be experiencing the same problem.

I believe it may be a GitHub issue.

Give [this link a try](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip), which is our mirror of the assets over on the [Material Design spec](http://www.google.com/design/spec/material-design/introduction.html)

If that one works ok, I can definitely blame GitHub ;-)
If it doesn't work, I may still be able to blame GitHub, as that zip was created through GitHub, but I might have to dig a little more ;-)
