### ISSUE TITLE
can not load icon under toggle

### ISSUE THREAD

**Issue by keluokeda** [google/material-design-icons#464]
![image](https://cloud.githubusercontent.com/assets/16809185/18038833/2316432c-6dcf-11e6-8905-a26d8680ea9d.png)

**Comment by jestelle** [comment]
I'm not sure what bug you're describing here, but I believe it may be a bug with this tool:
https://github.com/konifar/android-material-design-icon-generator-plugin

Feel free to reopen if there's something we can do here.
