### ISSUE TITLE
SVG symbol sprites not generated for the device category

### ISSUE THREAD

**Issue by shawmanz32na** [google/material-design-icons#469]
The `svg-sprite-device-symbol.svg` and `svg-sprite-device-symbol.html` files do not exist in the sprites/svg-sprite directory.

**Comment by shawmanz32na** [comment]
Quick investigation shows that the `device` category is missing from the list of categories in the gulp file. #406 should fix this.

**Comment by shyndman** [comment]
Fixed! Thanks for the report. We're cutting a new release now.
