### ISSUE TITLE
Icon Request: audiotrack off

### ISSUE THREAD

**Issue by seghers** [google/material-design-icons#471]
Hello

![ic_audiotrack_off_black_24dp](https://cloud.githubusercontent.com/assets/5781289/18175388/684baeba-7071-11e6-9c52-e3efc83ece19.png)
_audiotrack_off in paint..._

There is an audiotrack icon available.[1]
I'd like to see another version which would indicate audiotrack is disabled.

I can't use the 'mic / mic off' icon because that would indicate sound is (not) currently being recorded.
I can't use the 'volume up / volume off' icon because that would indicate the device is (not) playing it but it's available.

I would use it for a media editing activity on android using the svg versions. 
## Thank you.

[1]
https://design.google.com/icons/#ic_audiotrack

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
