### ISSUE TITLE
Chrome on Mac is missing many icons

### ISSUE THREAD

**Issue by bmcleod** [google/material-design-icons#478]
Many of the icons are not appearing on the [Official Google Material Icons site](https://design.google.com/icons/) or on my own website. 

I have tried using the fallback numeric character reference and even tried adding the CSS properties `font-feature-settings: 'liga';` and `text-rendering: optimizeLegibility;`

This issue was verified on several other Macs running the latest version of Chrome.  The problem is consistent (with the computers it does not work on), but the icons do load for some Macs on Chrome.

<img width="1234" alt="" src="https://cloud.githubusercontent.com/assets/1984936/18391667/ba4d0900-767c-11e6-9f12-5c2cae0de7b9.png">

This problem does not manifest in any other browsers or Chrome on Windows.

**Comment by TheChrisPratt** [comment]
Make sure you don't have the previous version installed.  If you do, you
don't have those glyphs to display.  Uninstall that version and things
should work just fine.
  (*Chris*)

**Comment by jestelle** [comment]
Chris is probably right.
This usually happens if you have a local version of the icon font installed, that isn't most up to date.

Feel free to reopen if something else is going wrong.
