### ISSUE TITLE
Icon Request: To-do

### ISSUE THREAD

**Issue by farbodsz** [google/material-design-icons#479]
An icon to show to-do/incomplete items - sort of an opposite for the 'Done' icon.

**Comment by CodeVINCI** [comment]
How do i help solving this issue.... How should i upload my solution to this issue.

**Comment by FarbodSalamat-Zadeh** [comment]
@CodeVINCI

I'm not in charge of this repository, but I guess you need to create the icon, and put it in its different formats and resolutions (E.g. SVG, PNGs) and then create a pull request.

**Comment by CodeVINCI** [comment]
i have designed the icon - please tell me how to make a pull request for it. i mean which repository

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
