### ISSUE TITLE
Sprites directory missing from download?

### ISSUE THREAD

**Issue by henrywright** [google/material-design-icons#48]
I downloaded the zip archive from [here](https://github.com/google/material-design-icons#download-the-zip) and after reading [this](https://github.com/google/material-design-icons#spritesheets) I'd like to try working with SVG sprites. Problem is, I can't find the sprites directory anywhere in the download. Please let me know if I'm being dumb?

**Comment by jestelle** [comment]
Hey guys, see issue #8, particularly my last comment there, which might provide you a solution.
