### ISSUE TITLE
Icon-request: Freight Truck

### ISSUE THREAD

**Issue by ncovercash** [google/material-design-icons#481]

**Comment by bash-j** [comment]
You may find the icon "local shipping" useful. 

`
<i class="material-icons">local_shipping</i>
`

Did not see this at first. Tried searching terms such as "truck", "freight", "delivery", "courier", but nothing came up.

Thank you.

**Comment by smileytechguy** [comment]
Awesome, thanks.  I will open an additional request for multiple terms to match an icon, as that would make searching so much better.
