### ISSUE TITLE
How to edit or add an icon?

### ISSUE THREAD

**Issue by engkuskusnadi27** [google/material-design-icons#482]
Is google materials icon is free for editing and adding an font? how to edit or add an icons? Thanks

**Comment by yordis** [comment]
How the development of the icon works? Should I just create the SVG icon and you create or the related files? I am confused how that works

**Comment by shyndman** [comment]
We are not currently accepting external contributions.

You might want to check out https://materialdesignicons.com/. It's a similar set of icons, using ours as a base, and has been extended by the community. They may be interested in your designs.

**Comment by yordis** [comment]
@shyndman, just for curiosity and learn about it. How the process of creating an icon work? Do you normally just work in the SVG file and generate the PNGs from there?
