### ISSUE TITLE
[Icon Request] Home Outline

### ISSUE THREAD

**Issue by joncursi** [google/material-design-icons#484]
Many icons have two design versions. For example:
- Notifications solid: https://design.google.com/icons/#ic_notifications
- Notifications outline: https://design.google.com/icons/#ic_notifications_none

---
- Person solid: https://design.google.com/icons/#ic_person
- Person outline: https://design.google.com/icons/#ic_person_outline

I am looking for the counterpart to Home solid (https://design.google.com/icons/#ic_home). This is needed in components such as the Bottom Navigation, where an icon is used to designate a section of the app you can navigate to. Available navigation options use the outline state, whereas the actively selected option (when the user taps it) use the solid state.

**Comment by joncursi** [comment]
Real world example: Instagram

![img_2990](https://cloud.githubusercontent.com/assets/4974609/18685605/d05e39d0-7f46-11e6-93bb-2dbb18517aad.png)
![img_2991](https://cloud.githubusercontent.com/assets/4974609/18685606/d060a86e-7f46-11e6-8c58-a14099fe282f.png)

**Comment by RoelN** [comment]
This can now be found in the outline set:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4570664/107635983-46801900-6c6c-11eb-9f6c-3625b501caf5.png">
