### ISSUE TITLE
Material icons not showing in Edge

### ISSUE THREAD

**Issue by CyberianIce** [google/material-design-icons#485]
Hardware: Intel x86-64 (Reak McCoy, not a VM)
OS: Windows 10 Pro (x64) 1607 Build: 14.393.187
Browser: Microsoft Edge

Expected behaviour: I expected ti see nicely shaped material icons every time i visit that web page.

Actual behaviour: **Sometimes** no material icon is shown on MS Edge, just text-tags, page loading is prolonged. When they don't work, it's regardless if hosted on CDN nor locally. Sometimes they work just fine, and page is loaded instantly. Basic debugging gives me no trace of any error; Very difficult for debugging :/

**Comment by aseemgautam** [comment]
Console error message when this happens -

CSS3120: No fonts available for @font-face rule

**Comment by e-cloud** [comment]
Any member or contributore can give some response?

Checkouting this page - https://material.io/icons/#ic_keyboard_arrow_down on Microsoft Edge and IE 10-11, none them display the icons but text.

**Comment by e-cloud** [comment]
A crazy thing is, I just find out if I turn off my proxy setting, displaying goes fine.

Once I turn the proxy on,
Edge, IE10 and IE 11 look like below:

![image](https://cloud.githubusercontent.com/assets/5255354/24957539/9a026ce4-1fbe-11e7-91b1-01e1dda95071.png)

**Comment by smartHasmukh** [comment]
Material icons not showing in Edge and IE Browser

**Comment by adamreisnz** [comment]
Experiencing the same issue

**Comment by AMIDIBOSS** [comment]
Don't use edge :}

**Comment by adamreisnz** [comment]
Oh I'm not, but some of our clients are and I can't change that unfortunately.

**Comment by adamreisnz** [comment]
I've created a build too that might aid you with these issues, it replaces ligatures with the unicode character code for you: https://www.npmjs.com/package/material-icon-convert

**Comment by pentoolism** [comment]
just use unicode in content

example:
`.icon {
  content: "\e14a";
  font-family: "Material Icons"
}`

**Comment by lkraav** [comment]
We're seeing this happen. Did anyone figure out the underlying cause yet?

**Comment by adamreisnz** [comment]
`font-feature-settings: 'liga';  //Fix for Edge` worked for us, apply it to your `.Icon` or `.material-icons` class.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
