### ISSUE TITLE
Lack of heart icon ♥

### ISSUE THREAD

**Issue by samiuelson** [google/material-design-icons#486]
Dear Googlers,

I'm deeply disappointed by the lack of heart icon ♥.
I firmly believe it's the basic icon for every app. 
Please take my disappointment into account. 

Best,
@samiuelson

**Comment by elmasry** [comment]
https://material.io/icons/#ic_favorite

**Comment by spacefruit** [comment]
As a favorite icon usually is a star (not a heart), the naming of this icon is misleading. I'd suggest changing it to a more intuitive alternative like "heart" or "love".

**Comment by michaelpumo** [comment]
The search on the icons page of material.io is annoyingly basic. They need to have each icon tagged with multiple terms somehow.

**Comment by FrancescoMussi** [comment]
Come on @google.

Rename that icon 'heart' for goodness sake.

**Comment by AntowaKartowa** [comment]
I also searched for this icon by terms heart and love. For me sounds reasonable proposition for tagging each icon with multiple terms.

**Comment by PCTipsGR** [comment]
Thank you @elmasry. You just saved me.
I wish that Google could rename it to heart or at least allow us to find it when we search for "heart" or love".

**Comment by cah-dunn** [comment]
I feel like if someone solved this search thing it could be a fairly successful business.

**Comment by lukefisklennon** [comment]
@cah-dunn Not really a business because this is a free and open-source collection, but yeah.

**Comment by sawonersm** [comment]
I searched for it as heart and nothing. I suppose all users have to visit this thread for learning to search the HEART icon, that's nonsense. @google-admin, don't be stubborn, hearts exist before social networks

**Comment by maexen** [comment]
my personal opinion, who assigned the name "FAVORITE" to an icon that represents a heart, has serious problems, or should deal with something else in life.

**Comment by WitnessMee** [comment]
I also feel the name `favorite ` is not intuitive at all and I had to come here to find it. However I think it is too late to change it now. A lot of websites refer to material icons directly and changing the name would break them.
@google-admin However, it might be a good idea to introduce a search function that can search the icon name + possible aliases. In this case you could add aliases `heart `and `love`.

**Comment by Aunlarce** [comment]
it's present mate it's just titled as "favorite".

**Comment by tphinney** [comment]
There are two different things Google could do:
1) tag icons with additional terms, for searching the catalog
2) alias the actual name so you can actually refer to the icon that way

If this were a common sort of request, we could create one or more new tags for it to help us track and address them. I am surprised I haven’t seen more such feedback.

**Comment by WitnessMee** [comment]
> it's present mate it's just titled as "favorite".

We know. They have already fixed it by adding a search alias `heart` for `favorite`. This was not the case in 2020.

**Comment by pooja143-tech** [comment]
Heart-pulse/heart-beat and chalkboard_user icons are not there in angular material.
you guys giving so many new features in angular but still failing to add some basic icons to angular material.
so sad we still need to depend on external resources.

**Comment by pooja143-tech** [comment]
Google please google on google and add the icons that you missed on angular material.

**Comment by tphinney** [comment]
@pooja143-tech You are commenting on a closed issue about a different problem. If you would like these other issues addressed, please create a separate issue: (1) about angular material and (2) about whatever particular icons
