### ISSUE TITLE
Wrong Strikethrough SVG

### ISSUE THREAD

**Issue by Robert-Christopher** [google/material-design-icons#489]
![image](https://cloud.githubusercontent.com/assets/3964370/18794615/ecb4e432-81dd-11e6-8f15-ec1bc61839aa.png)

When clicking on the strikethrough white svg from [Material Icons](https://design.google.com/icons/), downloads a file from [ic_strikethrough_s_white_24px.svg](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_strikethrough_s_white_24px.svg) which is black svg instead of a white one.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
