### ISSUE TITLE
1x_ios has only 24*24 and 48*48 size, which are too small or too big in the UITabbar icon

### ISSUE THREAD

**Issue by gclsoft** [google/material-design-icons#49]
![1](https://cloud.githubusercontent.com/assets/1269898/5223072/ffb0606c-76e9-11e4-950f-0793a235b272.png)
I have to use 36dp 36*36 in drawable-mdpi

**Comment by ajsecord** [comment]
Hi, thanks for letting us know how the icons are working for you!

[Apple recommends](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW1) "about 22x22" for tool bars and navigation bar icons, we use 24x24. They recommend "about 25x25" for tab bar icons, we again use 24x24.

Is there something particular about your situation that is making those sizes seem too small?

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed.
