### ISSUE TITLE
ic_scanner_48px.svg has superfluous (hidden) white rectangle

### ISSUE THREAD

**Issue by nigeltao** [google/material-design-icons#490]
hardware/svg/production/ic_scanner_48px.svg contains a white rectangle:

<path fill="#fff" d="M16 34h22v4H16z"/>

which is redundant. It is completely overwritten by the subsequent path.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
