### ISSUE TITLE
ic_airplanemode_active_48px.svg has degenerate path

### ISSUE THREAD

**Issue by nigeltao** [google/material-design-icons#491]
device/svg/production/ic_airplanemode_active_48px.svg and maps/svg/production/ic_flight_48px.svg both contain:

<path d="M20.36 18"/>

which is redundant. Filling this degenerate path (consisting of only one MoveTo command) has no effect.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
