### ISSUE TITLE
ic_notification_48px family icons have fill

### ISSUE THREAD

**Issue by elliotdahl** [google/material-design-icons#496]
I noticed that in social/svg/design and social/svg/production the following notification icons have a fill. I don't believe they should have a fill.

ic_notification_48px.svg
ic_notification_active_48px.svg
ic_notification_none_48px.svg
ic_notification_off_48px.svg
ic_notification_paused_48px.svg

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
