### ISSUE TITLE
Icon Request: sun

### ISSUE THREAD

**Issue by tomekck2** [google/material-design-icons#497]
All icons are fantastic!! great job but please add new sun like this:

http://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-sun-o

thanks!

**Comment by mmatiaschek** [comment]
i second that!

**Comment by RoelN** [comment]
Looks like this has been added:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/4570664/107621764-0b271f80-6c57-11eb-8488-52b20a2326ae.png">
