### ISSUE TITLE
Font icon names are indexed by search engines

### ISSUE THREAD

**Issue by deepfriedbrain** [google/material-design-icons#498]
I'm using font icons in my page h1 header for e.g.:

    <i class="material-icons">thumb_up</i> My Page Title</h1>

I noticed that my page shows up as `thumb_up My Page Title` in Google SRPs. Is there a way to avoid this, other than removing the icons from the header or switching to image icons?

Thanks.

**Comment by shyndman** [comment]
Hi @deepfriedbrain,

In this case, we recommend that you reference the icon using its codepoint. For `thumb_up`, you'd write this:
```html
<i class="material-icons">&#xE8DC;</i>
```
You can find the complete mapping between icon names and their codepoints here: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by deepfriedbrain** [comment]
That's what I ended up doing but it's a very poor workaround. I lose the advantage of using readable icon names or add those readable names as comments wherever I'm using Material Icons. 

Why doesn't Material Icons use the approach similar to Font Awesome (make the icon name a CSS class)? Were you not aware of the problems with search engines (especially Google) indexing those names?

**Comment by MrXyfir** [comment]
A year and a half later, are there any better solutions for this?

**Comment by ZdrowyGosciu** [comment]
Maybe this solution could help https://stackoverflow.com/questions/37281861/how-to-use-google-material-icons-as-class-instead-of-i-tag

**Comment by voyula** [comment]
I prepared a repository for solution;
https://github.com/voyula/material-icons-font-classes
```html
<!-- Using material-icons with classes. -->
<span class="material-icons m_i_ICON_TAG_HERE"></span>
```

**Comment by kjdeepak** [comment]
> Hi @deepfriedbrain,
> 
> In this case, we recommend that you reference the icon using its codepoint. For `thumb_up`, you'd write this:
> 
> ```
> <i class="material-icons">&#xE8DC;</i>
> ```
> 
> You can find the complete mapping between icon names and their codepoints here: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

This link is no more working. Did any one found solution to this issue?

**Comment by MrXyfir** [comment]
The best solution is don't use font icons. Use SVG icons.

**Comment by marvinpoo** [comment]
Any official updates to this?

**Comment by PowerKiKi** [comment]
The attribute `data-nosnippet`, as detailed in https://developers.google.com/search/docs/advanced/crawling/special-tags#data-nosnippet, can be used to workaround this issue, at least for Google.

**Comment by remixer-dec** [comment]
There's a more recent [answer](https://stackoverflow.com/a/61659184) in stackoverflow thread mentioned [above](https://github.com/google/material-design-icons/issues/498#issuecomment-393799784), which offers a pretty convenient solution. Similar solution is also mentioned in a [linked issue](https://github.com/trimox/angular-mdc-web/issues/1851#issuecomment-481425631).

**Comment by PowerKiKi** [comment]
https://stackoverflow.com/a/61659184 is great, but unfortunately it requires control of the DOM, like all other answers I've seen here. And since I'm using those icons via Angular components [mat-icon](https://material.angular.io/components/icon/overview), it's unfortunately not an option (AFAIK).

**Comment by crustamet** [comment]
THIS IS NOT FIXED WHATSOEVER THE CODEPOINT IS A WORKAROUND. this workaround only works on google search but does not work on other search engines
GOOGLE IS NOT THE ONLY SEARCH ENGINE ON THE PLANET!!!

![image](https://github.com/user-attachments/assets/a279e38e-576e-47c5-b049-14208e3bd10f)
![image](https://github.com/user-attachments/assets/78a98129-ee30-4893-816b-0a6d92f0e7ba)

"Seo friendly ligature icons" my ass. What happened to the old ?
          
            <i class="material-icons md_thumb_up"></i>

this should work as before and my example is seo friendly because there is no text to get indexed.
While other codepoints if you search the codepoints on google its still gets indexed LOL

![image](https://github.com/user-attachments/assets/d4d044b1-6f2b-41b7-8a57-330eb98b3f99)
