### ISSUE TITLE
Prevent '?' from displaying when no icon name is intentionally specified

### ISSUE THREAD

**Issue by quadsurf** [google/material-design-icons#499]
I am dynamically passing the icon name into the icon element, however, there are times where I want no icon to render or to just be blank. But when I do that by leaving the icon name="" property empty, it defaults to a question mark... how do I prevent the question mark from displaying when no name is **intentionally** provided? A transparent "spacer" icon would be great.

**Comment by RoelN** [comment]
Looks like passing something like the letter `x` works for that purpose.

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
