### ISSUE TITLE
Viral license question-- Can non-FLOSS projects/apps use these icons?

### ISSUE THREAD

**Issue by fat-tire** [google/material-design-icons#5]
I'm not sure if an issue is the appropriate way to ask this (maybe it is), but the CC-SA-BY 4.0 has a requirement that "_if you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original_." The meaning of this has been [debated](http://opengameart.org/forumtopic/practicality-of-cc-by-sa) previously in other contexts, but I'd like to seek clarity from Google directly about the intent of this license-- these icon images, if used and credited (I assume to "Google, Inc."?), may be used as part of a non-[FLOSS](http://en.wikipedia.org/wiki/Free_and_open-source_software) project without having to CC-SA-BY the _entire_ app... right?  What about other art that may "intermingle" with the CC'd art, as in screenshots, etc?

IANAL, but from the terms of the license itself, "Adapted Material", and "Adapter's License" _seem to me_ to fall within the scope of "stuff pertaining to these images" only.  But I think it would be helpful and reassuring to be explicit on this, ie "You may use these images for any kind of purpose you like-- and if you make changes to these images, THOSE ALTERED IMAGES ALONE will be licensed under the same terms, and not any other part of the app, including artistic content or executable or source code."

Or perhaps, to be even clearer, consider re-licensing without the viral "Share-Alike" requirement because I've seen it lead to confusion....

Finally, how are these icons licensed compared to the [ones used by Polymer](https://www.polymer-project.org/components/core-icons/demo.html)  ([github](https://github.com/Polymer/core-icons))?

Thanks!

Bonus question:  Why no ldpi?

**Comment by stefan-niedermann** [comment]
@jestelle could you please give an  answer @DawnPaladin s question? I would love to use material design icons, but i have to know if it is enough to put the by-annotation as an comment into the markup. please consider my last post-edit.

**Comment by jestelle** [comment]
@stefan-niedermann We'd prefer it is a user-visible attribution, but like I said, we don't mind it hidden away on some general about page or the like.

You're probably better off for performance reasons not including extra non-rendering comments in all your HTML, unnecessarily bloating the size of your page.
