### ISSUE TITLE
Bad preview or icon for person pin icon

### ISSUE THREAD

**Issue by shinze** [google/material-design-icons#501]
On https://design.google.com/icons/ The preview for _person_ pin shows a rounded circle and the downloaded one is a rounded square one.

![capture d ecran 2016-10-10 a 15 00 36](https://cloud.githubusercontent.com/assets/218396/19236936/56a5ffb0-8efa-11e6-9518-de816fe25ff5.png).

On the picture : @ right is the svg preview shown on osX.

**Comment by PushkaCom** [comment]
Does anyone actually have the circle person icon?

Duplicate post:
https://github.com/google/material-design-icons/issues/563

**Comment by fabyeah** [comment]
I'm also looking for the circle version. Anyone?

**Comment by RoelN** [comment]
The circle version has been added. The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
