### ISSUE TITLE
cog icon

### ISSUE THREAD

**Issue by jedielson** [google/material-design-icons#502]
Hi!

I've been looking for something like a cog icon, but I cannot find.

Does anybody have one suggestion about it?
Is there any icon being built?

**Comment by jossef** [comment]
https://design.google.com/icons/#ic_settings

```
<i class="material-icons">settings</i>
```

![image](https://cloud.githubusercontent.com/assets/1287098/19410297/f3a11d5a-92f0-11e6-8eb8-fb9f954febcf.png)

**Comment by jedielson** [comment]
Thanks!!!!!!!

**Comment by vaibhavhrt** [comment]
can't find it anymore on https://material.io/resources/icons seems to have disappeared.
But still works in my webpages using `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />` to include icons.

**Comment by JimVercoelen** [comment]
+1

**Comment by rubenheymans** [comment]
this issue still exists though, 3 years later

**Comment by stuartwakefield** [comment]
Link to the SVG incase anyone needs it: https://fonts.gstatic.com/s/i/materialicons/settings/v1/24px.svg?download=true
