### ISSUE TITLE
[Icon Request] Launch Rocket

### ISSUE THREAD

**Issue by joncursi** [google/material-design-icons#504]
The rocket icon can be used to describe launching something, starting something, finalizing / "shipping" something. Very popular these days IMO. Would be a great addition to the library.

![rocket-512](https://cloud.githubusercontent.com/assets/4974609/19530281/3ec760c4-9601-11e6-8595-b46d6ce61b70.png)

**Comment by Editandrew** [comment]
Agreed, +1

**Comment by nicholas-davis** [comment]
+1

**Comment by joshua-fogg** [comment]
+9000

**Comment by 4ctarus** [comment]
+1

**Comment by christophedemey** [comment]
+1

**Comment by cyberalien** [comment]
This repository is out of date and seems to be abandoned.

Good news is its open source, so anyone can make a copy and update it, which is what I did: https://github.com/cyberalien/google-material-design-icons-updated

Its up to date with latest icons from material.io. Each icon has 5 variations, like in new material.io repository. There are also few custom icons.

I've created custom rocket icon:
* ![baseline-rocket.svg](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/action/baseline-rocket.png)  [baseline-rocket.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/content/baseline-rocket.svg)
* ![outline-rocket.svg](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/action/outline-rocket.png)  [outline-rocket.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/content/outline-rocket.svg)
* ![round-rocket.svg](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/action/round-rocket.png)  [round-rocket.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/content/round-rocket.svg)
* ![sharp-rocket.svg](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/action/sharp-rocket.png)  [sharp-rocket.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/content/sharp-rocket.svg)
* ![twotone-rocket.svg](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/action/twotone-rocket.png)  [twotone-rocket.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/content/twotone-rocket.svg)

Icons are available as SVG, PNG, SVG framework that replaces font and React component.

For example of how to use icon in SVG framework or React see [baseline-rocket icon](https://iconify.design/icon-sets/ic/baseline-rocket.html).

Enjoy :)

**Comment by jimmyzhen** [comment]
The repo appears to have been updated recently and newly added icons are great! Well done!

Can some sorta launch rocket icon be added in the next update? Soon?

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
