### ISSUE TITLE
[Icon request] Cardboard/VR icon

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [google/material-design-icons#508]
Please add Cardboard/VR icon (2 variants: for disabled VR mode and for enabled VR mode). Something like:

Disabled:
![Disabled](https://cloud.githubusercontent.com/assets/7892779/19836909/f023c0a4-9ebe-11e6-81a0-e7794090ddd7.png)

Enabled:
![Enabled](https://cloud.githubusercontent.com/assets/7892779/19836911/0be8f7aa-9ebf-11e6-8297-db49046470fb.png)

**Comment by Robinnnnn** [comment]
+1

**Comment by alex2844** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by FluorescentHallucinogen** [comment]
@jalpadoshi
> Icon available at: https://fonts.google.com/icons

Sorry, but I don't see this icon on https://fonts.google.com/icons. I've looked through all the icons and tried to search "cardboard", "vr", "reality", etc.

Could you please share the name and screenshot?
