### ISSUE TITLE
[Icon request] Pin icon

### ISSUE THREAD

**Issue by aurotones** [google/material-design-icons#517]
I seen pin icon somewhere on one of google's websites but can't remember, i was pretty sure there would be one but it's missing, It's a very useful icon so please add these two.

![image](https://cloud.githubusercontent.com/assets/23254324/20093935/fc6d15aa-a5d9-11e6-9dbb-309c55006375.png)

**Comment by bendrexl** [comment]
I've been looking for that thumbtack / push-pin icon also...

It's present in Android, and visible as a thumbnail here also: https://material.google.com/style/icons.html#icons-system-icons

**Comment by Omiod** [comment]
It is used in Keep and Inbox too.
I would expect MDI to be more in synch with the various Google apps.

**Comment by nicholas-davis** [comment]
+1

**Comment by bduyng** [comment]
+1

**Comment by conan06** [comment]
+1

**Comment by 0x70b1a5** [comment]
+1

**Comment by fermin** [comment]
+1

**Comment by jasondiazg** [comment]
+1

**Comment by Joshuasony** [comment]
+1

**Comment by ghdrn11** [comment]
+1

**Comment by jamesweitlauf** [comment]
I think this is a duplicate request:
#450

**Comment by RoelN** [comment]
Looks like it has been added, see linked issue
