### ISSUE TITLE
Unable to Install from npm (extract not completing)

### ISSUE THREAD

**Issue by tomwanzek** [google/material-design-icons#518]
I am unable to install **material-design-icons** from npm.

When trying to install with npm version 3.10.3 (windows 10 machine), the extraction step:

`\ extract:material-design-icons: sill doParallel extract 1`

does not complete even after appr. 10min. The progress slash eventually stops spinning completely.

Your insights are most appreciated.

**Comment by Hades1996** [comment]
Yes, this is also happening to me.

node version: v6.4.0
npm version: 3.10.9

**Comment by AlexDmr** [comment]
Same problem here
System: windows 10
npm --version   => 3.10.8
node --version => 6.9.1

**Comment by kennyy0123** [comment]
Same problem, npm version 3.8.6, node version v6.1.0

**Comment by AlexDmr** [comment]
It turns out that it took about 20mns to complete....
maybe one could split this large library inti multiple small ones?

**Comment by tomwanzek** [comment]
@AlexDmr thanks for the patience in investigating. For all intents and purposes 20min seems prohibitively long, i.p. if all one might need are the icon fonts for self-hosting.

**Comment by tomwanzek** [comment]
Is this going to be addressed?

**Comment by sikko** [comment]
Same problem here on OSX: node 3.10.9, npm v6.9.2

**Comment by gregbown** [comment]
Same problem Windows 10 pro, npm 4.0.2, node 6.9.1.
It appears that the content loads into node_modules/staging, however the node_modules/material-design-icons folder is never generated

**Comment by LosEagle** [comment]
Same here, 
node 6.9.2 
npm 4.0.3
Debian Jessie

**Comment by geelife** [comment]
Same here with Win10, node 6.9.4, npm 4.1.2

**Comment by shankjn** [comment]
After 20 minutes of installation, it shows several errors and ultimately does not get installed. Does anyone have a solution or any updates for installation on Windows 10, Node 6.10.0 and npm 3.10.10.

**Comment by davidgreens** [comment]
@tacaswell
@efiring
@anntzer
@NelleV

**Comment by efiring** [comment]
@davidgreens Why are you pinging matplotlib devs?

**Comment by grulex** [comment]
Same problem, npm 4.3.0 on OSX and Linux.

**Comment by datadidit** [comment]
Upgraded to 4.4.1 download is still taking quite a while.

**Comment by shankjn** [comment]
After upgrading to the latest versions of node and npm, I'm unable to install it.

**Comment by mankey-ru** [comment]
Still occurs.
node v.6.9.5
npm v.4.4.4
Windows 10

**Comment by karser** [comment]
Installing `material-design-icons-iconfont` solves this issue:
```
npm install material-design-icons-iconfont --save
```

```
//styles.scss
$material-design-icons-font-path: "~material-design-icons-iconfont/dist/fonts/";
@import "~material-design-icons-iconfont/dist/material-design-icons";
```

npm 3.10.10
node v6.10.0

**Comment by tomwanzek** [comment]
@jestelle and @shyndman (simply mentioning you as main contributors):

This fairly fundamental issue has been open without any investigation of root cause and possible remediation for an extended period.

Is this repo still supported? Thanks for looking into it.

**Comment by jmauerhan** [comment]
This is still a problem.

**Comment by clusteratlas** [comment]
It's frustrating, but lol it worked somewhere around the 10th try.

Just persist <3

**Comment by doodlemeat** [comment]
I installed npm 5.3.0 and it worked like a charm.

**Comment by diogoweb2** [comment]
same problem using Yarn v0.27.5 @ win10

**Comment by tomwanzek** [comment]
The issue seems to be resolved. I have been able to install the lib in version 3.0.1 using npm.  🎉

**Comment by jmauerhan** [comment]
Still a problem on Windows 10. 

@karser's solution above still works: https://github.com/google/material-design-icons/issues/518#issuecomment-290924590

**Comment by tomwanzek** [comment]
@jmauerhan The install takes appr. 4min for me. Windows 10, npm version 5.3.0. Slow, but at least working.

**Comment by molikh** [comment]
same here

**Comment by raspu** [comment]
Same here, still an issue

**Comment by srinek** [comment]
me too.  npm install material-design-icons is not working.

**Comment by whisher** [comment]
Hi there,
with ng 1.6 it works but with warning like
```
WARNING in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
(Emitted value instead of an instance of Error) postcss-url: /Users/whisher/Projects/src/styles.scss:7:3: Can't read file '/Users/whisher/Projects/src/~material-design-icons-iconfont/dist/fonts/MaterialIcons-Regular.eot', ignoring
```

**Comment by raphaelstary** [comment]
still a problem in 2018 😢
(using node v9.4.0, npm 5.6.0 on ubuntu bash under windows 10 - using folder in the win10 file system)

**Comment by viktorko99** [comment]
Update for 2018: 

It's possible to install this package, but you have to wait really long time (about 10 min).

**Comment by cvgaviao** [comment]
Please, could someone explain me one thing?  
If I install material-design-icons in my project will all icons of it be added to the production bundle or just those being used ?

**Comment by itskaizad** [comment]
@cvgaviao your node_modules will contain ALL ICONS when you do that

**Comment by rgalaxy** [comment]
Is there any way i can import just the icons that i wanted? and how to implement it after installing it?
for me [karser solution](https://github.com/google/material-design-icons/issues/518#issuecomment-290924590) not working anymore.

**Comment by urmichauhan** [comment]
i have also problem after done everything !

**Comment by ifeature** [comment]
I've faced this issue when trying to install moduled through `npm-cli`.
But it seems to me that issue is disappeared when I install modules through `yarn`.

**Comment by jesraygarciano** [comment]
Issue still exists?

**Comment by kastork** [comment]
Yes it does.
node 10.10, yarn 1.9.4, macos

I can wget the archive manually in about 4 seconds, but yarn can't, it times out and retries after a minute or so and ultimately fails.

**Comment by jossef** [comment]
Hey @kastork @jesraygarciano @ifeature @urmichauhan @rgalaxy @itskaizad @cvgaviao @viktorko99 @raphaelstary @whisher @srinek @raspu @molikh @tomwanzek @jmauerhan @diogoweb2 @Nyadesune @AlexDmr @klouzoun 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by liudonghua123** [comment]
same here.
https://github.com/google/material-design-icons/issues/800

**Comment by 839998664** [comment]
Same issue...This just cost me a job...tech screening round had a project with dependency on this...needless to say `npm install` would just not complete successfully...deadline shot by...using `npm v6.5.0` `node v10.15.0` `Windows 7`...

**Comment by thw0rted** [comment]
The real problem here is that 99% of users want an icon font (<1MB on disk, <10 files total) and this package gives you a pile of individual icons (216MB on my computer, ~90,000 files!).  This package deserves to be abandoned, we should all switch to an icon-font (only!) package instead.

**Comment by jossef** [comment]
Hey @839998664 @PatSk @liudonghua123 @thw0rted

This project is on low maintenance and out of date for a while.

I've forked it and simplified things, please give it a try: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

- added support for scss
- removed the many irrelevant files that cause congestion and timeouts 
- using the most updated icon-fonts (without modifications) from Google's CDN.


![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)
https://github.com/jossef/material-design-icons-iconfont

**Comment by m0o0hammad** [comment]
same here 
npm 6.8
node 9.11

**Comment by irowbin** [comment]
Its 2019 and the problem never gets away. 😞

**Comment by karlos-oliveira** [comment]
I had the same problem with another package, i don't know if is the same issue, but my problem was insufficient memory that makes the extract process take forever and than fail. In my case, i'm using Ubuntu on azure, the procedure below helped me:

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

**Comment by logicbomb421** [comment]
Yup still happening.. Been 2.5 years now, any chance this will get prio, MUI devs?

**Comment by jimrpy** [comment]
same.
try next step may solve the problem
remove node_modules folder
run npm install --save

**Comment by manukarthik** [comment]
The entire npm installation hangs up because of this. I'm using node v8.11.0, npm 6.9.0 and angular CLI 7.3.6.
Then later i had to remove it from package.json and install it as a seperate dependacy which took for about 20 mins.

**Comment by pea3nut** [comment]
I have fixed it by using the primitive terminal!

**Comment by valcioiudragos** [comment]
Hello,
I occured the same problem

`yarn add material-design-icons --dev`

with error: 
info There appears to be trouble with your network connection. Retrying...

and with mention that other packages works

**Comment by thw0rted** [comment]
It looks like people are still trying to use this package for simple websites.  If you want to develop new icons and customize the SVG sources for Material icons, use this package.  If you want to use material2 with `mat-icon` and have everything just work out of the box, use `material-design-icons-iconfont` instead.  It's 467kb, 21 files in my `node_modules`.  I don't have an install of `material-design-icons` handy but I'm sure it's at least tens of thousands of files (maybe hundreds?) and no less than an order of magnitude larger.  Just get the `iconfont` package and ignore this one.

**Comment by PhotoByLucas** [comment]
it confuse me too
node 10.16.3
npm 6.9.0

**Comment by kevzettler** [comment]
2021 checking in:

```
npm -v 7.5.4
node -v v12.18.1
```

`npm install` gets hung and stuck on `@icons/material`
```
⸨                  ⸩ ⠦ reify:@icons/material: timing reifyNode:node_modules/typescript Completed in 14909ms
⸨                  ⸩ ⠦ reify:@icons/material: timing reifyNode:node_modules/typescript Completed in 14909ms
⸨                  ⸩ ⠦ reify:@icons/material: timing reifyNode:node_modules/typescript Completed in 14909ms
⸨                  ⸩ ⠦ reify:@icons/material: timing reifyNode:node_modules/typescript Completed in 14909ms
```

**Comment by mgscuteri** [comment]
The issue seems to be related to a hidden git prompt for a SSH passphrase.  To fix this, either create an SSH key without a passphrase,
https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

or run 
```
ssh-add ~/.ssh/id_rsa
```
to store your passphrase and prevent git from asking you for it all the time.

**Comment by edPratt** [comment]
Same issue as @kevzettler. I thought it was hung, but it ended up completing after a few minutes.

**Comment by thw0rted** [comment]
Apparently every couple of years I have to chime in again, because people (justifiably) don't want to read 20 pages of backchat.

**If you just want to use Material icons on a website, do not install this package.**  This package includes full sources for all the icons and as a result is an *enormous* download that takes ages to unpack.  You should install `material-design-icons-iconfont` and forget this package exists.

**Comment by ananix** [comment]
it still happened ：
macOS
node v16.13.0
npm 8.1.3

**Comment by sky-1991-sia** [comment]
ANSWER!

(windows 10, node v16.13.0 , npm 8.1.0 , @mui/icons-material 5.5.0 )

GIVE SOME TIME TO IT...!!
Depending on your network and config it will take a different install duration.
just let it finish !!!



for me, it takes about 6 min


![Screenshot 2022-03-11 013651](https://user-images.githubusercontent.com/79264045/157784359-64aaffdc-6d44-47ad-befd-56db08c5c48c.png)

**Comment by thw0rted** [comment]
Seriously people read upthread 👆👆👆👆 just like *half a page*, please.

**Comment by tphinney** [comment]
Agree with @thw0rted: For many purposes, the icon font is a smaller single-file equivalent.
(Even the fancy new Material Symbols fonts, with four axes and infinite variations, are only 4-6 MB each.)

**Comment by thw0rted** [comment]
@tphinney good to see the team is aware of the community project! I suppose a link from the README (or even an official supported package) would be too much to hope for?  (I don't know if you saw, but [I asked them for a Symbols version](https://github.com/jossef/material-design-icons-iconfont/issues/89) already.)

**Comment by tphinney** [comment]
I actually just updated the readme tonight with a link to a more updated third-party re-architected npm set. I hope that seems like the right set. I am out of my knowledge zone when dealing with npm.

I welcome suggestions on what else might be good to say in the readme.
Might split the npm advice and give it its own page, just linked from the readme.

**Comment by thw0rted** [comment]
I have no insight into the difference between the packages maintained by @marella and @jossef , I just happened to find the latter some years ago and found that it met my needs.

The readme update looks fine, though maybe instead of saying "Google does not maintain npm packages", you could say "Google no longer maintains [the npm package for this repo](https://www.npmjs.com/package/material-design-icons)" -- I think a lot of people wind up in this thread because they don't notice that the package was last updated 6 years ago.  (I guess people don't just remove old NPM packages, do they?)

**Comment by tphinney** [comment]
I tweaked the wording, and specifically pointed out that the package was last updated in 2016.

**Comment by cristi41611** [comment]
Last update was in 2016 and yet people commented in 2017, 2018, 2019 to assure others that it's still a problem

**Comment by AhmedAbdelfaheem** [comment]
Still have the problem with npm@6.10.2 MacOS Monterey V 12.4

**Comment by tphinney** [comment]
@AhmedAbdelfaheem did you try the package linked from the readme, here: https://github.com/google/material-design-icons#npm-packages ?

**Comment by taipignas** [comment]
im stuck here for more than 5 minutes
![image](https://user-images.githubusercontent.com/55182635/187892185-34c97fe8-e46c-424c-9141-e8888b27bdf0.png)

**Comment by tphinney** [comment]
@taipignas which NPM package are you installing? The 5-year-old one from this repo, or the one linked here? https://github.com/google/material-design-icons#npm-packages
