### ISSUE TITLE
[Icon Request] Toggle Vibration

### ISSUE THREAD

**Issue by ozgurg** [google/material-design-icons#519]
I need this toggle vibration icon material design style.
Like this: 
![screenshot_1](https://cloud.githubusercontent.com/assets/6717356/20239252/189012ae-a905-11e6-82b6-149885aca336.png)
(I'm made it on the Photoshop. I want to use SVG version.)
![screenshot_1](https://cloud.githubusercontent.com/assets/6717356/20239441/96dc9a44-a908-11e6-9d16-a348bb8d4c01.png)

Like these:
![screenshot_1](https://cloud.githubusercontent.com/assets/6717356/20239304/244c89b4-a906-11e6-9bdb-ea3d516f1370.png)

**Comment by tomscholz** [comment]
So what you mean is mute?

**Comment by OzgurGorgulu** [comment]
No. Vibration on or off. This is off, not mute.
