### ISSUE TITLE
"Sort Options" Icon from Google Drive

### ISSUE THREAD

**Issue by oberkorn** [google/material-design-icons#52]
The Google Drive web interface uses an icon for "Sort Options." It would be great to see that icon added to the library.

**Comment by danielhickman** [comment]
They already have it. See it on @templarian 's site
http://materialdesignicons.com/icon/sort-alphabetical

**Comment by RoelN** [comment]
Closing this because it's an ancient issue. Apologies for leaving it open for so long. If you feel it's still relevant, feel free to reopen or create a new one with updated information!
