### ISSUE TITLE
Earth / World / Globe icon missing

### ISSUE THREAD

**Issue by tomscholz** [google/material-design-icons#520]
![bildschirmfoto 2016-11-13 um 22 21 52](https://cloud.githubusercontent.com/assets/20381749/20248942/a083f5be-a9ef-11e6-9d4b-91f4dba8b05b.png) I found this icon on the Internet (maps.google.com) etc. but it's not listed anywhere

**Comment by tomscholz** [comment]
Got it! But why is it called "public" ?

**Comment by vip2017A** [comment]
Vsr

**Comment by simonmysun** [comment]
I would like to request for globe icons with other locations at center.

**Comment by WaterHoldingFirebug** [comment]
Excccccddddxceeccxcccccr

**Comment by DoubleHub** [comment]
Man material design icons are weird. Couldn't you just call it "EARTH"? you know!!!

**Comment by ino76** [comment]
they have all stupid names ;/

**Comment by zessu** [comment]
I was doing an icon in flutter and I had to do this lol 
`   children: <Widget>[Icon(Icons.public), Text("www.johndhoe.com")],`

**Comment by zessu** [comment]
Could improve the naming of the icons but that might break things ...

**Comment by felixkriechbaum** [comment]
Search 10 min to know that the globe/planet/earth is called public 🤦🏻🤦🏻🤦🏻

**Comment by SayedMainUddin** [comment]
Icons.language

**Comment by tphinney** [comment]
Just go to the main icons page and use its built-in search function.
https://fonts.google.com/icons

I totally agree that the name is kind of goofy. This is generally true for older icons. For those introduced in the last few years, the name generally matches what the icon LOOKS like regardless of the intended usage.

Of course this itself has interesting consequences, like that the new icon to be used to indicate vegetarianism is called “sqare_dot”... sigh.

Again, the built-in search function is your friend.
