### ISSUE TITLE
[Icon request] AMP icon

### ISSUE THREAD

**Issue by roderickhsiao** [google/material-design-icons#521]
Would be good to have [AMP](https://www.ampproject.org/) icon like https://www.ampproject.org/static/img/logo-blue.svg (without text)

**Comment by Paul-Ver** [comment]
Will "flash_on" work for you?
`<i class="material-icons">flash_on</i>`

**Comment by roderickhsiao** [comment]
I think AMP icon is kind of like the brand icon, will be good to match the spec

**Comment by rejhgadellaa** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
