### ISSUE TITLE
incoming/outgoing icon

### ISSUE THREAD

**Issue by TZanke** [google/material-design-icons#522]
We like to have a icon for incoming and outgoing to show the user the direction of a mail or  ticket in our software. Like the Thunderbird Mail-Threads.

At the moment we decided to use the "call made" and "call received" icon. But i think this is not the best solution.

Or should we use an other existing icon? But which would be best?

![image](https://cloud.githubusercontent.com/assets/1613368/20554466/7bee59a0-b15c-11e6-8d63-dcc4c64495d8.png)

Something like this could fit the need? [extern example](https://cdn4.iconfinder.com/data/icons/finance-4-3/24/184-512.png)

**Comment by guettli** [comment]
Like TZanke I would like to have nice incoming/outgoing icos.

I sketched something:

![incommig-outgoing-icon--like-bouncing-ball](https://cloud.githubusercontent.com/assets/414336/20827625/7bdd1366-b873-11e6-8e08-1635acae2a28.jpg)

It is like a bouncing ball: It comes in. Touches the ground, and bounces up (and out) again.

The green boxes are the boarders of the two icons.

I think a general icons (incoming, outgoing) make more sense than concrete "call made" and "call received" icons.

**Comment by guettli** [comment]
Hello, anybody out there?

**Comment by jestelle** [comment]
Hi Thomas,
Thanks for the request.
I turned your other question #577 into a post on our FAQ: https://github.com/google/material-design-icons/labels/FAQ

**Comment by guettli** [comment]
@jestelle  yes, I understand you. You can't provide icons for every need.

Please look at this particular issue.

You provide "call received" and "call made". That's great. That's what we need.

Maybe renaming them to "incomming" and "outgoing" could be done, since this addresses more use cases.

Please look at the bouncing ball painting I provided some months ago. I came across this issue today in a similar use case, and still think that the curved arrow is a nice way to represent these two fundamental different directions.

What do you think?

**Comment by guettli** [comment]
@jestelle You said in #577 

> we can't be the service organization that creates every icon everyone needs

Yes, that's true. If you want to create a special icon for every special use case, this won't work.

On the other hand, in this particular case I don't request for a special icon. I want the opposite. I want the special "incoming call" icon to become a more general and more widely usable "incoming" icon.

AND the bouncing ball analogy makes sense. At least to my mind.

**Comment by guettli** [comment]
There is some progress concerning incoming/outgoing icons here: https://github.com/jossef/material-design-icons-iconfont/issues/47

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by TZanke** [comment]
> Icon available at: https://fonts.google.com/icons

can you please send us the names of the icons you refer to? Just closing feels a little bit _conceited_. Thank you in advance.

**Comment by jalpadoshi** [comment]
north_west, north_east, call_made, call_received
