### ISSUE TITLE
[Icon request] Server icon

### ISSUE THREAD

**Issue by turnerniles** [google/material-design-icons#523]
Requesting a server icon for the hardware category.

**Comment by RDGAlmeida** [comment]
I used the storage icon https://material.io/icons/#ic_storage
Maybe it will work for you

**Comment by tomasz1986** [comment]
The dns icon also looks alike to the storage one. It is just a little bulkier and narrower.

[https://material.io/icons/#ic_dns](https://material.io/icons/#ic_dns)

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
