### ISSUE TITLE
[Icon request] UpAndDown Arrow (for sortable, but unsorted columns.)

### ISSUE THREAD

**Issue by CookieJon** [google/material-design-icons#524]
For sortable table headings, you've given us many nice options to indicate the sort order applied to a particular column.  E.g.

- keyboard_arrow_up / keyboard_arrow_down,
- arrow_drop_up / arrow_drop_down.
- etc.

But what's missing are matching icons to indicate that a column _may_ be sorted when no sorting has been applied yet.  

Most often, a "double" arrow (up+down) is used for this purpose, as in the example image below...

![image](https://cloud.githubusercontent.com/assets/6636471/20582753/20a55b0c-b238-11e6-8dca-ac0fd4bc6c98.png)

Thank you for your consideration.

**Comment by CookieJon** [comment]
I was too quick, I beg your pardon... Just noticed the MD guide specifies its own appeoach...

> If sorting is enabled, display a light sort icon upon hover, which indicates that the column is sortable.

So MD doesn't require the icon, but I'll leave the issue for you to close because there is still no solution for Mobile, and it may well be a useful addition for other purposes.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
