### ISSUE TITLE
Sentiment icons are diferent from font to image files

### ISSUE THREAD

**Issue by GelsonMR** [google/material-design-icons#525]
All of the sentiment icons on the material.io website are different when I download the image files, actually it's a little difficult to differ the sentiments when using the font, the ones used on images are more expressive.

Example of the "sentiment dissatisfied":
On website:
![image](https://cloud.githubusercontent.com/assets/14277065/20831377/d88257a0-b86b-11e6-8184-d6504b55f0ac.png)

PNG:
![image](https://cloud.githubusercontent.com/assets/14277065/20831403/0da9d43a-b86c-11e6-9918-d8e39badced0.png)

**Comment by ObviouslyGreen** [comment]
The svg's for very (dis)satisfied are also different, they have crosses instead of circles for eyes:
![screen shot 2017-03-13 at 7 06 45 pm](https://cloud.githubusercontent.com/assets/4269549/23882800/3ac101c4-0820-11e7-9c57-e9383b5d057e.png)

**Comment by mrtnbroder** [comment]
Bump, can we get this fixed? Open since Mar 14.

**Comment by moomoomamoo** [comment]
Bump, can we please get this fixed? Would really like to use this icons :)

**Comment by steplerbox** [comment]
Bump, can we please get this fixed?

**Comment by RoelN** [comment]
Thanks for reporting! I'm closing this issue in favor of https://github.com/google/material-design-icons/issues/652 which addresses the same issue.
