### ISSUE TITLE
Icon files downloaded from library site differ from repository versions

### ISSUE THREAD

**Issue by juriejan** [google/material-design-icons#526]
This issue is originally in reaction to the differences (apart form the application of a color) between the 'drag_handle' SVG file in the repository and the one downloaded from the library site (https://material.io/icons/).

It would be interesting to know where and why the variation occurs between the two files, and also where issues for the library site can be reported.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
