### ISSUE TITLE
[Icon Request] Medical Icons

### ISSUE THREAD

**Issue by ma4crt** [google/material-design-icons#528]
There are no Medical icons, it will be good if you could include them with the other icons

**Comment by ninchica** [comment]
+1

**Comment by kristaki90** [comment]
+1

**Comment by AlexSemenov** [comment]
+1

**Comment by RoelN** [comment]
Several medical-themed icons have been added: https://material.io/resources/icons/?search=medic&icon=arrow_back_ios&style=baseline

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
