### ISSUE TITLE
Youtube?

### ISSUE THREAD

**Issue by deadbaed** [google/material-design-icons#53]
Hello!
I'm working on my website, and I need a Youtube icon, but when I search in the icons, I don't see any Youtube icon... :cry: 
Could you create one, or give my the path if there's already any?
Thank you anyway!

**Comment by boustanihani** [comment]
Why are essential icons like **youtube-play** not part material-design-icons?

**Comment by loctauxphilippe** [comment]
@boustanihani I have the same question.
