### ISSUE TITLE
image files and iconfont/codepoints out of date?

### ISSUE THREAD

**Issue by devoncarew** [google/material-design-icons#531]
It looks like the iconfont/codepoints file (and likely the images files) are out-of-date with the latest icon font. Would it be possible to update this repo, or is there a better system-of-record for the material design icons?

/cc @shyndman

**Comment by shabib3** [comment]
I created this for who ever needs - https://github.com/google/material-design-icons/issues/813#issuecomment-401601344

**Comment by RoelN** [comment]
The codepoints can now also be found in the `.codepoints` files here: https://github.com/google/material-design-icons/tree/master/font
