### ISSUE TITLE
guide on how to customize material icons

### ISSUE THREAD

**Issue by sombriks** [google/material-design-icons#532]
i have a small team and i want to add icons to the material design icons in order to avoid two distinct ways of put icons on the web/hybrid app being developed.

as far as i know, the icons must be put on the svg iconset version and from there we should generate the remaining font files (.eot, .woff2, .ttf, etc)

is there a guide explaining the needed steps to do it? 

custom icons will be published in a public git repo, however we want to do it correctly in order to make the result usable for more people.

thanks in advance.

**Comment by TheMainCoder** [comment]
I also want to know

**Comment by PeterShaggyNoble** [comment]
The community-driven [Material Design Icons project](https://materialdesignicons.com/) may be of interest to you.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
