### ISSUE TITLE
Alias search on Material.io/icons

### ISSUE THREAD

**Issue by Christilut** [google/material-design-icons#534]
It would be great if we can search for aliases on the icons website. For example, looking for an X icon, I tried the following:
- times
- disable
- x

before scrolling through the list and finding its called 'clear'. 

Edit: For anyone still looking: https://materialicons-alias.today

**Comment by Omiod** [comment]
Yes, please add searchable alias names, would be quite useful.

**Comment by MonsterCritic** [comment]
+1

**Comment by Christilut** [comment]
Perhaps an idea to open a special repo for these aliases? So anyone who wants to add an alias can open a PR. That way we can let the community do the hard work.

Personally I'd be fine with coming up with a bunch of aliases (or borrowing them from FontAwesome, lets be honost) and putting in some time for this.

**Comment by Christilut** [comment]
Actually I just started building a site for alias search so here it is: 
https://materialicons-alias.today

Contributions for better aliases are welcomed

**Comment by RoelN** [comment]
Searching by alias is now possible! Apologies for leaving this issue open for so long.

**Comment by tounsoo** [comment]
Is the alias info in the codebase somewhere? I would like to use them in my project.

**Comment by tounsoo** [comment]
@Christilut It looks like [Google Fonts Icon](https://fonts.google.com/icons) also has alias searching so I was looking if google kept an alias list somewhere.
