### ISSUE TITLE
Doesn't render icons in Chrome/Chromium on Ubuntu 16.10

### ISSUE THREAD

**Issue by dschep** [google/material-design-icons#537]
This is in Google Chrome Version 55.0.2883.87 (64-bit) with a completely new user profile. The same issue is present in Chromium too, but not Firefox.

![material-icons-kaput](https://cloud.githubusercontent.com/assets/667763/21430934/4f71255e-c833-11e6-92eb-bc9e1dc31826.png)

**Comment by FarzanDalaeeBamilo** [comment]
+1

**Comment by vistiyos** [comment]
+1

**Comment by lmanolov** [comment]
+1

**Comment by dschep** [comment]
So, I don't know what's exactly different, but I had to reformat my machine for other reasons, and now have Ubuntu Gnome 17.04 and chromium renders these icons correctly `¯\_(ツ)_/¯`

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
