### ISSUE TITLE
Icon Request: Map Signs Icon

### ISSUE THREAD

**Issue by darklilium** [google/material-design-icons#542]
Hello, 
Im actually using the material icon lib and i want to request an icon related to map signs.
![image](https://cloud.githubusercontent.com/assets/8507515/21726657/74bc53e8-d41c-11e6-8d48-d0c9cb536b16.png)
This is from font awesome tho.

Thanks in advice!

**Comment by alexkwa** [comment]
Consider just using https://material.io/icons/#ic_place ?

**Comment by alexkwa** [comment]
@darklilium Consider maybe just using https://material.io/icons/#ic_place ?

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
