### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by joncombe** [google/material-design-icons#546]
In the documentation for using the icons in HTML, you give the example:
`<i class="material-icons">face</i>`

However, you don't state here that icons with a space in their name should have an underscore instead, e.g.:
`<i class="material-icons">insert_drive_file</i>`

Yes, this information is in the ligatures section, but it would probably be helpful to mention the underscores thing in the main docs, i.e. found here: https://google.github.io/material-design-icons/#icon-font-for-the-web

**Comment by RoelN** [comment]
The docs have been updated in the meantime! Sorry for the confusion.
