### ISSUE TITLE
New Icons not rendering in Chrome and Safari

### ISSUE THREAD

**Issue by kev2480** [google/material-design-icons#547]
Chrome Version: 55.0.2883.95
Safari Version: 10.0
MacOS 10.12.1

This happens on the Material Icon website and if the webfonts are self hosted on a local project.

![chrome](https://cloud.githubusercontent.com/assets/2478058/22061470/f9b17606-dd6c-11e6-887c-8a27bb6a1141.png)
![safari](https://cloud.githubusercontent.com/assets/2478058/22061474/fd0f99ea-dd6c-11e6-9481-232688ff4651.png)

**Comment by RoelN** [comment]
Apologies for the inconvenience! The site has been updated in the meantime so this issue is solved :-)
