### ISSUE TITLE
[Icon request] Thermometer icon

### ISSUE THREAD

**Issue by Paul-Ver** [google/material-design-icons#548]
I'd like a thermometer icon (for a home automation project).

I'm currently using the "ac_unit" icon, but it looks a bit too cold and doesn't indicate it's possible to heat aswel.

[Example](http://imageog.flaticon.com/icons/png/512/12/12335.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF)

Use case:
![screen shot 2017-01-20 at 14 36 54](https://cloud.githubusercontent.com/assets/16624288/22151319/f29d8ba4-df1d-11e6-95ac-326eea114809.png)

**Comment by Sandtalker** [comment]
there's a "ac unit" icon for that.

**Comment by FrozenDroid** [comment]
@Sandtalker did you even read the issue? :P

**Comment by Utkarsh-vishnoi** [comment]
It's been more than a year. Is the icon being made?

**Comment by hooksoft** [comment]
It's been more than a year. Is the icon being made?

**Comment by RoelN** [comment]
Looks like this icon has been added! \o/

<img width="646" alt="image" src="https://user-images.githubusercontent.com/4570664/107616334-22adda80-6c4e-11eb-8950-c8747cd82ae5.png">
