### ISSUE TITLE
The icon doesn't align with text-align

### ISSUE THREAD

**Issue by MohamedYoussouf** [google/material-design-icons#549]
Hi, there 

I am using Icon font for the web, and I noticed that the icon doesn't has **inline element** behaviors even when to apply ``display: inline`` it  doesn't work!

**Comment by RoelN** [comment]
Did you solve the issue @MohamedYoussouf? I'll close the issue assuming this isn't longer relevant. If you're still running into problems, could you make a small example so we can look at it?
