### ISSUE TITLE
keyboard alt and timer auto icons are incorrect

### ISSUE THREAD

**Issue by caseyjhol** [google/material-design-icons#55]
The **keyboard alt** icon is a smiley face (same as **mood**, **insert emoticon**, etc.) and the **timer auto** icon is the same as **person**. I'm assuming these are just temporary icons until actual icons can be developed, but these icons don't really make sense in their current context.

See the **hardware** and **image** sections here: http://google.github.io/material-design-icons/.

**Comment by jestelle** [comment]
Looking into this one.  Probably a mistake when exporting some assets.

**Comment by epelc** [comment]
+1

**Comment by shyndman** [comment]
I'm not seeing either of these icons in the repo. Closing.
