### ISSUE TITLE
Fonts in iconfonts folder and webfonts are outdated?

### ISSUE THREAD

**Issue by rejhgadellaa** [google/material-design-icons#550]
Hi,

The readme was updated 5 months ago (with announcement of 3.0.1) but the files in the iconfont folder are a year old, at least according to github.

The webfonts seem to point to v2 (it says 'v20' in the url)

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v20/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
}
```

Is this correct?

**Comment by naivefun** [comment]
any plan to update fonts to 3.x?

**Comment by vipex** [comment]
Is the repo still active? it's been a while since last release...

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
