### ISSUE TITLE
Size and color chooser do not work on new website on Firefox

### ISSUE THREAD

**Issue by lorenzos** [google/material-design-icons#552]
It's impossibile to choose the size and color of the icon on the new website when using Firefox 50.1. When selecting an icon, the blue bottom bar appears, but `Select an item` is displayed instead of the sizes dropdown, and the black and white circles are missing. 

Download buttons work, but they always download the 24dp black version.

Worked before the site update, before the big dark header and new favicon. Works on Chromium on the same PC.

**Comment by aketchm** [comment]
Anthony passed away in April of 2015.  If you were a customer of his, for
monolith multimedia...just informing you of such.

**Comment by lorenzos** [comment]
Any news on this? At least, can you confirm the issue?

**Comment by shyndman** [comment]
Hi there,

Yes, this is a known issue. Turns out it's related to the very old version of Polymer used by the site. I'm going to see whether someone can take a look in the next few days.

Thanks for the report.

**Comment by jordanfine** [comment]
💃🕺 fixed 💃🕺
