### ISSUE TITLE
Font file displays boxes in inDesign

### ISSUE THREAD

**Issue by vannut** [google/material-design-icons#553]
I'm trying to use the font in inDesign. But somehow when using the font it displays a box as substitute for the characters being replaced with the icon/ligature. 
![schermafbeelding 2017-01-26 om 11 59 09](https://cloud.githubusercontent.com/assets/7419859/22328919/0ab537f0-e3bf-11e6-9fe2-60c1956df472.png)

When exporting the document to PDF the boxes are gone.
Any suggestions how to remove these boxes in inDesign?

**Comment by marklanham** [comment]
I found the same problem using Googles Material Icons in InDesign but managed to fix it by setting a paragraph style with Justification > Composer to Adobe World-Ready Single-line Composer.
