### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by ZyeF** [google/material-design-icons#556]
Hello !

I am a web developer and the pack of icons interests me a lot for the creation of my web applications.

But I ask myself a few questions:
- Do I have the right to provide these icons at the same time as selling a website (knowing that Google has written that it does not want to be sold)?
- Can I use them without having to mention anything (license included)?

Or

- Do I have to indicate the license of these icons in the "Terms of Use" page?
- If I modify these icons, do I have to indicate it somewhere?

(Sorry if there are mistakes, I'm French)

Thank you !

**Comment by jamesappitized** [comment]
CF README.md

"We have made these icons available for you to incorporate them into your products under the Apache License Version 2.0. Feel free to remix and re-share these icons and documentation in your products. We'd love attribution in your app's about screen, but it's not required. The only thing we ask is that you not re-sell these icons."

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
