### ISSUE TITLE
Feature request: multiple search terms for an icon

### ISSUE THREAD

**Issue by ncovercash** [google/material-design-icons#558]
I would like to request that multiple terms match 1 icon when searching.  Although the identifier would be the same, it would be immensely easier to find a desired icon.

For example, `local_shipping` would have `freight`, `truck`, `shipping`, etc.

**Comment by BenRacicot** [comment]
Wow, we need this. As an example, searching for "Calculator" returns nothing.

**Comment by Baneeishaque** [comment]
+1

**Comment by RoelN** [comment]
The site now has aliases. Closing this issue as I'd consider this fixed :-)
