### ISSUE TITLE
Icon Request: Lab/Beaker/Flask Icon

### ISSUE THREAD

**Issue by lotsawa** [google/material-design-icons#559]
Hello,

I think a flask/lab/beaker icon would be a great addition to the library, for indicating products' experimental features.

Thanks.

**Comment by CD-UNCC** [comment]
This is a must. just drag in the flask from google start up weekend

**Comment by makitsune** [comment]
Yes please!

**Comment by RoelN** [comment]
There's the `science` icon that would fit that description:

<img width="122" alt="image" src="https://user-images.githubusercontent.com/4570664/107616738-efb81680-6c4e-11eb-9369-f8cf6517b95f.png">
