### ISSUE TITLE
person pin svg and it's preview on website

### ISSUE THREAD

**Issue by rssems** [google/material-design-icons#563]
ic_person_pin_black_24px.svg and it's preview on https://material.io/icons are not the same

<img width="274" alt="screen shot 2017-02-08 at 8 08 12 pm" src="https://cloud.githubusercontent.com/assets/847648/22764713/563da0f6-ee3a-11e6-9ef5-659dca86b758.png">

**Comment by PushkaCom** [comment]
Does anyone have a copy of the actual circle icon?

Duplicate post here:

https://github.com/google/material-design-icons/issues/501

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
