### ISSUE TITLE
[Suggestion] Icon Package Generator

### ISSUE THREAD

**Issue by AlbertMarashi** [google/material-design-icons#564]
We know that there is over 170+ icons here, I think I can comfortably say, not everybody uses all of them. So I ask that you create an icon selector package, which only includes selected icons. Similar to how Google Fonts works. This would reduce website overhead.

**Comment by MrMashy** [comment]
I really think you should consider this.

**Comment by jfbrennan** [comment]
Especially since there's 900+ now lol!

**Comment by jfbrennan** [comment]
@AlbertMarashi did you ever find a way to do this?

**Comment by rsheeter** [comment]
https://github.com/google/material-design-icons/issues/1201#issuecomment-914678154 describes how one might approach this in Python.

**Comment by AlbertMarashi** [comment]
@jfbrennan check out https://materialdesignicons.com/

**Comment by tphinney** [comment]
The original request was for this to be “similar to how Google Fonts works.” Well, the icons are now available through Google Fonts, so they can work exactly that way!
https://developers.google.com/fonts/docs/material_symbols newest, variable font
https://developers.google.com/fonts/docs/material_icons classic version

**Comment by jfbrennan** [comment]
OP request was:
>I ask that you create an icon selector package, which only includes selected icons.

No such tool exists. Google Fonts API cannot do this for Material Symbols or Icons (which there are now 3,000+).

This ticket or https://github.com/google/material-design-icons/issues/1201 should be reopened. The demand is there and so far no one in the dev community has been able to put together a working solution. Would be great if Google put some folks on a solution. CLI would be ideal.
