### ISSUE TITLE
Icons appear blank on material.io/icons

### ISSUE THREAD

**Issue by JulianKingman** [google/material-design-icons#567]
For some reason many icons appear blank on material.io/icons
![screen shot 2017-02-18 at 5 27 44 pm](https://cloud.githubusercontent.com/assets/1566400/23097360/b19a3e92-f5ff-11e6-84da-906afdb1f1b4.png)

I tried clearing cache, doesn't help. Incognito window: same thing. I thought it could be because I have a version of the font installed, but removing it seemed to have no effect. It only occurs in chrome.

**Comment by RoelN** [comment]
This has been addressed in the meantime, thanks for reporting!
