### ISSUE TITLE
Draggable

### ISSUE THREAD

**Issue by rzb** [google/material-design-icons#568]
I'm looking for the drag handles (vert and horiz) used in most google apps, e.g. google forms. The "drag_handle" one is different and it's missing the vertical variation. Any plans to include them?

By the way, perhaps not the proper place to ask but I've just recently found this [community-extended icon set](https://materialdesignicons.com/). Any tip on how to import some of those icons? I'd just replace packages with their bootstrap version, but since you're using text nodes and they use classes, it'd be massive to adapt at this point for my app.

**Comment by mmoravcik** [comment]
+1

**Comment by huug** [comment]
I think this issue can be closed cause the icon is included in the set: https://material.io/tools/icons/?search=drag&icon=drag_indicator&style=baseline

**Comment by yang** [comment]
drag_indicator seems to be missing from the icon font, at least in the latest package available via npm.

**Comment by joostblok** [comment]
Can confirm, drag_indicator is still missing

**Comment by bs-thomas** [comment]
Confirmed just now, drag_indicator is still missing

**Comment by doublehelix** [comment]
Is this the icon you're looking for?

https://github.com/google/material-design-icons/blob/master/editor/svg/design/ic_drag_handle_24px.svg

**Comment by yang** [comment]
@doublehelix No not drag_handle, it's drag_indicator that's missing.  @huug linked to it above:

https://material.io/tools/icons/?search=drag&icon=drag_indicator&style=baseline

**Comment by meoblast001** [comment]
Confirming this is still an issue. Just searched the repository for "drag_indicator" and it doesn't occur.

**Comment by rainyer** [comment]
Confirmed just now, drag_indicator is still missing.

**Comment by DiZhou92** [comment]
same issue here, still missing

**Comment by RoelN** [comment]
Looks like it has been added in the meantime:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/4570664/107371091-245b8f00-6ae4-11eb-90da-45263181f515.png">

Make sure you're using the latest assets (e.g. font from this repo, or as served by Google Fonts)
