### ISSUE TITLE
Missing icons google material design

### ISSUE THREAD

**Issue by Redani** [google/material-design-icons#569]
I'm would like to start using google material icons (material.io) but they are so many icons missing such as the social networks, or the globe, ....

- Is this library still maintained coz the last commit is about a year ago?
- Is it possible to easily add new icons?
- I've found an alternative library: materialdesignicons but I'm still hesitating if I should switch to it! what do you think about it?

Thanks in advance

**Comment by RoelN** [comment]
1. Yes, this library is still maintained! :-)
2. Icons are only added by Google internally. But you can open an issue if you want to request a specific icon.
3. I'm not sure to which one you're referring, but the community has been providing really great alternative sources for Material Design Icons!
