### ISSUE TITLE
Some icons are wrong.

### ISSUE THREAD

**Issue by Wolftein** [google/material-design-icons#57]
For example ic_done_white_48dp has the same size for hdpi and mdpi. And xxhdpi image is smaller than xhdpi.

**Comment by jestelle** [comment]
I believe you're mistaken.  Icons look ok to me.
Do tell me if I'm wrong.

$ find . | grep ic_done_white_48dp | xargs -n1 identify
./action/1x_web/ic_done_white_48dp.png PNG 48x48 48x48+0+0 8-bit sRGB 363B 0.000u 0:00.000
./action/2x_web/ic_done_white_48dp.png PNG 96x96 96x96+0+0 8-bit sRGB 587B 0.000u 0:00.000
./action/drawable-hdpi/ic_done_white_48dp.png PNG 72x72 72x72+0+0 8-bit sRGB 476B 0.000u 0:00.000
./action/drawable-mdpi/ic_done_white_48dp.png PNG 48x48 48x48+0+0 8-bit sRGB 363B 0.000u 0:00.000
./action/drawable-xhdpi/ic_done_white_48dp.png PNG 96x96 96x96+0+0 8-bit sRGB 587B 0.000u 0:00.000
./action/drawable-xxhdpi/ic_done_white_48dp.png PNG 144x144 144x144+0+0 8-bit sRGB 791B 0.000u 0:00.000
./action/drawable-xxxhdpi/ic_done_white_48dp.png PNG 192x192 192x192+0+0 8-bit sRGB 1.03KB 0.000u 0:00.000
