### ISSUE TITLE
Material icons not showing across all google sites

### ISSUE THREAD

**Issue by daanaerts** [google/material-design-icons#570]
Browser: Chrome 56, Firefox 51, Safari saf
MacOS: 10.12.3 (16D32)

Hi, for a couple of weeks none of google material icons are showing across google sites, e.g. firebase and developers.google.com.

I see the alt tag of the icons. This happens in FF, Safari and Chrome.

http://pasteboard.co/DTZMv1fUL.jpg
http://pasteboard.co/3ZoPLVjbC.png

**Comment by jestelle** [comment]
Hi @daanaerts Is it possible you've disabled custom fonts in some way?  I believe both those products use the Material Design icons via our icon fonts.

Other possibilities are ad blockers or anything else that might be blocking the font from loading?

**Comment by daanaerts** [comment]
Hi @jestelle. I've tried in 3 browsers, and also in chrome without adblock.

**Comment by jestelle** [comment]
@daanaerts Do you see the same problem here? https://material.io/icons/

Also – I don't think your screenshot uploaded properly, if you upload it so I can see it I may be able to help more.

**Comment by daanaerts** [comment]
Yes, sorry, screenshot upload wasn't working. 

http://pasteboard.co/DTZMv1fUL.jpg
http://pasteboard.co/3ZoPLVjbC.png

**Comment by daanaerts** [comment]
Hi, Thanks for the effort.

After some hours of searching, it turns out a Sketch plugin installed Material icons font locally. Removing that font fixed the issue for me.

**Comment by jestelle** [comment]
Got it.  You likely had an old version of the font installed locally, and
it was missing some of the glyphs that web pages were expecting to see.
