### ISSUE TITLE
Icon Request: Window Popout

### ISSUE THREAD

**Issue by EliotSlevin** [google/material-design-icons#571]
Popout icon is used to show window is going from inline or embedded, to it's own window. This icon is common, but not always the same. Eg

Gmail
![screen shot 2017-03-01 at 5 50 39 pm](https://cloud.githubusercontent.com/assets/4987326/23446379/aea66976-fea7-11e6-85c5-5781d9079803.png)

Chrome dev tools
![screen shot 2017-03-01 at 5 50 52 pm](https://cloud.githubusercontent.com/assets/4987326/23446378/aea41d24-fea7-11e6-9fef-bd174452f086.png)

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
