### ISSUE TITLE
Bad hover behavior for star_rate icon and other improperly named icons

### ISSUE THREAD

**Issue by tw3** [google/material-design-icons#572]
If you add a CSS hover style to the `star_rate` icon you will notice that the hover state is activated outside the bounds of the icon.

HTML:
```
<md-icon class="md-18 test-hover">star_rate</md-icon>
```

CSS:
```
.test-hover:hover {
  background: teal;
}
```

Plunker:
[https://plnkr.co/edit/LW7qLF?p=preview](https://plnkr.co/edit/LW7qLF?p=preview)

This also happens if you misname an icon, e.g. 

HTML:
```
<md-icon class="md-18 test-hover">visibility_on</md-icon>
<md-icon class="md-18 test-hover">visibility_foobar</md-icon>
```

There is no `visibility_on` icon defined in the docs but there are `visibility` and `visibility_off` icons.  The `visibility_foobar` is obviously misnamed.  For both of these ids the `visibility` icon appears.  The correct behavior should be that misnamed icons do not appear.

**Comment by jestelle** [comment]
This is a tricky bit with using ligatures.

There _is_ an icon called 'star', so when you write 'star_rate', it renders the star, and then '_rate', which renders as empty boxes.

Angular might be able to fix this by how they wrap the icons.

But you could also fix it by only using the names of icons that actually exist ;-)

'star_rate' is the only one in your example that _is_ defined, but likely hasn't been pushed out to our icon font.

I'm going to give in to this – talking to our font team and the angular team and see how we might be able to best address this.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed, or not relevant after recent updates. If not, feel free to reopen this issue or create a new one with more information.
