### ISSUE TITLE
request lineal version

### ISSUE THREAD

**Issue by alphaelf** [google/material-design-icons#574]
about UX the lineal icons more popular.

**Comment by jestelle** [comment]
Could you clarify your question?  Are you asking for icons that are outlined vs the solid fills?

**Comment by alphaelf** [comment]
@jestelle yep! more like ios icons

**Comment by RoelN** [comment]
Various styles are now available from https://material.io/resources/icons:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/4570664/107371629-c54a4a00-6ae4-11eb-97dc-402f6e096bfc.png">
