### ISSUE TITLE
ICON Request

### ISSUE THREAD

**Issue by kgtkr** [google/material-design-icons#575]
fork.
Icon like github.

**Comment by jestelle** [comment]
You might consider the https://material.io/icons/#ic_call_split icon for this?

**Comment by kgtkr** [comment]
Thanks you!

**Comment by Derekjohnson277** [comment]
Format-overline (Editor section of icons).
There are already icons for underline and strike through, but not for overline.

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
