### ISSUE TITLE
Request: add "install" icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#578]
as title says.

**Comment by jestelle** [comment]
Consider file_download or cloud_download

**Comment by AndroidDeveloperLB** [comment]
@jestelle Not good alternatives, as the install source might not be from the Internet. It could be from the file-system (APK file) .
Plus, the icons you mentioned are for download alone. To actually have the app installed, it's not enough to just download the file. You have to install it too.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi You mean "install_mobile" ? Is it good for APK install?

**Comment by jalpadoshi** [comment]
There are other icons similar to this request:install_desktop, install_mobile, download

**Comment by AndroidDeveloperLB** [comment]
@jalpadoshi While those are nice, it's not what I was talking about.
I talked about installing an APK file. Here, made a new request as this one seems to be unclear:
https://github.com/google/material-design-icons/issues/1267
