### ISSUE TITLE
Request Link & Unlink

### ISSUE THREAD

**Issue by FeralBytes** [google/material-design-icons#581]
More Like a Chain and a Broken Chain.
Less Like the [Hyperlink Icon](https://material.io/icons/#ic_link) that currently exists. 
See these from Font Awesome:
[Link](http://fontawesome.io/icon/link/)
[Unlink](http://fontawesome.io/icon/chain-broken/)

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
