### ISSUE TITLE
Request for New Rupees Icon

### ISSUE THREAD

**Issue by imChiragSuthar** [google/material-design-icons#584]
I am using png and svg file for the rupees icon with material Design but it not proper set with the design that's i need the indian rupees icon for material Design.
Icon as Follow Link : https://image.flaticon.com/icons/svg/25/25473.svg

I also need icon as fire-base database for database. and Budget icon with suitable appropriate.

**Comment by imChiragSuthar** [comment]
It's my bad that not received any reply  😒

**Comment by RoelN** [comment]
Apologies for the delay! I marked this as an icon request.

**Comment by RoelN** [comment]
Closing this in favor of https://github.com/google/material-design-icons/issues/371
