### ISSUE TITLE
Multiple Clicks and the button changes white

### ISSUE THREAD

**Issue by chandanndeep** [google/material-design-icons#585]
Hi,

When I multi-click on the button, and the button turns into white. Please see the video and help me.

https://www.screencast.com/t/7c8zITVz

Thanks

**Comment by chandanndeep** [comment]
After click class "waves-ripple" never remove.

**Comment by chandanndeep** [comment]
Any update here?

**Comment by shyndman** [comment]
Hey @chandanndeep,

I don't think you're posting to the right repo. material-design-icons deals specifically with icon assets. 

I can't play Flash, so I don't know what you're running into. Are you using a UI framework as well? Something like Material Design Lite, or Angular Material?

**Comment by chandanndeep** [comment]
Thanks for the reply.
I am using **materialize**
http://materializecss.com/table.html

**Comment by shyndman** [comment]
Ah, great. https://github.com/Dogfalo/materialize would be the right place to file your issue.
