### ISSUE TITLE
BUG: 'ic_book' icon

### ISSUE THREAD

**Issue by cfacundo** [google/material-design-icons#588]
'ic_book' icon is showing a space at the beginning, this can be solved using 'class' icon instead:

![image](https://cloud.githubusercontent.com/assets/1285712/24517081/47eb1f34-1553-11e7-9494-3da391e91b95.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
