### ISSUE TITLE
lines added to ic_high_quality_48px.svg

### ISSUE THREAD

**Issue by cortopy** [google/material-design-icons#59]
When downloading or sacing ic_high_quality_48px.svg lines appear on the right side. The same happens with the smaller version

**Comment by jestelle** [comment]
Hi @cortopy, I can't seem to reproduce what you're describing.  Can you give me a little more detail?  Or a screenshot, or something?

Where are you viewing the SVG?

**Comment by cortopy** [comment]
Please see a screenshot here http://tinypic.com/r/zl582e/8

The HQ icon displays with an overflowing line on the right and a distorted Q. 

The screenshot shows how the icon is displayed in my Ubuntu laptop. But I believe this may have to do with formatting. When I was using the SVG as a single file on a website, the distortions would appear on every browser no matter what. However, when I added the file to a SVG sprite, icon seems to be working fine.

**Comment by jestelle** [comment]
There is a bug with librsvg such that it parses SVGs incorrectly.

This is the bug I filed:
https://bugzilla.gnome.org/show_bug.cgi?id=747428
And see the bug it's marked duplicate of.

If you update librsvg, or your image viewer, it may resolve the issue.
