### ISSUE TITLE
Icons with underscores rendering with extra whitespace

### ISSUE THREAD

**Issue by tziporaziegler** [google/material-design-icons#591]
I'm trying to use the border color icon on my web page: https://material.io/icons/#ic_border_color

When I use `<i class="material-icons">border_color</i>`, the icon is rendering with a lot of empty whitespace on both side:
![extra_space](https://cloud.githubusercontent.com/assets/10053938/24726475/8ecdeafe-1a20-11e7-9720-acee7ccc1384.png)

The icon looks fine if I use `<i class="material-icons">&#xE22B;</i>`, with the code instead of the friendly name:
![no_space](https://cloud.githubusercontent.com/assets/10053938/24726486/926d69c8-1a20-11e7-9ddc-a9b00e94d52b.png)

I tried `format_color_fill`, `account_box`, `format_paint`, and they all have the same whitespace issue.
Icons like `face`, `build` and `edit`, that do not have underscores, look fine though.

This issue occurs both when I reference `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`, and also when I reference a local hosted font sheet.

I was able to reproduce this issue in both Chrome and Firefox.

Related issues:
- https://github.com/google/material-design-icons/issues/302 - Was using icon names that didn't exist.
- https://github.com/google/material-design-icons/issues/390 - Was adding an extra "s" to the end of the icon name.
- https://github.com/google/material-design-icons/issues/238 - Was using a space instead of an underscore.

`border_color` does exist, seems to be spelled right, and I am using an underscore, so this does not seem to be the same problem as the related issues. This issues seems to be most related to #238, however instead of the underscore being the solution, it seems to be what is causing the problem here.

**Comment by DavyDeDurpel** [comment]
I'm also have this issue.  As a side effect when trying to render 'add_comment' I get 2 icons instead of one.  The reason seems to be that the underscore is interpreted as a space and so angular sees it as 2 separate icons.

**Comment by Dakshank** [comment]
Also, have the issue with `<i class="material-icons">star_rate</i>`

**Comment by Elypson** [comment]
I also have this issue

**Comment by adamglowacki** [comment]
I had exactly the same problem.
https://stackoverflow.com/a/63874454/8019153

**Comment by RoelN** [comment]
Looks like this specific issue has been fixed:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/4570664/107369574-3fc59a80-6ae2-11eb-959a-fc94a4c29c81.png">

Codepoints files can indeed be found here: https://github.com/google/material-design-icons/tree/master/font
