### ISSUE TITLE
Small defect in the Sim card icon

### ISSUE THREAD

**Issue by francescobaldan** [google/material-design-icons#599]
There is an almost invisible defect in the sim-card icon (https://github.com/google/material-design-icons/blob/master/hardware/svg/production/ic_sim_card_24px.svg).

The right side of the icons is not perfectly perpendicular to the bottom side, there is a very small inclination.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
