### ISSUE TITLE
huge file size during bower install

### ISSUE THREAD

**Issue by bobmash** [google/material-design-icons#60]
I'm not sure what's going on, once the installation is complete it takes up a total of 49.4MB, but during install, I was running out of disk space when I had 750MB free.  Something seems weird, and wrong with that.

**Comment by ilanbiala** [comment]
Biggest issue is downloading so many files that for most people are probably not necessary right now. Maybe it would make sense to have a repo with just one file per icon that is an optimized SVG or something like that?

**Comment by addyosmani** [comment]
There are already open issues about this, but we do intend on splitting out the repo into separate bundles that are more easily consumable. At the moment, I agree that a 50MB download is pretty huge. We're also working on an official icon font version for those that prefer consuming them that way.

**Comment by ilanbiala** [comment]
@addyosmani can you link us to the open issues so we can subscribe? Is there any place that we can track the progress of improvements i.e. milestones or specific labels and such?
