### ISSUE TITLE
culture icon

### ISSUE THREAD

**Issue by RWOverdijk** [google/material-design-icons#600]
I'm not sure if I'm allowed to do requests here, but a culture icon would be perfect. It's the only icon I'm missing.

Something like this: http://www.in-fusiongroup.com/sites/default/files/culture-icon.png

**Comment by jalpadoshi** [comment]
the link is broken.  Closing this issue for now.

**Comment by RWOverdijk** [comment]
Did you people just wait 5 years to say that? I'll attach a new example then. See you in another 5 years.
