### ISSUE TITLE
Stuck-How to pass values from aps.net to javascript - Chartist.JS

### ISSUE THREAD

**Issue by aqeelahmedqs** [google/material-design-icons#602]
Dear Team,

We are stuck at pulling data from asp.net to javascript. Charts are not showing data. 

Please help us to come out from this critical situation.

**Comment by RoelN** [comment]
Closing this issue because it doesn't contain a concrete question or a detailed description regarding Material Design Icons. Feel free to reopen this issue or create a new one with more information.
