### ISSUE TITLE
Intermittent display issue on Apple devices, predominately iOS 8 onwards

### ISSUE THREAD

**Issue by jonsamwell** [google/material-design-icons#604]
Hi,

It seems the icons are not always getting displayed when viewing on any Apple device (iOS 8) Safari (including the latest iPhone).  The icon's text representation is display instead of the icon.  See the image at the bottom the button should have the 'send' icon but the text representation is displayed instead.

![icon-not-displaying](https://cloud.githubusercontent.com/assets/3694497/25651215/31434828-3025-11e7-8cc0-f1d7c4b06c6c.jpg)

This is an Angular 1 app but I don't think that should make any difference.  The icon font is linked to in the header and it makes no difference if the '&#x...;' code is used instead of the text representation.

Usually, after a page refresh, the icons appear which is more puzzling.

This issue can be seen here https://app.easilog.com visiting with Safari on an Apple device with iOS 8.

Any suggestions on how to fix this would be great!!

Thanks,

Jon

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
