### ISSUE TITLE
Redundant icons

### ISSUE THREAD

**Issue by salmanulkhair** [google/material-design-icons#607]
Both "local dining" and "restaurant menu" icons are exactly same . The only difference is in dp options. The "restaurant menu" icon don't have 12 dp option.
"landscape" and "terrain" icons are exactly same.
"hotel" and "local hotel" icons are exactly same.
"insert invitation" and "event" are exactly same
"query builder" and  "access time" are same
"directions subway" and "directions transit" are same

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
