### ISSUE TITLE
Request for Bar-code and QR code icons

### ISSUE THREAD

**Issue by hussamite** [google/material-design-icons#609]
Hey all,

Please consider making icons for bar-code and QR code.

It would be a big addition to your awesome collection.

https://en.wikipedia.org/wiki/Barcode
https://en.wikipedia.org/wiki/QR_code

Thanks from your friend in Syria :)

**Comment by evnexus** [comment]
Any plans on it at all?

**Comment by RoelN** [comment]
Closing this as QR code has arrived! \o/
