### ISSUE TITLE
Icon Request: tag

### ISSUE THREAD

**Issue by TangSteven** [google/material-design-icons#610]
The tag icon which is used in [inbox.google.com](inbox.google.com) for the promotions label in unavailable.

![tag](https://ssl.gstatic.com/bt/C3341AA7A1A076756462EE2E5CD71C11/2x/ic_offers_24px_clr_r3_2x.png)

**Comment by sampayne** [comment]
@TangSteven 

Search for 'local offer' at https://material.io/icons/
