### ISSUE TITLE
IE & https

### ISSUE THREAD

**Issue by pengxianggui** [google/material-design-icons#611]
The icons doesn't work while i access my site using https under IE. 
I don't down why.
It's work well under chrome.
It's work both well using http.
Could someone help me, thinks!

**Comment by cy19890513** [comment]
I accessed https://google.github.io/material-design-icons/ using IE. It did same thing, not showing icon but content.

**Comment by pengxianggui** [comment]
@cy19890513 How did it happend?I accesse it perfectly( [https://google.github.io/material-design-icons/](https://google.github.io/material-design-icons/)), my IE version is 11, what about you?The problem makes me crazy!Someone help me.

**Comment by severinkehding** [comment]
There is the off chance that your organization (if your computer is in one) handles some setting for example via a GPO.

I for one would check the 
* "Internet Options" of the IE
* Tab Security
* Internet - globe Icon
* Security Level -> "Custom level..."
* Scroll to Downloads -> Font download and make sure the Setting is "enabled"
* ![image](https://user-images.githubusercontent.com/1046539/60968196-cae61980-a31c-11e9-8b7a-c5ada2ccd154.png)

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information. Or track the issue mentioned above.
