### ISSUE TITLE
has this project been abandoned?

### ISSUE THREAD

**Issue by jamesdixon** [google/material-design-icons#614]
Hi,

I love the icons, but it seems like the project has been abandoned and no new icons are being created. Is this the case?

Thanks!

**Comment by DanielRuf** [comment]
Personally I think this project has way too few contributors. Other material design projects have around 200 - 300 contributors. I guess the 15 contributors are working on other projects at the moment and all are @google employees.

For example @shyndman (and other contributors) work now on @material-components projects.

**Comment by Templarian** [comment]
@DanielRuf Fixing that shortly to give the contributor team (6 main) more ability to manage the project. We've prioritized quality at the 2k mark slowing down icon addition a little and focusing on tooling.

Also I don't think Google has stopped this project, they release in batches. Looking at their new/current apps they have new icons that we'll hopefully see added shortly.

**Comment by DanielRuf** [comment]
Ah ok. Hopefully this project sees some progress in the near future =)

**Comment by DanielRuf** [comment]
Just as a sidenote, some icons eg https://material.io/icons/#ic_close have bigger sizes like 256dp but the files (ic_close_black_256px.svg) are not here in the repository.

**Comment by bendrexl** [comment]
It's been well over a year since the last content update (if I'm reading the release log correctly), certainly seems like this project is on life support.

**Comment by RoelN** [comment]
Work is being done, by humans! :-) Feel free to track specific updates in their respective issue. For now, closing this issue because it doesn't contain a concrete question or a detailed description. Feel free to reopen this issue or create a new one with more information.
