### ISSUE TITLE
Request: shutdown icon

### ISSUE THREAD

**Issue by zyarnold** [google/material-design-icons#618]
https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=658&q=shutdown+icon&oq=shutdown+icon&gs_l=img.3..0l9.4756.6049.0.6258.14.14.0.0.0.0.186.1312.8j5.13.0....0...1.1.64.img..1.13.1311.0.vcr978hSkls

**Comment by RoelN** [comment]
It's here! \o/

<img width="285" alt="image" src="https://user-images.githubusercontent.com/4570664/107367464-9ed5e000-6adf-11eb-8b97-c4c1ba10b764.png">
