### ISSUE TITLE
How do you generate png from svg?

### ISSUE THREAD

**Issue by dafi** [google/material-design-icons#62]
Hi,

I'm using this amazing icon pack in my apps and I need to add about 30 new icons and I want to conform to material-design-icons png directory structure creating for every SVG version the 12 png shown below

`**icon_name**_black_18dp.png`

`**icon_name**_black_24dp.png`

`**icon_name**_black_36dp.png`

`**icon_name**_black_48dp.png`

`**icon_name**_grey600_18dp.png`

`**icon_name**_grey600_24dp.png`

`**icon_name**_grey600_36dp.png`

`**icon_name**_grey600_48dp.png`

`**icon_name**_white_18dp.png`

`**icon_name**_white_24dp.png`

`**icon_name**_white_36dp.png`

`**icon_name**_white_48dp.png`

Creating icons manually (I use inkscape) it's error prone, complicated and it requires a lot of time so, do you use some script to generate png files?
May you release this script?
If the scripts doesn't exist do you have any idea how to simplify generation process?

**Comment by kalisto74** [comment]
Hi!
http://romannurik.github.io/AndroidAssetStudio/ MAKE ICONS FOR YOUR APP

**Comment by dafi** [comment]
Ok thanks, you give me the idea to find (or write myself) some imagemagik based script

**Comment by jestelle** [comment]
We intend to release our scripts at some point, but it may take quite some
time before we're able to do so.

We've used a combination of rsvg-convert, PhantomJS, and ImageMagick to do
the heavy lifting, and some python scripts to tie everything together.

**Comment by dafi** [comment]
@jestelle if you need help to make public these scripts, I'm here. Maybe you can release as an alpha version and I can try to use it, I can pull requests if necessary.

Just now I started to combine ImageMagick and https://github.com/shakiba/svgexport but I don't want to reinvent the wheel.

**Comment by Templarian** [comment]
@dafi http://materialdesignicons.com/custom 

This is probably exactly what you want. Let me know if you find any issues.

(Just got back from vacation or would have linked it sooner, the alpha tests of the site use it to test their files).

**Comment by dafi** [comment]
@Templarian please apologize me but I don't understard how to use it.

I try to explain better my needs, I've a lot of svg files (just for complete information they are 48x48 pixel but this doesn't matter), they are monochrome, exactly like the svg file in material-design-icon repository.
I want to execute some unix script that recursively scan all svg files and for every single svg the script generated
- black
- white
- grey 666
and
for every black/white/grey666 generate
- 18dp/24dp/36dp/48dp for all drawables: 'drawable-hdpi', 'drawable-mdpi', 'drawable-xhdpi', 'drawable-xxhdpi', 'drawable-xxxhdpi'

So for one single svg the scripts must generate 3 *4 * 5 = 60 png files
3 = black + white + grey 666
4 = 18dp + 24dp + 36dp + 48dp
5 = 'drawable-hdpi', 'drawable-mdpi', 'drawable-xhdpi', 'drawable-xxhdpi', 'drawable-xxxhdpi'

**Comment by Templarian** [comment]
Oh, yea, sorry due to the architecture (the system manages a few different icon packs, and these exports only support 24x24).

It will generate all those files you need if you import a 24x24 SVG. You can export your 48x48 at half the size and then it will import just fine.

It also needs to be a single path (it's tied to a bunch of validation logic for the font generation portion).

**Comment by dafi** [comment]
Resizing svg files to 24x24 is reasonable in my scenario so your tool seems simply perfect but I don't understand if it supports the batch mode (eg passing more svg files at once)

**Comment by Templarian** [comment]
No it does not allow batch at this time. I could make it do that, but realistically this tool assumes people are doing one off logo/a few icons. I'm putting all my dev time into the community icons, this is just to handle the "Can I have my company logo added?" icon requests.

My batch process on the server uses `PHP` and `ImageMagick`. If it would help I could share part of the source that does the generation (pseudo code, since I'm assume you don't use `PHP` for your scripts).

**Comment by dafi** [comment]
Your tool is simply amazing and I totally agree with the "one-shoot" scenario. 
I use `ruby` but at this time everything working is welcomed so `PHP` could be my new best friend :D
Anything you can share is good for me, many thanks :)

**Comment by dafi** [comment]
@Templarian just tried your tool with some svg file and the results are simply awesome!!! I don't understand why doesn't upload the file with Firefox but doesn't matter at all, switched to chrome

**Comment by Templarian** [comment]
I'll look into that [bug](https://github.com/Templarian/MaterialDesign/issues/81), probably just an oversight on my part.

I deleted a lot of the unnecessary code, the code below should give you an idea of how `ImageMagick` can be used to generate all the files (should be very easy to convert to `Ruby`).

```php
$details = array(
    'icon_data' => 'M to Z path data here',
    'icon_name' => 'icon-name-here'
);
include('zipstream.php'); // PHP library for zip files
$zip = new ZipStream($details['icon_name'].'.zip');
$folders = array(
    'drawable-mdpi' => array(18, 24, 36, 48),
    'drawable-hdpi' => array(27, 36, 54, 72),
    'drawable-xhdpi' => array(36, 48, 72, 96),
    'drawable-xxhdpi' => array(54, 72, 108, 144),
    'drawable-xxxhdpi' => array(72, 96, 144, 192)
);
$name = str_replace('-', '_', $details['icon_name']);
$dps = array('18dp', '24dp', '36dp', '48dp');
foreach ($folders as $folder => $sizes) {
    foreach ($sizes as $i => $size) {
        $dp = $dps[$i];
        $zip->add_file($folder.'/ic_'.$name.'_black_'.$dp.'.png', icon_png_blob($details['icon_data'], $size, '000000'));
        $zip->add_file($folder.'/ic_'.$name.'_grey600_'.$dp.'.png', icon_png_blob($details['icon_data'], $size, '757575'));
        $zip->add_file($folder.'/ic_'.$name.'_white_'.$dp.'.png', icon_png_blob($details['icon_data'], $size, 'FFFFFF'));
    }
}

// This simple function makes creating each icon 1 line of code. Huge time-saver.
function icon_png_blob ($data, $size = 24, $color = '000000', $opacity = 1) {
    $foregroundHex = $color == "000000"
        ? '' : 'fill="#'.$color.'" ';
    $foregroundOpacity = $opacity == 1
        ? '' : 'fill-opacity="'.$opacity.'" ';
    $im = new Imagick();
    $im->setBackgroundColor(new ImagickPixel("transparent"));
    $svg = '<?xml version="1.0" encoding="UTF-8"?>';
    $svg .= '<svg width="'.$size.'" height="'.$size.'" viewBox="0 0 24 24">';
    $svg .=     '<path '.$foregroundHex.$foregroundOpacity.'d="'.$data.'" />';
    $svg .= '</svg>';
    $im->readImageBlob($svg);
    $im->setImageFormat("png32");
    return $im->getImageBlob();
}
```

**Comment by dafi** [comment]
Ok thanks, your code is easy to read so I hope to rewrite it using unix scripts. Stay tuned :)

**Comment by jestelle** [comment]
We may eventually release some of our scripts and tooling we used for processing icons, see issue #11, but for the time being, I can suggest two tools we've used:

rsvg-convert
and
PhantomJS

We've used both pretty successfully for rastering PNGs out from SVGs.
