### ISSUE TITLE
Checkmark length

### ISSUE THREAD

**Issue by daveroberts** [google/material-design-icons#621]
It appears that the checkmark icon's width is based on the width of the word "checkmark", and not the width of the single symbol ✔.

This has two impacts:
1. The checkmark leaves a lot of space to the right.  You can work around this bug by setting the width to 1em.
2. Even with the width 1em workaround, if you have a hover effect on the checkmark, the hover style is activated over where the full word "checkmark" would have been, not just over the checkmark.

Both of these impacts are demonstrated in the jsfiddle below.

https://jsfiddle.net/8raex6as/

**Comment by The3Null4Player613310** [comment]
try this as a quick fix.
`<i class="material-icons" style="width: 1em;">check</i>
<span class="tip-content">Lorem ipsum</span>
</span>`

**Comment by daveroberts** [comment]
Thanks, this is a valid workaround.  Also, the word 'done' works appropriately.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
