### ISSUE TITLE
Icon Request: +/- 

### ISSUE THREAD

**Issue by oliver6d** [google/material-design-icons#626]
Either an icon with the plus minus sign (±) or with a slash between the two (+/-) to be used for adding and removing

**Comment by kevingermain** [comment]
I agree ;)

**Comment by yamster9** [comment]
this would be useful!

**Comment by cyberalien** [comment]
Here you go:
![baseline-plus_minus.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/baseline-plus_minus.png) [baseline-plus_minus.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/baseline-plus_minus.svg)
![round-plus_minus.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/round-plus_minus.png) [round-plus_minus.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/round-plus_minus.svg)

![baseline-plus_minus_alt.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/baseline-plus_minus_alt.png) [baseline-plus_minus_alt.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/baseline-plus_minus_alt.svg)
![round-plus_minus_alt.png](https://raw.githubusercontent.com/cyberalien/google-material-design-icons-updated/master/png/black/math/round-plus_minus_alt.png) [round-plus_minus_alt.svg](https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/math/round-plus_minus_alt.svg)

See this comment for explanation: https://github.com/google/material-design-icons/issues/699#issuecomment-491877380

Enjoy :)

**Comment by RoelN** [comment]
Could you please see if the new icons satisfy your need? https://material.io/resources/icons/?search=plus&style=baseline If not, feel free to reopen this issue!
