### ISSUE TITLE
ZIP file release missing many directories, no index.html

### ISSUE THREAD

**Issue by justicegray** [google/material-design-icons#63]
When I download material 1.01 as a zip file the only directory that comes out of the archive is "action", and there is no corresponding index.html either.  Dir structure of the zip has only
\action
LICENSE
README.md

At first I thought it might be something with me, but it seems that other issues (missing SVG folder, etc.) make note of the same problem.

**Comment by danieldev** [comment]
I am facing the same problem. Any solutions yet?

**Comment by justicegray** [comment]
Hey, Daniel,

I simply found a different material icon set - it is *excellent*.  I'm
going to assume given the lack of response here that this project is dead.

http://zavoloklom.github.io/material-design-iconic-font/examples.html

-Justice

**Comment by danieldev** [comment]
Hi, 
thanks for your reply. I found a way to unzip the folder correctly in another issue: use Git Bash: jar xvf material-design-icons-1.0.1.zip :)

**Comment by danieldev** [comment]
Hi,
thanks for your reply. I found a way to unzip the folder correctly in another issue - using Git Bash: jar xvf material-design-icons-1.0.1.zip :)

**Comment by jestelle** [comment]
Check out issue #8 
Lots of discussion around this issue and a few suggested work arounds.
