### ISSUE TITLE
Website does not work correctly on Safari/Firefox

### ISSUE THREAD

**Issue by AlexLardschneider** [google/material-design-icons#639]
Hello,

I noticed that part of the [Website](https://material.io/icons) does not work on Safari. When I select an icon and want to change the icon color on Chrome I am presented by two dots (one white, one black), on Safari however those dots are missing and I get a "Select an item" option, which does nothing on click.

Downloading the icon works correctly on both Safari and Chrome.

**Comment by shyndman** [comment]
Dupe of #552
