### ISSUE TITLE
"unarchive" icon [enhancement]

### ISSUE THREAD

**Issue by caseyjhol** [google/material-design-icons#64]
Any plans to include an "unarchive" icon? Could just be the same as "archive" with the arrow flipped the opposite direction.
![unarchive](https://cloud.githubusercontent.com/assets/2874325/5714606/a6269256-9a88-11e4-9fd7-01cb410bc215.png)

**Comment by grovina** [comment]
+1

**Comment by RoelN** [comment]
<img width="650" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108867928-fef77680-75f5-11eb-9425-dd530d60ecb1.png">

It's here!
