### ISSUE TITLE
ICON Request: zoom_in_map

### ISSUE THREAD

**Issue by puneet97** [google/material-design-icons#643]
A **_zoom_in_map_** icon to complement the already available _zoom_out_map_ icon.
Something similar to the following pair,
![fullscreen](https://user-images.githubusercontent.com/15259105/28105126-d6a6ce90-66fb-11e7-8546-72517772000b.png)  ![fullscreen_exit](https://user-images.githubusercontent.com/15259105/28105134-dab737cc-66fb-11e7-9864-18673cf26711.png)
Source:
- [Fullscreen](https://thenounproject.com/term/full-screen/684346/)
- [Exit Fullscreen](https://thenounproject.com/term/exit-full-screen/684334/)

**Comment by mtb24** [comment]
+1

**Comment by juansinmiedos** [comment]
+2

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
