### ISSUE TITLE
Icon Request: Arrow (move Icon)

### ISSUE THREAD

**Issue by winterdesign** [google/material-design-icons#645]
Is there a "Move"/"Arrow" icon?

I made this (like "Open With" icon, with thinner arrows, or "Zoom Out Map" rotated)
![move arrow 4x](https://user-images.githubusercontent.com/28007441/28135856-15e56400-671e-11e7-8d3f-d2d33186f83b.png)

**Comment by dhuv** [comment]
This is necessary to convey the ability to drag something around. Please add this.

**Comment by alcmacys** [comment]
Has this been fixed yet? Seems odd its not included

**Comment by anjaloots** [comment]
Need this...

**Comment by aspidites** [comment]
@anjaloots, is either open_with or zoom_out_map (rotated 45deg) sufficient?

**Comment by RoelN** [comment]
Thanks for the help, @aspidites! Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by dhuv** [comment]
@RoelN From reading your comment, it is unclear what the solution is. Is there a new icon as suggested by @winterdesign or do we have to rotate a different icon 45 degrees?

**Comment by RoelN** [comment]
I suggest using `open_width`:

![image](https://user-images.githubusercontent.com/4570664/107381335-08111f80-6aef-11eb-8e30-243ec9315841.png)

**Comment by dhuv** [comment]
Thanks @RoelN , I missed that icon when I browsed the list earlier. That definitely works.

I have to admit, I am not if the name makes sense for that icon but there are probably cases I am not considering.
