### ISSUE TITLE
Person_pin icon is square sometimes and round others

### ISSUE THREAD

**Issue by farley911** [google/material-design-icons#646]
**Bug, feature request, or proposal:**

Bug

**What is the expected behavior?**

The icon for "person_pin" should always be the same icon.

**What is the current behavior?**

If I include the person_pin icon using the icon font the icon is round matching what is shown on the website (https://material.io/icons/#ic_person_pin), however when I download the SVG or PNG the icon is squared.

**What are the steps to reproduce?**

View the person_pin icon on https://material.io/icons, download either the SVG or PNG and compare the icon with the font icon and what is displayed on the icons page.

**What is the use-case or motivation for changing an existing behavior?**

Consistent behavior.

**Comment by aderaaij** [comment]
Indeed, would love to have the SVG person pin!

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
