### ISSUE TITLE
icon request: icon to show ranking/score

### ISSUE THREAD

**Issue by m98** [google/material-design-icons#649]
I think the title is clear, I searched but I could not find an icon to show score/ranking.

**Comment by leoshak** [comment]
Is there any icon now???

**Comment by RoelN** [comment]
Could you perhaps add a short description of how this icon would look?

**Comment by m98** [comment]
Yes, of course, the main use case would be for something like the following:
- Leaderboard
- Sport team rankings in the table
- prediction games 

And if I was going to design it, I would go with something like when you win in an Olympic match, and you should stand on 3 different levels based on your rank (depend on Gold, Silver, and bronze) to receive your medal. ([this image](https://ftw.usatoday.com/wp-content/uploads/sites/90/2014/02/usp-olympics_-medal-ceremony-day-one.jpg?resize=2048,1363))

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
