### ISSUE TITLE
Asterisk icon

### ISSUE THREAD

**Issue by menou2u** [google/material-design-icons#653]
There is no icon representing an asterisk.
All that approach to it are 'stars' which are more meant for rating.
I work on a editor project which provides asterisk-bulleted lists. For now I use star icon but it is a bit childish in the context.

**Comment by attila-albert** [comment]
true... would be cool to have it

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons

**Comment by TheCGDF** [comment]
> Icon available at: https://fonts.google.com/icons

![image](https://user-images.githubusercontent.com/17256673/152649798-2bf1b658-157e-4e55-b61f-282c6d67ce20.png)

**Comment by giovanicascaes** [comment]
> Icon available at: https://fonts.google.com/icons

Just letting a record, `emergency` is the icon name
