### ISSUE TITLE
ICON Request: move_folder

### ISSUE THREAD

**Issue by AlbertoFardin** [google/material-design-icons#654]
Please introduce the icon "move to folder" used in google drive
![schermata 2017-07-24 alle 10 20 36](https://user-images.githubusercontent.com/14926886/28514328-e8445cd2-7059-11e7-9456-0501f533db74.png)

**Comment by RoelN** [comment]
This has been added in the meantime \o/

<img width="367" alt="image" src="https://user-images.githubusercontent.com/4570664/107367115-3424a480-6adf-11eb-9ab1-d0f8ab843a70.png">
