### ISSUE TITLE
missing icons: toggle switch on/off

### ISSUE THREAD

**Issue by dante-inferno** [google/material-design-icons#655]
Hi there, I´m really missing the toggle switches like useful described in the guide https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

any chance to get those icons into the material-icons webfont?

Cheers,

Dante

**Comment by shyndman** [comment]
We don't plan on adding switch icons to the font. You may want to take a look at mdc-web's switch component:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch
