### ISSUE TITLE
Bug: Several new icons are invisible

### ISSUE THREAD

**Issue by TangSteven** [google/material-design-icons#656]
https://material.io/icons/#ic_bubble_chart

Not visible in Chrome 60.0.3112.72, Chrome 60.0.3112.78, and Edge 38.14393.1066.0 on Windows 10.

<img width="960" alt="capture" src="https://user-images.githubusercontent.com/18170455/28691369-ecb1b21a-72d9-11e7-890f-fc8cdc19f448.PNG">

**Comment by skoblenick** [comment]
There are several new icons that do not work now in IE or Safari; see the attached

![chrome_materialicons](https://user-images.githubusercontent.com/1390364/28691229-2947dcbc-72ea-11e7-8adc-bdf9f480bac6.png)
<img width="1144" alt="safari_materialicons" src="https://user-images.githubusercontent.com/1390364/28691228-2942f56c-72ea-11e7-9ccf-c3831ef276d4.png">

**Comment by skoblenick** [comment]
Chrome 60.0.3112.78 on Mac OS X works.
![chrome60_mac](https://user-images.githubusercontent.com/1390364/28691716-e6a71704-72eb-11e7-80eb-c150a1c9fc47.png)

**Comment by shyndman** [comment]
Thanks for the report. I'm taking a look.

**Comment by shyndman** [comment]
We tracked it down. A new build should be up in a couple of hours, and we've added checks to make sure this doesn't happen again. Sorry for the inconvenience.
