### ISSUE TITLE
sentiment_dissatisfied is no longer displaying

### ISSUE THREAD

**Issue by joshsanger** [google/material-design-icons#657]
When using the CDN for the icon font and on the [Material Icon site](https://material.io) the "sentiment_dissatisfied" no longer displays

**Comment by shyndman** [comment]
We released a bad build yesterday that has since been fixed. Mind [bypassing your cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) and seeing if it appears then?

**Comment by joshsanger** [comment]
Well now I feel silly :) Works now. Thanks!
