### ISSUE TITLE
Exported webfonts are not the latest ones

### ISSUE THREAD

**Issue by r4in** [google/material-design-icons#659]
The exported webfonts in material-design-icons/iconfont/ isn't the latest one (last export was a year or two) Can anyone export the latest version (3.0.1) ? There's alot of missing icons when I use this one. Thanks!

**Comment by jossef** [comment]
Hey @r4in 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
