### ISSUE TITLE
Icon Request: Slack

### ISSUE THREAD

**Issue by KotlinKoder** [google/material-design-icons#667]
I would love to have an icon for [Slack](https://slack.com/).

**Comment by aress31** [comment]
Any update on this? I need this icon too 🙏

**Comment by jalpadoshi** [comment]
We currently cannot provide 3P product icons/logo in our catalogue.

**Comment by aress31** [comment]
The Slack icon is a must include! It's one of the most used collaboration platform in business. How can you not include it? That baffles me! Forces people to add a second icon library or add unnecessary code for a single icon that should be there out of the box!
