### ISSUE TITLE
Icon Request: Telegram

### ISSUE THREAD

**Issue by KotlinKoder** [google/material-design-icons#668]
I would love to have an icon for [Telegram](https://telegram.org/).

**Comment by mwawrusch** [comment]
Check out the http://www.socicon.com/ project for social icons.

**Comment by SalahAdDin** [comment]
> Check out the http://www.socicon.com/ project for social icons.

Not available anymore.

**Comment by jalpadoshi** [comment]
We currently cannot provide 3P product icons/logo in our catalogue.
