### ISSUE TITLE
Icons won't load in Mac OS X

### ISSUE THREAD

**Issue by coogle** [google/material-design-icons#670]
I am using Sketch to design some interfaces using MDI. Specifically I am trying to modify existing interfaces. I've installed the MDI icons in my Mac OS X folder appropriately however they do not actually load. By that I mean I open it in Font Book and it shows the item but there is nothing when it renders, and when I try to select the font from another application it's no where to be found. Has any experienced this problem?

**Comment by houstontrueblood** [comment]
I'm having the same problem. Have you found any resolution for this? It's super annoying…. I didn't notice this until installing High Sierra.

**Comment by Buffalo6666** [comment]
The same is in Sierra(

**Comment by singleseeker** [comment]
any update?

**Comment by RoelN** [comment]
Please note that the icons will only be rendered when you enter the matching Unicode value (e.g. `&#xe865;` or `book`).

Also, the assets have been updated in the meantime.

I think these two combined will solve your issue :-) If not, feel free to reopen or create a new issue.
