### ISSUE TITLE
Wrong version number in package.json 

### ISSUE THREAD

**Issue by suriyaprashath** [google/material-design-icons#673]
In the package.json file of tag 3.0.1 the version number is not updated

**Comment by suriyaprashath** [comment]
Are you planning to update this or should I close it?

**Comment by RoelN** [comment]
We're gathering all feedback and suggestions regarding updating the npm package in a central issue: https://github.com/google/material-design-icons/issues/1129 Please have a look and see if the package, as published in the way suggested there, would suit your needs.
