### ISSUE TITLE
Request Unlink Icon!

### ISSUE THREAD

**Issue by QuestionPython** [google/material-design-icons#674]
Unlink - http://fontawesome.io/icon/chain-broken/

https://github.com/google/material-design-icons/issues/581

**Comment by questionpython** [comment]
@addyosmani

**Comment by questionpython** [comment]
!!!

**Comment by merfert** [comment]
@QuestionPython there is an link off icon
https://material.io/resources/icons/?search=link&icon=link_off&style=baseline

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
