### ISSUE TITLE
Issue with the materials.io/icons page

### ISSUE THREAD

**Issue by dedayoa** [google/material-design-icons#676]
Hello,
I can't get the materials.io/icons page to display. On inspecting, I see this error just immediately after the page loads.

`Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at XMLHttpRequest.send (catcher.js:208)
    at XMLHttpRequest.send (webcomponents.js?v13:4406)
    at HTMLElement.request (third-party.js:13)
    at HTMLElement.go (third-party.js:14)
    at n.complete (third-party.js:12)`

I'm running Chrome Version 60.0.3112.113

**Comment by dedayoa** [comment]
Page loads OK on Firefox ver. 54.0.1

**Comment by makdeniss** [comment]
same here using latest of chrome

**Comment by kanokgan** [comment]
Me too but on chrome incognito mode is show normally.

**Comment by gabstv** [comment]
same here  
The culprit seems to be the "Request Maker" plugin, at least for me.
![screen shot 2017-10-31 at 6 53 59 pm](https://user-images.githubusercontent.com/1563110/32248464-e81e06f2-be6c-11e7-8057-de63aa740782.png)  
Disabling the plugin makes the page load correctly again.

**Comment by jestelle** [comment]
Sounds like this is an issue with plugin's that do weird things.
