### ISSUE TITLE
Request Category Icon!

### ISSUE THREAD

**Issue by QuestionPython** [google/material-design-icons#677]
Request Category Icon!

**Comment by RemnNiscetic7** [comment]
Category icon needed

**Comment by questionpython** [comment]
!!!!

**Comment by danger89** [comment]
Aha! I'm not the only one!

**Comment by Abdullah0991** [comment]
+3 up.

**Comment by danger89** [comment]
+4 I waited too long already.

**Comment by danger89** [comment]
@marcopashkov  How to set motion into this request?

**Comment by Abdullah0991** [comment]
@danger89 I used `material-design-icons-iconfont` lib which contains all icons.

**Comment by RoelN** [comment]
There is one in the current icon set:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/4570664/107510458-43b9f100-6ba4-11eb-8dfa-99735592dd3e.png">
