### ISSUE TITLE
Icon Request: Temperature

### ISSUE THREAD

**Issue by esutton** [google/material-design-icons#682]
A thermometer icon perhaps?

http://fontawesome.io/icon/thermometer-three-quarters/

![screen shot 2017-09-20 at 4 28 50 pm](https://user-images.githubusercontent.com/6115047/30668572-cde18b0e-9e20-11e7-9b04-21741ad85e73.png)

**Comment by LoganDupont** [comment]
Any update on this?

**Comment by duminos** [comment]
Come on, theese icons are very usefull!

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
