### ISSUE TITLE
Icon Request: about Network

### ISSUE THREAD

**Issue by huajianjiang** [google/material-design-icons#683]
Hello , guys ,  I suggess  to add some material icons about  network , like LAN neighbors icon , view wifi password icon, find wifi icon , wifi ssid chart .......

something like :

lann neighbors:
![ic_menu_network_topology](https://user-images.githubusercontent.com/12984573/30779913-e5141158-a130-11e7-9a08-5973307020e4.png)
find wifi:
![ic_menu_findwifi](https://user-images.githubusercontent.com/12984573/30779921-02c85772-a131-11e7-86d8-32a2d061a596.png)
ssid chart:
![view_time_graph](https://user-images.githubusercontent.com/12984573/30779932-46f40d1a-a131-11e7-91ca-c8db48e8eb37.png)
wifi channel:
![view_channel_graph](https://user-images.githubusercontent.com/12984573/30779937-5ee623ea-a131-11e7-9b08-0874663b2967.png)

PS: Thanks in advance!

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
