### ISSUE TITLE
'keyboard arrow left' and 'keyboard arrow right' do not align

### ISSUE THREAD

**Issue by Toutouwai** [google/material-design-icons#685]
Visible here in zoomed screenshot from official icons preview. Chrome v61.0.3163.100, Windows 8.1.
Same issue is visible in Firefox and IE11.

![2017-09-27_133758](https://user-images.githubusercontent.com/1538852/30890475-b38d260a-a389-11e7-8203-893efdc10799.png)

**Comment by tphinney** [comment]
This has since been fixed!
