### ISSUE TITLE
Icon request: clear filters

### ISSUE THREAD

**Issue by vileppanen** [google/material-design-icons#687]
I'd need an icon for describing an action that would clear or reset all filters the user has set.

I was thinking something like the _filter list_ icon, but with the same overstroke as is used in for example _layers clear_ or _format clear_ icons

**Comment by ranne10** [comment]
Having the same dilemma :D

**Comment by hanktrizz** [comment]
Hi, just wondering what's the status with this request? Many thanks.

**Comment by CollinAlpert** [comment]
I also need this. It would be great to get a status update.

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
