### ISSUE TITLE
[RFE] Add open solid lock icon

### ISSUE THREAD

**Issue by SamWhited** [google/material-design-icons#69]
There are three lock icons:

![lock](http://google.github.io/material-design-icons/action/svg/ic_lock_24px.svg) `lock`, ![lock open](http://google.github.io/material-design-icons/action/svg/ic_lock_open_24px.svg) `lock-open`, and ![lock outline](http://google.github.io/material-design-icons/action/svg/ic_lock_outline_24px.svg) `lock-outline`.

There should also be a `lock solid open` (and maybe it could even be renamed for consistency, though this may cause confusion in existing projects).

**Comment by nbonnec** [comment]
Still missing.

**Comment by jalpadoshi** [comment]
Icon available at: https://fonts.google.com/icons
