### ISSUE TITLE
Error found in thumb icons

### ISSUE THREAD

**Issue by kaifaust** [google/material-design-icons#693]
See attached image

![thumb icon error](https://user-images.githubusercontent.com/3498300/32412698-39d5d09e-c1bd-11e7-9838-2a268c0c52de.png)

**Comment by kaifaust** [comment]
Also, please address this issue from 2016 https://github.com/google/material-design-icons/issues/392

**Comment by as8297** [comment]
Can You please be more specific.
As i didn't find any Error in this 👇
[https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_thumb_up_48px.svg](url)


Give the Exact Detail (Location) where you have found this.

**Comment by as8297** [comment]
Can You please be more specific.
As i didn't find any Error in this 👇

https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_thumb_up_48px.svg

Give the Exact Detail (Location) where you have found this.

**Comment by Templarian** [comment]
@as8297 34000% zoom in Illustrator. 😃 (had to fix it last week in the community pack)

**Comment by jestelle** [comment]
I'll have a look and see if we can get both of these on a queue to get fixed... and pushed out.

**Comment by tphinney** [comment]
In both Material Symbols and Material Icons, this seems to be all good now.
