### ISSUE TITLE
unicode attribute is no unicode attribute in svg-file

### ISSUE THREAD

**Issue by Sukrams** [google/material-design-icons#695]
Hello,

the svg-file for the iconfont hast normal content for the unicode attribute within the <glyph>-tag and no unicode.

Within some systems this can cause some problems.

**Comment by jestelle** [comment]
You mean in iconfont/MaterialIcons-Regular.svg?
Can you be more specific about what systems you're seeing what problem?

Generally we encourage folks to use our icons fonts as served from Google Fonts:
http://google.github.io/material-design-icons/
Then we'll be sure to serve your user a most-compatible font for whatever system they're using.

**Comment by jestelle** [comment]
Feel free to reopen with more information.
