### ISSUE TITLE
Circle outlined icons and Alarms / Timers don't line up

### ISSUE THREAD

**Issue by jamesmfriedman** [google/material-design-icons#70]
Ran into a couple of cases where I needed to use a timer and a circle outline icon next to each other, and they don't play well. IMO I think the circular part should be the same size. Might not be possible with the size constraints, but wondering about it.
![screen shot 2015-01-29 at 11 32 23 am](https://cloud.githubusercontent.com/assets/975256/5963670/79476960-a7ab-11e4-9fd7-d98ad9492fb6.png)

**Comment by jestelle** [comment]
HI James,
I'll talk to our designers about this.
Our icons are generally consistent, but sometimes there are good reasons to reduce the size of a circle... e.g., with the alarm and the 'bells' on the top, with the larger circle, those 'bells' might not fit well.

Either way, we'll have a look at it.

**Comment by jestelle** [comment]
Hi James.
Talked to our designers about this.
These icons are correct and intended to be these sizes.

The reason for different size circles is to better balance the overall visual weight of our icons across the board.

We might consider matching the size of these circles if these two icons were likely to be needed to be used next to each other, but we haven't received a request like that.

Hope that helps.
