### ISSUE TITLE
Icon request:  Archived Folder

### ISSUE THREAD

**Issue by btn-ninja** [google/material-design-icons#702]
Hi,
I would like to request a folder icon to represent deleted or archived items.  Often (always?) in application designs, I need lists/tables to have a link to items which were removed by the user.  

Perhaps something like this (but in your style):
http://icons.iconarchive.com/icons/iconsmind/outline/512/Folder-Trash-icon.png

This is distinctly different from the trashcan icon, which is an action rather than a folder. 
Thanks!

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
