### ISSUE TITLE
Why don't icons go to edge of 24px viewport?

### ISSUE THREAD

**Issue by RhysyG** [google/material-design-icons#704]
Hi there,

Is there any reason why the icons don't go to the edge of the 24px grid?

![image](https://user-images.githubusercontent.com/5491092/33297718-afa3090a-d436-11e7-8c99-306492b9d5ed.png)

![image](https://user-images.githubusercontent.com/5491092/33297685-7d48549c-d436-11e7-9421-43c8eb72ae2e.png)

**Comment by Templarian** [comment]
https://material.io/guidelines/style/icons.html#icons-system-icons

Specifically the section on grid and proportions. It's easier to see when several are lined up in a vertical or horizontal list. Each icon proportionally views correct to the eye. You'll find this proportional grid used across many icon packs.

**Comment by jestelle** [comment]
☝️ 
Templarian answers this well.
It helps with alignment of the visual icon both at design time and development time.
