### ISSUE TITLE
Icon requests: newspaper, blog-post, etc...

### ISSUE THREAD

**Issue by cubetastic33** [google/material-design-icons#707]
Hello, I have a need for some new icons: a newspaper icon, a blog-post icon, and a post-box kind of icon, and also, it would be nice if you had a feature where you could combine icons to create new icons. For example, I want an icon of a person and a document or webpage in it, to say something like "my page". That would be possible even if I could just combine the "person" icon and the "web" icon.

**Comment by pixelyunicorn** [comment]
See also #194 for Newspaper

**Comment by cubetastic33** [comment]
@pixelyunicorn well, it doesn't work if I do `<i class="material-icons">newspaper</i>`.

**Comment by kael** [comment]
+1

Having some icons to distinguish different types of publications would be nice.

Following the [SchemaOrg](https://schema.org/docs/full.html) hierarchy, there could be:
- article
- news article
- tech article
- scholarly article
- report
- blog posting
- API reference

- Specification like RFC, drafts, etc (not in the hierarchy)

But it might not be easy to design easliy meaningful and distinguishable icons.

**Comment by jalpadoshi** [comment]
Icons available on https://fonts.google.com/icons
