### ISSUE TITLE
Rendered icon set needs to be brought up-to-date

### ISSUE THREAD

**Issue by msorens** [google/material-design-icons#709]
The rendered version of the icon set at https://material.io/icons/ is out-of-date; that is, it is only showing a subset of the icons available in the git repo. And it is darn inconvenient to browse the images in the repo, so it would be really, really, really! helpful to have the displayed set match the set in the repo. Thanks!

**Comment by Mancerrss** [comment]
Is it really? How many are in the repo vs in the website? Also does this repo still in development? It looks like dead to me, nobody manage and update it anymore

**Comment by azattaher** [comment]
ok

**Comment by jestelle** [comment]
Hi all,

We're working on some future updates to how we deliver these icons which will address these issues of consistency.  I can't guarantee we'll have those improvements done particularly quickly, but it is something we're working on.

This repo is fairly inactive, but not dead. Stay tuned and expect some updates from us on iconography in the coming months.

Cheers,
Josh

**Comment by tphinney** [comment]
Happily, this has since been addressed—previously I think, but certainly for the newest live site at https://fonts.google.com/icons which shows the current icons (both Material Icons and Material Symbols)
