### ISSUE TITLE
Material Design Icons don't working on firefox anymore

### ISSUE THREAD

**Issue by ErickVal** [google/material-design-icons#713]
Windows 10
Firefox:
![image](https://user-images.githubusercontent.com/14150049/34298131-49318ac2-e703-11e7-83a8-8482561e7830.png)

I try:
Self host (No success)
Use CDN (No success)
Disable hardware acceleration(No success)
Disable UBlocker (like AdBlocker) (No success)

Check Oficial page:
![image](https://user-images.githubusercontent.com/14150049/34298116-39574d9e-e703-11e7-8169-29f991fa0352.png)

**Comment by ThetaSinner** [comment]
I'm seeing this too using the latest Firefox. I'm using npm to fetch the material-design-icons then loading them into a static webpage using the iconfont/material-icons.css method

**Comment by ErickVal** [comment]
I can't figure out a workaround yet but same Firefox on other PC looks normal.

**Comment by shyndman** [comment]
@ErickVal, does https://fonts.google.com load its fonts properly?

**Comment by ErickVal** [comment]
Thanks for reply.
Working now.

Not sure if was that but I done that:
(Make a backup)

Enter in url (using firefox PC)

- about:support
- Press Refresh Firefox.

**Comment by audeoudh** [comment]
Also try to check the box at "about:preferences" → Fonts & colors → Advanced → “Allow web pages to use their own fonts instead of the ones chosen above”.

**Comment by craig-dae** [comment]
This problem is happening for me right now. 

I've tried about:support->refresh firefox, and "Allow web pages to use their own fonts instead of the ones chosen above" is checked.

**Comment by daveschwerstein** [comment]
@craig-dae, same here.

**Comment by cyberalien** [comment]
Can you try this: https://material-icons.github.io/material-icons-font/samples/test.html

Its same font, but built without ligatures, using different build process

**Comment by cyberalien** [comment]
Changing to http is not a solution. Modern browsers won't load insecure content when visiting website via https. Your website should be accessible via https

**Comment by audeoudh** [comment]
> Can you try this: https://material-icons.github.io/material-icons-font/samples/test.html
> 
> Its same font, but built without ligatures, using different build process

@cyberalien It works for me.  I have five columns of correctly displayed icons, plus one column of icon name.  My browser effectively loaded `MaterialIcons*.woff2` files from material-icons.github.io website (.woff2, .css and .html are from the same website).

However, when comparing to https://material.io/resources/icons/?style=baseline, this page uses fonts from fonts.gstatic.com, so from a third party website.  No attempt is made there by Firefox to download the font files.

Not sure how it can explain that.

**Comment by vitaly-zdanevich** [comment]
The same for me, Firefox 68.5.0est, Gentoo.

![image](https://user-images.githubusercontent.com/3514015/75505564-95498a00-59ec-11ea-9840-ec710f9288de.png)

Looks like Google against Mozilla.

**Comment by vitaly-zdanevich** [comment]
Hm ok now after page refresh...

**Comment by cstodor** [comment]
I had the same issue when using `<link rel="preload" as="style" onload="this.rel = 'stylesheet'"
    href="https://fonts.googleapis.com/icon?family=Material+Icons">`. Changing it back to `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">` fixed the bug on Firefox

**Comment by EnockOMONDI** [comment]
Try and link your sylesheet...add this line of code. 
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
