### ISSUE TITLE
Expand icon

### ISSUE THREAD

**Issue by Hongbo-Miao** [google/material-design-icons#715]
Right now there is one
![image](https://user-images.githubusercontent.com/3375461/34369641-606df4ce-ea72-11e7-9f9a-a14cdd1c87be.png)

But it would be great to have an Expand icon like the one in Gmail. Something like 
![image](https://user-images.githubusercontent.com/3375461/34369657-79d3e644-ea72-11e7-9d84-f18d556c5960.png)
![image](https://user-images.githubusercontent.com/3375461/34369562-7d96a29a-ea71-11e7-96a0-49c37b3919c2.png)

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
