### ISSUE TITLE
Material Icons - Vertical Align Doesn't work well alongside text in firefox

### ISSUE THREAD

**Issue by EliShaXu** [google/material-design-icons#716]
firefox：
![_20180102172455](https://user-images.githubusercontent.com/13866430/34479606-b9da567c-efe2-11e7-8efc-a5bf1d2dcdac.png)
chrome
![_20180102173342](https://user-images.githubusercontent.com/13866430/34479675-1ce9ca72-efe3-11e7-8c9f-b0d413cb7887.png)

**Comment by jestelle** [comment]
Have a codebin or jsbin or something where you can show us the problem?

You might look at http://google.github.io/material-design-icons/#icon-font-for-the-web

Particularly all the way at the bottom, where the alignment of those icons with the text next to them looks pretty good to me, both in Chrome and Firefox.

**Comment by jestelle** [comment]
Feel free to re-open if you still have this question, or can point us to a more specific example to help with.

**Comment by wachunga** [comment]
Right, but that page is "cheating" by using flexbox:

![image](https://user-images.githubusercontent.com/438545/48656352-30297b00-e9d9-11e8-97ad-df2de04af134.png)

Turn that off and the default alignment is quite poor. The font should have sensible defaults IMO.
