### ISSUE TITLE
balance icon removed?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [google/material-design-icons#717]
Where is the balance icon? I looked for it over 10 minutes and found nothing at https://material.io/icons/

The icon I need is similiar to this thing https://us.123rf.com/450wm/milo827/milo8271406/milo827140600040/29385071-balan%C3%A7a-tempo-e-dinheiro.jpg?ver=6

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
