### ISSUE TITLE
Icon Request/Missing: YouTube playback speed icon

### ISSUE THREAD

**Issue by bernaferrari** [google/material-design-icons#718]
I would love to see the playback speed icon on this library.

![youtube-video-speed](https://user-images.githubusercontent.com/351125/34949012-f5fac282-f9f5-11e7-90a0-ce0c46d4f2af.jpg)

It is called internally as "quantum_ic_slow_motion_video_grey600_24".
![quantum_ic_slow_motion_video_grey600_24](https://user-images.githubusercontent.com/351125/34949538-871cdc2c-f9f7-11e7-86bb-69253633ebe1.png)

**Comment by Baneeishaque** [comment]
+1

**Comment by bernaferrari** [comment]
Included on the new material.io/icons.
