### ISSUE TITLE
multiple MaterialDropDown do not work when hover=false

### ISSUE THREAD

**Issue by mtmmtm9** [google/material-design-icons#719]
Starting with the maven archetype i changed the ui-file.
This example works only if changing the line with hej2 to hover=true.

<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:g='urn:import:com.google.gwt.user.client.ui'
             xmlns:me='urn:import:gwt.material.design.addins.client.menubar'
             xmlns:m="urn:import:gwt.material.design.client.ui">
    <ui:with field="res" type="mp.client.resources.AppResources"/>
    <m:MaterialPanel>

        <me:MaterialMenuBar m:id="sidenav" width="280">
            <m:MaterialLink text="Link 1" iconType="POLYMER"/>
            <m:MaterialLink text="Link 2" iconType="POLYMER" activates="hej">
                <m:MaterialDropDown activator="hej" hover="false" belowOrigin="true">
                    <m:MaterialLink text="test123" iconType="POLYMER"/>
                    <m:MaterialLink text="sune" iconType="PLAY_ARROW" iconPosition="RIGHT"  activates="hej2">
                        <m:MaterialDropDown activator="hej2" hover="false" belowOrigin="true">
                            <m:MaterialLink text="testing link1" iconType="POLYMER"/>
                            <m:MaterialLink text="hejsan" iconType="PLAY_ARROW" iconPosition="RIGHT" >
                            </m:MaterialLink>
                            <m:MaterialLink text="testing link2" iconType="POLYMER"/>
                        </m:MaterialDropDown>
                    </m:MaterialLink>
                    <m:MaterialLink text="test234" iconType="POLYMER"/>
                </m:MaterialDropDown>
            </m:MaterialLink>
            <m:MaterialLink text="Link 3" iconType="POLYMER"/>
        </me:MaterialMenuBar>

    </m:MaterialPanel>
</ui:UiBinder>

**Comment by jestelle** [comment]
I think you may have filed this in the wrong github project.

Are you using Polymer?  Or some other framework?  Feel free to open with more information and we can help redirect you.

**Comment by jestelle** [comment]
Which guide?

Are you sure you aren't running into a bug with this project:
https://github.com/GwtMaterialDesign/gwt-material
?
