### ISSUE TITLE
A Pregnancy icon

### ISSUE THREAD

**Issue by royale1223** [google/material-design-icons#72]
An icon to indicate pregnancy would be nice.

**Comment by eugeneisrambo** [comment]
@royale1223 lol why?

**Comment by royale1223** [comment]
Just search for pregnancy apps. You'll understand. There's an app for
everything and pregnancy is the least weird of them.

**Comment by eugeneisrambo** [comment]
@royale1223  You are right about the weird part but I believe, and could be wrong, the icons are  action icons which are used in most applications.  Possibly to create consistency across all applications.  I don't see a pregnancy icon as an everyday action but I did find a pregnancy icon that you might like.  The link below is a Human Pictos icons.  If you look at the preview sheet it is located at column 3, row 8.  
![shape 73](https://cloud.githubusercontent.com/assets/7454787/6848404/648629de-d3a3-11e4-9837-f07a17e10f68.png)

http://www.noupe.com/essentials/exclusive-freebie-on-noupe-human-pictos-with-500-icons-of-everyday-people-80392.html  

I only see one size in the png file so you could go to link below to generate the icon to all different screen sizes.  
http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=none

I found it on Pinterest.  I am sure there are a ton of other icons out there that might be what you are looking for.

**Comment by jestelle** [comment]
Hi all – we'll track icon requests like this, but I can't guarantee we'll get to them soon (or some ever) ;-)
Best, Josh

**Comment by shyndman** [comment]
https://www.google.com/design/icons/#ic_pregnant_woman

**Comment by kmillerdevx3** [comment]
@shyndman This currently shows under the "Actions" category, which, while action is required to enter this state, is probably not the intended message.
