### ISSUE TITLE
share varient vs share icon request !

### ISSUE THREAD

**Issue by LOG-TAG** [google/material-design-icons#720]
https://materialdesignicons.com/ if we search in this for share we will get share button like Google Youtube share icon !  
![share 1](https://user-images.githubusercontent.com/1190344/35668353-27a9d516-0757-11e8-9802-076bbb4bcf12.png)

**Comment by BaileyMillerSSI** [comment]
I am looking for this icon and the current share I am not a fan of.

**Comment by Jessman5** [comment]
+1 for this one.
This icon is used by google themselves but as svg icon not as part of the font.
Please put this icon as variant of the actual share icon into the icon font.

**Comment by cyberalien** [comment]
But it is available: https://github.com/google/material-design-icons/blob/master/content/svg/production/ic_reply_24px.svg

Flip it vertically using css transformation `style="transform: scaleX(-1)"` and you have share icon.

**Comment by Jessman5** [comment]
No it is not available in the font. That's why this issue was opened. If you want to use the font, you don't want to use extra svg icons.

**Comment by cyberalien** [comment]
But you can use font with css.

**Comment by Jessman5** [comment]
It would be a cleaner solution to simply have a correct and nice looking share icon without manually "hacking" the font.

**Comment by jalpadoshi** [comment]
Icon is available on fonts.google.com/icons
