### ISSUE TITLE
cssRules error in Chrome update v64

### ISSUE THREAD

**Issue by zekhrom** [google/material-design-icons#721]
This error is happening since I update Google Chrome version to 64:

![image](https://user-images.githubusercontent.com/26353290/35863596-2bc76d24-0b1d-11e8-9f23-6f74914f656b.png)

any ideas why is this? any help would be grateful

**Comment by jayeshvg** [comment]
We are facing same issue from past few days. We use cssRules to copy page styles to print window and it broke all of a sudden, only in Chrome.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
