### ISSUE TITLE
Inconsitent naming for `play arrow`, `stop` and `pause`

### ISSUE THREAD

**Issue by adamreisnz** [google/material-design-icons#723]
Compare:
![image](https://user-images.githubusercontent.com/490562/36142297-8736942e-110c-11e8-963f-f708ff83a297.png)
![image](https://user-images.githubusercontent.com/490562/36142307-8eb8fb24-110c-11e8-97e4-1079ced2af4b.png)

And:
![image](https://user-images.githubusercontent.com/490562/36142312-93f2293a-110c-11e8-8cd8-6c7672149e2e.png)

Why does the latter need the "arrow" suffix?
The former are not called "stop square" or "pause rectangles", so why do we need to clarify "play" as  "play arrow"?

I would recommend for consistent to drop the "arrow" suffix.

**Comment by RoelN** [comment]
This is likely to differentiate between the multiple play icons (e.g. `play_arrow`, `play_circle`). If you still feel it's necessary to add an alias, please feel free to reopen this issue or create a new one!
