### ISSUE TITLE
Fixing the icon search filter on the website

### ISSUE THREAD

**Issue by adamreisnz** [google/material-design-icons#725]
Could the search algorithm on the [website](https://material.io/icons/) be updated, so that it doesn't just match icons on their literal name, which are often confusing and [don't reflect what the icon represents](https://github.com/google/material-design-icons/issues/724), but by additional meta data or icon description as well? 

It'd be nice for example if I search for a "clock" icon that one or all of the icons that actually represent a clock would show up, e.g. "query builder", "access time", "schedule" and "watch later".

![image](https://user-images.githubusercontent.com/490562/36142804-03ee62b6-110e-11e8-8653-78d26430bd7e.png)

Instead, we get a blank screen:

![image](https://user-images.githubusercontent.com/490562/36142646-8db7d46a-110d-11e8-9c66-9a7f7477095e.png)

There's many more examples, for example searching for "bag" yields nothing, but there is a shopping bag icon called "local mall". 

If meta data could be added to the icons on the site, the search algorithm could be improved a lot.

**Comment by RoelN** [comment]
Searching for `clock` now returns a bunch of 'em:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/4570664/107361996-7bf3fd80-6ad8-11eb-8f85-3d7fb948dc19.png">
