### ISSUE TITLE
self-hosted iconfont causes dublicate style 

### ISSUE THREAD

**Issue by cagcak** [google/material-design-icons#727]
Seperating font files from style code caused duplicate style. Even if modifying font files sources as absolute path entries didn't solve the issue. So fonts work, but I am getting 404 errors for font files. Here is what I see in the dev console:
```
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'liga';
}
```
 
  `.material-icons {`
  ~~`font-family: 'Material Icons'`~~;
  ~~`font-weight: normal`~~;
  ~~`font-style: normal`~~;
  ~~`font-size: 24px`~~;
  ~~`display: inline-block`~~;
  ~~`line-height: 1`~~;
  ~~`text-transform: none`~~;
  ~~`letter-spacing: normal`~~;
  ~~`word-wrap: normal`~~;
  ~~`white-space: nowrap`~~;
  ~~`direction: ltr`~~;
  ~~`-webkit-font-smoothing: antialiased`~~;
  ~~`text-rendering: optimizeLegibility`~~;
  ~~`-moz-osx-font-smoothing: grayscale`~~;
  ~~`font-feature-settings: 'liga'`~~;
`}`

here is the font-face:
```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(http://localhost:3000/assets/webfonts/MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url(http://localhost:3000/assets/webfonts/MaterialIcons-Regular.woff2) format('woff2'),
    url(http://localhost:3000/assets/webfonts/MaterialIcons-Regular.woff) format('woff'),
    url(http://localhost:3000/assets/webfonts/MaterialIcons-Regular.ttf) format('truetype');
}
```
Font location : `localhost:3000/assets/webfonts/`
Style location: `localhost:3000/assets/style/style.css`

I use gulp task manager, but also tried without it. Is there a change some embedded style code exist in font files?

**Comment by jossef** [comment]
Hey @cagcak 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
@cagcak It looks like your CSS was applied twice. Did you find out what part of your code was loading the CSS twice? Feel free to reopen this issue is you think this is an issue.
