### ISSUE TITLE
INR sign

### ISSUE THREAD

**Issue by Pulkit-Sharma** [google/material-design-icons#728]
I see already many requests are made. A country with 1.3 billion population do not have a material INR sign!!!
Developers please release it.

**Comment by planetabhi** [comment]
@jestelle Are you peeps open for contributions? or any way to pitch ideas for highly requested icons?

**Comment by deviousasti** [comment]
They don't have a yen or yuan sign either.
Why not just use unicode?

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
