### ISSUE TITLE
Is there a JSON of all the icons

### ISSUE THREAD

**Issue by JoshMerlino** [google/material-design-icons#729]
Im looking for a large json file of all the icons.

**Comment by JoshMerlino** [comment]
Exactly what I was looking for. Thanks.

**Comment by thbwd** [comment]
For future reference: https://fonts.google.com/metadata/icons

**Comment by henadzIvachkin** [comment]
> For future reference: https://fonts.google.com/metadata/icons

Is it possible to get Material **Symbols** JSON list? Seems this endpoint responses JSON with Material **Icons** and these lists might be different.

**Comment by phayes** [comment]
You can find an up-to-date list here: https://github.com/Templarian/MaterialDesign/blob/master/meta.json

**Comment by ivanabovin** [comment]
[(https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true)](https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true)

**Comment by digistate** [comment]
> material_symbols - https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true

This list is included both Material Icons and Material Symbols.
Is there a way to specify a parameter that allows me to extract only the Material Symbols font?
