### ISSUE TITLE
A terminal icon

### ISSUE THREAD

**Issue by royale1223** [google/material-design-icons#73]
An icon to indicate a terminal would be nice.

**Comment by depyronick** [comment]
i was sure that there were a terminal icon, damn mandela.

**Comment by bonellia** [comment]
I am looking for alternative icon suggestions.  
Closest I can find is the "code" icon:  
![image](https://user-images.githubusercontent.com/16254153/141494592-abd4d6a1-548c-4bba-b421-5c252e403ee1.png)

**Comment by jalpadoshi** [comment]
Icon available on https://fonts.google.com/icons (terminal emulator)
