### ISSUE TITLE
Iconsistent 24/48px icon sets

### ISSUE THREAD

**Issue by mindplay-dk** [google/material-design-icons#731]
The 24px and 48px svg icon sets don't contain the same set of icons.

When I switched from the 24px to the 48px icon set, an entry in my commit log revealed that all of the following icons from the 24px set are missing in the 48px set:

```
"camera-enhance",
"eject",
"gif",
"help-outline",
"offline-pin",
"reorder",
"youtube-searched-for",
"zoom-in",
"zoom-out"
"hd",
"sort-by-alpha",
"phonelink-erase",
"phonelink-lock",
"phonelink-ring",
"phonelink-setup",
"font-download",
"money-off",
"device-hub",
"collections-bookmark",
"photo-size-select-actual",
"photo-size-select-large",
"photo-size-select-small",
"vignette",
"indeterminate-check-box",
"star",
"star-border",
```

I can't tell if it's deliberate or not? Maybe some icons only work well at small sizes??

I figured I'd report it, in case it's an error.

**Comment by RoelN** [comment]
Thanks for reporting! Some of these have been fixed in the meantime, others are being tracked here: https://github.com/google/material-design-icons/issues/1082 Closing this issue in favor of the 1082!
