### ISSUE TITLE
Font URLs in CSS are missing quotes and break compilation

### ISSUE THREAD

**Issue by Dunos** [google/material-design-icons#733]
When using the package with the latest Angular CLI (1.7.1), the compilation stops while trying to load the material-icons.css file because the src url params are not using quotes:

`@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype');
}
`

Changing it manually to the following, fixes the problem:

`@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url('MaterialIcons-Regular.eot'); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url('MaterialIcons-Regular.woff2') format('woff2'),
       url('MaterialIcons-Regular.woff') format('woff'),
       url('MaterialIcons-Regular.ttf') format('truetype');
}`

**Comment by edujjalvarez** [comment]
It happens exactly the same

**Comment by Dunos** [comment]
With the release of Angular CLI 1.7.2 this has been fixed.
