### ISSUE TITLE
quote missing in /iconfont/material-icons.css

### ISSUE THREAD

**Issue by codedumper** [google/material-design-icons#738]
Error occurs when building Angular (5.2.6) code with  material-design-icons (3.0.1):
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/material-design-icons/iconfont/material-icons.css
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/cdurieux/Dev/Obkio/Obkio/node_modules/material-design-icons/iconfont/material-icons.css:9:12: Can't resolve 'MaterialIcons-Regular.woff)%20format(%27woff%27' in '/Users/cdurieux/Dev/Obkio/Obkio/node_modules/material-design-icons/iconfont'

   7 |        local('MaterialIcons-Regular'),
   8 |        url(MaterialIcons-Regular.woff2) format('woff2'),
>  9 |        url(MaterialIcons-Regular.woff) format('woff'),
     |            ^
  10 |        url(MaterialIcons-Regular.ttf) format('truetype');
  11 | }
```
I solved it by adding single quote : 
```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url('MaterialIcons-Regular.eot'); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url('MaterialIcons-Regular.woff2') format('woff2'),
       url('MaterialIcons-Regular.woff') format('woff'),
       url('MaterialIcons-Regular.ttf') format('truetype');
}
```
I'm not sure that's the correct way.

**Comment by shyndman** [comment]
Looks like the post-css parser has a bug — quotes are not required in CSS urls: https://www.w3.org/TR/CSS1/#url

That said, we can update it on our end. Mind sending a PR?

**Comment by codedumper** [comment]
#740 
I just sign the CLA, waiting for nocla flag update.

**Comment by codedumper** [comment]
PR #736

**Comment by jossef** [comment]
Hey @codedumper 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
Please see linked PR:

> This file got removed in the restructure. Thanks for the PR though, and apologies for the delay!
