### ISSUE TITLE
Bower warning

### ISSUE THREAD

**Issue by volodchenkov** [google/material-design-icons#74]
Hello. While installing this package via bower I have this warning:
`invalid-meta material-design-icons is missing "main" entry in bower.json`
`invalid-meta material-design-icons is missing "ignore" entry in bower.json`
`resolved git://github.com/google/material-design-icons.git#1.0.1`

**Comment by holmesal** [comment]
Adding a `main` property would make make life easier for people (like me :smile:)  that use gulp/grunt wiredep to automatically inject project dependencies to `index.html`. You could set this up for css by adding

```json
"main": "path-to-css"
```

or if you want to have both pulled in, you could do:

```json
"main": [
  "path-to-css",
  "path-to-svg"
]
```

**Comment by ripper2hl** [comment]
:+1: fix this please !!  , and not use min css D:

**Comment by moisessalgado** [comment]
Im getting this error when I try install using bower (bower install material-design-icons):

> error: unable to create file device/ios/ic_signal_cellular_connected_no_internet_4_bar_white_48pt.imageset/ic_signal_cellular_connected_no_internet_4_bar_white_48pt_3x.png (Filename too long)
> Checking out files: 100% (89817/89817), done.% (67664/89817)   
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'

**Comment by ahmed-sherien** [comment]
any fixes for this soon ? I got same error as @moisessalgado

**Comment by srend42** [comment]
If experiencing "Filename too long" on Windows: this is actually a Git issue (@ahmed-sherien; @moisessalgado). See: http://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows (I had to edit my .gitconfig file in C:\Users\[username]\.gitconfig, other options didn't work for me).

**Comment by RoelN** [comment]
Bower is not used anymore, closing this issue. Hope y'all got it worked out in the meantime!
