### ISSUE TITLE
Is it possible to make a new release on npm

### ISSUE THREAD

**Issue by LPCmedia** [google/material-design-icons#743]
Are you guys still making releases on npm registry ?

**Comment by thw0rted** [comment]
More activity in #786, I'm wondering the same thing

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
