### ISSUE TITLE
Icon Request: Lock Reset

### ISSUE THREAD

**Issue by steventango** [google/material-design-icons#744]
According to this website, this is a Google icon, however it's not yet been added to this library. Thanks.

https://materialdesignicons.com/icon/lock-reset

![lock-reset](https://user-images.githubusercontent.com/18170455/36930645-ee33f276-1e62-11e8-8811-4a03c33514ec.png)

**Comment by eleumas** [comment]
+1

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
