### ISSUE TITLE
Icon request: Signin Signout

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [google/material-design-icons#745]
I saw these a while ago but now theyre just not in? Why cant we have sign-in sign-out icons, that seems so common lol wht happened

**Comment by eleumas** [comment]
Hi! Search the icon here: https://materialdesignicons.com/ with `login` or `logout`.

**Comment by diego-lipinski-de-castro** [comment]
Is it google's default new material icons or it's a new thing created by the community?

**Comment by eleumas** [comment]
Oh sorry! I have wrong. I thought be here: https://github.com/Templarian/MaterialDesign/issues. So, https://materialdesignicons.com is a valid project from community.

**Comment by RoelN** [comment]
`login` and `logout` are both part of the icon set now.
