### ISSUE TITLE
Alternative icon font that allows for fallbacks to other fonts

### ISSUE THREAD

**Issue by CBenni** [google/material-design-icons#746]
From what I understand, the material icons font blanks out all other characters. In my specific case, this is not necessarily the behavior I want - If an icon (or rather, a ligature) is not found, I want the browser to fall back to another font.

Is there some way to set that up with the current font, modify it or somehow else achieve the desired result?

**Comment by victor-geere** [comment]
If you want to fall back to another font it could be done by specifying multiple font-family items and it would work just like a normal font. It would be nice to be able to fall back to an image though e.g. where the network policy blocks font downloads in the browser.

**Comment by RoelN** [comment]
Specifying a second (fallback) font is indeed what'd fix this here.
