### ISSUE TITLE
keyboard hijacked in firefox

### ISSUE THREAD

**Issue by avdd** [google/material-design-icons#747]
When using firefox in the icon library page at https://material.io/icons/ my pageup/pagedown/arrows keys don't scroll the page as they normally would.  It seems that the search box hijacks all keyboard input in firefox.  Not nice.

Quoting https://material.io/guidelines/usability/accessibility.html#accessibility-implementation

> Keyboard/mouse interfaces should have every task and all hover information accessible by keyboard-only

Hypocrisy!  :grin:

Firefox latest.  Ubuntu 14LTS.

**Comment by RoelN** [comment]
They do if the scrollable area is in focus! So indeed, if you have focused the search-area, PGUP/PGDOWN will try to scroll there... which isn't possible if there isn't overflowing content :-)

I hope this issue is solved for you, if not, feel free to reopen!
