### ISSUE TITLE
Icon request: eggs

### ISSUE THREAD

**Issue by samuelesantoni** [google/material-design-icons#749]
Hi! I would like have the eggs something icon like this:
![egg03](https://user-images.githubusercontent.com/19838074/37769983-2adf62d0-2dd3-11e8-806b-1b38ebe6a07e.png)
![egg02](https://user-images.githubusercontent.com/19838074/37769984-2afdccde-2dd3-11e8-9536-1b8892d55a1a.png)
![egg01](https://user-images.githubusercontent.com/19838074/37769985-2b16d936-2dd3-11e8-9e66-2dcdcfb9f789.png)
Thanks!

**Comment by RoelN** [comment]
Also see https://github.com/google/material-design-icons/issues/1000

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
