### ISSUE TITLE
MD icons not working in IE11

### ISSUE THREAD

**Issue by Franckou31** [google/material-design-icons#752]
Hello,
I'm using MaterialDesign icons on my application, however, it isn't working on my IE 11 (11.0.9600.18952).
I have done several tests, it works on some laptop wih same version of IE, but doesn't works on another laptop. The same thing for my customers : some of my customers have the same problem with IE11, for other, it works.

Following instruction in issue https://github.com/google/material-design-icons/issues/536, I take a look at http://codepen.io/shyndman/pen/aJpygO in IE11 and I have the same problem: I cannot see the icons. I see the string "bug_report android goat build pregnant_woman shopping_cart".

Please, can you help me understand the problem ?

**Comment by mkmllr** [comment]
Removing the `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` tag helped in my case.  There's more info about it on Microsoft's documentation page: [specifying legacy document modes](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/jj676915(v%3dvs.85)).

**Comment by tribridge-jonathanmbeck** [comment]
I found a similar issue where the Chrome/Mozilla/Edge versions were aligned properly, but in IE 11 I had to remove a `font-size:` CSS that was being applied to the `<i>`

**Comment by eguardiola** [comment]
I'm having the same issue. If all clear all cache and cookies the first time i enter the icons are displayed but after a page reload the icons are gone. :-(

**Comment by jossef** [comment]
Hey @eguardiola @tribridge-jonathanmbeck @mkmllr @Franckou31 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by am-awais** [comment]
any update??
only material icons outlined not working in IE 11, on other browsers its working fine==== help please
`<i class="material-icons-outlined">note_add</i> `
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">`

**Comment by severinkehding** [comment]
Maybe my comment on a differend Issue will solve that problem -> https://github.com/google/material-design-icons/issues/611#issuecomment-510035548

**Comment by coderDem** [comment]
> Maybe my comment on a differend Issue will solve that problem -> [#611 (comment)](https://github.com/google/material-design-icons/issues/611#issuecomment-510035548)

This is not very helpful. My client have an global policy in the IE browser. This seems only an local solution.

**Comment by ThanosAlmighty** [comment]
Okay, it's been over a year and I'm running into the same issue. Can we please get some actual support from the team?

**Comment by bethtorres** [comment]
I was able to fix my problem by overwriting the 'display: inline-block' and changing it to 'display: inline' in the .material-icons {} styles.

**Comment by jtg-pics** [comment]
> I'm having the same issue. If i clear all cache and cookies the first time i enter the icons are displayed but after a page reload the icons are gone. :-(

Having the exact same issue.

**Comment by tphinney** [comment]
This is unfortunate, but seeing as it was not resolved in previous years,  with IE 11 becoming completely unsupported in six weeks (June 15, 2022), I suspect it is too late to get any more attention on it.
