### ISSUE TITLE
Download .tff .woff

### ISSUE THREAD

**Issue by CharlieMcFly** [google/material-design-icons#756]
TTF & .woff file seems corrupted [See here](https://imgur.com/a/td7HtEO)

When build with angular-cli, it appears wrong whereas with Gstatic cdn url it works.

**Comment by jonbodart** [comment]
Same issue here. 
When I am downloading all the MaterialIcon fonts files from the github on my server and refering to them in my font-face url, the font does not load but when using the one provided by gstatic (https://fonts.gstatic.com/s/materialicons/v36/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2), it works fine.

**Comment by dragonfax** [comment]
My mac reports these as bad, as well.

**Comment by jossef** [comment]
Hey @CharlieMcFly @jonbodart 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

Please find the most up-to-date otf/ttf files here: https://github.com/google/material-design-icons/tree/master/font
