### ISSUE TITLE
Bitcoin icon

### ISSUE THREAD

**Issue by dt1973** [google/material-design-icons#76]

**Comment by r3wt** [comment]
🙏

**Comment by schnogz** [comment]
The BTC Unicode char (U+20BF) was accepted in November 2015. We need this! 😜

**Comment by irontiga** [comment]
Plleeeeaaasssseeeeee

**Comment by OkanEmeni** [comment]
A bitcoin icon would be really usefull for our Currency application which has a cryptocurrency page.

**Comment by kebbbnnn** [comment]
any update about this request?

**Comment by orinu** [comment]
+1

**Comment by 021-projects** [comment]
.+1

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
