### ISSUE TITLE
Some icons renders with extra space in front of them

### ISSUE THREAD

**Issue by lobo-tuerto** [google/material-design-icons#762]
### Steps to reproduce
```html
<span style="border: 1px solid red"><v-icon color="success">user_account_box</v-icon></span>
<span style="border: 1px solid red"><v-icon color="success">user_account_box</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">create_new_folder</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">person</v-icon>some text</span>
<span style="border: 1px solid red"><v-icon color="success">nonsense</v-icon>some text</span>
```

### Reproduction Link
[https://codepen.io/lobo-tuerto/pen/aGLrKz](https://codepen.io/lobo-tuerto/pen/aGLrKz)

![screenshot-2018-05-06](https://user-images.githubusercontent.com/5730/39677720-538162ac-5145-11e8-92bb-69ab2eb6ad3b.png)

Guys from Vuetify say there is nothing they can do, so probably this is the right place to report this problem: https://github.com/vuetifyjs/vuetify/issues/3997

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
