### ISSUE TITLE
HTML preview for IE9 or below doesn't work anymore

### ISSUE THREAD

**Issue by thomas-keck** [google/material-design-icons#764]
Hello,

I noticed the preview for IE9 or below doesn't work anymore on https://material.io/tools/icons/?icon=accessible&style=baseline, an example :
![capture d ecran 2018-05-09 a 13 16 19](https://user-images.githubusercontent.com/1893343/39812030-4678085c-538b-11e8-96dc-5d7e709d1f18.jpg)

**Comment by andreszs** [comment]
**Yes, this is part of Google's policy to render all Android 4.x and the IE9 browser obsolete as fast as possible**. However, you can still get the code points [**here**](https://nofile.io/f/h5aZX7M7equ/codepoints.txt). Uploaded to external server before they are deprecated / deleted here and lost forever.

Example usage:
`<i class="material-icons">&#xE8E8;</i>`

If someone saved the old Material Icons page, kindly upload it to a file hosting server. Now it takes twice the time to get the icons' HTML tag.

**Comment by thomas-keck** [comment]
Thanks for your feedback @andreszs ! So then I'll drop IE9 browser support in my projects.
