### ISSUE TITLE
Release table_chart

### ISSUE THREAD

**Issue by oliviertassinari** [google/material-design-icons#765]
I couldn't find the *table_chart* icon on this repository, but it's demonstrated [in your website](https://material.io/tools/icons/?search=table&icon=table_chart&style=outline). Am I looking at the wrong place? Thanks

![capture d ecran 2018-05-09 a 14 57 55](https://user-images.githubusercontent.com/3165635/39815756-64c1aea4-5399-11e8-9d08-fb6bfc0cac0e.png)

![capture d ecran 2018-05-09 a 14 58 47](https://user-images.githubusercontent.com/3165635/39815803-8006faca-5399-11e8-8629-70b3eab97267.png)

*First raised in https://github.com/mui-org/material-ui/issues/11290*

**Comment by libjared** [comment]
_meeting_room_ and _no_meeting_room_ are in the same boat. Thanks.

**Comment by PMudra** [comment]
Same thing for _link_off_ (?)

**Comment by oliviertassinari** [comment]
@thw0rted 786 > 765

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
