### ISSUE TITLE
Did you remove the code form from each icon?

### ISSUE THREAD

**Issue by marcocoelho** [google/material-design-icons#766]
Was the site updated and why did they remove the code form from each icon?
I used a lot of the codes for colcor in: after e: before in the content: \

**Comment by andreszs** [comment]
I almost cried when I noticed they removed the HTML codepoints for each icon, rendering them useless on older browsers like Android 4.x. Luckily, [here are the codepoints](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints), **now it's twice the work** to find the icon HTML code. Thanks Google for finding yet another way to waste developer's time.

**Save the page now in your hard disk before it is deprecated / deleted.**

**Comment by Weegle99** [comment]
But a lot of icon present on the material.io site are not present in the font apparently no ? Or did I miss something ?

**Comment by ChrisProlls** [comment]
@sgehrman same here ! 
Have you find any solution ?

**Comment by Weegle99** [comment]
Unfortunately no... I reverted to font awesome

**Comment by shabib3** [comment]
I created this for who ever needs - https://github.com/google/material-design-icons/issues/813#issuecomment-401601344

**Comment by RoelN** [comment]
The codepoints can now also be found in the `.codepoints` files here: https://github.com/google/material-design-icons/tree/master/font
