### ISSUE TITLE
New Material Icons Web, can't download 18dp SVG

### ISSUE THREAD

**Issue by grunburg** [google/material-design-icons#767]
Hello, as the title explains, I can't select and download 18dp SVG icons. The problem occurs when I select the size of icon, in this example - 18dp, which I wan't to download - It downloads 24dp sized icon.
I'm really frequent user to Google Material icons website, I hope this will be fixed ASAP.

Ričards.

**Comment by andreszs** [comment]
You are not alone, the new layout has also broken compatibility with Android 4.x and IE9.

If someone saved the old page that worked, please upload it to a file host now and share it here.

**Comment by snds117** [comment]
Does anyone have a zip file with the 18dp versions of the icons. I can't find one as the site won't let you download anything but 24dp, and the Sketch theme generator only provides the 24dp variants.

**Comment by andreszs** [comment]
@snds117 Most certainly [these ZIP releases](https://github.com/google/material-design-icons/releases) will contain all the icon sizes including the 18px ones.

**Comment by RoelN** [comment]
Turns out this has been fixed in the meantime. Thanks for your patience!
