### ISSUE TITLE
“calendar_view_day” ligature seems to have problems

### ISSUE THREAD

**Issue by konradekk** [google/material-design-icons#768]
I’m encountering problems with “calendar_view_day” icon from 3.0.1 in Angular Material 5.2.5 having 240px width instead of ca. 24px; rest of the icons (e.g. “short_text”) behaves correctly.

**Comment by FingalP** [comment]
I discovered that calendar_today is no longer an icon, but today is!

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
