### ISSUE TITLE
file_copy icon not working 

### ISSUE THREAD

**Issue by rktaxali** [google/material-design-icons#771]
Using 
    `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

and 
`<span title="Make a Copy" 
	style="cursor:pointer;"><i class="material-icons">file_copy</i></span> `

It does not display the icon. If I use any other icon, e.g. drafts or filter_first, it works

**Comment by blyndcide** [comment]
content_copy works.  It isn't listed on the material icons website.

**Comment by DanielFrancois** [comment]
content_copy works but it's not the same icon. Will this issue be handled ?

**Comment by jpduckwo** [comment]
I think the site that lists the icons isn't accurate for the web font... (https://material.io/icons/). It's changed recently and also there isn't any way to use the different 'themed' icons with the web font either... 

Probably better to switch to svg sprites

**Comment by econsolo** [comment]
Same issue here, but after installing by **npm** _material-design-icons@3.0.1_
Using from **CDN** it works fine.

**Comment by SimonKnu** [comment]
Same issue here

**Comment by TheParad0X** [comment]
Same problem here with material-design-icons 3.0.1. 
content_copy did work.

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
