### ISSUE TITLE
Maximize and resize icons are missing

### ISSUE THREAD

**Issue by alvaromat** [google/material-design-icons#775]
Installed npm package, and imported via styles.scss:

`@import '~material-design-icons/iconfont/material-icons.css';`

using @angular/material:
`<mat-icon>maximize</mat-icon>`
does not display anything.

**Comment by thw0rted** [comment]
I think that icon is newer than the (very old) fonts in the NPM package, see #786

**Comment by RoelN** [comment]
Agreed. This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
