### ISSUE TITLE
icon can't show in edge

### ISSUE THREAD

**Issue by bfss** [google/material-design-icons#776]
Hello,
The icon shows well in chrome, ie and firefox except edge.
In edge, the icon is showd as text , not image.
My edge vresion is Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134.
The website is [https://bfss.github.io/software.html](https://bfss.github.io/software.html)
Thanks.

**Comment by jossef** [comment]
Hey @bfss 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)


![image](https://user-images.githubusercontent.com/1287098/47608579-7160e780-da38-11e8-99be-2aef92f9457f.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
