### ISSUE TITLE
save_alt icon is missing

### ISSUE THREAD

**Issue by OzzyCzech** [google/material-design-icons#777]
Hi,

There are missing some icons like save_alt ...

https://material.io/tools/icons/?search=save_alt&icon=save_alt&style=baseline

https://github.com/google/material-design-icons/blob/224895a86501195e7a7ff3dde18e39f00b8e3d5a/iconfont/MaterialIcons-Regular.svg#L1763

Does anyone have any idea why?

**Comment by lltb** [comment]
I've encoutered the same problem, <i class="material-icons">save_alt</i> not working, please help

**Comment by AtofStryker** [comment]
also having the same issue via npm. is there an ETA to fix?

**Comment by bionicoz** [comment]
Same here with icons like battery_50, battery_90 etc.

**Comment by jossef** [comment]
Hey @AtofStryker @bionicoz @lltb @OzzyCzech 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608144-10ceac00-da32-11e8-903d-906ae1663f3e.png)


![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by edoardoo** [comment]
Got the same issue.
The reason why a repository like Google Material Icons is on low maintenance remains a mystery.

**Comment by jossef** [comment]
@edoardoo have you tried my workaround? [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

**Comment by edoardoo** [comment]
@jossef yes, thanks! I used your version of the font and worked like a charm. 
Is there a way you could submit a pull request? 
Did you fix the font manually or managed to fix the build?

**Comment by jossef** [comment]
@edoardoo 

I serve in [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont) the officially (compiled by Google) font artifacts. I scrape the most updated compiled fonts AS-IS straight from Google Fonts CDN (see my build.py script, I literally scrape & crossing variant user-agents)

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
