### ISSUE TITLE
power_off and other _off not working

### ISSUE THREAD

**Issue by robstoll** [google/material-design-icons#778]
It seems like there is an issue with icons ending with `_off`. Might be a coinsicende but some of them do not work as expected and instead of showing a striked-through version it shows the normal version:
- power_off
- tv_off
- wifi_off
- explore_off
- work_off

Maybe more. What I noticed in addition is, that you can choose an arbitraty suffix for those icons and only the version without any suffix is shown. For instance, `power_on` shows the same as `power_foo` and `power`

**Comment by Nawsen** [comment]
I had the exact same issue. My problem was that I downloaded the font files from this repo. These are outdated.

`<html>
<head>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
<i class="material-icons">
work_off
</i>
</body>
</html>`

I created this simple example above and that works for me. (https://fonts.googleapis.com/icon?family=Material+Icons uses updated font files)

**Comment by robstoll** [comment]
👍 Thanks for the workaround
Not only master is wrong, also the latest stable version mentioned here https://google.github.io/material-design-icons/#downloading-everything contains the bug

**Comment by RyanEwen** [comment]
I'm seeing the same issue with npm `"material-design-icons-iconfont": "3.0.3"`

:(

**Comment by jossef** [comment]
Hey @RyanEwen @robstoll @Nawsen 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608554-2d6de280-da38-11e8-9a64-3cfcc92c5165.png)


![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

The font in this repo has been updated too.

**Comment by ewolfman** [comment]
By chance I found how to make link_off work. Used the 'outlined' font.

`<mat-icon class="material-icons-outlined">link_off</mat-icon>
`
```
.material-icons-outlined {
  font-family: "Material Icons Outlined";
  // rest of css
}
```
