### ISSUE TITLE
'Reorder' icon is not available in 48px in SVG

### ISSUE THREAD

**Issue by Xaviju** [google/material-design-icons#78]
Only in 24px in [https://github.com/google/material-design-icons/tree/master/action/svg/design](https://github.com/google/material-design-icons/tree/master/action/svg/design)
Also, the SVG formation is different from the others:
```
<g xmlns="http://www.w3.org/2000/svg" id="XMLID_11_">
	<rect fill="none" width="24" height="24"/>
	<path d="M3,15h18v-2H3V15z M3,19h18v-2H3V19z M3,11h18V9H3V11z M3,5v2h18V5H3z"/>
</g>
```
Instead of a simple ```<path>``` as the other icons. As the _receipt_ icon, for example
```
<path xmlns="http://www.w3.org/2000/svg" d="M36 34h-24v-4h24v4zm0-8h-24v-4h24v4zm0-8h-24v-4h24v4zm-30 26l3-3 3 3 3-3 3 3 3-3 3 3 3-3 3 3 3-3 3 3 3-3 3 3v-40l-3 3-3-3-3 3-3-3-3 3-3-3-3 3-3-3-3 3-3-3-3 3-3-3v40z" />
```

**Comment by jestelle** [comment]
Per my other comment, we won't necessarily provide more than one SVG source size.
SVG is a vector format meant to be scaled.

The only reason we sometimes have more than one source size is to help with pixel-perfect icons at the various sizes we recommend using.

As per the SVG format, this may be addressed in my next push to github.
