### ISSUE TITLE
offline_bolt not available?

### ISSUE THREAD

**Issue by juristr** [google/material-design-icons#781]
I just downloaded the latest version from master, but it seems like the `offline_bolt` is not available, also didn't find it in the [codepoints](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints)

![image](https://user-images.githubusercontent.com/542458/40168490-e2fea058-59c3-11e8-8a1b-80f90d265c70.png)

**Comment by meglio** [comment]
I can confirm the issue is in the `3.0.1` release

**Comment by dussann** [comment]
I can confirm too

**Comment by vlad-h** [comment]
This issue still exists. Any solutions ?

**Comment by Klayemore** [comment]
Not working for me also

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
