### ISSUE TITLE
Missing outline icons in icon fonts.

### ISSUE THREAD

**Issue by Antoniossss** [google/material-design-icons#787]
For example 
`assignment_returned_outline`
https://stackblitz.com/edit/angular-cxc9um?file=app/icon-overview-example.html

**Comment by wanderval** [comment]
Missing outline icon "create_new_folde_outline"
https://stackblitz.com/edit/angular-cxc9um-d7nlvw?file=app/icon-overview-example.html

Doc: https://material.io/tools/icons/?search=folder&icon=create_new_folder&style=outline

**Comment by DKastani** [comment]
"check_circle_outline" is also absent 
https://material.io/tools/icons/?icon=check_circle_outline&style=baseline
from the .ijmap file

**Comment by thw0rted** [comment]
I think the most popular "missing icon" issue is #786, maybe we could consolidate everything there?

**Comment by cguilhermef** [comment]
You can use, for while, this repository. Works pretty equal to Material Icon normal

[cguilhermef/material-icons-outline][1]

  [1]: https://github.com/cguilhermef/material-icons-outline

**Comment by hmachefe** [comment]
very interesting to get whatever `label` icon rendered as its `label_outline` counterpart. But exclusively.
But what if I want them both: I mean either using `label` icon somewhere and `label_outline` somewhere else

**Comment by hmachefe** [comment]
Any roadmap about when everything will be shipped (w/o `outline`) to have them altogeher

**Comment by cguilhermef** [comment]
I will try do this merge, but I'm not sure about the final size of this font files. Maybe, it will grow a lot. There are 1044 icons. Merging they, up tu 2088 glyphs. But.. we can try!

**Comment by feldmanz66** [comment]
Any update on this? Local offer, local play, and local activity are all not available in outline. I'm willing to guess there are more.

<mat-icon>local_activity_outline</mat-icon>
![image](https://user-images.githubusercontent.com/10455366/71707579-a3967380-2db8-11ea-8291-68d6dbc72241.png)

**Comment by boutell** [comment]
Came here because I couldn't find the magic incantation, the site says "border" is part of the name but "_outline" is the necessary suffix for the fonts, thanks.

**Comment by tphinney** [comment]
Moving forward with the latest variable font versions, in general we do not have separate glyphs for a regular and "_outline" variants of the same design; we instead introduced a Fill axis, so you can get the outline version (as the default glyph) and then use the Fill effect to get at the filled version if you need it. This has the extra ability to allow for an animated transition between the states.

In the process of “variable fontification” we made more glyphs outlined in their default state. And of course pretty nearly everything that is outlined transmutes to filled with the Fill axis. This includes all of the icons specifically discussed in this thread! That is:
- local_activity
- label
- check_circle
- create_new_folder
- assignment_return

I hope you like the new effect, and the greater variety of styles enabled by this and the other three design axes (weight, optical size, grade). My team and I have been working on it for a long time, and have enhanced over 2000 base icons with these additional style variations.

**Comment by thw0rted** [comment]
@tphinney is the additional "axis" available now?  I don't see anything about it in the docs linked from the front page of this repo.  I'm looking for a simple description of how to take advantage of the feature, ideally from Angular Material `mat-icon`, if possible.

**Comment by tphinney** [comment]
Yes, it is available now! I updated the front page (Readme) to point to the current docs. Sorry about the dated links there, should be better now.

The Readme page of the repo now also clarifies the two different versions of the fonts, the Material Icons (non-variable classic fonts) and the Material Symbols (new 4-axis variable fonts).

**Comment by thw0rted** [comment]
Thanks, I'll read the updated docs.  I mentioned Angular Material (Angular Components?) above, apparently there's already an issue tracking support for the newer version: https://github.com/angular/components/issues/24845

**Comment by tphinney** [comment]
Closing this as it has been resolved on the icon font side with Material Symbols. The old Material Icons are not being updated.
