### ISSUE TITLE
'Supervisor account' icon not available in 48px

### ISSUE THREAD

**Issue by Xaviju** [google/material-design-icons#79]
'Supervisor account' icon in 48px not available [http://google.github.io/material-design-icons/action/svg/ic_supervisor_account_48px.svg](http://google.github.io/material-design-icons/action/svg/ic_supervisor_account_48px.svg)

Available instead 24px version [http://google.github.io/material-design-icons/action/svg/ic_supervisor_account_24px.svg](http://google.github.io/material-design-icons/action/svg/ic_supervisor_account_24px.svg)

**Comment by jestelle** [comment]
We don't always author multiple sizes of the SVG source.

You can render that 24px SVG at 48px and get the desired result.
