### ISSUE TITLE
access_alarm breaks website

### ISSUE THREAD

**Issue by AntonHermann** [google/material-design-icons#790]
I'm using the Material Icon font with vue-mdc-adapter and when I try to embed the 'access_alarm' icon, it appears ca 100px to the right, while my dev tools still display the bounding box in the right position. But the bug isn't only graphical, when I hover the wrong positioned icon it still detects that.
I'm using Firefox, and these are my dependencies:
``"dependencies": {
    "material-components-web": "^0.35.2",
    "normalize.css": "^8.0.0",
    "vue": "^2.5.2",
    "vue-mdc-adapter": "^0.15.3",
    "vue-router": `"^3.0.1"`
  }``

![screen_recepie](https://user-images.githubusercontent.com/12369750/40574638-f21c9edc-60d5-11e8-9f8a-419fd679f3fa.png)

 The other icons seemed to work so far

**Comment by jossef** [comment]
Hey @AntonHermann 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)


![image](https://user-images.githubusercontent.com/1287098/47608507-78d3c100-da37-11e8-8ed6-92409867a2c1.png)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
