### ISSUE TITLE
Can not find not_listed_location icon

### ISSUE THREAD

**Issue by nathan-ca** [google/material-design-icons#791]
The icon is available on the web page:

https://material.io/tools/icons/?icon=not_listed_location&style=baseline

but I couldn't find it under the map directory.

**Comment by thw0rted** [comment]
See #786, this package is very outdated

**Comment by jossef** [comment]
Hey @nathan-ca  

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)


![image](https://user-images.githubusercontent.com/1287098/47608418-f0a0ec00-da35-11e8-8cf1-e18247214c86.png)


![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed (just checked, the fonts are there \o/). If not, feel free to reopen this issue or create a new one with more information.
