### ISSUE TITLE
Outline Icons not working in offline

### ISSUE THREAD

**Issue by sreekumarp** [google/material-design-icons#792]
outline icons are not working as mentioned in the demo.

tried settings_outline in mat-icon

`<mat-icon  class="mat-icon material-icons" role="img" aria-hidden="true">settings_outline</mat-icon>`

It seems like github repository is not updated.

**Comment by thw0rted** [comment]
Most of the recent issues seem to be about how outdated the package is, I think the most active is #786

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

Also, `mat-icon`, does that point to a non-Google implementation? If the bug's still around, maybe mention it there?
