### ISSUE TITLE
Use outlined icons in pseudoelements (::before)

### ISSUE THREAD

**Issue by arturhaddad** [google/material-design-icons#795]
I'm trying to add an outlined icon to a button using ::before, but it only displays the icon filled.

There are no guides about how to set the icon outlined.

This is my code:

```
view-site:before{
    content: "\E8F4";
    font-family: 'Material Icons';
}
```

How do i display the outlined icon?

**Comment by TangSteven** [comment]
There is currently no way to do this, besides using the pngs and svgs on the [material.io/icons](material.io/icons) website.

Related issue: #773

**Comment by mparker11** [comment]
This is a little old, but the last answer isn't correct. Maybe it was how the OP implemented it, but it does work by doing:

```
div::before {
    content: '\e7fb';
    font-family: 'Material Icons';
}
```

My guess is there was something else going on in the OP's CSS.

**Comment by RoelN** [comment]
Make sure you're loading and applying the correct fonts. See https://github.com/google/material-design-icons/tree/master/font or your Google Fonts CSS.

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
