### ISSUE TITLE
Inconsistent radius in rounded icon with 'i' character

### ISSUE THREAD

**Issue by alexbouchardd** [google/material-design-icons#796]
Hey there!

Big fan of the new rounded icons, however it looks like all the icons featuring a `i` have inconsistent radius between the `i` dot and trunk. It looks somewhat ridiculous.

<img width="57" alt="screen shot 2018-05-30 at 11 51 32 am" src="https://user-images.githubusercontent.com/2049224/40731867-068f655c-6400-11e8-8dea-ca1bb8aa9f20.png">
<img width="73" alt="screen shot 2018-05-30 at 11 51 22 am" src="https://user-images.githubusercontent.com/2049224/40731868-069ff944-6400-11e8-8f95-a8735f644e98.png">
<img width="79" alt="screen shot 2018-05-30 at 11 51 25 am" src="https://user-images.githubusercontent.com/2049224/40731869-06bd62c2-6400-11e8-8461-bb5838c2bab5.png">

**Comment by RoelN** [comment]
Thanks for reporting! This looks to be fixed in the meantime:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/4570664/107339928-81901a00-6abd-11eb-95ae-57cabbea9654.png">
