### ISSUE TITLE
bar_chart icon missing

### ISSUE THREAD

**Issue by Corsseir** [google/material-design-icons#799]
Regarding https://material.io/tools/icons/?style=baseline is missing. Also there is icon which name is 'cut' in the icons set, but there is no such icon on the website.

**Comment by thw0rted** [comment]
Most of the recent issues seem to be about how outdated the package is, I think the most active is #786

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
