### ISSUE TITLE
The zip file only contains the "acttion" icons. Its missing all other icons.

### ISSUE THREAD

**Issue by tjerkw** [google/material-design-icons#8]
I just downloaded the zip file. And it only has an "action" directory. It misses all other icons.

**Comment by jestelle** [comment]
One other alternative for folks, give [this link a try](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip), which is our mirror of the assets over on the [Material Design spec](http://www.google.com/design/spec/material-design/introduction.html)

Let me know if you experience the same issues downloading from there.

**Comment by dhamini-poornachandra** [comment]
Was very helpful.
