### ISSUE TITLE
baseline_waves - 240px width 

### ISSUE THREAD

**Issue by Riddeller** [google/material-design-icons#801]
The baseline_waves has a strange bounding box making the icon 240px wide.  

```
<div>
    <i class="material-icons">baseline_waves</i>
</div>

```

See image below:
![image](https://user-images.githubusercontent.com/3812154/41151852-e33802b0-6b09-11e8-8829-d821a5c36d85.png)

When setting for the font-size of the icon this causes the problem to get worse.  

[Codepen](https://codepen.io/anon/pen/rKWpgo)

**Comment by hegelstad** [comment]
What was the cause?

**Comment by SaltyPotato** [comment]
What was the issue?

**Comment by Pedrazl** [comment]
Still wrong behavior
