### ISSUE TITLE
bookmarks icon show bookmark icon in Angular Material

### ISSUE THREAD

**Issue by abrahamortiz** [google/material-design-icons#805]
When I use the _bookmarks_ icon in my Angular(6.0.4)/Angular Material(6.2.1) app, the browser always show me the _bookmark_ icon. I'm using Google Chrome on Ubuntu 18.04

**Comment by wasp898** [comment]
Yep, same issue here. Can we do something about it?

**Comment by RoelN** [comment]
Both icons are properly available in this repo and the font. Maybe it's an issue with Angular Material? Please file an issue there, or reopen with more info if you believe this is a Material Design Icons issue!
