### ISSUE TITLE
Need a person_delete icon

### ISSUE THREAD

**Issue by robrwo** [google/material-design-icons#809]
There is a person_add icon. It would be helpful to have a person_delete icon with a minus sign, that corresponds to removing a person or contact.

**Comment by Montesdodgers13** [comment]
Need help to install my profile email accounts on my iPhone and Domain raiders13@calebvalle.com

**Comment by nullatmidnight** [comment]
Agree, we all love to add friends and even make new ones, but some times we need to remove/unfollow someone. It seems there is no person_minus icon in the Social icon set.

**Comment by RoelN** [comment]
I think this is what you're looking for:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/4570664/107387153-d56a2580-6af4-11eb-8efc-c5b53309c8a7.png">
