### ISSUE TITLE
add themes to iconfonts

### ISSUE THREAD

**Issue by m0wh** [google/material-design-icons#811]
Each icon has five themes : filled (regular), outlined, rounded, two-tone and sharp.
Currently this repo only stores the regular one. It would be great to publish the entire iconset and font files !
It is actually not that hard, all the icons are done and the css for webfonts is not very complicated.

The hard part is to redefine the directory architrecture
Could be :
```
material-design-icons/
├── baseline/
│   ├── action/
│   ├── alert/
│   ├── ...
│   └── toggle/
├── outline/
├── round/
├── twotone/
├── sharp/
└── iconfonts/
```

**Comment by gek15** [comment]
O

**Comment by hanakin** [comment]
this does not need to include the font version even...the icons themselves first would be highly useful than can add fonts in separate prs...

**Comment by cyberalien** [comment]
Its much harder. I've made a repository with latest icons: 
https://github.com/cyberalien/google-material-design-icons-updated

While cleaning up and fixing icons I've noticed that many icons have rather complex shapes. They are not usable for fonts. Also two-tone icons are not usable at all. I suspect its one of reasons this repository hasn't been updated yet.

Good news is *shameless plug* icon set can be used with Iconify. Its a SVG framework that is designed to replace glyph fonts. All 5000+ icons are available there. Unlike fonts that load entire fonts and stylesheets, Iconify only loads icons used on pages, so you can mix different icon sets on same page. So you can use Google Material Icons, Templarian's Material Design Icons, FontAwesome, even few emoji sets all on same page without wasting lots of bandwidth and you get benefit of pixel perfect SVG rendering.

See https://iconify.design/ for long explanation.
Code example for twotone-add-a-photo icon: https://iconify.design/icon-sets/ic/twotone-add-a-photo.html

**Comment by hanakin** [comment]
you can even use them on github ![shield-check](https://api.iconify.design/mdi-shield-check.svg?color=%2329b6f6&height=24)

**Comment by RoelN** [comment]
The repo has been updated in the meantime. So I believe this issue can be closed — if not, feel free to reopen or create a new one with more info.
