### ISSUE TITLE
File like baseline restore (baseline_restore_black) when downloaded in PNG for IOS version have wrong contents.json

### ISSUE THREAD

**Issue by Neogene** [google/material-design-icons#812]
When downloading iOS version of some icons (https://material.io/tools/icons/?search=restore&icon=restore&style=baseline)

 eg: baseline , baseline_restore_black_<SIZE>pt_[1x/2x/3x] images folders (baseline_restore_black_<SIZE>.imageset) 

downloaded zip contains folders versions which use the template-rendering-intent": "template" which displays in the Xcode simulator and on device the icon with blue color instead of the black on white color. 

I've read the documentaion that suggests to do :

let button = UIButton()
let closeImage = UIImage(named:"ic_close")?.imageWithRenderingMode(
    UIImageRenderingMode.AlwaysTemplate)
button.tintColor = UIColor(white:0, alpha:0.54)
button.setImage(closeImage, forState:UIControlState.Normal)

But this should be reported in the generator online: should be provided a way to user to select when downloading which is the preferred  render mode of the icons (normal or template) otherwise every time a user generates a new icon he/she has to:

1) import
2) REMEMBER to change the "render as" property of the image set.
3) use

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
