### ISSUE TITLE
Latest codepoints

### ISSUE THREAD

**Issue by shabib3** [google/material-design-icons#813]
Hi, 

Is there any chance of update the [icons codepoints document](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints)...There is a lot of new icons that I can't find in this codepoints document.

Thanks! :)

**Comment by shabib3** [comment]
For who ever that need it, I create a simple angular project to my self that imports the css and run from hexacode `e000` till `f000` and show the icon and his match codepoints.
 
so there is a photos of all the icons and theirs codepoints (without the name of the icon, sorry):

<img width="890" alt="screen shot 2018-07-01 at 14 36 11" src="https://user-images.githubusercontent.com/27296296/42134062-d224f31c-7d3c-11e8-84fe-9a26c5ad47dc.png">
<img width="873" alt="screen shot 2018-07-01 at 14 36 22" src="https://user-images.githubusercontent.com/27296296/42134063-d2447138-7d3c-11e8-9daf-40045c3d20c8.png">
<img width="877" alt="screen shot 2018-07-01 at 14 36 35" src="https://user-images.githubusercontent.com/27296296/42134064-d2659192-7d3c-11e8-9c92-7184b274f320.png">
<img width="851" alt="screen shot 2018-07-01 at 14 36 46" src="https://user-images.githubusercontent.com/27296296/42134065-d28477c4-7d3c-11e8-9b8c-d30efab21998.png">
<img width="858" alt="screen shot 2018-07-01 at 14 36 56" src="https://user-images.githubusercontent.com/27296296/42134067-d2a4e96e-7d3c-11e8-9f2d-b139b2073a0c.png">
<img width="897" alt="screen shot 2018-07-01 at 14 37 05" src="https://user-images.githubusercontent.com/27296296/42134068-d2c4e0d4-7d3c-11e8-8183-17d0d7ffdfc7.png">
<img width="899" alt="screen shot 2018-07-01 at 14 37 17" src="https://user-images.githubusercontent.com/27296296/42134069-d355f5b0-7d3c-11e8-8a7a-fba3cdcfce32.png">
<img width="880" alt="screen shot 2018-07-01 at 14 37 27" src="https://user-images.githubusercontent.com/27296296/42134070-d37c5994-7d3c-11e8-954c-b2e79087ee95.png">
<img width="896" alt="screen shot 2018-07-01 at 14 37 37" src="https://user-images.githubusercontent.com/27296296/42134071-d4035f16-7d3c-11e8-9b38-7771988a472e.png">
<img width="886" alt="screen shot 2018-07-01 at 14 37 44" src="https://user-images.githubusercontent.com/27296296/42134072-d44ecc80-7d3c-11e8-8b3c-ccd4718c66b3.png">

**Comment by andreszs** [comment]
Thanks, well done. But in uppercase and without italic the codes would be more readable.

**Comment by webleaf** [comment]
@shabib3 cannot find [category](https://material.io/tools/icons/?icon=category&style=baseline) icon code

**Comment by shabib3** [comment]
@webleaf - What is exactly the category icon code?
the link you attached takes me to the main icons page...

**Comment by shabib3** [comment]
@webleaf - ohh sorry... take a look on this https://github.com/google/material-design-icons/issues/815#issuecomment-403952958

**Comment by alienriver49** [comment]
It looks like someone has forked this repository and reworked it based on the font hosted by Google (which is the most up to date) at [Material Design icons + Development Experience](https://github.com/jossef/material-design-icons-iconfont). If you look under src/_variables.scss you'll see the codepoints for the latest font, currently located [here](https://github.com/jossef/material-design-icons-iconfont/blob/master/src/_variables.scss).

The image above was great but it lacked the icons name from the Google Material Icons site and is not searchable, which makes it difficult to use.

**Comment by hawkeye64** [comment]
You can drop the WOFF file here and get all the info about a font you need.
https://fontdrop.info/

**Comment by shabib3** [comment]
@hawkeye64 - Nice!

[Here is the woff file](https://github.com/google/material-design-icons/files/3389674/material.design.icons.woff.zip) for the material design icons so every one can use [fontdrop](https://fontdrop.info/) website to get the fonts info

**Comment by eliudio** [comment]
Try this: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart

**Comment by roipoussiere** [comment]
The [codepoint file linked in op](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) doesn't exist anymore...

**Comment by Batreek** [comment]
I was looking for an update codepoints file, I ended up extracting the codepoints from the current font being used in the [Material Icons Library](https://material.io/resources/icons/)
https://fonts.gstatic.com/s/materialicons/v76/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2

[MaterialIcons.codepoints.txt](https://github.com/google/material-design-icons/files/5915604/MaterialIcons.codepoints.txt)

**Comment by RoelN** [comment]
The `.codepoint` files [here](https://github.com/google/material-design-icons/tree/master/font) will indeed inform you of the codepoints. This has been updated to reflect the icons in the latest icon fonts! Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by Batreek** [comment]
> The `.codepoint` files [here](https://github.com/google/material-design-icons/tree/master/font) will indeed inform you of the codepoints. This has been updated to reflect the icons in the latest icon fonts! Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

But there seems to be a problem with those codepoints. They are definitely incomplete. I extracted 1786 codepoints from [this](https://fonts.gstatic.com/s/materialicons/v76/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) font. The largest codepoints available [here](https://github.com/google/material-design-icons/tree/master/font) only have 1563. That's a huge 223 missing codepoints. Why are they not included?

**Comment by RoelN** [comment]
If they're still out of sync, I'll reopen this issue and attach the proper labels so the Google team can address this. Thanks, @Batreek

**Comment by AtosNicoS** [comment]
I also stumbled across this issue. Especially the outlined version seems incomplete. For example `4k_plus` is missing here:
https://github.com/google/material-design-icons/blob/master/font/MaterialIconsOutlined-Regular.codepoints

**Comment by tphinney** [comment]
That most recent link given just above is up to date these days.
In general, the codepoints files are updated in sync with the latest font files now.
However, the original link given at the beginning of this issue leads to a file not found.

So, I think this is generally fixed now, although the specific file being pointed to originally isn’t there any more.
