### ISSUE TITLE
i can not find category icon in material-design-icons/maps/**

### ISSUE THREAD

**Issue by anlexN** [google/material-design-icons#815]
![image](https://user-images.githubusercontent.com/8686739/42212959-20575b2a-7eea-11e8-80d9-23d37e2e5ebd.png)

**Comment by kintz09** [comment]
I am having the same issue. Can't find it in the project and the unicode character is not included in the codepoints file.

**Comment by kintz09** [comment]
I managed to find the code for this icon here: [#813 (comment)](https://github.com/google/material-design-icons/issues/813#issuecomment-401601344)

category e574

The character is still missing from the ttf font file though.

**Comment by kintz09** [comment]
For anyone else looking to use this icon, I was able to get an updated font file from a comment in [issue #786](https://github.com/google/material-design-icons/issues/786) which contained the category glyph.

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
