### ISSUE TITLE
 icon request: Configuration Sliders

### ISSUE THREAD

**Issue by mohaqqani** [google/material-design-icons#818]
https://fontawesome.com/icons/sliders-h?style=light

can we have this icon

**Comment by danielhickman** [comment]
It exists in the image editing context as tune

**Comment by RoelN** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/4570664/107479935-148f8980-6b7c-11eb-895c-e3ac41b669b8.png">

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
