### ISSUE TITLE
restore_from_trash icon not available for use in version 3.0.1

### ISSUE THREAD

**Issue by kihot** [google/material-design-icons#820]
commute icon not available to use in version 3.0.1, like:

\<i class="material-icons"\>restore_from_trash\</i\>

**Comment by eelcowen** [comment]
Please read #786 
Google isn't updating this repo for the foreseeable future.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
