### ISSUE TITLE
Codepoints file is out of date

### ISSUE THREAD

**Issue by RezaRahmati** [google/material-design-icons#821]
Hello

I just noticed that code point file is for v2.2.0 and doesn't contains new icons

https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by eelcowen** [comment]
Please read #786 
Google isn't updating this repo for the foreseeable future.

**Comment by RoelN** [comment]
Please see the updated codepoints files here: https://github.com/google/material-design-icons/tree/master/font
