### ISSUE TITLE
Icon 'arrow_back_ios' not centered

### ISSUE THREAD

**Issue by JohannesKuehnel** [google/material-design-icons#824]
The icon 'arrow_back_ios' is not centered correctly in the 'Filled'-theme (baseline).

Here is the misaligned version in 'Filled':
![screen shot 2018-07-17 at 17 33 46](https://user-images.githubusercontent.com/6152455/42827963-e8510ae2-89e7-11e8-900f-c7cbf81b939e.png)

Here is the centered version in 'Outlined':
![screen shot 2018-07-17 at 17 34 20](https://user-images.githubusercontent.com/6152455/42827966-e9c5c732-89e7-11e8-8479-935deecc7793.png)

Source: https://material.io/tools/icons/?search=arrow&icon=arrow_back_ios&style=baseline

**Comment by SvenBudak** [comment]
Check this: https://github.com/material-icons/material-icons Here you can get fixed icons

**Comment by CarlosOrozc** [comment]
when I import this in my application it looks the same as the image

> import ArrowBackIosIcon from '@ material-ui / icons / ArrowBackIos';


<img width="1440" alt="Screen Shot 2020-02-26 at 21 47 24" src="https://user-images.githubusercontent.com/8071575/75410778-968e9000-58e2-11ea-82af-9412ddfc1817.png">

**Comment by RoelN** [comment]
Closing in favor of https://github.com/mui-org/material-ui/issues/17425 which has the solution.
