### ISSUE TITLE
Icon download_done is missing

### ISSUE THREAD

**Issue by rafaelbeck** [google/material-design-icons#826]
Hello,

I would like to use the download_done icon but it's missing on the https://material.io/tools/icons/ website as well as in the codepoints file on github.
So far it's only available as symbol in the sketch file from https://material.io/tools/theme-editor/downloads/icons/material-design-icons-outlined.sketch.

Best regards,
Rafael

**Comment by eelcowen** [comment]
Duplicate of #786

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
