### ISSUE TITLE
icon name is not visible anymore on Zeplin 

### ISSUE THREAD

**Issue by Alicote** [google/material-design-icons#829]
When downloading an icon, the icon name used to be visible on zeplin - it's not anymore 
This issue started after the new redesign of the material icons page (a month ago or smg)
<img width="271" alt="screen shot 2018-07-25 at 15 56 57" src="https://user-images.githubusercontent.com/26568956/43205336-6cbd4002-9023-11e8-9002-1dc1904d773f.png">

**Comment by RoelN** [comment]
This sounds like a bug with Zeplin. If not, feel free to reopen this issue or create a new one with more information.
