### ISSUE TITLE
Improve icon search with tags

### ISSUE THREAD

**Issue by mriede** [google/material-design-icons#830]
Hello,

the current (very basic) search on the Material Icons website allows searching for icons via name, which makes it quite difficult to find icons if they are misleadingly named. Imagine, you're searching for a heart icon. The heart icon is named _favorite_, which will take some time to figure out if you're a new user. This could be fixed by using a tag system that allows for associating icons with more common search terms

**Comment by montoyaaguirre** [comment]
Good point. I support this one

**Comment by RoelN** [comment]
Thanks for reporting! Closing this in favor of https://github.com/google/material-design-icons/issues/907 which tracks the same problem.
