### ISSUE TITLE
print_disabled icon looks exactly like print

### ISSUE THREAD

**Issue by acherniak** [google/material-design-icons#831]
`<i class="material-icons">print_disabled</i>`  looks exactly like `<i class="material-icons">print</i>`

**Comment by eelcowen** [comment]
This all has to do with issue Google not updating this Git repository.
Duplicate of #786

**Comment by RoelN** [comment]
Looks like this has been addressed: https://github.com/google/material-design-icons/search?q=filename%3Aprint_disabled

If not, feel free to reopen this issue or create a new one with more information.
