### ISSUE TITLE
star_rate icon code is missing.

### ISSUE THREAD

**Issue by ruwaroshan** [google/material-design-icons#834]
star_rate icon code is missing.

![image](https://user-images.githubusercontent.com/12517126/43383945-28f261ce-93fa-11e8-919e-aca17c552c5d.png)

![image](https://user-images.githubusercontent.com/12517126/43383999-4e39ec90-93fa-11e8-8fc1-1ecfd53fe1a7.png)

**Comment by eelcowen** [comment]
This all has to do with issue Google not updating this Git repository.
Duplicate of #786

**Comment by RoelN** [comment]
Closing this in favor of the issue mentioned above. Apologies for the delay.
