### ISSUE TITLE
check_circle_outline not present?

### ISSUE THREAD

**Issue by kamilkubickioenb** [google/material-design-icons#835]
Hi,

I'm not sure, if I don't get it, but maybe you guys can help me.

Due to some security requirements, I had to install material-design-icons 3.0.1 with bower (yes I know, we are migrating to webpack soon :) ):

`bower install material-design-icons -save`

for some reason I can't manage to put check_circle_outline in my page. It's always filled black or white. I need the icon having transparent background and black lines. I searched for it in the directory, but could only find the filled icon.

`<md-icon class="material-icons">check_circle_outline</md-icon>`

Am I overseeing something?

Thank you in advance.

Regards from Vienna!

**Comment by eelcowen** [comment]
This all has to do with issue Google not updating this Git repository.
Duplicate of #786

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
