### ISSUE TITLE
Upload & Download File icons are missing

### ISSUE THREAD

**Issue by iddan** [google/material-design-icons#839]
When searching through the Material Icons catalog I couldn't find `file_upload` & `file_download` icons.

**Comment by Springrbua** [comment]
I don't think this is an icon request, as the two icons already exist.
They only seem to be missing in the [documentation](https://material.io/tools/icons/?style=baseline).
Both icons can be used as `file_download`/`file_upload`

**Comment by ZMYaro** [comment]
I would add that while `file_download` is listed available in the documentation in the form of `get_app`, but `file_upload` is not there at all.

**Comment by hbugdoll** [comment]
`file_download` and `file_upload` were added in v4.0.0.

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons 
file_upload
file_download
