### ISSUE TITLE
Unable to create archive

### ISSUE THREAD

**Issue by GRRedWings** [google/material-design-icons#84]
When I try to sync with SVN it fails. I have tried it on the main URL, as well as the trunk.

I tried the zip download, but it does not appear to bring down all the icons.  Any help would be appreciated.

**Comment by jestelle** [comment]
See issue #8 

My last comment there describes a quick alternative:

One other alternative for folks, give [this link a try](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip), which is our mirror of the assets over on the [Material Design spec](http://www.google.com/design/spec/material-design/introduction.html)

Let me know if you experience the same issues downloading from there.
