### ISSUE TITLE
Not informed the code point of the icon: drag_indicator

### ISSUE THREAD

**Issue by samuelcust** [google/material-design-icons#841]
There was no information in the list of [code points](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) the icon drag_indicator.

**Comment by jestelle** [comment]
Unfortunately we're quite behind on this project.
We expect to catch up on all of this - but it may take us a while before we're able to revisit it in full.
Sorry for the inconvenience.

**Comment by meoblast001** [comment]
Is it possible this is a duplicate of #568?

**Comment by MurhafSousli** [comment]
This is still an issue since 2 years!

**Comment by tphinney** [comment]
I think this was eventually updated. Please let me know if it is still a problem? And if so at what location(s).

**Comment by tphinney** [comment]
The original link is simply broken, but the latest codepoints files seem good.
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
generally these get updated at the same time as the fonts, nowadays.
