### ISSUE TITLE
Add rounded, outline and new icons to icon font

### ISSUE THREAD

**Issue by sms1989** [google/material-design-icons#842]
please update icon font; your last commit was 2(3) years ago ...

**Comment by philfleck** [comment]
+1

**Comment by aissaghouti** [comment]
+1

**Comment by Quenice** [comment]
+1

**Comment by nrone** [comment]
https://github.com/google/material-design-icons/issues/773

**Comment by jestelle** [comment]
We intend to do this. But I can't commit to how soon.
Sorry for the inconvenience.

**Comment by jossef** [comment]
Hey @sms1989 @philfleck  @aissaghouti  @quenice @nrone 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

Only new icons, the rounded / outlined versions are not yet released as an iconfont in material.io/icons.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
