### ISSUE TITLE
Icon request: Wifi signal no internet

### ISSUE THREAD

**Issue by YZahringer** [google/material-design-icons#843]
It would be great to have a set of icons for wifi signals without internet connection alert. Same as signal_cellular_connected_no_internet_*_bar.

**Comment by Mancerrss** [comment]
Yea like on Xperia phones. The wifi Icon had exclamation mark ! on it's bottom side to show it doesn't have inter. Please make that

**Comment by jalpadoshi** [comment]
Icons available on fonts.google.com/icons
