### ISSUE TITLE
save_alt

### ISSUE THREAD

**Issue by Corsseir** [google/material-design-icons#844]
```
          <i class="material-icons nav-icon">save_alt</i>
```

save_alt gives me the same icon as save

```
          <i class="material-icons nav-icon">save</i>
```

**Comment by jestelle** [comment]
Our icon font may be missing the save_alt icon.

Unfortunately we may not be able to address this for a while.  Sorry for the inconvenience.

**Comment by MeteorCoder** [comment]
> Unfortunately we may not be able to address this for a while. Sorry for the inconvenience.

What I guess I'm not understanding is, you guys are sitting here teasing us with the new icons and not releasing them. It's been 3 years since you've added more icons. If you want more people to use your icons I suggest you serve your users right. 

> Our icon font may be missing the save_alt icon.
Ya think? You haven't released a new one for 3 years.

**Comment by jossef** [comment]
Hey @Corsseir @jestelle @MeteorCoder 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608144-10ceac00-da32-11e8-903d-906ae1663f3e.png)


![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by MeteorCoder** [comment]
> Hey @Corsseir @jestelle @MeteorCoder
> 
> This project is on low maintenance and out of date for a while.
> 
> The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.
> 
> ### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)
> ![image](https://user-images.githubusercontent.com/1287098/47608144-10ceac00-da32-11e8-903d-906ae1663f3e.png)
> 
> ![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

Thank god someone is here to help us all...

**Comment by davidrenne** [comment]
This thread is pretty funny.  I love when angry devs fork google stuff.  Send a pull request back please to get some of these goodies into master on the google tree.

**Comment by ecoopresent** [comment]
![errorpage](https://user-images.githubusercontent.com/29815801/102187430-f1838900-3eee-11eb-999c-d9bcc308052a.PNG)

**Comment by ecoopresent** [comment]
![image](https://user-images.githubusercontent.com/29815801/102187581-2099fa80-3eef-11eb-94e9-67c962e72f1d.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
