### ISSUE TITLE
codes index not updated for a long time，please update

### ISSUE THREAD

**Issue by Kyrosee** [google/material-design-icons#845]
material-icons font codes index not updated for a long time，please update

**Comment by philfleck** [comment]
+1

**Comment by Mancerrss** [comment]
Yea I am seeing more icons on repo here, and less on that Icon Tool. Google products even have their own new icons too, but apparently either this tool or their repo is slow to catch up. Isn't Google employees especially on development isn't using this too? Why they aren't automatically adding it after they're done? 

Material Design Icons Community is even faster on this c'mon. Any explanations on this?

**Comment by jestelle** [comment]
Unfortunately we're a bit underwater with respect to the open-sourcing of our icons.

https://material.io/tools/icons/?style=baseline
is the up-to-date source, and unfortunately the only part of our icon system we have completely maintained.

We'll be catching up towards the end of the year.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
