### ISSUE TITLE
Material Design Icon Tool doesn't export other sizes anymore, other than 24dp

### ISSUE THREAD

**Issue by Mancerrss** [google/material-design-icons#847]
No matter what size you select, whether it be the new iOS or Android option there, it always just export 24dp. Is this really intended or is this a bug, I'm pretty sure it is. Please ry it and fix it

**Comment by RoelN** [comment]
This looks to be fixed on the website. So I'm closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
