### ISSUE TITLE
Icon request: QR/Barcode

### ISSUE THREAD

**Issue by iSinch** [google/material-design-icons#848]

**Comment by RoelN** [comment]
Closing this as QR code has arrived! \o/ Feel free to reopen for barcode is you still need one.

**Comment by tphinney** [comment]
I just wanted to let people know 1D (linear) /barcode and /barcode_scanner icons have been approved for me to add them to Material Symbols. I will be adding them on the source side today. I know it has been a long wait! Thanks for your patience.
