### ISSUE TITLE
Can't find flag_outlined icon

### ISSUE THREAD

**Issue by TKul6** [google/material-design-icons#849]
Hi,

First of all thanks for this great library, it saves me tons of hours of work.

I'm developing Angular app (using angular-material)

I used the icons library via the http feed:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">`

and it works perfect.
BUT THEN,
a new requirement of supporting private networks (without access to the internet) was thrown at me.

So I read the `readme.md` file and saw that I cant download a package and use it.
 I followed the instructions for self hosting and it works OK, except the `outlined_flag`  (https://material.io/tools/icons/?search=outlined_fl&style=baseline) that now shows a regular flag.

I browse the library and saw there's no svg of this file (but flag exists).

Is outlined icons require special handling?

Thanks

**Comment by jestelle** [comment]
Unfortunately our icon fonts have not yet been updated for the new Material icon styles. It may be some time before we're able to do that. Sorry for the inconvenience.

**Comment by TKul6** [comment]
Thanks a lot, 
Looking forward for the next version :)

**Comment by RoelN** [comment]
I believe this is a design issue. Closing this in favor of https://github.com/google/material-design-icons/issues/1130
