### ISSUE TITLE
`image -> wb irradescent` is mispelled

### ISSUE THREAD

**Issue by sariyamelody** [google/material-design-icons#85]
Relevant: https://www.google.com/search?q=how+to+spell+irradescent&ie=utf-8&oe=utf-8

**Comment by RoelN** [comment]
<img width="507" alt="afbeelding" src="https://user-images.githubusercontent.com/4570664/108869191-403c5600-75f7-11eb-8732-a55a633f03c3.png">

Fixed! \o/
