### ISSUE TITLE
Icon alternate_email not showing correctly in IE11

### ISSUE THREAD

**Issue by inONEL** [google/material-design-icons#850]
Icon alternate_email shows an enveloppe instead of the "@" symbol in IE11. Other icons show up correctly.
Thanks for the help

**Comment by jossef** [comment]
Hey @inONEL 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

![image](https://user-images.githubusercontent.com/1287098/47608107-c3523f00-da31-11e8-9882-e71bc648cc4a.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
