### ISSUE TITLE
Icon Request: stop_circle_outline and stop_circle_filled

### ISSUE THREAD

**Issue by yaminyaylo** [google/material-design-icons#851]
It would be more consistent if **Av** icons category will have _stop_circle_outline_ and _stop_circle_filled_  (stop icon inside the circle) icons as well as _[play](https://material.io/tools/icons/?search=play%20circle&icon=play_circle_outline&style=baseline)_ and _[pause](https://material.io/tools/icons/?search=pause%20circle&icon=pause_circle_filled&style=baseline)_ icons that are already present.

Expected example https://codepen.io/changer/pen/RYMrvd

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
