### ISSUE TITLE
Stop rendering in fallback font

### ISSUE THREAD

**Issue by timtribers** [google/material-design-icons#852]
Hi,
Thanks for all the hard work on this font set.
The problem with using ligature naming for icons (as recommended in the guide) is that it falls back to displaying the string name while the icon font loads.  Could you use something like "font-display: block" in the css @font-face declaration to overcome this?
At present, I have to use the codepoint method for icons, as that will just display a single outlined square as the font loads.
Thanks

**Comment by jestelle** [comment]
Good feedback. It may be a while before we're able to work deeply on this again. But we'll get back to it as soon as we're able.

**Comment by rsheeter** [comment]
If you are using Google Fonts you can now specify `&display=block`

**Comment by RoelN** [comment]
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
