### ISSUE TITLE
SVG Symbol sprites not updated with latest icons?

### ISSUE THREAD

**Issue by ajkandy** [google/material-design-icons#854]
There are icons listed on the material.io/tools/icons page that are not in the downloadable folders here. They can be downloaded one-by-one from that page, but it's tedious if you're trying to assemble a full icon set, and particularly if you are trying to merge them into a single symbol-based SVG. 

It doesn't seem like the files here have been updated in over a year. Am I missing something? 

Will the symbol sprite SVGs here be updated, or will there be a tool to allow us to multi-select icons across the different categories, so we can customize and download a single SVG? (Similar to how IcoMoon works?) Thanks!

**Comment by jestelle** [comment]
HI ajkandy,
We're a bit underwater with this project right now. We'll be ramping up some new work towards the end of the year, but unfortunately we won't be able to address this in the short term.
Keep the bug reports and feature requests coming. We're reading them, and expect to fold it all back into Material Design as soon as we're able.
Best,
Josh

**Comment by ajkandy** [comment]
Thanks for the feedback! If and when you know when they're on track for updates that'll be great. 

In the meantime I did use IcoMoon's icon-selector tool to generate a custom set of SVG symbol defs. They don't have the updated icons either but I can always manually insert them if needed. 

Thanks for all the work, it's greatly appreciated.
