### ISSUE TITLE
Icons with  numbers in classname do not work

### ISSUE THREAD

**Issue by koooooray** [google/material-design-icons#856]
Icons which have a number in the class name are not displayed at all or displayed as wrong icons:
https://stackblitz.com/edit/angular-zhk9mm?file=app/icon-overview-example.html
battery_charging_30 and signal_wifi_1_bar_lock are not displayed properly in the example above.

**Comment by nasermirzaei89** [comment]
I have this problem too!
https://codepen.io/nasermirzaei89/pen/wQWVyL

**Comment by anymos** [comment]
A the earliest that I can stop using this lib I will, it is just not up to the standard and by using it we are all complicit of google hegemony on everything ...

so many exemple of missing icon for years! Any other project if it was not for google would have been abandonned ...

**Comment by RoelN** [comment]
This looks to be a problem with `@angular/material`, could you report it there? The current icons on https://material.io/resources/icons seem to display fine, so I believe this issue has been fixed when the assets got updated.
