### ISSUE TITLE
Multiple icons missing from "iconfont" folder of the repo.

### ISSUE THREAD

**Issue by shivalipawar** [google/material-design-icons#857]
Several icons like arrow_back_ios, check_mark_outline is not as per latest in the icons in this folder. 
There are multiple issues related to various icons missing.

Can you update on by when will this icons be upated to latest.

**Comment by jossef** [comment]
Hey @shivalipawar 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
