### ISSUE TITLE
How to give proper attribution?

### ISSUE THREAD

**Issue by MarcusWolschon** [google/material-design-icons#86]
There should be a part in the readme.md stating how to give attribution.
What's the NAME to give attribution to?

"using material-design-icons"?
"using google/material-design-icons"?
"uses Material Design icons by Google"?
...

**Comment by addyosmani** [comment]
To the best of my knowledge, we should be fine with the very last of these. @jestelle I think for the next release we should update the README to include more details on attribution as these questions come up semi-regularly. Sound worthwhile?

**Comment by tryagains** [comment]
I would also like to know where we need to put the attribution. In the homepage? source? every page?

**Comment by andreynovikov** [comment]
Why should we give it? It's an official icon set by Google (or am I wrong?). By providing it Google encourages us to implement material design in our applications. Google also provides us with Android API, Google Play Services, Android Studio and tons of other stuff that helps us create and promote Android applications. Should we give attribution to all that also?

**Comment by schildbach** [comment]
@andreynovikov Simply because of the license. See http://creativecommons.org/licenses/by/4.0/

**Comment by jestelle** [comment]
We would generally like attribution to be user-visible (i.e., not hidden in code / view-source), however we don't expect attribution to be anywhere prominent.

Many Android apps include a section within their Help / About section that list open source licenses used by their project.  Something akin to that is fine.
