### ISSUE TITLE
Restart icon is misaligned

### ISSUE THREAD

**Issue by thgh** [google/material-design-icons#862]
<img width="244" alt="screen shot 2018-10-04 at 10 24 19" src="https://user-images.githubusercontent.com/1109982/46461725-affbdd00-c7bf-11e8-8e64-60ff07c29d30.png">

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
