### ISSUE TITLE
Please update the iconfont folder

### ISSUE THREAD

**Issue by Zibonnn** [google/material-design-icons#864]
Please update the iconfont folder with the new version of Icon Fonts.

**Comment by philfleck** [comment]
bump

**Comment by harunalikadic** [comment]
Why not?

**Comment by tmx976** [comment]
Needed!
Please update...

**Comment by ThePatzen** [comment]
Here too!
Please update :-)

**Comment by jossef** [comment]
Hey @Zibonnn @philfleck @harunalikadic @tmx976 @ThePatzen 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

**Comment by Zibonnn** [comment]
> Hey @Zibonnn @philfleck @harunalikadic @tmx976 @ThePatzen
> 
> This project is on low maintenance and out of date for a while.
> 
> The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.
> 
> ### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)
> ![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

Thank you Jossef! Unfortunately, the font (.ttf) [you uploaded here](https://github.com/jossef/material-design-icons-iconfont/tree/master/dist/fonts) looks corrupted and can not be installed on my Mac. :( Can you please help?

**Comment by jossef** [comment]
@Zibonnn thanks! 

fixed and published a new release (it was a bug in the font scraper script I wrote)

I've just pushed [this commit](https://github.com/jossef/material-design-icons-iconfont/commit/b89f3b609fbbe21eb6130cf6c82482fb99facb1e) and released [4.0.2](https://github.com/jossef/material-design-icons-iconfont/releases/tag/4.0.2)

Demo page will reflect changes in the next minutes
Thanks for the update! totally missed that.

**Comment by Zibonnn** [comment]
@jossef Thanks, Man! It's working now.

This is life saver! Really appreciate it. 👍

**Comment by Amaimersion** [comment]
> Hey @Zibonnn @philfleck @harunalikadic @tmx976 @ThePatzen
> 
> This project is on low maintenance and out of date for a while.
> 
> The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.
> 
> ### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)
> ![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)

Good job!

**Comment by conceptworld** [comment]
Thanks @jossef 

Is it possible to create ttf font files for different themes? Outline fonts etc?

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
