### ISSUE TITLE
Broken link in SVG Sprite descriptions

### ISSUE THREAD

**Issue by renestalder** [google/material-design-icons#87]
In the HTML Files of the icon sprite description, there is a paragraph that references to the documenation on how to embed SVG sprite. This link does not point at the correct section.

https://github.com/google/material-design-icons/blob/master/sprites/svg-sprite/svg-sprite-action.html#L212

```
The embedded sprite (A) slightly differs from the generated external one. Please see the documentation for details on how to create such an embeddable sprite.
```

Point to https://github.com/jkphl/svg-sprite#inline-embedding. But there is no section with this anchor point.

**Comment by shyndman** [comment]
Sprites have been updated.
