### ISSUE TITLE
Can't find notification_important icon

### ISSUE THREAD

**Issue by Samuel-divvito** [google/material-design-icons#870]
Hi,

Thanks for this library, it is useful to my project.
I tried to leverage notification_important icon, whose picture is listed on the website, but can't find it in the library (checked \iconfont\codepoints, no this icon)

Could you help to take a look into this and have a update? Or something else I missed?

Thanks

**Comment by jossef** [comment]
Hey @Samuel-divvito 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47607980-f3004780-da2f-11e8-8214-b6603048a534.png)

**Comment by RoelN** [comment]
Closing this one in favor of https://github.com/google/material-design-icons/issues/933
