### ISSUE TITLE
Material Design 2?

### ISSUE THREAD

**Issue by drakeet** [google/material-design-icons#871]
I noticed there are many new icons used in such Google Photos, Google Calendar, and Google Keep, which are more outlined. Are they Material Design 2 style icons? Does Google have any plans to update them into this icon collection? 

<img src="https://user-images.githubusercontent.com/5214214/47479072-6fdbc780-d85e-11e8-88c3-41f33931f50c.png" width=300/>

Thanks!

**Comment by drakeet** [comment]
@MGaetan89 Thanks, it's helpful, but it doesn't contain these icons used in such Google Photos screenshot, especially the trash/delete and settings icon.

**Comment by MGaetan89** [comment]
The trash and settings icons are also there, but they are not exactly the same as on your screenshot.

**Comment by RoelN** [comment]
Material Design Icons is a general purpose icon set, not necessarily the same as the icon sets used by Google products. So Google-specific icons will not be included.

if you believe these should be added, feel free to create a new issue with a specific icon request. Thanks!
