### ISSUE TITLE
Missing codes arrow_forward_ios & arrow_right ?

### ISSUE THREAD

**Issue by Rmy5** [google/material-design-icons#874]
I can't find the codes for the  [arrow_forward_ios](https://material.io/tools/icons/?search=arr&icon=arrow_forward_ios&style=baseline) or the [arrow_right](https://material.io/tools/icons/?search=arr&icon=arrow_right&style=baseline) in the [codepoints](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) file.
Can I find these codes elsewhere ?

**Comment by jossef** [comment]
Hey @Rmy5 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47607815-956afb80-da2d-11e8-840e-0949439d766b.png)

**Comment by jossef** [comment]
@Rmy5 
Currently I don't manage a mapping of the codes in my fork. 
You're more than welcome to add an issue to https://github.com/jossef/material-design-icons-iconfont

**Comment by Mister-N** [comment]
I also can't find "delete_outline" and "preview" in /iconfont/codepoints. And I need them since I have an application on nativesript and codepoint is needed here.
Tried going here https://jossef.github.io/material-design-icons-iconfont/ and looking at the code, but it doesn't seem to work for the npm version. Here's 3.0.1 https://www.npmjs.com/package/material-design-icons 
e92e does not allow to get delete_outline icon on this version

**Comment by jossef** [comment]
Hey @Mister-N,
In my forked project - [material-design-icons-iconfont](https://www.npmjs.com/package/material-design-icons-iconfont), you can find [this json file](https://github.com/jossef/material-design-icons-iconfont/blob/master/dist/fonts/MaterialIcons-Regular.json) 

```
{
    "360": "E577",
    "1k_plus": "E95D",
    "19mp": "E95B",
    "18mp": "E95A",
    "17mp": "E959",
    "16mp": "E958",
    "15mp": "E957",
    "14mp": "E956",
    "13mp": "E955",
    "12mp": "E954",
    "11mp": "E953",
    "10mp": "E952",
    "10k": "E951",
    "1k": "E95C",
    "2k_plus": "E964",
    "24mp": "E962",
...
```

BTW
![image](https://user-images.githubusercontent.com/1287098/95838706-c5ab2200-0d4a-11eb-8063-11797bee7284.png)
![image](https://user-images.githubusercontent.com/1287098/95838744-d3f93e00-0d4a-11eb-8111-fc867b4cc649.png)

```
npm install material-design-icons-iconfont --save
```

**Comment by Mister-N** [comment]
Ok thanks

**Comment by RoelN** [comment]
@jossef Thanks for providing workarounds and solutions so people can still get their jobs done!

The assets have been updated in the meantime, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
