### ISSUE TITLE
missing icon file_copy

### ISSUE THREAD

**Issue by linksee-dev** [google/material-design-icons#877]
![image](https://user-images.githubusercontent.com/12714985/47910190-034f7100-decd-11e8-8a67-8d5edafbd286.png)

file_copy icon not show

**Comment by thiswallz** [comment]
that happens quite often

**Comment by wachunga** [comment]
So is this library not maintained? Or the documentation not maintained?

**Comment by qin9smile** [comment]
i think this library not maintained but the documentation has maintained...

**Comment by qin9smile** [comment]
because i found the icon in documentation but when i use in code , the icon is not show correctly

**Comment by jossef** [comment]
Hey @qin9smile @wachunga @thiswallz 

This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss, removed irrelevant files (jams `npm install`).

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

as a proof, the `file_copy` icon is available as you would expect

![image](https://user-images.githubusercontent.com/1287098/49375502-28721200-f70d-11e8-83b9-928985e6e83a.png)
