### ISSUE TITLE
add_to_home_screen displays as add and home when selfhosted

### ISSUE THREAD

**Issue by ChildishGiant** [google/material-design-icons#878]
If self hosting the font [as the docs describe](https://google.github.io/material-design-icons/) baseline-add_to_home_screen displays completely wrong

It can be reproduced by making a test HTML page in the [iconfont folder](https://github.com/google/material-design-icons/tree/master/iconfont) of this repo.
```
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="material-icons.css">
    </head>
    <i class="material-icons">add_to_home_screen</i>
</html>
```
Expected:
![image](https://user-images.githubusercontent.com/13716824/48100283-839e0b00-e21a-11e8-8387-ec18758286fd.png)

Result:
![image](https://user-images.githubusercontent.com/13716824/48100251-581b2080-e21a-11e8-960c-e179adbd7af5.png)

I doubt this will ever get fixed in this repo *but* there is a fix and @jossef has it over at [MDIDX](https://github.com/jossef/material-design-icons-iconfont). I'm mainly posting this as a signpost for future devs who run into this issue.

**Comment by RoelN** [comment]
Tracking progress in the issue linked above.
