### ISSUE TITLE
Missing icons on self-hosted fonts

### ISSUE THREAD

**Issue by apercova** [google/material-design-icons#879]
I´m able to see all the icons when using web font via Google Web Fonts, but if I use self-hosted fonts a described [here](https://google.github.io/material-design-icons/) I notice that most recent icons are not 
available, as the last update is from February 8th 2016!
As an example, the icon: **drag_indicator** does not exists.

Could you level up font archives in this repo to the online google's fonts version?

**Comment by sentika** [comment]
Same with **notes** icon

**Comment by apercova** [comment]
@sentika I've prepared offline files from online-font version 41 as a work around.
You could give it a try and use if it works for you.

Checkout here: [https://github.com/apercova/material-icons-font](https://github.com/apercova/material-icons-font)

**Comment by danemacmillan** [comment]
`category` and `accessibility_new` are also not available.

**Comment by jossef** [comment]
Hey @danemacmillan @apercova  @sentika 

This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss, removed irrelevant files (jams `npm install`).

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

as a proof, the `category`  `accessibility_new`  `notes`  `drag_indicator` icons are available as you would expect

![image](https://user-images.githubusercontent.com/1287098/49375637-98809800-f70d-11e8-9491-29d2cfd05b17.png)

**Comment by stewwan** [comment]
thank you @jossef it works great.

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
