### ISSUE TITLE
All folder

### ISSUE THREAD

**Issue by Eldqs** [google/material-design-icons#88]
Hi, How will I can download all folder, when I download zip file within only one folder "action" but have not other folder.

**Comment by jestelle** [comment]
Eldqs, there is a bug in the Windows unzipper and Github.  See issue #8 for some solutions.

In short, try downloading the zip [from here](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip
