### ISSUE TITLE
Enable "click to copy" for icon names from material.io/icons

### ISSUE THREAD

**Issue by sboesch** [google/material-design-icons#880]
I read before that this isn't the right place to draw attention to documentation issues but I can't see another way to report this massive UX issue:

Please allow icon names to be copied to clipboard with a single click. It's way too complicated to copy a single icon name while browsing. And since you cut off half of the icon names, you can't even type it by hand without performing multiple clicks:

<img width="576" alt="screen shot 2018-11-21 at 11 30 55" src="https://user-images.githubusercontent.com/16945695/48836109-1fcf2280-ed82-11e8-831e-4f6c489b352d.png">

Thank you!

**Comment by jossef** [comment]
hey @sboesch , trust me, I know your pain. until the team address your issue you can try my version

https://jossef.github.io/material-design-icons-iconfont/

![image](https://user-images.githubusercontent.com/1287098/49580094-cdcbf680-f956-11e8-8ed2-690668b5990e.png)

**Comment by sboesch** [comment]
@jossef thank you, I was already using your version since I figured out this repository is practically dead anyway ;) This is something you can finally work with. Thank you for your effort!

**Comment by RoelN** [comment]
There's an issue we're tracking improvements to the search in. Since it seems your specific problem is fixed, I'm closing this issue. If you feel it's still relevant, feel free to reopen.
