### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by Domvel** [google/material-design-icons#881]
Icon Request:
- [QR-Code](https://www.google.com/search?tbm=isch&as_q=qr+code+icon)
- [Barcode](https://www.google.com/search?tbm=isch&as_q=barcode+icon)

**Comment by RoelN** [comment]
Closing this as QR code has arrived! \o/ Feel free to reopen when you still need a barcode icon.

**Comment by tphinney** [comment]
I just wanted to let people know 1D (linear) /barcode and /barcode_scanner icons have been approved for me to add them to Material Symbols. I will be adding them on the source side today. I know it has been a long wait! Thanks for your patience.
