### ISSUE TITLE
Need help to fix this error

### ISSUE THREAD

**Issue by alam1251** [google/material-design-icons#887]
![screenshot_2018-12-11-21-25-51-64](https://user-images.githubusercontent.com/45454258/49807251-2d2d6a80-fd8c-11e8-979b-5dc477e9750a.png)
like you are see guys i got error where the icons changed to mandarin language, can someone help me ? 
and yeah with the bottom overflowed by 44 fixed too hahaha

this is my source code : 

import 'package:flutter/material.dart';
import './help_screen.dart';

class Main extends StatefulWidget {
  @override
  _Main createState() => _Main();
}

class _Main extends State<Main> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Image.asset('images/gurita.png'),
        backgroundColor: Colors.black,
        centerTitle: true,
        actions: <Widget>[
          new Column(
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.more_vert),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) =>
                          Help(), //Pindah halaman ke help, herp oh herp :v
                    ),
                  );
                },
              ),
            ],
          )
        ],
      ),
      body: Scaffold(
        drawer: Drawer(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              new UserAccountsDrawerHeader(
                accountEmail: new Text("Alam Jaya"),
                accountName: new Text("tengusky1@gmail.com"),
                currentAccountPicture: new CircleAvatar(
                  backgroundColor: Colors.white,
                  child: Icon(Icons.person),
                ),
              ),
              new ListTile(
                leading: QrCode(),
                title: Text("Profile"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("Voucher / Point"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("My Flash Deal"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("Kategori"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("Reservasi"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("History"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("About"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.feedback),
                title: Text("FeedBack"),
              ),
              new Divider(
                height: 0,
              ),
              new ListTile(
                leading: new Icon(Icons.people),
                title: Text("Logout"),
              ),
              new Divider(
                height: 0,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by jossef** [comment]
Hey, I think it's a bit off-topic here.
suggesting to open this issue in the [flutter repo](https://github.com/flutter/flutter/issues)

**Comment by baotoan95** [comment]
Did you resolve this yet? I have the same issue, help me...

**Comment by RoelN** [comment]
This sounds like something specific to your code. Can you point us to an online test case? Closing this issue in the meantime — feel free to reopen this issue or create a new one with more information.
