### ISSUE TITLE
Icon request; Swipe left/Swipe right 

### ISSUE THREAD

**Issue by deap82** [google/material-design-icons#890]
Inspiration:

https://www.google.com/search?q=swipe+icon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjpvIaX-63fAhVdAxAIHT1AB10Q_AUIDigB&biw=2560&bih=1299

![image](https://user-images.githubusercontent.com/1295067/50272305-9d488a00-0437-11e9-9fb5-dd37a3cd1fe0.png)

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
