### ISSUE TITLE
"notes" not listed in editor map

### ISSUE THREAD

**Issue by Ruud-cb** [google/material-design-icons#893]
The icon "notes" under Editor: https://material.io/tools/icons/?search=notes&style=baseline
Cannot be found in this folder: https://github.com/google/material-design-icons/tree/master/editor/drawable-anydpi-v21
Could not find the same icon by searching, only "speaker_notes" which is a different one.

Where is it?
Later I noticed it did download along when clicking on the PNG button when having android selected. I would suggest some more info on that on the page.

**Comment by jossef** [comment]
Hey @Ruud-cb ,

This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss and removed irrelevant files (jams `npm install`).

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

as a proof, the `notes` icon is available as you would expect

![image](https://user-images.githubusercontent.com/1287098/50767926-4b9d5d80-1287-11e9-859e-5c570b215778.png)

**Comment by Ruud-cb** [comment]
Thanks, I will use this for web-development. This issue is actually regarding the android development: finding the .xml files. These .xml files are similar to .svg files yet a bit different structured and a bit different "path" values.
Thanks for your comment though!

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
