### ISSUE TITLE
arrow_left and arrow_right icons can't display in web

### ISSUE THREAD

**Issue by xavier-9527** [google/material-design-icons#896]
I use React to build my project.  they can't display after installing <ArrowLeft/> and <ArrowRight/>.  I hope someone can help me to fix it.

**Comment by jossef** [comment]
Hey @XxIwen ,

This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss and removed irrelevant files (jams `npm install`).

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

as a proof, the `arrow_left` and  `arrow_right` icons are available as you would expect

![image](https://user-images.githubusercontent.com/1287098/51088041-cbce3200-1763-11e9-84d7-95b477eadbd2.png)

**Comment by The-MAZZTer** [comment]
After trying to figure this out on my own (without having found this issue until now) I have come to the conclusion Windows refuses to print these glyphs for some reason (despite they are in the private use area just like all the other ones). Chrome can print them but I can't get any other app to. Character Map refuses to display these glyphs and acts like they do not exist in the font, but if you iterate through the entire private area space Chrome happily prints them out. And of course the ligatures work fine in Chrome as well.

**Comment by XxIwen** [comment]
@jossef 
Thank you very much for everything you have done!

**Comment by RoelN** [comment]
The assets have been updated in the meantime, and I believe this is fixed. If not, feel free to reopen this issue or create a new one with more information.
