### ISSUE TITLE
[Request] Create megaphone icon

### ISSUE THREAD

**Issue by adrianknight89** [google/material-design-icons#900]
Not sure if this already exists, but it'd be great to have this icon in the set. It could be used for a variety of reasons. In my case, I'm considering using it as a share button.

**Comment by rhadfi22** [comment]
Hola buenas noches vamos a probar

**Comment by InhamulHassan** [comment]
Would be useful.

**Comment by ahurtaud** [comment]
Have you found an alternative?

**Comment by mockturtl** [comment]
@adrianknight89 What did you end up using instead?
