### ISSUE TITLE
<mat-icon> 'cast_for_education' missing

### ISSUE THREAD

**Issue by qortex** [google/material-design-icons#902]
#### What is the expected behavior?
`cast_for_education` should be ok as shown on [Material design page](https://material.io/tools/icons/?icon=cast_for_education&style=baseline)

#### What is the current behavior?

Icon `cast` is shown instead.

#### What are the steps to reproduce?
[Stackblitz showing issue](https://stackblitz.com/edit/angular-material2-issue-8seawf)

**Comment by Gabfranck** [comment]
Thx for this report. Same error here !

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

Make sure you're using the font from this repo or as served by Google Fonts, the NPM package is unfortunately outdated, currently. Issue for that: https://github.com/google/material-design-icons/issues/1129
