### ISSUE TITLE
vertical_split icon is not displayed

### ISSUE THREAD

**Issue by roipoussiere** [google/material-design-icons#906]
The icon `vertical_split` is not displayed at all when using local icons set on this repo. To check it:

    <i class="material-icons">vertical_split</i>

Not that it works using cdn, ie `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`.

**Comment by alexkindel** [comment]
See #786

**Comment by RoelN** [comment]
Closing this issue in favor of the one linked above. Thanks for reporting.
