### ISSUE TITLE
Correct License?

### ISSUE THREAD

**Issue by martinheidegger** [google/material-design-icons#912]
The `LICENSE` file contains the entire Apache License but it seems to be missing the important copyright information:

https://github.com/google/material-design-icons/blob/224895a86501195e7a7ff3dde18e39f00b8e3d5a/LICENSE#L181-L188

**Comment by russellmcc** [comment]
Any movement on this?  I'm not sure who to credit the copyright to when I'm redistributing this work.

**Comment by RoelN** [comment]
The copyright notice is added to any code ([example](https://github.com/google/material-design-icons/blob/master/update/update_repo.py)), the Apache 2.0 license is in the [root of the repo](https://github.com/google/material-design-icons/blob/master/LICENSE) and Github confirms the license:

![image](https://user-images.githubusercontent.com/4570664/103651731-549e9380-4f62-11eb-9614-9bff7f57ec5a.png)

Everything in this repository is offered by Google and under the Apache 2.0 license :-)

I hope this clarifies. Feel free to reopen this issue or create a new one if you have any other questions!
