### ISSUE TITLE
Border around rounded star icon

### ISSUE THREAD

**Issue by fatihsolhan** [google/material-design-icons#913]
Hi, the rounded star icon has a weird border around it.
[svg from material.io](https://material.io/tools/icons/static/icons/round-star-24px.svg)
[Reproduced on codepen](https://codepen.io/anon/pen/wOJdMZ)

I have asked a question on stackoverflow and a friend provided a solution for it.
[StackOverflow solution link](https://stackoverflow.com/a/55042837/7971182)

**Comment by shawnwwwww** [comment]
same issue!

**Comment by jthom330** [comment]
Just ran into this as well.

**Comment by 6Jonathan6** [comment]
Same here

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by stephanieraymos** [comment]
I'm having this issue with all svg icons from material IO

**Comment by stephanieraymos** [comment]
I had my img wrapped in a button.
This weird border came from the styling of the button itself. 
I resolved it by adding these styles to my button:

                  style={{border:"none", backgroundColor:"transparent"}}

As a side note; I'm using react-bootstrap throughout my app. Not sure if that's relevant but adding incase it might be important info for anyone reading this.
