### ISSUE TITLE
Missing music_off icon

### ISSUE THREAD

**Issue by kfeng0806** [google/material-design-icons#914]
This icon is still missing
https://material.io/tools/icons/?search=music_off&icon=music_off&style=baseline

**Comment by haskasu** [comment]
will music_off be added in the future?

**Comment by RoelN** [comment]
It's seems to be here now :-)

<img width="371" alt="image" src="https://user-images.githubusercontent.com/4570664/103646670-549a9580-4f5a-11eb-8d76-0eb7962cc6f3.png">
