### ISSUE TITLE
Black square in rounded star icon

### ISSUE THREAD

**Issue by rolurq** [google/material-design-icons#915]
The star icon in the toggle section is a square instead of the star, at least after the download. This is what I got when downloading it

![term](https://user-images.githubusercontent.com/13684824/54290614-a900a400-4581-11e9-9288-3538c7d6cab0.png)

**Comment by cyberalien** [comment]
Here is fixed version: https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/toggle/round-star.svg

**Comment by skbrown333** [comment]
@cyberalien How would I use the raw svg of this as part of the google font?

**Comment by cyberalien** [comment]
That would require rebuilding font. Tools for that are not included in this repository.

I suggest to forget about font. It is big, renders not as precise as SVG. Switch to Iconify instead. It it as easy to use as font, but it renders SVG, it loads only icons that you use on page and there are way more icons to choose from. See https://github.com/cyberalien/google-material-design-icons-updated and https://github.com/iconify/iconify

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
