### ISSUE TITLE
Problem with two tone font on Chrome Windows

### ISSUE THREAD

**Issue by jfaissolle** [google/material-design-icons#917]
There is a problem with Two Tone font on Chrome on Windows.

![material-icon-bug](https://user-images.githubusercontent.com/941866/55616581-68680500-5792-11e9-8cb3-9bf16905ed19.PNG)

It is as if the 360 icon was displayed over all other icons.

The strangest part is that it displays correctly on Firefox and Edge and also Chrome on Linux.

Sample code (https://codepen.io/jfaissolle/pen/dLMQxy):

```html
<html>
  <head>
    <link href="//fonts.googleapis.com/icon?family=Material+Icons+Two+Tone" rel="stylesheet" type="text/css">
  </head>
  <body>
    <i class="material-icons-two-tone" style="font-size: 128px;">description</i>
  </body>
  
</html>
```

**Comment by cyberalien** [comment]
That font doesn't work on in Chrome Android at all, it shows monotone icon in Samsung browser. 

Try this instead:
```
<html>
  <head>
    <script src="https://code.iconify.design/1/1.0.0/iconify.min.js"></script>
  </head>
  <body>
    <i class="iconify" data-icon="ic-twotone-description" style="font-size: 128px;"></i>
  </body>
  
</html>
```

**Comment by timc986** [comment]
I got the same issue on my win10 chrome but it seems fine on win7. Its really weird as they were all fine a while ago then suddenly something is messed up.

**Comment by Coding-Kiwi** [comment]
Are there any updates for this?

**Comment by gaganbal** [comment]
any update on this?

**Comment by Masterfellow** [comment]
Please fix this 🙏🏻

**Comment by santoshdvc** [comment]
> There is a problem with Two Tone font on Chrome on Windows.
> 
> ![material-icon-bug](https://user-images.githubusercontent.com/941866/55616581-68680500-5792-11e9-8cb3-9bf16905ed19.PNG)
> 
> It is as if the 360 icon was displayed over all other icons.
> 
> The strangest part is that it displays correctly on Firefox and Edge and also Chrome on Linux.
> 
> Sample code (https://codepen.io/jfaissolle/pen/dLMQxy):
> 
> ```
> <html>
>   <head>
>     <link href="//fonts.googleapis.com/icon?family=Material+Icons+Two+Tone" rel="stylesheet" type="text/css">
>   </head>
>   <body>
>     <i class="material-icons-two-tone" style="font-size: 128px;">description</i>
>   </body>
>   
> </html>
> ```

It is working fine while using UTF-8 encoding while saving html file. Chrome and Edge on Win 10 are displaying the font correctly.

**Comment by ssk7833** [comment]
> It is working fine using UTF-8 encoding in Notepad while saving html file. Chrome and Edge on Win 10 are displaying the font correctly. Online code editors still not showing properly.

It is not working for me on Win 10. Maybe it is not a good solution.

**Comment by JakeFDev** [comment]
Still a problem. Anyone come up with their own hacky solution? Our design team has to design around it which sucks.

**Comment by cyberalien** [comment]
> Still a problem. Anyone come up with their own hacky solution? Our design team has to design around it which sucks.

In addition to using SVG, I've been experimenting with fonts a bit few months ago and came up with this: https://github.com/material-icons/material-icons-font

Its the same icon font as latest official font, including two tone icons, but built without ligatures. It splits two tone icons into 2 separate shapes, then overlaps them on top of each other using :before and :after pseudo selectors with opacity for transparent layer.

Its a browser proof solution because it uses old technology. All stuff is in stylesheet.

**Comment by Coding-Kiwi** [comment]
@JakeFDev you can download the icons as svg from the [material website](https://material.io/resources/icons/?style=twotone), then generate the webfont yourself with [icomoon](https://icomoon.io/), but ligatures will be disabled:

>Font glyphs cannot have more than one color by default. Using CSS, IcoMoon stacks multiple glyphs on top of each other to implement multicolor glyphs. As a result, these glyphs take more than one character code and cannot have ligatures.
To avoid multicolor glyphs, re-import your SVG after changing all its colors to a single color.

**Comment by RoelN** [comment]
Checking this on Chrome 80 and above on Windows 10, the example in https://codepen.io/jfaissolle/pen/dLMQxy seems to be working correctly. The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
