### ISSUE TITLE
Download doesn't appear to be correct

### ISSUE THREAD

**Issue by andyseaton83** [google/material-design-icons#92]
Hi all, I may be doing something really daft, but I can't download all the icons from the main hub - I try the download zip option on the main material-design-icons page and I get the 57.5Mb file downloaded. However, when I open it, it only has one class of icons (action) and no svgs included in the download. I was expecting all 16 classes of icon, with an SVG file for each icon.

I want to import these all into Icomoon so that I can use them on an upcoming project, but haven't figured out if I can actually download these all yet. Any help or tips would be much appreciated.

Thanks

Andy

**Comment by Jarlotee** [comment]
+1

**Comment by jestelle** [comment]
There is a bug in the Windows unzipper and Github.  See issue #8 for some solutions.

In short, try downloading the zip [from here](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNUzJ4c1VXWDYzbTA/material-design-icons-1.0.1.zip)
