### ISSUE TITLE
For anyone who needs the rounded star icon 

### ISSUE THREAD

**Issue by shawnwwwww** [google/material-design-icons#925]
Apparently there's some issue and every time I tried to download it, it just turned into a black square. 

So I made a quick fix. Here is the download link
https://www.dropbox.com/s/ytw2w56z038rgi1/round-star-24px.svg?dl=0

Hope I helped

**Comment by RoelN** [comment]
Thanks for sharing your solution, much appreciated!

The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
