### ISSUE TITLE
Problem with material fonts in Pagespeed Insights

### ISSUE THREAD

**Issue by VeeK727** [google/material-design-icons#926]
I'm trying to target a high score on Pagespeed insights but one of these warnings is out of my control. Pagespeed insights suggests "Ensure text remains visible during webfont load". I've done this for all my self hosted fonts but how the warning still appears for the material fonts .woff file. Can I fix this myself?

![97](https://user-images.githubusercontent.com/11595460/56643883-3282b600-6698-11e9-9a75-a0e30f18b880.jpg)

**Comment by cyberalien** [comment]
You can try self hosting that font too. That way you'll have everything under your control.

> I've done this for all my self hosted fonts

Do you include many fonts on same page?

**Comment by VeeK727** [comment]
I read in the readme and probably somewhere else too that self hosting the file is not recommended so I didn't do it.

> Do you include many fonts on same page?

I have 3 font weights of another font whose files are self hosted.

**Comment by rsheeter** [comment]
FYI, we recently added font-display support to Google Fonts, use `display=swap` (or whatever your preferred value is).

https://developers.google.com/fonts/docs/getting_started#use_font-display

**Comment by VeeK727** [comment]
Bingo! Thank you so much. Thats perfect!

**Comment by jonsamwell** [comment]
@rsheeter this doesn't seem to be supported which the material icon cdn url?

https://fonts.googleapis.com/icon?family=Material+Icons&font-display=block

returns css without `font-display: block;` 

```
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v81/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
