### ISSUE TITLE
Please update this font

### ISSUE THREAD

**Issue by ahainen** [google/material-design-icons#927]
There are so many icons listed on material.io that are not in this font. Please update it.

**Comment by TZanke** [comment]
see: https://github.com/google/material-design-icons/issues/786

**Comment by jossef** [comment]
try the fork - https://jossef.github.io/material-design-icons-iconfont/


![image](https://user-images.githubusercontent.com/1287098/59142921-0021e380-89ce-11e9-9628-1213e7c56173.png)

**Comment by RoelN** [comment]
The fonts in the repo have been updated: https://github.com/google/material-design-icons/tree/master/font

If you're using the NPM package, we're keeping track on updating it here: https://github.com/google/material-design-icons/issues/1129
