### ISSUE TITLE
SVG options are not respected

### ISSUE THREAD

**Issue by DarrienG** [google/material-design-icons#929]
I'm probably just yelling into the void at this point, because it looks like this repo is no longer updated. That aside, the buttons that customize your icon do not work with SVG icons.

To reproduce:
Pick any icon
Pick the SVG version
Choose any customization other than the default (e.g. white, higher dpi, etc.)
Get the default icon without customizations

**Comment by rastalamm** [comment]
Any update on this / how to get the correct icon?

**Comment by rastalamm** [comment]
I was trying to get the icon to be the white version and managed to do so using the below svg modification. Try adding `opacity="1"` and `fill="currentColor"` to the `svg`'s `path`.

```
<svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
  >
    <path d="M0 0h24v24H0z" fill="none" />
    <path
      opacity="1"
      fill="currentColor"
      d="M5 16h3v3h2v-5H5v2zm3-8H5v2h5V5H8v3zm6 11h2v-3h3v-2h-5v5zm2-11V5h-2v5h5V8h-3z"
    />
  </svg>
```

Before:
![before](https://user-images.githubusercontent.com/9030131/65782087-ef32e480-e11a-11e9-925a-e75ef0a84aad.png)


After:
![after](https://user-images.githubusercontent.com/9030131/65782044-d5919d00-e11a-11e9-8d20-de0613eddf3d.png)

**Comment by RoelN** [comment]
This seems to work now in the downloader?

If not, feel free to reopen this issue or create a new one with more information.
