### ISSUE TITLE
SVG sprite enhancements

### ISSUE THREAD

**Issue by robertbaker** [google/material-design-icons#93]
Need 48px versions of SVG spirtes.

**Comment by stryju** [comment]
if you use [inline SVG embedding](https://github.com/jkphl/svg-sprite#inline-embedding), there's no need for that - SVG will scale up/down

**Comment by robertbaker** [comment]
For most icons there are 24px, 36px, and 48px versions. Since the svg paths
are different for each size, I'm guessing that the 24px version has less
detail for the smaller size than the 36 and 48 version. Otherwise the path
would be identical.

I currently use them with angular-material using md-icon. I plan on
assembling my own sprite set based on the icon and size.

**Comment by stryju** [comment]
i wrote my own angular directive for using material icons.

also, i have *"created"* sprites for that purpose (see https://github.com/google/material-design-icons/pull/100) and the size is being controlled with css (as well as `fill` property)

**Comment by robertbaker** [comment]
Reviewing a few of the icons, the 24px (height and width set to 48px) and 48px versions look 100% identical to me.

Maybe a note of that should be placed in the readme. I was thinking details were removed from the smaller sizes, but that doesn't seem to be the case.

**Comment by stryju** [comment]
no, they are scaled - that's it.

if you want "responsive" icons, [iconic](https://useiconic.com/) is for you ;-)

**Comment by shyndman** [comment]
Seems reasonable. I've included a Gulpfile with the latest release, so you can be able to fork our repo and add a task for generating 48px sprites.

https://github.com/google/material-design-icons/blob/master/gulpfile.babel.js#L65
