### ISSUE TITLE
Alert notification_important icon is missing

### ISSUE THREAD

**Issue by AlexZhidkov** [google/material-design-icons#933]

**Comment by jossef** [comment]
try https://jossef.github.io/material-design-icons-iconfont/

![image](https://user-images.githubusercontent.com/1287098/59142906-bdf8a200-89cd-11e9-819d-08d8b7b549ff.png)

**Comment by trixrabbit** [comment]
@jossef I know this is old but I just tried MDIDX and the icon is still not showing

installed following this the github page, imported the following in my style.scss

```
$material-design-icons-font-directory-path: '~material-design-icons-iconfont/dist/fonts/';

@import '~material-design-icons-iconfont/src/material-design-icons';
```

All other icons I tried seem to work, not sure how it is showing on the demo page and not in other apps

**Comment by arucar** [comment]
Same problem here after installing with npm. notification_important and vertical_split not showing

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

If you use the fonts from this repo, or from Google Fonts, the icon will be there.
