### ISSUE TITLE
Unicode hex numbers aren't shown, only ligatures.

### ISSUE THREAD

**Issue by synchronos-t** [google/material-design-icons#936]
On the selected icon dialog, the page should supposedly show the ligature text to generate the icon, and the Unicode fallback. I tried to access the Unicode, as I have some issues of the ligature breaking when it's rotated. However, the page only shows the ligatures, even under the `<!-- For IE9 or below. -->` section.

**Comment by jossef** [comment]
check out https://jossef.github.io/material-design-icons-iconfont/
![image](https://user-images.githubusercontent.com/1287098/59142867-31e67a80-89cd-11e9-8e3a-b1500c834497.png)

**Comment by RoelN** [comment]
There are now codepoints-files for each font, e.g. https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

I believe this addresses your issue. If not, feel free to reopen this issue or create a new one with more information.

**Comment by synchronos-t** [comment]
To me, the bigger part of the issue is that the hex codes aren't available right at the [Material Design site icon list](https://material.io/resources/icons/) (which was also the point of the original issue https://github.com/google/material-design-icons/issues/772), but at least that works as a workaround.

**Comment by RoelN** [comment]
@synchronos-t Ah gotcha. Please track this issue which requests explicitly that: https://github.com/google/material-design-icons/issues/1110

**Comment by synchronos-t** [comment]
I thought my issue explicitly requested the hex codes to be shown on the website. :) After all, my first sentence was "On the selected icon dialog, the page should supposedly show [..]". Anyway, let's continue on that issue.

**Comment by RoelN** [comment]
Yeah, sorry, I've been looking at hundreds of issues in this repo the past few weeks, trying to clean up a bit so the original developers can start focussing, so I missed that 😅
