### ISSUE TITLE
<i class="material-icons"> minimize </i> does not show any icon

### ISSUE THREAD

**Issue by russellswift** [google/material-design-icons#941]
When I use icon font all icons that i embed are OK, but minimize is not shown at all

**Comment by jossef** [comment]
This project is on low maintenance and out of date for a while.

I've forked this repo, scraped the updated fonts from `Google Fonts` CDN, added support for scss, removed irrelevant files (jams `npm install`).

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/49375637-98809800-f70d-11e8-9491-29d2cfd05b17.png)

**Comment by RoelN** [comment]
The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.
