### ISSUE TITLE
Icon request: key

### ISSUE THREAD

**Issue by TsavyPrince** [google/material-design-icons#942]
There is no generic key icon, only the VPN key icon which does not fit well. At least rename the VPN key to something more generic.

**Comment by hbugdoll** [comment]
There is a new `key` icon in Google Fonts (https://fonts.google.com/icons?icon.query=key&icon.category=communication), but not yet in the GitHub repo.

**Comment by jalpadoshi** [comment]
Icon now available on: https://fonts.google.com/icons
