### ISSUE TITLE
Replace Google Material Icons with Own Icons, Keep Same Content Code or Create New One

### ISSUE THREAD

**Issue by AerialSky93** [google/material-design-icons#945]
Google Material Icons has different variations in Icon font Families: Rounded, Sharp, TwoTone, etc.

The UX team is taking some icons, and customizing them bit, little thicker or minor touch up.

1)
Is it possible to replace/edit the icons, and keep the same content code without any issues? Example: We are using Visual Studio .Net Core application, and placed Material Icons in our library.

2)
Additionally, is it possible to Create New Content Code? Say, I create Company logo. Can I assign it a Content Code?

Referring to Material icons with both content code and class name
```

.carouselrightarrow {
    font-family: Material Icons;
    font-size: 36px;
    position: absolute;
    top: 16px;
    content: "\e409";
}
<button id="add-to-favorites"
        class="mdc-icon-button">
    <i class="material-icons mdc-icon-button__icon mdc-icon-button__icon--on">favorite</i>
    <i class="material-icons mdc-icon-button__icon">favorite_border</i>
</button>


```
Right now, currently replacing the rounded icon base. Another reason to conduct this besides saving coding time/existing code base; if client ever want to swap to Google Material: Filled, Sharp, Two Tone, Outlined, it can be done in easy manner.

References:

https://stackoverflow.com/q/40194077/1366033
https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by RoelN** [comment]
You can't change/add icons inside the existing fonts easily. You could take the SVG files, make your changes, and build your own front through the various tools like https://github.com/13rac1/scfbuild or https://icomoon.io/

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.
