### ISSUE TITLE
Some charging battery icons not displayed

### ISSUE THREAD

**Issue by gmikhail** [google/material-design-icons#946]
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

```
<i class="material-icons">battery_charging_20</i>
<i class="material-icons">battery_charging_30</i>
<i class="material-icons">battery_charging_50</i>
<i class="material-icons">battery_charging_60</i>
<i class="material-icons">battery_charging_80</i>
<i class="material-icons">battery_charging_90</i>
```

An empty space is displayed instead.

PS: it seems this project is abandoned?

**Comment by RoelN** [comment]
These icons have been removed from the project, but this issue is keeping track of possibly re-adding them: https://github.com/google/material-design-icons/issues/181 I'll close this issue in favor of the other one.
