### ISSUE TITLE
Self-Hosted Material Icon Not Showing On Both Chrome and IE OTS parsing error

### ISSUE THREAD

**Issue by srinivass92** [google/material-design-icons#948]
Failed to decode downloaded font: http://localhost:8080/ui/assets/iconfont/MaterialIcons-Regular.woff2
localhost/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
localhost/:1 Failed to decode downloaded font: http://localhost:8080/ui/assets/iconfont/MaterialIcons-Regular.woff
localhost/:1 OTS parsing error: OS/2: Failed to parse table
localhost/:1 Failed to decode downloaded font: http://localhost:8080/ui/assets/iconfont/MaterialIcons-Regular.ttf
localhost/:1 OTS parsing error: cmap: Failed to parse table

I am getting same error please help me.
i downloaded today from master branch.
https://github.com/google/material-design-icons

**Comment by brightest-dazes** [comment]
gpg: Signature made Fri 09 Oct 2015 05:41:55 PM CEST using RSA key ID 4F25E3B6
gpg: Can't check signature: No public key
gpg: Signature made Tue 13 Oct 2015 10:18:01 AM CEST using RSA key ID 33BD3F06
gpg: Can't check signature: No public key

**Comment by RoelN** [comment]
Apologies for the delay. The fonts have been updated in the mean time, if you get them from Google Fonts they'll always stay up to date:

```html
<link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
```

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by devgrigor** [comment]
This is an issue again. It was working fine yesterday. The link code is following 
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"  rel="stylesheet">
```

**Comment by rafaelmontes8** [comment]
Yesterday the link was working just fine, this morning the icons have dissapeared. Maybe the server is down.

**Comment by devgrigor** [comment]
> Yesterday the link was working just fine, this morning the icons have dissapeared. Maybe the server is down.

Not sure if that's the case, the files are still there. They just are not decodable, maybe file is just somehow corrupted...
Even the google demo is not working at https://fonts.google.com/icons?selected=Material+Icons 
When you choose filled, all icons are becoming blank and the same error is in the console.
