### ISSUE TITLE
Calendar icon request.  

### ISSUE THREAD

**Issue by EugeneHoran** [google/material-design-icons#95]
I have seen week and day but no month icon.  I think it will be very useful for applications that have a calendar within their application.

**Comment by jestelle** [comment]
Do the "today" or "event" icons work for your need?

**Comment by EugeneHoran** [comment]
@jestelle I have been using "today."  I figured it would be helpful to create consistency.

**Comment by rayshan** [comment]
Maybe "today" just needs an alias for ease of searching.

**Comment by brianpkelley** [comment]
+1
An empty calendar icon would be great!

**Comment by justbeez** [comment]
Agreed; I feel like a blank calendar (or one with the common "31") on it would be helpful and could be done either in the style of "event" / "today" / "event note" or the more distinct "perm contact calendar".

I also feel like _especially_ when using with ligatures for semantics, you really wouldn't want to use those other options to mean "calendar".  Sure, you could duplicate one—but the point is that we're assigning meaning to these things, and only having specific implementations while missing more commonly used general concepts seems obtuse.

**Comment by j-greig** [comment]
+1 for a generic looking calendar icon

![image](https://cloud.githubusercontent.com/assets/616194/24944525/8c338faa-1f53-11e7-8dc6-9b1a22864bb0.png)

**Comment by cfacundo** [comment]
_date_range_ works as a good alternative =)

**Comment by mnemanja** [comment]
The point is that the calendar icon for a month is missing.
Everything else has it's special usage, but nothing covers the month calendar like @j-greig mentioned.

**Comment by jalpadoshi** [comment]
Icon now available on : https://fonts.google.com/icons
