### ISSUE TITLE
Deprecate save for save_alt

### ISSUE THREAD

**Issue by superwills** [google/material-design-icons#959]
The save icon looks to be a mixture of a legacy 3.5" floppy disk and a 5.25" floppy disk

I think this only has good recognition for people who actually saw and used these diskettes.

Deprecate the save icon for save_alt and move forward into 2020!

**Comment by fjhm** [comment]
Me gusta

**Comment by RoelN** [comment]
Perhaps `save_alt` will serve your needs?

![afbeelding](https://user-images.githubusercontent.com/4570664/106718763-c4f01180-6601-11eb-8c77-03b995af8b81.png)

If not, feel free to reopen this issue.

**Comment by troyehall** [comment]
And those who recognize it may also notice the other big issue. The hole isn't even in the center. That disk won't spin. :-)

**Comment by tphinney** [comment]
I suspect that is the problem with trying to make everything hit the grid at the design size.

I did an experimental tweak/redesign for the old "save" icon, will propose it.
