### ISSUE TITLE
Switch account icon

### ISSUE THREAD

**Issue by lcswillems** [google/material-design-icons#964]
This is the current "switch account" icon in Youtube:

![image](https://user-images.githubusercontent.com/5437552/68060827-59ced580-fd02-11e9-809e-fc843d68754b.png)

Is it part of Material Design icons? I can't find it. If not, is it expected to share it?

Thank you for having already published this whole set of awesome icons!!

**Comment by mohalobaidi** [comment]
There is a "secret" extended version of the metarial icons pack that only used in google products. I think youtube also uses that. I don't know if it is legal for us to use it.

**Comment by RoelN** [comment]
This is indeed not part of the Material Design Icons, but I will mark it as an icon request.

**Comment by jalpadoshi** [comment]
Icon  is an existing icon and available on: https://fonts.google.com/icons
