### ISSUE TITLE
Astrix icon

### ISSUE THREAD

**Issue by LeoJHarris** [google/material-design-icons#965]
I was looking for something like this in the material icons collection but couldnt find one. Somethink like this:

![download](https://user-images.githubusercontent.com/5468757/69188803-17224f80-0b82-11ea-8094-28dec5a170d8.png)

**Comment by RoelN** [comment]
Material Design Icons typically don't include regular punctuation marks. If you still feel this should be the case, please reopen this issue or create a new one with more information.
