### ISSUE TITLE
post_add icon is missing

### ISSUE THREAD

**Issue by sic-sic** [google/material-design-icons#967]
the [post_add icon](https://matérialiste/resources/icons/?search=post_add&style=baseline) can be found on material design official website. But this icon is missing in this library.

Can any one help me know how I can use it.

**Comment by RoelN** [comment]
https://github.com/google/material-design-icons/tree/master/src/editor/post_add

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by LorenzoDelpi** [comment]
Hi, at moment the post_add icon could be found on the documentation page but isn't be shown when you insert it.
