### ISSUE TITLE
Self hosted font icon offset bug

### ISSUE THREAD

**Issue by Yizhachok** [google/material-design-icons#973]
Material font icon has wrong position using self hosted node modules font (this module)
![image](https://user-images.githubusercontent.com/1171048/72670802-bc568880-3a4a-11ea-9e91-d05c044d1f3e.png)
Including like this `@import '~material-design-icons/iconfont/material-icons.css';`

If including css form google CDN all works perfectly
![image](https://user-images.githubusercontent.com/1171048/72670892-ca58d900-3a4b-11ea-867d-92f3f2d3cc3e.png)
Including like this `@import "https://fonts.googleapis.com/icon?family=Material+Icons";` (just replacing that line)

Seems like it make text `calendar_today` transparent and append at the end icon. And as we can see seems like this 2 fonts is two different versions.

Chrome 79.0.3945.117

**Comment by ChildishGiant** [comment]
I had an issue when selfhosting (#878) and for me I found using this fork was a workaround: [jossef/material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont) so have a look at that

**Comment by RoelN** [comment]
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.
