### ISSUE TITLE
Icon request: Ruler

### ISSUE THREAD

**Issue by retnikt** [google/material-design-icons#975]
A simple ruler icon would be nice, to represent:
- units/conversions
- measurement tool (c.f. #327)
- rulers in a art/design/typesetting/text editor app

There is [`square_foot`](https://material.io/resources/icons/?icon=square_foot&style=baseline) but it doesn't completely fit purpose and its name suggests it was designed with different intentions in mind.

**Comment by AnggiPrasetyo30** [comment]
hope can help you
![ruler](https://user-images.githubusercontent.com/65654499/82436955-d1a6f680-9ac0-11ea-9106-a86fcb4226fd.png)

**Comment by AnggiPrasetyo30** [comment]
I made the icon with GIMP, here are the steps:
1. Create a new layer as the background
2. Show the grid
3. Create a new layer (transparent)
4. Create a rectangular path
5. Combine the two paths
6. Sroke path
7. Use the rectangle select tool to draw a line on the ruler
8. Give the rectangle fill
9. Remove the visibility of the background layer
10. export as png

**Comment by RoelN** [comment]
I just found this icon is in the set:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/4570664/107761317-7510f900-6d2b-11eb-98c0-0ee800ba11c1.png">

:-)
