### ISSUE TITLE
icons not showing in sketch app

### ISSUE THREAD

**Issue by karamjeetiron** [google/material-design-icons#978]
Hi,

I am using the Sketch app. Material Icons not showing by sketch app even I installed the material regular TTF but still no luck. 

Here are the screenshots for better Understand. Please let me know what am missing.

https://www.screencast.com/t/dwonKqZFpO
https://www.screencast.com/t/hTjwHdR5

Thanks!

**Comment by cyberalien** [comment]
Its possible Sketch doesn't support ligatures.

Instead of importing font, you can use my Sketch plug-in to import icons. It has latest version of Google Material Design Icons: https://github.com/iconify/iconify-sketch and imports them as shapes that you can customise.

**Comment by karamjeetiron** [comment]
Thanks, @cyberalien for the quick response. I already used your plugin. It is good to use when you are starting the new design but am in the middle of the design with material icons. It was working fine a few months back but am not sure why it is not working anymore?

Regarding ligatures, I also used the ttf file of the themify icon and it is working fine. I having problems with the material icons only. Is there any other way around to fix it?

**Comment by cyberalien** [comment]
Plugin should be working, just make sure its up to date. Sketch is always changing, which is not always backwards compatible so sometimes old versions of plug-ins stop working.

As for font, there are several versions of font. There is outdated font from this repository, new version of font on Google Fonts. Then there is Templarian's material design icons font. Maybe you tried to install wrong font?

**Comment by karamjeetiron** [comment]
Still no luck :(

**Comment by RoelN** [comment]
The fonts in this repo have been updated in the meantime.

In the second screenshot you posted, it looks like The Material Design Icons font isn't installed. Can you check if the new font works as expected, and if not, re-open this issue and/or ask at Sketch?
