### ISSUE TITLE
svg round

### ISSUE THREAD

**Issue by Gaetanbrl** [google/material-design-icons#995]
Hi,
I try to download icons as SVG with round theme. 
But after git clone, i don't see SVG for round theme.
Is it possible ? Where can i find them ?

Thanks.

**Comment by cyberalien** [comment]
This repository hasn't been maintained for several years.

You can find repository with latest SVG files for all 5 themes here: https://github.com/material-icons/material-icons

**Comment by RoelN** [comment]
They are in the `materialiconsround` directories, for example: https://github.com/google/material-design-icons/tree/master/src/action/accessibility/materialiconsround
